### ISSUE TITLE
Can WebAssembly code efficiently generate and run new WebAssembly code, eg. for dynamic recompilation in emulators?

### ISSUE THREAD

**Issue by dreamlayers** [WebAssembly/design#1001]
[Various emulators and virtual machines](https://en.wikipedia.org/wiki/Dynamic_recompilation#Applications) including [DOSBox](https://github.com/dreamlayers/em-dosbox) can use [dynamic recompilation](https://en.wikipedia.org/wiki/Dynamic_recompilation). When running on a supported CPU, the non-native program is translated into native machine code. This can give much better performance than interpreting the code. Often specific sections get compiled into native code at runtime, instead of the whole thing being recompiled all at once beforehand.

Will it be possible to dynamically recompile into WebAssembly in a way that's sufficiently efficient to boost emulator and virtual machine performance?

**Comment by RyanLamansky** [comment]
Absolutely.  The WebAssembly JS API allows for feeding raw bytes into the compiler.  Those bytes can be loaded from a served file, generated in JavaScript, or even generated by an already-loaded WebAssembly process.

**Comment by kripken** [comment]
To add to that, while generating a raw wasm binary manually can take some effort, there are tools that focus on making it easy to build wasm, from either compiled C++ or JS, like binaryen. DOSBox should be able to use that.

**Comment by jfbastien** [comment]
In addition to what's been said, the [JIT compilation part of future features](https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#platform-independent-just-in-time-jit-compilation) should be helpful.

Assuming this is answered, please re-open and clarify if not. Maybe there are parts of the design repo which aren't making this clear enough? If so do file PRs!
