### ISSUE TITLE
Is the official version number 0x1 now?

### ISSUE THREAD

**Issue by pipcet** [WebAssembly/design#1005]
In https://bugzilla.mozilla.org/show_bug.cgi?id=1342060, IIUC, SpiderMonkey has stopped accepting 0xd as a version number and now requires version 0x1.

BinaryEncoding.md still says the current version number is 0xd, and that it will be reset to 0x1 in the MVP.

As far as I can tell, that means I can no longer build a module that conforms with BinaryEncoding.md (which allows only (0xd) and test it on SpiderMonkey (which allows only 0x1). I think that's an unfortunate state of affairs.

At the very least, BinaryEncoding.md should be updated to reflect the new reality.

Changing the emitted version number is a minor issue, but if there are now browsers out there which think they understand wasm version 1, which has not yet been released, we've effectively closed the door on significant changes to WebAssembly that would otherwise have gone into version 1. If that's the case, the MVP might as well be released now.

**Comment by jfbastien** [comment]
Yes, see [the announcement](https://lists.w3.org/Archives/Public/public-webassembly/2017Feb/0002.html). I'll file a PR to fix the binary version, sorry for missing this change.

**Comment by pipcet** [comment]
Congratulations! That's great news (that I'd somehow missed)!
