### ISSUE TITLE
Exporting an import either via table or normal exports

### ISSUE THREAD

**Issue by saambarati** [WebAssembly/design#1013]
Say a particular import is not a [Web Assembly Host Function](https://github.com/WebAssembly/design/blob/master/JS.md#exported-function-exotic-objects). When such an import is exported, why do we bother creating a Web Assembly Host Function for it? Why don't we just export it as is? This behavior seems weird to me. Maybe I'm missing something?
(Note that this also applies to "exporting" it via a table via the Element section)

The relevant spec is here:
https://github.com/WebAssembly/design/blob/master/JS.md#webassemblyinstance-constructor

**Comment by lukewagner** [comment]
That's the way it was originally written; see #798 for the rationale for the change.

One useful thing about these wasm function wrappers is that they give the JS function a wasm signature which makes it easy to put in tables.

**Comment by saambarati** [comment]
@lukewagner Thanks for the link to that issue.

I think the only thing in your original justification that makes this somewhat awkward is this requirement that you stated:

>That also means that, while I can't assign a JS function to a Table element directly via set, I could get it wrapped and then assign it: either by import+elem or import+reexport+Table.set. I really like this b/c it removes an otherwise potentially-frustrating limitation on import+elem usage without allowing full-on untyped JS functions in tables (which I'd like to avoid).

I think it's a bit weird to think about typed and untyped JS functions. Just b/c Wasm describes a type to an import, a JS function does not care at all about such a type. It seems awkward to not just accept that this is the world JS operates in, and allow `table.set(...)` to take normal JS functions.

You say you'd like to avoid this, but why?

**Comment by saambarati** [comment]
I suppose the main benefit of avoiding this is that we want call_indirect to have a sane type checking story. Is this the reason?

**Comment by lukewagner** [comment]
Mainly, I just bought the arguments @rossberg-chromium made.  My point about untyped-JS-functions-in-Tables wasn't a hard restriction; it's just something that I wanted to avoid for the MVP b/c it's a good deal more complicated to implement (and optimize all the cases with fast paths).  (With the wasm wrappers, once you've optimized monomorphic calls-to-JS-imports, the fast table calls kindof fall out for free.)  But this does seem like a restriction we could consider loosening going forward.

**Comment by saambarati** [comment]
@lukewagner I agree. Thanks for pointing me to that thread. It makes sense to restrict the type the more I think about.
