### ISSUE TITLE
WebAssembly and Accessibility

### ISSUE THREAD

**Issue by spidoche** [WebAssembly/design#1015]
I Couldn't found any documentation concerning WebAssembly and Accessibility. 
I would like to know what are the accessibility best practices when building  WebAssembly apps?

If someone can clarify this point. Thank you.

**Comment by RyanLamansky** [comment]
WebAssembly is pure logic, it has no user interface functionality of any kind.  Your question is similar to "what are the accessibility best practices for the Intel Core i7 processor?".

Accessibility guidelines depend on the environment that use it.  For instance an HTML web page that uses WebAssembly--or any other language--for processing should use HTML-oriented accessibility guidelines.

**Comment by spidoche** [comment]
Ok, now I got it.
Thank you for your explanations.

**Comment by jfbastien** [comment]
Assuming resolved. Feel free to reopen if not.

**Comment by hook-s3c** [comment]
The author's going to have to build a HTML-based alternative to anything presented in the content of the WebAssembly context, much like how we used to build `<noscript>` to compliment javascript or flash-powered sites back in the day
