### ISSUE TITLE
desktop opengl supported?

### ISSUE THREAD

**Issue by shi-yan** [WebAssembly/design#1023]
Sorry, I meant to post this on a discussion forum. But all discussion channels I found on the web page are github projects.

Forgive me if this is an inappropriate place to post this.

I want to know if webassembly is able to build desktop opengl?

 from this link
http://webassembly.org/docs/c-and-c++/
it seems to imply that webassembly can build desktop opengl apps (not opengl es) and run it through webgl. but this statement is rather vague, what version of opengl is supported? 4.0 4.4? 

I have an old app developed 10 years ago with opengl 1.1/SDL. Porting it to use opengl es is a big effort. I want to know if it is possible to compile it into webassembly today.

**Comment by kripken** [comment]
WebAssembly doesn't support things like OpenGL directly - you need libraries for that. So the question here is basically the same for asm.js and WebAssembly.

Yes, Emscripten's WebGL library does have some support for older OpenGL, see [the docs](http://kripken.github.io/emscripten-site/docs/porting/multimedia_and_graphics/OpenGL-support.html) - it's not complete, as full OpenGL is a very broad API, but it does work on many codebases. (And it works identically with asm.js and WebAssembly.)

See the emscripten test suite for examples of things that work, grep for `LEGACY_GL_EMULATION` which is the relevant option.

**Comment by jfbastien** [comment]
I think @kripken answered the question. Feel free to re-open if not!

**Comment by shi-yan** [comment]
This is perfect! Thank you!
