### ISSUE TITLE
Lack of clear roadmap in project

### ISSUE THREAD

**Issue by officialpatterson** [WebAssembly/design#1026]
Looking over the website's docs, features of an MVP and feature's to be added in a post-MVP release are described, but their is no time of reference for which the project aims to implement them. Could it be possible to set deadlines for development to keep the momentum/interest going?

Also, programming in WebAssembly looks like it will be tedious, so whats the vision here? How will WebAssembly fit into the engineering landscape 5 years from now? If you have a high-level language in mind, what one would you be using?

**Comment by jfbastien** [comment]
What do you mean by "which the project aims to implement them"? The WebAssembly W3C Community Group only creates a proposed standard, it doesn't set a timeline for its implementation.

**Comment by dschuff** [comment]
As for the second question, WebAssembly is designed to be generated by compilers rather than written by humans. Today we have fairly-mature C and C++ support via emscripten, work-in-progress on some other languages (e.g. Rust), and early experiments for several others. Over time the hope is that there will be lots of lanugage and runtime options, although some of them will require additional future features that are already on the roadmap.

**Comment by officialpatterson** [comment]
@jfbastien don't get me wrong here, cause I do believe in what WA is trying to do, but a standard is pretty useless unless it:
1. Covers the bases
2. Is widely implemented
3. has deadlines set
I'm not concerned with point 2 right now, but its the others. For example, is DOM manipulation going to be added to the standard? If so, when? 

The list of future features is apparent, but there is no indication as to when these will be added to the proposed standard.

@dschuff So given that in the future we'll have higher-level language compilers targeting WebAssembly, how do you envision most developers taking advantage of it? Will it be in most cases front-end frameworks akin to React/Angular/etc?

**Comment by Horcrux7** [comment]
I can agree with the requirement of a roadmap. I am working on a [Java to WebAssembly compiler](https://github.com/i-net-software/JWebAssembly). I need a GC which is on the future plan. But when will there a standard which support it? Does I need to create a workaround for the next years?

The future plan is currently a loosely list without any order of milestones. Like a wish list for Santa Claus.

**Comment by Azareal** [comment]
I would also like to ask for a road-map, but less of a timescale, and more... What has been done for the MVP? What needs to be done before it's considered complete? There's a lot of talk about MVP and post-MVP, but what exactly is going on here?

**Comment by jfbastien** [comment]
@Azareal the MVP is [considered complete](https://lists.w3.org/Archives/Public/public-webassembly/2017Feb/0002.html).

**Comment by jfbastien** [comment]
I think we can clarify individual roadmap things by using labels or documenting better. Please file separate PRs / issues for specific items.
