### ISSUE TITLE
Clarification of select after unconditional branch

### ISSUE THREAD

**Issue by cretz** [WebAssembly/design#1030]
Why is the following supposed to succeed (from [here](https://github.com/WebAssembly/spec/blob/2d821d9394549dd406d8248405fcb6c8e9569664/test/core/select.wast#L22)):

```
(module
  (func (export "select_unreached")
    (unreachable) (select)
    (unreachable) (i32.const 0) (select)
    (unreachable) (i32.const 0) (i32.const 0) (select)
    (unreachable) (f32.const 0) (i32.const 0) (select)
    (unreachable)
  )
)
```

and the following is supposed to fail (from [here](https://github.com/WebAssembly/spec/blob/2d821d9394549dd406d8248405fcb6c8e9569664/test/core/unreached-invalid.wast#L26))?:

```
(module
  (func $type-poly-num-vs-num (result i32)
    (unreachable) (i64.const 0) (i32.const 0) (select)
  )
)
```

The semantics for validation say "A polymorphic stack also matches any possible signature at the end of a block or function. After the end of a block, the stack is determined by the block signature and the stack before the block." This means to me that the second one there that is supposed to be invalid should be valid because it's a polymorphic stack that should match the sig at the end of the implicit block. What am I missing?

**Comment by dschuff** [comment]
The latter is invalid not because of the operands of the select, but because the result of the select (i64) doesn't match the result of the function (i32).

**Comment by cretz** [comment]
@dschuff - But the quote I gave specifically says the "polymorphic stack matches any possible signature at the of a [...] function". So why doesn't that hold true here?

**Comment by dschuff** [comment]
The stack is polymorphic after the unreachable (which is why the select is valid), but the select still leaves a concrete i64 on the stack. IIUC, if you were to consume that i64 (with e.g. `drop`) then the stack above the i64 would be polymorphic again and it would be valid.

**Comment by kripken** [comment]
In other words the second example is the same as this,
````
(module
  (func $type-poly-num-vs-num (result i32)
    (unreachable) (i64.const 0)
  )
)
````
And the popped `i64` causes the error. The select is a red herring.

**Comment by cretz** [comment]
Gotcha. I was considering that sample code as valid too. As soon as I saw an unconditional branch I was marking that entire implicit branch as having a polymorphic stack for the rest of its execution per the doc. I wasn't expecting to have to match the branch's result type based on other tests, but I'll make sure to do so here. I assume the behavior is the same as if it were an explicit block w/ an i32. I suppose it would succeed in an empty stack, it's just that is the wrong type that fails. Thanks.

**Comment by binji** [comment]
@cretz I wrote a blog post about type-checking [here](https://binji.github.io/2017/03/05/webassembly-type-checking.html), that might help. :-)

**Comment by cretz** [comment]
@binji thanks, will read. My code is at https://github.com/cretz/asmble, it's early but I have most of the checking down save for some of these oddities. I think the language does need to be amended to not say it matches all sigs.

**Comment by rossberg-chromium** [comment]
@cretz, the text in the design doc is just a rough hint. For a proper spec of validation see here:

https://webassembly.github.io/spec/validation/index.html

A pseudo code algorithm implementing this spec:

https://docs.google.com/document/d/1E9zNSnATBeETbIAcrwblDrEKKaR5enjNNk4PhlN0a4c/

**Comment by cretz** [comment]
I have applied this [change](https://github.com/cretz/asmble/commit/989ae254299251beb3eb32404767de7ac8b0b31d#diff-63c8add2afb42fa47f69f2e5dcac7ae1) to my compiler and successfully pass the tests. Should this issue remain open or shall I close it?

**Comment by binji** [comment]
I think it's fine to close, since there's no work to do in the design repo.
