### ISSUE TITLE
get type for given table index / nested tables

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/design#1032]
It might be usefully to have an operation the returns a type for an element in a table given that table and the index of the element.  Also it might be use to have an 'table type' table which just hold opaque references to other tables. 

With these two things I think you could generalize a wasm container as tables, where each section would be an element in a table.

**Comment by rossberg-chromium** [comment]
Wasm has no runtime types, so when you say "returns a type", what would that mean concretely?
