### ISSUE TITLE
Binary Encoding: Add counts of each external kind to the imports section

### ISSUE THREAD

**Issue by Bablakeluke** [WebAssembly/design#1033]
We're currently implementing a WebAssembly runtime in .NET - essentially going from WebAssembly to CIL _(the much easier direction!)_

Presently we must parse the whole imports section into a collection of Vectors (Lists in our case) to establish how many imported functions/ globals etc there actually are. If there were fields which declared e.g. `there's 340 imported functions` or `there's 1120 imported globals` then we can use fixed size arrays instead and ultimately know things like how big the function index actually is very quickly. We're experimenting with multiple modules working together so those import numbers _get big fast_ making those fixed array gains all the more worthwhile.

**Example:** We don't know there's 1120 imported globals - we just know there's a few thousand imported things. As we parse the imports section, we add each one to a List of global-kind entries. _That list gets resized 10 times_. If there was a field somewhere declaring that 1120, we can avoid those unnecessary resizes.

Some small further gains may be possible by sorting the imports section by `external_kind` to tidy up the sections currently fragmented layout and then removing the per-entry kind field. I.e, structuring the imports section more like this:

| Field | Type | Description |
|---|---|---|
| count  | `varuint32`  | The number of import kinds in this section  |
| kinds | `kind_type*`  | Each imported kind  |

`kind_type`:

| Field | Type | Description |
|---|---|---|
| external_kind  | `external_kind`  | The kind of all of these entries being imported  |
| count | `varuint32`  | **The number of entries of this kind**  |
| entries | `import_entry*`  | All the entries of this kind. `import_entry` does not need the `kind` field.  |

The main gain here is we can immediately create those fixed arrays as we know e.g. how many imported globals there are/ how many imported functions there are etc.

**Comment by jfbastien** [comment]
Maybe I'm misunderstanding, but this looks like a binary format breaking change? Two browsers have already shipped WebAssembly, so the binary format has to remain stable. Only additive changes can go in from now on, unless there's a really good reason to break things.

I'm also not convinced that this is a really big issue. It's ever so slightly inefficient but I really don't find it compelling compared to the amount of work that's spent compiling right after this is done.

WebAssembly to CLI sounds fun though! Looking forward to hearing more.

**Comment by binji** [comment]
There is some additional discussion here: #882

**Comment by Bablakeluke** [comment]
Yep you're right - after implementing almost all of the runtime, this is the _only thing_ I'd consider a slight flaw _(it's very impressive - excellent work!)_ so in the pursuit of perfection I'm essentially just being picky!

There is an alternative which doesn't require any binary changes - slightly change the definition of the function/ global index etc values. It was the definition of the function index which was throwing me off - I ultimately just looked at the source of the tools to figure out the correct way to link them.

So, instead of it being defined as increasing whenever there's another imported function, it's simply relative to all imported things. No lists/ counts are required here as the linker just directly uses `entries` and `types`:

    if(functionIndexToFind < ImportSection.Count)
      // Use ImportSection.Entries[functionIndexToFind], verifying that it's actually a function entry

    // Otherwise, use FunctionSection.Types[functionIndexToFind - ImportSection.Count];

For example, if we want function 14 and there's 10 imported things, then it's a local function. If we wanted function 8, then it's just the 8th imported entry.
