### ISSUE TITLE
Create SIMD repo to discuss SIMD proposal?

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/design#1035]
People are [interested](https://github.com/stoklund/portable-simd/issues/2) in discussing what SIMD in wasm would look like, starting from the current [portable-SIMD](https://github.com/stoklund/portable-simd/blob/master/portable-simd.md) proposal.  I propose creating a new github.com/webassembly/simd repo that is a fork of the spec repo which can host SIMD-scoped discussions (similar to what is being proposed for [GC](https://github.com/WebAssembly/design/pull/1022#issuecomment-291587910)).  Initial discussion would probably be around .md files in a new /proposals/simd subdir and could later progress to modifications to the spec text and interpreter.  Make sense?

**Comment by jfbastien** [comment]
I do like the format in the design repo. Tables are easy to read :)

**Comment by arunetm** [comment]
Thanks @lukewagner. Is there a plan/need to migrate these new proposals to the main Wasm/Design repo once they mature with implementations? 
It is useful for implementations to have toolchain support (like wabt) for these features even before spec/interpreter can be updated. I think it makes sense to have these reside in private forks until the feature gets added to the spec/interpreter. Any thoughts?

**Comment by jfbastien** [comment]
Tools like wabt can just support "extensions" IMO, without needing forks.

**Comment by binji** [comment]
A number of folks have asked about adding extensions to wabt. I agree that it would be good to support extensions w/out forks, but I'd like to make sure we can do it in a way that doesn't make it difficult to maintain.

**Comment by lukewagner** [comment]
@arunetm Yes, I think the idea of these feature repos is that they culminate with their branch being merged into the main spec repo and the feature repo either being retired/archived or moved on to a new "v.2" branch of the feature.

**Comment by stoklund** [comment]
I've updated the [WebAssembly mapping in the portable SIMD repo](https://github.com/stoklund/portable-simd) to use a single `v128` type plus the boolean vectors. This eliminates all of the reinterpret operations.

**Comment by Art** [comment]
Please let me know ... where best to post this issue.

Please consider - '...A new data type called a "posit" is designed for direct drop-in replacement for IEEE Standard 754 floats ...' From Dr. John L. Gustafson's intro:
[John Gustafson presents: Beyond Floating Point – Next Generation Computer Arithmetic
](http://insidehpc.com/2017/02/john-gustafson-presents-beyond-floating-point-next-generation-computer-arithmetic/)
Google Groups thread -
[POSIT (Unums "type 3") talk with live demonstration @ Stanford. February 1st 2017
](https://groups.google.com/forum/#!topic/unum-computing/FCataJnoxFc)  
"**_A new data type called a "posit"_** is designed for direct drop-in replacement for IEEE Standard 754 floats. Unlike unum arithmetic, posits do not require interval-type mathematics or variable size operands, and they round if an answer is inexact, much the way floats do. However, they provide compelling advantages over floats, including simpler hardware implementation that scales from as few as two-bit operands to thousands of bits. For any bit width, they have a larger dynamic range, higher accuracy, better closure under arithmetic operations, and simpler exception-handling. For example, posits never overflow to infinity or underflow to zero, and there is no "Not-a-Number" (NaN) value. Posits should take up less space to implement in silicon than an IEEE float of the same size. With fewer gate delays per operation as well as lower silicon footprint, the posit operations per second (POPS) supported by a chip can be significantly higher than the FLOPs using similar hardware resources. GPU accelerators, in particular, could **_do more arithmetic per watt_** and per dollar yet deliver superior answer quality."

Thanks @lukewagner for all you and the WA community do. I love WebAssembly ... it enables magic like [webDSP WebAssembly Video Editor](https://d2jta7o2zej4pf.cloudfront.net/)! 
I'd like to see webDSP 'posit arithmetic' enabled and similar, any IEEE 754, and, SIMD WebAssembly projects too.

**Comment by lukewagner** [comment]
I created github.com/webassembly/simd, so closing out this issue.

@Art This issue is scoped pretty narrowly to just the administrative task of creating a repo in which to discuss SIMD, so probably better to create a new issue for posits.

**Comment by binji** [comment]
Actually closing this issue. :-)
