### ISSUE TITLE
Does local variables count include function arguments?

### ISSUE THREAD

**Issue by piranna** [WebAssembly/design#1037]
On the docs of the binary format, we have a field to specify how much arguments a function has (and its types) and another for how much local entries (local variables) does it have, mostly to reverse space in advance on the stack for them. I know both function arguments and local variables are in the same space and are accessed the same way (`get_local()` and `set_local()`), but does the count of the local variables includes the needed space for the function arguments, or does it needs to be added to it? It's not clear on the spec of the binary format...

**Comment by hammacher** [comment]
The index space for local variables contains the parameters **plus** local variables.
Note that in the binary encoding spec, the `local_count` is defined as "number of local entries", not local variables. Each entry contains a `count` itself.
Thus the index space for `get_local` and `set_local` is `param_count` of the current function type plus the sum over all `count` of local entries.

**Comment by nidin** [comment]
Simple answer: Yes.
local variables count include function arguments!
total locals = function arguments + local variables.
first local variable index = num function arguments + 0
second local variable index = num function arguments + 1

**Comment by piranna** [comment]
That's what I supposed :-) Maybe we should put it explicitly on the spec?

**Comment by rossberg-chromium** [comment]
@piranna, it is: http://webassembly.github.io/spec/syntax/modules.html#functions ;)

**Comment by nidin** [comment]
It is a confusion between local entries vs local variables. spec explicitly saying local entries.

**Comment by binji** [comment]
Closing, since the question seems to be answered. Please reopen if otherwise.
