### ISSUE TITLE
Require an ok status for instantiate responses?

### ISSUE THREAD

**Issue by annevk** [WebAssembly/design#1039]
It seems that may you want to require response's status to be an https://fetch.spec.whatwg.org/#ok-status to avoid compiling a 404 or 500 as WebAssembly.

**Comment by annevk** [comment]
(`<script>` does that too, if that helps make a decision.)

**Comment by jfbastien** [comment]
Seems like a good thing.

wasm files start with `\0asm` though, so the problem you describe would rather manifest as insta-fail compilation. Still a surprising results!

**Comment by annevk** [comment]
Well, theoretically a 404 could be WebAssembly, just like it could be JavaScript. In case of JavaScript it still won't execute though and if you make this change WebAssembly won't either.

**Comment by domenic** [comment]
Yeah, there's no requirement that 404 response bodies be text; they can be arbitrary byte streams.

I hope someone is writing web platform tests for things like this.

**Comment by gulbanana** [comment]
theoretically it might make sense to have a 404 as wasm in some future where people browse to .wasm apps directly

**Comment by annevk** [comment]
@gulbanana that is fair, but that would require integration with the navigation algorithm defined in the HTML Standard and we could make different decisions about 404 handling there.

**Comment by gulbanana** [comment]
you're right, that possibility doesn't have to be encoded in the instantiate api

**Comment by jfbastien** [comment]
@annevk would you be OK doing the PR for this?

**Comment by annevk** [comment]
Maybe, is `Web.md` the only resource to modify?

**Comment by jfbastien** [comment]
I believe so. The distinction between Web.md and JS.md is kinda weird IMO, but I think Web.md is right for now.
