### ISSUE TITLE
Clarification of types array and duplicate sigs

### ISSUE THREAD

**Issue by cretz** [WebAssembly/design#1041]
On https://github.com/WebAssembly/spec/blob/8c517ac81ca9f3f412ed88ef5d8eaf4189f3c53b/test/core/func.wast#L175 the `call_indirect` references function type 16. So which one does 16 point to? Specifically, it appears the order that types are added and deduped matters, correct? What are the rules about how to build the func type list when parsing sexprs?

(also, should this issue be in that repo or here?)

**Comment by rossberg-chromium** [comment]
The rule is that all function declarations (imports and definitions) are processed in order of appearance, and each inline function type is appended to the type section unless the same type is already present there. The type index used will then be the first suitable occurrence of such a type in the type section.

Of course, this will eventually be specified properly in the spec.

**Comment by cretz** [comment]
Perfect, thanks.

**Comment by cretz** [comment]
Actually, sorry to reopen, I am curious how this affects going from AST to sexprs. Any suggested algorithm for outputting the sexprs without having all of the `type` exprs at the top that are otherwise only used by imports/defs? I obviously can't just say "put all `type` exprs at the top that aren't represented by an import or func def" because things like `call_indirect` reference them by a specific index and there's a good bit of backwards work to make sure, for example in this case, the right type ends back up at index 16.

I assume the machine generated sexpr format (i.e. not hand written) will just have every possible type at the top even though it's quite redundant. True?

**Comment by cretz** [comment]
Also, when I look at [func_ptrs.wast](https://github.com/WebAssembly/spec/blob/6a01dab6d29b7c2b5dfd3bb3879bbd6ab76fd5dc/test/core/func_ptrs.wast#L10) the linked `import` references type 6. Does this mean that the explicit `type` entries can have duplicates and don't follow the "add type only of it doesn't exist" rule that imports and defs do?

**Comment by binji** [comment]
Explicit type definitions always create a new entry. Without this behavior, it would be impossible to represent this behavior from the binary format in the text format.

It may be useful to see the output of running wabt's wast-desugar tool on func_ptrs.wast:

```
(module
  (type (;0;) (func))
  (type $S (func))
  (type (;2;) (func))
  (type (;3;) (func (result i32)))
  (type (;4;) (func (result i32)))
  (type $T (func (param i32) (result i32)))
  (type $U (func (param i32)))
  (import "spectest" "print" (func $print (type $U)))
  (func (;1;) (type 0))
  (func (;2;) (type $S))
  (func (;3;) (type 4) (result i32)
    i32.const 13)
  (export "one" (func 3))
  (func (;4;) (type $T) (param i32) (result i32)
    get_local 0
    i32.const 1
    i32.add)
  (export "two" (func 4))
  (func (;5;) (type $T) (param $a i32) (result i32)
    get_local $a
    i32.const 2
    i32.sub)
  (export "three" (func 5))
  (func (;6;) (type $U) (param i32)
    get_local 0
    call $print)
  (export "four" (func 6)))
```

It's currently limited to just showing one module, unfortunately.

**Comment by cretz** [comment]
Yup, here's my desugaring of the same thing:

```
(module
  (import spectest print (func (param i32)))
  (export one (func 3))
  (export two (func 4))
  (export three (func 5))
  (export four (func 6))
  (func)
  (func)
  (func (result i32) (i32.const 13))
  (func
    (param i32)
    (result i32)
    (get_local 0)
    (i32.const 1)
    (i32.add)
  )
  (func
    (param i32)
    (result i32)
    (get_local 0)
    (i32.const 2)
    (i32.sub)
  )
  (func (param i32) (get_local 0) (call 0))
)
```

Now, flipping the bit having it assume there is a `call_indirect` in there does this:

```
(module
  (type (func))
  (type (func))
  (type (func))
  (type (func (result i32)))
  (type (func (result i32)))
  (type (func (param i32) (result i32)))
  (type (func (param i32)))
  (import spectest print (func (param i32)))
  (export one (func 3))
  (export two (func 4))
  (export three (func 5))
  (export four (func 6))
  (func)
  (func)
  (func (result i32) (i32.const 13))
  (func
    (param i32)
    (result i32)
    (get_local 0)
    (i32.const 1)
    (i32.add)
  )
  (func
    (param i32)
    (result i32)
    (get_local 0)
    (i32.const 2)
    (i32.sub)
  )
  (func (param i32) (get_local 0) (call 0))
)
```

Closing issue as I think I got it now...just a reminder (though I know it was already mentioned) to make it clear in the sexpr spec that type can add dupes, import/defs do not. Also it is helpful to say that imports always come before non-imports for reasons of building up function indices. Finally, it would be worth noting that implementers should resolve func indices (and maybe other index tables) ahead of time for forward invocations but it is unnecessary for type indices which is important since duplicate names can point to the same index.

**Comment by binji** [comment]
Looks good, although I personally think it's better to always explicitly list the module's function types and which functions use which types when desugaring. Your desugaring won't ever use `(type 1)` for example, even though it was used by func 2.

**Comment by rossberg-chromium** [comment]
Agreed with @binji, a text rendering should be invertible (i.e., not loose information), which doesn't seem to be the case for yours.

**Comment by cretz** [comment]
Note to future implementers and readers of this issue, this information is no longer accurate as of #512. Now the rule is to process all types in an initial forward-type-ref pass (ignoring funcs) and set as the index, then the rest of the processing including func processing happens, appending types if they are not yet seen.

Therefore, now `func` A of one type followed by a `type` B of another will mean the func type index of A is 1 and B is 0 because B was eagerly pre-processed..

**Comment by rossberg** [comment]
@crezt, I think you mean WebAssembly/spec#512.
