### ISSUE TITLE
Coding for inc/dec

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/design#1042]
I am writing on a [Java to WebAssembly Compiler](https://github.com/i-net-software/JWebAssembly). I am wondering why increment and decrement is such complex. A simple i++ looks like:
```
    get_local 0
    i32.const 1
    i32.add
    set_local 0
```
Are there a better encoding?

**Comment by jfbastien** [comment]
Dup of:
https://github.com/WebAssembly/design/issues/790
and
https://github.com/WebAssembly/design/issues/293

We should add this to the FAQ 😉

**Comment by Horcrux7** [comment]
I interpret your answer that I have encode it correctly. Thanks.

**Comment by jfbastien** [comment]
@Horcrux7 yes, but you can also commute the first two operands, or you could also avoid locals and keep everything on the stack.
