### ISSUE TITLE
new data type "posit" (SigmoidNumber) direct drop-in replacement for IEEE Standard 754 floats ...by Dr. John L. Gustafson (not unum 1 2)

### ISSUE THREAD

**Issue by Art** [WebAssembly/design#1043]
Aloha Hi -- Please consider - '...A new data type "posit" is designed for direct drop-in replacement for IEEE Standard 754 floats ...' From Dr. John L. Gustafson's talk with live demonstration @ Stanford. February 1st 2017

[John Gustafson presents: Beyond Floating Point – Next Generation Computer Arithmetic
](http://insidehpc.com/2017/02/john-gustafson-presents-beyond-floating-point-next-generation-computer-arithmetic/)

"A new data type called a "posit" is designed for direct drop-in replacement for IEEE Standard 754 floats. _**Un**like_ _unum_ arithmetic, posits do not require interval-type mathematics or variable size operands, and they round if an answer is inexact, much the way floats do. However, they provide compelling advantages over floats, including simpler hardware implementation that scales from as few as two-bit operands to thousands of bits. For any bit width, they have a larger dynamic range, higher accuracy, better closure under arithmetic operations, and simpler exception-handling. For example, posits never overflow to infinity or underflow to zero, and there is no "Not-a-Number" (NaN) value. Posits should take up less space to implement in silicon than an IEEE float of the same size. With fewer gate delays per operation as well as lower silicon footprint, the posit operations per second (POPS) supported by a chip can be significantly higher than the FLOPs using similar hardware resources. GPU accelerators, in particular, could _**do more arithmetic per watt**_ and per dollar yet deliver superior answer quality."

 WebAssembly ... enables magic like[ webDSP WebAssembly Video Editor](https://github.com/shamadee/web-dsp)!
I'd like to see webDSP 'posit arithmetic' enabled and similar, any IEEE 754, and, SIMD WebAssembly projects too.

There are two early GitHub "posit" projects currently [C++](https://github.com/libcg/bfp) and [Rust](https://github.com/japaric/posit) ... hope to see them compile to WebAssembly next.
Mahalo Thanks Art

**Comment by sunfishcode** [comment]
WebAssembly should already include everything needed to support reasonable library implementations of posits and other systems. If anyone finds something missing, please do report it.

If you are asking WebAssembly to support posits directly, my advice is that it's too early to consider yet. Library implementations are an appropriate vehicle for early experimentation.

**Comment by sunfishcode** [comment]
Closing, as there doesn't seem to be anything else to consider at the present time.
