### ISSUE TITLE
Add "proposal" topic to WebAssembly proposal repos

### ISSUE THREAD

**Issue by binji** [WebAssembly/design#1056]
See the comment here: https://github.com/WebAssembly/design/issues/950#issuecomment-300007960

It would be useful to be able to track all WebAssembly proposals with one search query, it seems like we could add a `proposal` topic to the repo, then use `org:WebAssembly topic:proposal` to find these.

**Comment by jfbastien** [comment]
Good idea!
Done: https://github.com/search?q=topic%3Aproposal+org%3AWebAssembly&type=Repositories

**Comment by trusktr** [comment]
Looks like this is not in sync with the `proposals` repo.

**Comment by dtig** [comment]
This should work better now, we may be missing some proposals that are already merged and marked as read-only.
