### ISSUE TITLE
Remove "contributors" GitHub team

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#1058]
We currently have 3 GitHub teams with the following access:

* Core (admin)
* Workshop (write)
* Contributors (read)

Additionally some folks have write access to individual repos which they effectively own.

This setup is along the lines of what the W3C guidance suggests (people who contribute a lot get merge privileges like any other open source process).

The "contributors" team is useless though: I created it before the WebAssembly announcement in 2015 so people had private access before everything went public. Everything is now public, read access is universal.

Any thoughts on deleting that group? Reshuffling anything else (I like the setup, but while we're here...)?

**Comment by lukewagner** [comment]
Makes sense to me.

**Comment by annevk** [comment]
No, contributors are useful. They can add labels and be assigned tasks. There's a difference between "read" the permission and being able to read things (as confusing as that is, blame GitHub).

**Comment by jfbastien** [comment]
@annevk thanks, I wasn't aware of this. Good points. I'll see if I can at least rename things to be more intuitive, and prune the lists so we only include recent participants (many in that list have never participated publicly).

Closing.
