### ISSUE TITLE
Versioning of modules

### ISSUE THREAD

**Issue by piranna** [WebAssembly/design#1063]
How is it suppossed that module dependencies versioning will be managed? Will it be used the first one that got to be loaded? There will be conflict problems with that...

**Comment by sunfishcode** [comment]
Core Wasm is a generic computational platform, and dependency resolution mechanisms are considered outside of its scope. It just has imports with simple identifiers that some other layer of a system must arrange to satisfy.

For example, one such higher-level layer is [Wasm Components](https://github.com/WebAssembly/component-model), which support dependency versioning using [embedded semver strings](https://github.com/WebAssembly/component-model/blob/main/design/mvp/Binary.md#import-and-export-definitions).
