### ISSUE TITLE
🛤 threads

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#1073]
**This is a tracking issue for a post-MVP feature**
It will be updated as the issue progresses.

**Topic** threads
**Champion** Ben Smith @binji 
**Status** in progress
**[Phase](https://github.com/WebAssembly/meetings/blob/master/process/phases.md)** Feature proposal
**Linked issues** #992, #950, #730, #485, #314, #300, #104
**Linked repositories** [github.com/WebAssembly/threads](https://github.com/WebAssembly/threads/blob/master/proposals/threads/Overview.md)

# Details

Provide low-level buildings blocks for pthreads-style shared memory: shared memory between threads, atomics and futexes.

New atomic memory operators, including loads/stores annotated with their atomic ordering property, will follow a model compatible with the [C++11 memory model][] (with [some differences](https://github.com/tc39/ecmascript_sharedmem/issues/88)), similarly to the [PNaCl atomic support][] and the [SharedArrayBuffer][] support in JavaScript. Even when there are data races, WebAssembly will ensure that the [nondeterminism](Nondeterminism.md) remains limited and local.

There is ongoing work to [formalize the memory model used by SharedArrayBuffer](https://github.com/tc39/ecmascript_sharedmem/issues/133). This can be used by WebAssembly threads, since both JavaScript and WebAssembly are intended to be able to communicate through SharedArrayBuffer.

  [C++11 memory model]: http://www.hboehm.info/c++mm/
  [PNaCl atomic support]: https://developer.chrome.com/native-client/reference/pnacl-c-cpp-language-support#memory-model-and-atomics
  [SharedArrayBuffer]: https://github.com/tc39/ecmascript_sharedmem

**Comment by binji** [comment]
Moved to https://github.com/WebAssembly/proposals/issues/14.
