### ISSUE TITLE
🛤 fixed-width SIMD

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#1075]
**This is a tracking issue for a post-MVP feature**
It will be updated as the issue progresses.

**Topic** Fixed-width SIMD
**Champion** @PeterJensen, @arunetm
**Status** in progress
**[Phase](https://github.com/WebAssembly/meetings/blob/master/process/phases.md)** Feature proposal
**Linked issues** #148, #41
**Linked repositories** [github.com/WebAssembly/simd](https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md)

# Details

Support fixed-width SIMD vectors, initially only for 128-bit wide vectors as demonstrated in [PNaCl's SIMD][] and [SIMD.js][].

SIMD adds new local types (e.g., `f32x4`) so it has to be part of the core semantics. SIMD operators (e.g., `f32x4.add`) could be either builtin operators (no different from `i32.add`) or exports of a builtin SIMD module.

  [PNaCl's SIMD]: https://developer.chrome.com/native-client/reference/pnacl-c-cpp-language-support#portable-simd-vectors
  [SIMD.js]: https://github.com/tc39/ecmascript_simd

**Comment by binji** [comment]
Moved to https://github.com/WebAssembly/proposals/issues/1.
