### ISSUE TITLE
Unclear how to resolve/reject promises for response based compile API

### ISSUE THREAD

**Issue by jeisinger** [WebAssembly/design#1081]
Right now, the spec says that the API will run an asynchronous task that eventually resolves the promise. It's a bit unclear to me what an asynchronous task should be, it would be great to explicitly reference an event loop model to explain what this is.

Furthermore, in HTML's event loop model, only regular tasks enter a microtask checkpoint. Without doing this, resolved promise will be left hanging until something else spins the event loop again.

I'd expect that the spec here uses similar terms as e.g. fetch, i.e, when a response promise is passed in and the method doesn't immediately abort, it will finish the compilation asynchronously and when the module is ready create a task on the main event loop and that task resolves the promise.

**Comment by domenic** [comment]
Will work on a PR.

**Comment by littledan** [comment]
Should JS.md be more explicit in a similar way? @kmiller68 's 3fb9bce77588f45912e791f60daede1183112772 does mention "queueing a task" for one of the Promise-returning functions, but it doesn't say on which queue. Should this be the microtask queue?

**Comment by domenic** [comment]
Yes, it should be more explicit; no, you cannot enqueue a microtask from a background thread, you need to use a normal task queue.

**Comment by littledan** [comment]
Seems like the wording introduced in the patch here makes the start function (part of instantiation) run "in parallel" as well. I assume that was unintentional, right? If so, I'll try to fix it, as part of the Bikeshed conversion.

**Comment by domenic** [comment]
Ah, yeah, I didn't realize WebAssembly instantiation needed to happen on the main thread. So I guess it's only compilation that makes sense on the background thread. This might significantly simplify the spec, e.g. since now the same steps are performed in parallel by both. Thanks for catching <3

**Comment by littledan** [comment]
I'm not sure which parts real implementations do off the main thread, actually. I don't see a reason why steps 1-16 of instantiation couldn't be on another thread; I need to learn more about what implementations do.

**Comment by lukewagner** [comment]
Incidentally, I filed [design/#1131](https://github.com/WebAssembly/design/issues/1131) about instantiation running in parallel; it could be closed once fixed in the new JS spec.
