### ISSUE TITLE
Code Coverage integration?

### ISSUE THREAD

**Issue by binji** [WebAssembly/design#1082]
Not sure the best place to file this issue. I was thinking it would be nice to add code coverage to wabt. I already [have a build](https://github.com/WebAssembly/wabt/blob/master/CMakeLists.txt#L27), and thought it would be good the info displayed on github.

Some questions:
* Do other WebAssembly repos want this?
* Which coverage integration tool should we use?

**Comment by sunfishcode** [comment]
Closing, as there doesn't seem to have been interest in this.

**Comment by sunfishcode** [comment]
The original post here was about coverage of wabt's own code, rather than WebAssembly code. If anyone would like to start a discussion on a new topic, please file a new issue!
