### ISSUE TITLE
Mutability flag missing on the binary encoding page

### ISSUE THREAD

**Issue by s3ththompson** [WebAssembly/design#1084]
Reposting WebAssembly/website#92 from @Bablakeluke:

> `global_entry` defines a mutability flag which is mentioned but not displayed here:
> 
> http://webassembly.org/docs/binary-encoding/#global-entry
> 
> I believe the table should be like this instead:
> 
> | Field | Type | Description |
> |---|---|---|
> | flags | `varuint1` | mutability flag |
> | type  | `global_type`  | type of the variables  |
> | init | `init_expr`  | the initial value of the global  |

**Comment by binji** [comment]
No, it is correct. global_type is defined as:

global_type

The description of a global variable.

| Field | Type | Description |
| -- | -- | -- |
| content_type | value_type | type of the value |
| mutability | varuint1 | 0 if immutable, 1 if mutable |

**Comment by binji** [comment]
It's also worth noting that the spec at webassembly.github.io/spec is much more thorough and should be preferred in most cases. See for example: https://webassembly.github.io/spec/binary/types.html#global-types
