### ISSUE TITLE
How to implement pointers

### ISSUE THREAD

**Issue by maierfelix** [WebAssembly/design#1090]
Hello, I hope this is the right place for my problem.

I'm currently trying to create a small C-ish language which compiles to Wasm but got stuck on how to correctly implement pointers.

If variables get accessed by the adress-of operator, they get stored inside memory with the same principle as asm.js's STACKTOP variable. Pointers get pushed into memory as well and just save the adress they point to.

But as soon as we try to change the *pointer's adress* itself, this doesn't work, since the pointer's adress is created at compile time and thus cannot be changed at runtime.

Pseudo code to show the problem:
````c
i32 *ptrA; // '0
i32 *ptrB; // '4
ptrA = ptrB; // ptrA=4, ptrB=4
*ptrA, *ptrB // correct adress resolving
ptrA == ptrB // incorrect, ptrA='0, ptrB='4
````

The project's demo is [here](http://maierfelix.github.io/mini-wasm/) if that helps, sauce is spaghetti

**Comment by RyanLamansky** [comment]
This seems like an issue with the design of the language you're creating, not an issue with WebAssembly itself.

WebAssembly doesn't natively have a special pointer type, i32 serves this purpose just as it's used for any other place where a 32-bit integer is needed.

**Comment by maierfelix** [comment]
I fixed the issue by storing another 4 bytes into the pointers memory offset, holding the actual memory address of it. I'm unsure if this is the optimal solution, but hopefully this will be useful for someone stumbling over the same issue in the future.
