### ISSUE TITLE
Do names in the names section need to be unique?

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/design#1094]
Right now a lot of the wasm tooling won't handle multiple functions with the same name.   e.g. wasm2wast will generate an invalid wast file with multiple functions with the same label (which is not valid wast) and wasm-dis will error out.

I'm working on a port of lld it seems quite common to link objects that contain the same local symbol.  This result in a binary which has many duplicate local symbols.

Up until now most of our tooling is based around llvm-link which seems to rename duplicate locals by adding a number to the end, so the final binary has foo.1, foo.2 etc, so this issue has been hidden.

**Comment by sbc100** [comment]
I  propose that we match the native ELF world and explicitly allow multiple functions to have the same name.  The tooling will need to handle this, so it will be up to wasm2wast or wasm-dis to uniquify the names when using them as labels in a wast file (where they do need to be unique).

**Comment by kevinbarabash** [comment]
When linking multiple wasm files together, are you modifying function indexes?  I'm curious about how "start" sections are dealt with, do you only allow a single wasm file to have a "start" section when linking them?

**Comment by jfbastien** [comment]
There can only be a single start section. A linker would have to chain-call them, similar to how static initialization is performed across `.o` files.

**Comment by sbc100** [comment]
Regarding the start section, basically what JF said. 

Regarding function indexes, yes they all need to get updated and re-wriiten . This is currently done by emitting relocation entries for each place a function index (or type or global) is written.

The currently plan is that the wasm files accepted by the linker will have certain restrictions on them, and should follow the conventions layed out in https://github.com/WebAssembly/tool-conventions/blob/master/Linking.md. Linking arbitrary objects together is currently not a goal.
