### ISSUE TITLE
Is the AST syntax deprecated in the Text Format?

### ISSUE THREAD

**Issue by thelonious** [WebAssembly/design#1097]
While looking over the WebAssembly repos, I saw this comment in [wasm-jit-prototype](https://github.com/WebAssembly/wasm-jit-prototype/blob/master/README.md)

> For the text format, it can load both the standard stack machine syntax and the old-fashioned AST syntax used by the reference interpreter...

It wasn't clear to me if `old-fashioned` meant that this syntax would not be supported in the spec. When I look at the grammar in the [spec/README.md](https://github.com/WebAssembly/spec/blob/master/interpreter/README.md) I see a production for expressions:

```
expr:
  ( <op> <expr>+ )
```

But I don't think this exists in the [spec on github.io](https://webassembly.github.io/spec/text/instructions.html#expressions).

Can you please clarify if the AST syntax can be used or should we standardize on the stack machine syntax?

Thanks!

**Comment by MikeHolman** [comment]
As I understand, the s-expr syntax is non-normative syntax for convenience in unit tests. S-exprs can't well represent the full range that a generic stack machine syntax can, and in some areas there are odd consequences from using s-exprs which is why it is not the standard. That said, the s-expr syntax isn't going anywhere, and I think it will be supported by wabt, the spec interpreter, and whatever else currently supports it for many years to come.

**Comment by thelonious** [comment]
I'm glad to hear the AST style will likely be around for a while. Can you share some examples where s-exprs will be too limiting?

Thanks for the quick response.

**Comment by binji** [comment]
> As I understand, the s-expr syntax is non-normative syntax for convenience in unit tests.

The "folded" syntax is [explicitly mentioned in the spec](https://webassembly.github.io/spec/text/instructions.html#folded-instructions). When we discussed the text format in the past, a few people mentioned that they found it easier to read than the flat syntax, so we decided to make it official. It's just syntactic sugar over the flat syntax, though, so it can have some surprising behavior. For example, the following are all valid and produce the same instruction sequence:

```
(i32.add (i32.const 1) (i32.const 2))
(i32.const 1) (i32.add (i32.const 2))
(i32.const 1) (i32.const 2) (i32.add)
i32.const 1 i32.const 2 i32.add
```

> I'm glad to hear the AST style will likely be around for a while. Can you share some examples where s-exprs will be too limiting?

The example we often referenced in the past was an operation returning no values. For example:

```
flat:
i32.const 1
nop
i32.const 2
i32.add
```

This cannot be completely folded:

```
(i32.const 1)
(nop)
(i32.add (i32.const 2))
```

There may need to be some special syntax for multiple return values as well (when those are added):

```
(func $returnTwo (result i32 i32) i32.const 1 i32.const 2)
(func (result i32 i32)
  call $returnTwo  ;; stack: => 1 2
  i32.const 1      ;; stack: => 1 2 1
  i32.add)         ;; stack: => 1 3
```

AIUI, common lisp uses `values` and `multiple-value-bind` to handle this case.

**Comment by thelonious** [comment]
> The "folded" syntax is explicitly mentioned in the spec.

Ah, yes. I didn't know the correct terminology when looking for that.

> It's just syntactic sugar over the flat syntax, though, so it can have some surprising behavior.

Agreed. FWIW, I see it as being more useful for hand-written assembly or even naive code generation made for human readability.

> Can you share some examples where s-exprs will be too limiting?

Thanks for those. That all makes sense.
