### ISSUE TITLE
Hint to flag off asm.js AOT

### ISSUE THREAD

**Issue by buu700** [WebAssembly/design#1100]
This isn't exactly a WebAssembly feature proposal, but it's directly related so I thought this would be a good place to suggest it.

I maintain a few libraries that I recently migrated from asm.js to wasm with an asm.js fallback. I'd expected that stripping out the `'use asm'` statements would be enough to prevent preemptive AOT compilation of the asm.js code, but when running the library in the latest Firefox I still see the usual console messages with asm.js compilation durations despite that the asm.js is never actually being executed.

It seems to me that what I'm doing will inevitably become a common pattern (if it isn't already) that WebAssembly-supporting browsers should optimise for. Possible solutions that come to mind:

1. Specifically avoid AOT compiling otherwise valid asm.js that doesn't begin with `'use asm'` (at least until it's actually being executed).

2. Add support for a new statement like `'use lazy-asm'` that could be included before a `'use asm'` to hint that preemptive AOT compilation should be avoided.

3. Add a heuristic to determine when a particular asm.js block is probably being used as a fallback for a wasm module.

**Comment by lukewagner** [comment]
asm.js AOT in FF is specifically keyed on presence of the 'use asm' processing directive, if you remove that it shouldn't trigger AOT; perhaps this is just a simple caching bug and you're running stale contents?

**Comment by buu700** [comment]
Oh. Yeah, it looks like you're exactly right; I just tested with a stale cache. Sorry about that.

Well that's pretty cool then; glad to know it's already doing exactly what I need it to!
