### ISSUE TITLE
How can I use .wasm in Web

### ISSUE THREAD

**Issue by skyfore** [WebAssembly/design#1104]
My problem is when I compile a C++ file to .wasm by **emscripten**, I got `a.out.wasm` file. 
and then when I use in browser:
```js
fetch('a.out.wasm').then(res => res.arrayBuffer())
  .then(bytes => WebAssembly.instantiate(bytes))
```
I got error:  _Imports argument must be present and must be an object_

I know there should be an importObject , but I don't know what objcet I need to given

> my c++ file is very simple that just printf "hello world". Can someone help me, thx!

**Comment by skyfore** [comment]
I just want to express how can I use `.wasm` file if I don't depend on **emscript**.
If I have a OpenGL c++ file and I compile to .wasm , **just a `.wasm` file**
and how can I display my c++ app on web app?

Also, I'm not clear understand the relationship between `WebAssembly` and `emscripten`, I just know `emscripten` can output _js/bc/html/wasm_ etc. 

In `WebAssembly`, just import `.wasm` to browser and use it.

**Unfortunately** , I don't know how to use it. :sob:

**Comment by nidin** [comment]
You need to bootstrap **.wasm** via emscripten helper javascript file. compiled .wasm modules is importing env object from javascript.

**Comment by nidin** [comment]
Check this out https://github.com/kripken/emscripten/blob/6dc4ac5f9e4d8484e273e4dcc554f809738cedd6/site/source/docs/porting/multimedia_and_graphics/OpenGL-support.rst
Also 
https://github.com/kripken/emscripten/tree/master/tests

**Comment by skyfore** [comment]
@nidin yes, I know and I just want to express compile OpenGL ES2 application to .wasm file and use in my web browser by WebAssembly API.
 
And I had read the doc about https://github.com/kripken/emscripten/blob/6dc4ac5f9e4d8484e273e4dcc554f809738cedd6/site/source/docs/porting/multimedia_and_graphics/OpenGL-support.rst.
Also had try demo in https://github.com/kripken/emscripten/tree/master/tests/glbook.

But, I'm not feel good. Because I just got a `static canvas`, just like a pic.

> My system environment: Ubuntu 16.04, emcc 1.37.15, clang 4.0.0

I expect to got a canvas that have interaction. such as `mouse event` or i`nput event`.

> Just like WebAssembly.ory demo but more small.

**Comment by nidin** [comment]
You need to handle events manually. check this demo https://github.com/kripken/emscripten/blob/master/tests/test_html5_mouse.c

**Comment by Becavalier** [comment]
@skyfore  

Checkout this one: https://github.com/shamadee/web-dsp, maybe helpful.

**Comment by skyfore** [comment]
@Becavalier Thanks ! It's helpful.

**Comment by sunfishcode** [comment]
The question in this issue appears to be answered; please reopen or file a new issue if there are any further questions.
