### ISSUE TITLE
WebAssembly corresponds to which representation?

### ISSUE THREAD

**Issue by kanishkdudeja** [WebAssembly/design#1105]
Hello,

Just wanted to ask a simple question. I've been reading several documents about WebAssembly and about the binary and the text formats. Just have a few fundamental doubts about what WebAssembly exactly is

Is WebAssembly by definition the binary format (which is encoded from the text format) or the text format (which is encoded to the binary format). Or is it some other third format?

When we say WebAssembly is a low level assembly language for the web, what does "language" here mean? It corresponds to which representation?

Also, this line is mentioned in the design doc.

"Wasm bytecode is designed to be encoded in a size- and load-time-efficient binary format."

What does Wasm bytecode refer to here? Does it mean the textual format or the binary format? If it is the binary format, why does it need to be encoded again?

Sorry, these are dumb questions. I'm planning on writing an introductory article for WebAssembly and just wanted to make sure that I understand the concept deeply and clearly.

**Comment by RyanLamansky** [comment]
WebAssembly is a binary format.  The bytecode is how instructions are represented in the binary file.

The text format you see in some samples is a way to represent the binary data in a more human-readable way.

WebAssembly binary files can be produced from several sources, including the text format you referred to, but larger applications typically use C++.  There are experimental projects to enable conversion from other sources to WebAssembly files.

**Comment by kanishkdudeja** [comment]
Thanks for the clarifications Ryan. They help bring much needed clarity.

**Comment by rossberg-chromium** [comment]
I would like to offer a slightly different angle: WebAssembly is a
language, and that language happens to have two concrete syntaxes, one
binary, and one textual. They serve different purposes, but both equally
represent Wasm code and both are interconvertible. However, the binary
format is the "primary" representation in the sense that it is what engines
consume.

**Comment by kanishkdudeja** [comment]
Thanks Rossberg for your answer. :)
