### ISSUE TITLE
What's better performance ?

### ISSUE THREAD

**Issue by extremety1989** [WebAssembly/design#1106]
Calling C++ code from javascript using bindings like 

"add.cpp"
#include <emscripten/bind.h>
using namespace emscripten;
int add(int x, int y){
    return x + y;
}
EMSCRIPTEN_BINDINGS(my_module){
    function("add",&add);
}

and from javascript 
    var result = Module.add(2,4)
    console.log(result)

or just using 

var response = fetch('add.wasm')
var buffer = response.arrayBuffer()
var {instance} = WebAssembly.instantiate(buffer,{})
var result = instance.exports.add(2,2)
 console.log(result)

i want to know which one is the better in performance or maybe faster ?

**Comment by jfbastien** [comment]
Did you try them, in different browsers?

**Comment by extremety1989** [comment]
Yes but, which approche is the best calling C++ function from js using BIND or fetching wasm file ?

**Comment by extremety1989** [comment]
Does someone here know which approche is the best ? calling c++ fuction with bind from javascript module or just fetch wasm file ? i'm just curious =)

**Comment by RyanLamansky** [comment]
I'm not aware of any benchmarking efforts for WebAssembly yet, so there's a it's possible no one knows for sure.  Please test it yourself and publish the results 🙂

**Comment by jfbastien** [comment]
I suggest benchmarking and profiling these, and reporting any bad performance to Emscripten.
