### ISSUE TITLE
If WebAssembly supply higher data security than Javascript.

### ISSUE THREAD

**Issue by messset** [WebAssembly/design#1107]
First,Thanks for your contributions!

In my project,I hope no body has access to most data in the program easily.
(Like IE ActiveX or other Chrome,Firefox plugins)
For protecting some personal infos and mechanisms of verifying,it needs to avoid some attacks as much as possible.
That's my motivation for using WebAssembly rather writing pure javascript.

Wasm is low level format,that is helpful to iobfuscate the code
However,I'm confused for something.

for example
I use memory buffer to pass string from wasm to Js.
However,I find that if I pass string(char array) between two function in the same wasm,it would store in memory too.
(as the Introduction says https://rsms.me/wasm-intro)
Is it mean somebody can get the string parameter in wasm from Js?
Or,does anyone have access to the stack & const ,static ,local variable & memory data by Js or other ways?

Thanks!

**Comment by jfbastien** [comment]
I think this document addresses your concerns:
https://github.com/WebAssembly/design/blob/master/Security.md
