### ISSUE TITLE
Q: Which is faster?

### ISSUE THREAD

**Issue by Becavalier** [WebAssembly/design#1113]
A method wrote in webassembly and the same method of native javascript function, which one will be faster?

**Comment by jfbastien** [comment]
That's highly dependent on exactly what code you're looking at. The [envisioned usecases](https://github.com/WebAssembly/design/blob/master/UseCases.md) should be faster, but you need to try it out for yourself.

**Comment by nidin** [comment]
It should be similar* with MVP version. Because leading browser vendors did an amazing optimization in JIT compiler
-
* If the implementation is similar. since JavaScript cannot represent int64 natively, wasm will be faster If the implementation uses int64.

Try speedy.js, you can compile Typescript to JavaScript and wasm using LLVM then compare. 
Note. If you translate JavaScript logic 1:1 to wasm, it will be slower as you are missing JIT optimization instead you need to optimize heavily using LLVM.

**Comment by chyingp** [comment]
@Becavalier It depends on many factors, such as how you write your code, how many times a function is called.

Below is an example I tested recently, an `add` function written both in `js` and `c++`, and the result is interesting.

When the `times` is set to 50000, wasm cost **1.54ms**, and js cost **1ms**.

When the `times` is set to 50000, wasm cost **22ms**, and js cost **31ms**.

**js version：**

```
	var add = function (a, b) {
		return a + b;
	};

	var times = 50000;  // change the loop times	

	var runTest = function (times) {
		var start = new Date ();
		var int_arr = [1000, 1000];
		var str_arr = ['hello', 'world'];
		for(var i = 0; i < times; i++) {
			if(i % 2 == 0) {
				add(int_arr[0], int_arr[1]);
			}else {
				add(str_arr[0], str_arr[1]);
			}
		}
		var end = new Date();
		document.getElementById('cost').innerHTML = (end - start).toFixed(2);
	};
	
	runTest(times);	
```

**cpp version:**

```
#include <iostream>
#include <ctime>
#include <chrono>
using namespace std;

int add (int a, int b) 
{
	int ret = a + b;
	return ret;
}

string add (string a, string b)
{
	string ret = a + b;
	return ret;
}

int main () 
{	
	std::chrono::high_resolution_clock::time_point t1 = std::chrono::high_resolution_clock::now();
	
	int int_arr[2] = {1000, 1000};
	string str_arr[2] = {"hello", "world"};

	int times = 50000;  // change the loop times
	int r;
	for(int i = 0; i < times; i++)
	{
		if(i % 2 == 0){
			add(int_arr[0], int_arr[1]);
		}else {
			add(str_arr[0], str_arr[1]);
		}
	}
		
	std::chrono::high_resolution_clock::time_point t2 = std::chrono::high_resolution_clock::now();
	std::chrono::duration<double, std::milli> time_span = t2 - t1;

	std::cout << "It took me " << time_span.count() << " milliseconds.";
	return 0;
}
```

**Comment by fanmingfei** [comment]
@chyingp 


> When the times is set to 50000, wasm cost 1.54ms, and js cost 1ms.
> When the times is set to 50000, wasm cost 22ms, and js cost 31ms.

50000 again?

**Comment by Becavalier** [comment]
Thanks, basically the same result as I did before: with the growth of input operand, the webassembly function will be much more efficient than native js functions.

![image](https://user-images.githubusercontent.com/8282020/28598841-e95aa7fe-71d8-11e7-8a93-591c4c99ca51.png)

**Comment by titzer** [comment]
It's generally not a good idea to write microbenchmarks. @chyingp, this example is basically comparing the performance of C++ strings vs JavaScript strings, which are totally different animals.

**Comment by nidin** [comment]
N-BODY Benchmark results of speedy.js
Reposted from TurboScript repo. Posted by @MichaReiser

Chrome
JS: 1.54775s 🎉
WASM: 1.91057s

Firefox:
JS: 1.360125s 🎉
WASM: 1.3785s

I prefer the results of Firefox. In my case, both implementations return the same result.

A side note. WebAssembly is also about predictability concerning performance. And this is true in this case. The variance of the WASM implementation is lower than the one of the JS implementation (at least using chrome. This is not the case for FF)

js x 0.64 ops/sec ±1.52% (8 runs sampled)
wasm x 0.51 ops/sec ±0.97% (7 runs sampled)
MacBook Mid 2014
