### ISSUE TITLE
Are Tables mutable by Wasm?

### ISSUE THREAD

**Issue by baptistemanson** [WebAssembly/design#1117]
Hi all,

While trying to understand what is the table object, I read http://webassembly.org/docs/semantics/#table that a table cannot be mutated from wasm.
At the same time, I see this example on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Table where it seems that the entries 0 and 1 are mutated inside the wasm context.
I must have missed something. Thanks for your time!

**Comment by kmiller68** [comment]
Tables cannot be mutated by wasm functions right now. They can, however, be initialized from the import object when the instance is created.

**Comment by rossberg-chromium** [comment]
To clarify further: Tables _are_ mutable, Wasm is merely lacking direct instructions for mutating them right now (other than the `elem` section of a module that @kmiller68 was referring to). However, Wasm is free to call back into JS any time, which has API to mutate tables.

**Comment by lukewagner** [comment]
And to add a bit of future-looking speculation: when wasm has [GC references](https://github.com/WebAssembly/gc/blob/master/proposals/gc/Overview.md) as first-class values, we could easily add `set_elem`/`get_elem` opcodes for mutating tables directly.

**Comment by baptistemanson** [comment]
Thank you all. It makes way more sense now.
