### ISSUE TITLE
🛤 Web Content Security Policy

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#1122]
**This is a tracking issue for a post-MVP feature**
It will be updated as the issue progresses.

**Topic** Content Security Policy
**Champion** none
**Status** in progress
**[Phase](https://github.com/WebAssembly/meetings/blob/master/process/phases.md)** Feature proposal
**Linked issues** #1092 #205 #972
**Linked repositories** [github.com/WebAssembly/content-security-policy](https://github.com/WebAssembly/content-security-policy)

# Details

# Details

Content Security Policy (CSP) is an added layer of security that helps to detect and mitigate certain types of attacks, including Cross Site Scripting (XSS) and data injection attacks. These attacks are used for everything from data theft to site defacement or distribution of malware.

In the context of WebAssembly, CSP can:

* Forbid usage of WebAssembly for developers who opted in to CSP before WebAssembly existed.
* Allow finer-grained control of JavaScript restrictions (including unsafe-eval) versus WebAssembly using new CSP mechanisms.

References:

* [MDN description of CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)
* @jfbastien has a [first proposal](https://github.com/WebAssembly/design/issues/1092#issuecomment-311869143) covering CSP as implemented in WebKit.
* This was [discussed in the 08-08 video call](https://github.com/WebAssembly/meetings/blob/master/2017/CG-08-08.md#content-security-policy-and-webassembly). A poll encouraged @flagxor to work on this.
* Some folks mentioned [Sub-Resource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) along with CSP.

**Comment by binji** [comment]
Moved to https://github.com/WebAssembly/proposals/issues/3.
