### ISSUE TITLE
Is it possible to use an array from js directly in webassembly's sandbox environment?

### ISSUE THREAD

**Issue by Becavalier** [WebAssembly/design#1125]
Is it possible/necessary to directly exposing the memory address of an array from js to webassembly?

Currently, if we wanna use an array which created from js in webassembly, we need to create a new memory buffer in wasm side first, and then copy the data of this array to this new buffer memory before we dealing with those data.  Also the same process if we wanna retrieve the data from wasm sandbox environment to js side.

I think those “filling” process would decrease the efficiency of wasm. It would be better if there are some kind of macros/operators can be used at this place to directly using the memory address of this js array instead of creating a new buffer memory at wasm side.

An example shows below:
![image](https://user-images.githubusercontent.com/8282020/29307975-8d178530-81d6-11e7-8b91-dd2088ee354d.png)

**Comment by Becavalier** [comment]
Would this feature be achieved after adding GC?
![image](https://user-images.githubusercontent.com/8282020/29322451-1873a314-8210-11e7-8ca8-75e47900d4a4.png)

**Comment by rossberg-chromium** [comment]
@Becavalier, indeed, this cannot be done without GC support in Wasm. Once that's there, there will likely be ways to access JS objects and arrays eventually, but details are still further out.
