### ISSUE TITLE
webassembly is slower than javascript - when i have tried dsp - promotional video

### ISSUE THREAD

**Issue by ghost** [WebAssembly/design#1127]
I have seen a nice video which was talking about performance of web-assembly, but running your example
the javascript is playing with similar speed, but on the graph it has been shown that the wasm is -97% is faster than javascript.

https://youtu.be/6v4E6oksar0?t=1796

my green line is showing 2.3, and my blue line is showing 400-500

I have a special idea and i want to code it, but i'm a little bit uncertain about the technology performancewise - Could i have made something wrong?

**Comment by raxim1** [comment]
Unexpected result - in firefox it's crossing the line at some point, but wasm is better overall.
In chrome javascript is faster

I'm using ubuntu 16.04

**Comment by sunfishcode** [comment]
This bug report doesn't contain or reference any code, and the account seems to have been deleted, so there doesn't appear anything we can do here.
