### ISSUE TITLE
Project!

### ISSUE THREAD

**Issue by gonardfreeman** [WebAssembly/design#1130]
Guys! I realy loved in what you do, but is project dead? I don't hear any new, since march((

**Comment by shurcooL** [comment]
FWIW, iOS 11 came out 3 days ago, which shipped WebAssembly support in mobile Safari.

**Comment by GGAlanSmithee** [comment]
Some related news which is really exciting for some of us :) https://medium.com/webpack/webpack-awarded-125-000-from-moss-program-f63eeaaf4e15

**Comment by rossberg-chromium** [comment]
There is quite a bit happening, even though the project front page hasn't been updated recently. You may want to join one of the [public](https://lists.w3.org/Archives/Public/public-webassembly/) [mailing lists](https://lists.w3.org/Archives/Public/public-webassembly-announce/) to stay up to date.
