### ISSUE TITLE
In Web.md, instantiateStreaming shouldn't do instantiation in processingSteps

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/design#1131]
(Just a spec-level bug, I think.)  Instantiation is inherently realm-specific and must be given an imports object and so can't happen in the parallel, realm-agnostic `processingSteps` of `Process a potential WebAssembly response` in Web.md.  Rather, I think `compileStreaming` and `instantiateStreaming` should have the same `processingSteps` (thus removing the need for `processingSteps` altogether) and `instantiateStreaming` should do instantiation in its `successSteps`.  CC @littledan since probably we can just get this right in the new bikeshed spec which will subsume and replace Web.md.

**Comment by littledan** [comment]
This is fixed in the current [Web.bs draft](https://littledan.github.io/spec/document/Web.html), see https://github.com/WebAssembly/spec/pull/591

**Comment by lukewagner** [comment]
Thanks, looks great!
