### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by TheDiamondYT1** [WebAssembly/design#1134]
Can WebAssembly be used offline? This could be useful for games when you lose internet connection, the game could do something such as go to the start screen (if its a multiplayer game) or just continue playing.

It would also be useful if you could save progress offline. I heard somewhere WebAssembly can also be used in native applications? If so, this could be useful because you can be useful because you could start playing in the web, then decide you really like the game and decide to download it then continue where you left off.

I'm assuming saving files offline is on the browsers end (well, obviously) and theres security issues and all that stuff but maybe one day we can find a solution to that.

EDIT: When i say saving files offline, i dont mean downloading them like normal. I mean something like a prompt box with custom text by the application. This is probably a proposal for brower vendors instead.

**Comment by RyanLamansky** [comment]
JavaScript can be used offline, and WebAssembly can (via imports and wrappers) use any JavaScript feature.
