### ISSUE TITLE
instantiateStreaming and Web Workers

### ISSUE THREAD

**Issue by Auron52** [WebAssembly/design#1136]
I noticed in Chrome 61 that WebAssembly.instantiateStreaming (and WebAssembly.compileStreaming) is supported in the main JavaScript thread, but not in Web Workers. Is this:
1. An extension that will be added later in Chrome?
2. Implementing the specification as written?
3. An oversight?
4. Something else?

Thanks,

Auron52

**Comment by littledan** [comment]
The current spec is a bit vague. I'm working on a formalized specification, where this is one of the first things to clarify in writing the interface in WebIDL.

What should the answer be here? Both can be expressed in WebIDL.

**Comment by flagxor** [comment]
It should work in workers. If it isn't in Chrome, that's a bug.
Will look into it.

**Comment by lukewagner** [comment]
Works on both in Firefox too.

**Comment by Auron52** [comment]
Thanks flagxor. Let us know what you find.

David

**Comment by ArtemGr** [comment]
Still a problem in Chrome `Version 65.0.3325.162 (Official Build) (64-bit)`.

**Comment by jfbastien** [comment]
We have agreement that the WebAssembly spec allows this. If specific browsers don't follow the spec please file a bug with that browser. Chrome is crbug.com

**Comment by ArtemGr** [comment]
For reference, [this article](https://pspdfkit.com/blog/2018/optimize-webassembly-startup-performance/#streaming-instantiation-combining-download-and-instantiation) mentions that it will be implemented soon, citing [this commit](https://chromium.googlesource.com/chromium/src/+/7566f0f5a88820cc89bd1c7e911a13575b99810b).
