### ISSUE TITLE
Are globals restricted to be const?

### ISSUE THREAD

**Issue by littledan** [WebAssembly/design#1139]
In some design documents (e.g., Modules.md, JS.md), I see comments about globals being restricted to being immutable, and this being enforced during validation. However, I'm having trouble understanding how that restriction was implemented [in the specification](https://webassembly.github.io/spec/valid/modules.html#globals) (I see const there, but looks like that just means the initializer has to be a constant expression). In the MVP, are globals only immutable, or can they be mutable as well?

**Comment by binji** [comment]
Only imported or exported globals must be immutable. This restriction will be relaxed in the threads proposal: https://github.com/WebAssembly/threads/blob/master/proposals/threads/Globals.md

**Comment by littledan** [comment]
Thanks! (Oh, I see, the restriction is specified in places like this: https://webassembly.github.io/spec/valid/modules.html#id12).
