### ISSUE TITLE
Proposal: Reserved opcode space for internal use

### ISSUE THREAD

**Issue by JohnSully** [WebAssembly/design#1141]
My specific use case is wanting to support macro op fusion in my interpreter (i.e. combine a compare+branch instruction into a single instruction).  Reserving a specific byte sequence (i.e. {0xff, 0xba}) to be used as a prefix would be sufficient to allow interpreters to allow translation to internal only ops for optimization in stream.

Without a reserved sequence its possible that in the future the chosen prefix could be used for a real wasm opcode and cause compatibility issues.

**Comment by eholk** [comment]
I think the idea was that this could be done by the Layer 1 compressor (see https://github.com/WebAssembly/decompressor-prototype for a prototype). In addition to compression/decompression, this would also be a place to add app-specific macros that expand at decode time to Wasm instructions.

**Comment by JohnSully** [comment]
I think you misunderstand the use case.  You in fact want the opposite effect whereby composing multiple wasm instructions into one instruction can allow for faster execution.  In this case by avoiding uselessly adding a '1' or '0' to the stack only to be immediately popped.

There are many use cases where optimization hints or other non-standard opcodes can be used by interpreters for internal purposes.  It is possible for those interpreters to store this information out of band, however that adds additional complexity and potentially requires checking external data structures on every opcode.

It is not intended that a wasm file including this prefix be considered a valid wasm file outside of the specific interpreter that generated it.

**Comment by eholk** [comment]
Ah, I see what you mean. Is this the sort of thing that could be done in your decode/validate step? For example, while validating a .wasm module, could you recognize sequences like compare-followed-by-branch and replace that with a special opcode that your interpreter understands?

**Comment by JohnSully** [comment]
That is the intent.  However if the opcode chosen isn't specially reserved to never be an actual valid wasm opcode then there is a chance that in the future it will conflict with a real opcode.  By carving out a specific opcode for this purpose we can ensure it never happens.  I would expect implementations to use that as a prefix and thereby have multiple internal opcodes.

**Comment by jfbastien** [comment]
I don't understand why an interpreter wouldn't decode the WebAssembly binary format opcodes to its own internal opcodes, instead of reusing the WebAssembly ones. Nothing prevents you from reusing if you want, but I don't see what the upside is in explicitly carving out reserved opcodes. Could you elaborate?

**Comment by JohnSully** [comment]
I'm thinking in the context of my own interpreter which statically translates wasm to X64 assembly.  Most wasm ops have direct translations in X64 so an intermediate representation is useless complexity most of the time.

Given that any intermediate representation would be 99% a 1:1 match for webassembly itself it seems better to keep it in that format and use reserved opcodes instead for internal use.   As only one opcode is needed it shouldn't clutter the wasm opcode space signficantly and would make it easier for embedders.

**Comment by jfbastien** [comment]
0xff is guaranteed to never be re-used, if only one opcode is what you need. Otherwise I'm really not sure avoiding a translation step really gains any simplicity, I'd need more details to understand.

**Comment by JohnSully** [comment]
If you look at: https://github.com/JohnSully/wasm_jit/blob/master/webasmRT/webasmRT/JitWriter.cpp

You'll see the switch on various wasm opcodes.  The intent of this static translator is to be extremely compact and simple (to aid in security validation).  An intermediate representation would make it much harder to prove correctness later on.  That said it is still nice to be fast.  

One major slow down is i32 compare ops followed immediately by a br_if.  In X64 it is much faster to do the comparison and rely on the flags register.  However to do so while still following the maxim of every op leaves the system in a consistent state (so we can validate it easily) requires the invention of a new op that does the compare & branch in one go.

Those ops wouldn't make sense as part of the wasm spec, but are useful internally.  An internal preprocessor would find these sequences and replace them with these all-in-one ops.

**Comment by JohnSully** [comment]
Also my understanding is that 0xff is reserved for future use.  Therefore if I were to rely upon it in my interpreter there is a good likelihood it would conflict with future opcodes.

**Comment by twitchyliquid64** [comment]
+1 to reserving a single opcode for implementation-specific stuff.

I'll also use `0xff` to symbolize calling into JIT'ed code, looks like a lot of the JITs went this path.

**Comment by LuisHsu** [comment]
According to these discussions, may we have `0xff` describe as `Un used` in the Spec?
"0xff is guaranteed to never be re-used in the spec and can be used by implementation" is not mentioned in the spec.

**Comment by binji** [comment]
When we discussed this in the [May 2017 CG meeting](https://github.com/WebAssembly/meetings/blob/master/2017/CG-05.md#webassembly-threads-proposal), we decided that 0xff would be reserved for future expansion. This isn't defined in a spec anywhere, however.

**Comment by twitchyliquid64** [comment]
Whats the plan for when the number of instructions exceeds 256? Are we going to dedicate an opcode to symbolize that the next byte is also part of the opcode?

Can we reserve an opcode for internal use at the next round of allocations? The less JITs that break the better.

**Comment by binji** [comment]
We've discussed putting most new instructions behind a prefix, followed by a leb128-encoded u32. We don't currently have a plan for when we run out of top-level opcodes, however.

**Comment by sunfishcode** [comment]
The questions here appear answered. There is an open question of exactly what the reserved 0xff byte means; see https://github.com/WebAssembly/spec/issues/1419 for discussion.
