### ISSUE TITLE
Small clarification about binary format of functions

### ISSUE THREAD

**Issue by steveklabnik** [WebAssembly/design#1142]
In `5.5.6  Function Section`, the spec says:

> The function section has the id 3.  It decodes into a vector of type indices that represent the type fields of the functions in the funcs component of a module. The locals and body fields of the respective functions are encoded separately in the code section.

Specifically, my question relates to the language around

> a vector of type indices

Does this index represent the index in both the `type` section as well as the `code` section? This seems to be implied, and it seems like in the binary files I read that this is true, but upon first reading, I assumed this index was only into the `type` section.

Thanks!

EDIT: Should this have been filed against the `spec` repository instead of `design`? If so, my bad, happy to move. Still getting my footing in all the repos.

**Comment by RyanLamansky** [comment]
The indexes in the function section is only to the type section, indicating the parameters and return of a function.  The code section should have the exact same number of entries as the function section, and contains the locals and bodies for the functions, in matching order of the function section.

So, it's possible that the same type index could be used by many functions if all those functions have the same signature.

Having them separated like this is useful for streaming compilation.

**Comment by steveklabnik** [comment]
Thank you! Makes perfect sense.
