### ISSUE TITLE
🛤 Non-trapping float-to-int conversions

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#1143]
**This is a tracking issue for a post-MVP feature**
It will be updated as the issue progresses.

**Topic** Non-trapping float-to-int conversions
**Champion** Dan Gohman @sunfishcode 
**Status** in progress
**[Phase](https://github.com/WebAssembly/meetings/blob/master/process/phases.md)** Implementation phase
**Linked issues** #986, #1089
**Linked repositories** [github.com/WebAssembly/nontrapping-float-to-int-conversions](https://github.com/WebAssembly/nontrapping-float-to-int-conversions)

# Details

The primary motivations are:

 - LLVM’s float-to-int conversion has an undefined result, rather than undefined behavior, and it seems LLVM does speculate it under certain conditions.
 - For the SIMD proposal, it’s more SIMD-hardware-like if no SIMD operations trap. This proposal would establish a convention for saturating operations which SIMD could share, to avoid introducing trapping.

This proposal is not motivated by performance data.

It's plausible that LLVM could be changed, to have something like an "nsw" flag for the "fptosi" instruction, especially with some of the recent proposals to modify the poison concept in LLVM. However, no one is currently working on this.

**Comment by binji** [comment]
Moved to https://github.com/WebAssembly/proposals/issues/11.
