### ISSUE TITLE
🛤 Multi-value

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#1146]
**This is a tracking issue for a post-MVP feature**
It will be updated as the issue progresses.

**Topic** Multi-value
**Champion** Andreas Rossberg @rossberg 
**Status** in progress
**[Phase](https://github.com/WebAssembly/meetings/blob/master/process/phases.md)** Implementation phase
**Linked issues** #937, #667, 
**Linked repositories** [github.com/WebAssembly/multi-value](https://github.com/WebAssembly/multi-value))

# Details

* Multiple return values for functions:
  - enable unboxing of tuples or structs returned by value
  - efficient compilation of multiple return values

* Multiple results for instructions:
  - enable instructions producing several results (divmod, arithmetics with carry)

* Inputs to blocks:
  - loop labels can have arguments
  - can represent phis on backward edges
  - enable future `pick` operator to cross block boundary
  - macro definability of instructons with inputs
    * `i32.select3` = `dup if ... else ... end`

**Comment by kripken** [comment]
Were any numbers presented about how much this can be used in practice? I think previous notes said something about testing in the wasm backend and elsewhere, to see code size etc. Sorry if I missed it in the notes.

**Comment by jfbastien** [comment]
@kripken I believe you're asking about https://github.com/WebAssembly/meetings/issues/94

**Comment by binji** [comment]
Moved to https://github.com/WebAssembly/proposals/issues/19.
