### ISSUE TITLE
🛤 Host bindings

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#1148]
**This is a tracking issue for a post-MVP feature**
It will be updated as the issue progresses.

**Topic** Host bindings
**Champion** Brad Nelson @flagxor and Luke Wagner @lukewagner 
**Status** in progress
**[Phase](https://github.com/WebAssembly/meetings/blob/master/process/phases.md)** Feature proposal
**Linked issues** 
**Linked repositories** [github.com/WebAssembly/host-bindings](https://github.com/WebAssembly/host-bindings)

# Details

Efficient bindings to host objects and functions.

**Comment by alexreg** [comment]
Has there been any progress towards this lately?

**Comment by binji** [comment]
Moved to https://github.com/WebAssembly/proposals/issues/8.
