### ISSUE TITLE
How do i compile file.cpp with #include headers ?

### ISSUE THREAD

**Issue by extremety1989** [WebAssembly/design#1150]
how can i compile cpp file that includes headers from MYSQL c++ lib and boost

here is my cpp file
#include <stdlib.h>
#include <iostream>
#include <cppconn/connection.h>

#include <cppconn/driver.h>
#include <cppconn/exception.h>
#include <cppconn/resultset.h>
#include <cppconn/statement.h>
#include <cppconn/prepared_statement.h>

using namespace std;
string username;
string userpass;
int main(void)
{
	cin >> username;
	cin >> userpass;
	try {
		sql::Driver *driver;
		sql::Connection *con;
		sql::Statement *stmt;
		sql::ResultSet *res;
		sql::PreparedStatement *pstmt;

		/* Create a connection */
		driver = get_driver_instance();
		con = driver->connect("tcp://127.0.0.1:3306/test", "root", "");
		/* Connect to the MySQL test database */
		con->setSchema("test");
		stmt = con->createStatement();
		delete stmt;
			pstmt = con->prepareStatement("INSERT INTO test (username,password) VALUES (?,?)");
			pstmt->setString(1,username.c_str());
			pstmt->setString(2,userpass.c_str());
		    pstmt->executeUpdate();
		    delete pstmt;

		/* Select in ascending order */
		pstmt = con->prepareStatement("SELECT id,username,password FROM test ORDER BY id ASC");
		res = pstmt->executeQuery();

		/* Fetch in reverse = descending order! */
		res->afterLast();
		while (res->previous())
			cout <<"ID :" <<res->getInt("id") << "  Username :" << res->getString("username").c_str() 
			<< "  Password :" << res->getString("password").c_str() << endl;
		delete pstmt;
		delete con;

	}
	catch (sql::SQLException &e) {
		cout << "SQLState: " << e.getSQLState()<< endl;
	}

	cout << endl;

	return 0;
}

em++ main.cpp -s WASM=1 ?????

how to add links ?

**Comment by sbc100** [comment]
This should work if you add the mysql C++ header and library path to your command line (e.g. using -I and -L).

This is really and emscripten question though, please ask there if you are still having problems.
