### ISSUE TITLE
Does instantiateStreaming instantiates a Wasm binary incrementally?

### ISSUE THREAD

**Issue by awtcode** [WebAssembly/design#1165]
Hi,

I read from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming that the instantiateStreaming API "compiles and instantiates a WebAssembly module directly from a streamed underlying source"

Does this mean that browsers can compile and instantiate the Wasm binary 'incrementally'? e.g. start compiling parts of the Wasm binary even before it is fully downloaded?

**Comment by xtuc** [comment]
The incremental compilation is probably an implementation details but a great optimization.

The binary format is divided into sections, they can be independently decoded or even written. That means that you can compile each section in the binary as they are streamed from the source.

**Comment by jfbastien** [comment]
Yes, it is possible with fetch to compile incrementally while downloading, but as @xtuc said it's an implementation detail.
