### ISSUE TITLE
Writing to address 0 generates **late** exception. What is the mechanism ? Why late ?

### ISSUE THREAD

**Issue by z--z---z-----** [WebAssembly/design#1168]
Hello,

All details are here:
https://webassemblycode.com/exceptions/webassembly-traps-exceptions-learning-experiences/

**But in short**

This C code:

```C
#include <stdio.h> 

int main() 
{ 
    char *p=0;  // declare a pointer to char and make it point to 0 
    char tmp=*p; // Read the content of address 0, enough to trap in Linux, but not in webassembly 
     
    printf("Here is what I have in address 0: %x\n", tmp); 
     
    *p=tmp; // Store the previously read character into 0, does not trap in webassembly, Linux already trapped earlier 
    printf("Wrote the same value back\n"); 
     
    (*p)++; // Modify the content of address 0, have late trap in Webassembly, unexpected. 
    tmp=*p; // Read the content of address 0 
    printf("Address 0 value was modified to %x\n", tmp); 
}
```
Generates this exception in both Firefox and Chrome:

![image](https://user-images.githubusercontent.com/8484772/34448650-8283b010-ecd6-11e7-934a-4d884ef69965.png)

The last message: "Address 0 value was modified to 66", should not be there as the trap should be caught before that, or at least this is what I think.

What is the mechanism for this exception ?

Thanks!

**Comment by titzer** [comment]
Hello,

Accessing null pointers (either read or write) is undefined behavior in C/C++. On most platforms, null is defined to be address 0, and if the platform OS supports it, the page containing address 0 is unmapped, leading to a memory access violation (i.e. a SEGFAULT on POSIX).

This is not the case when targeting WASM. Address 0 is mapped and accessible. The error that you are seeing is not being generated by the WASM engine but by your toolchain (probably Emscripten).

There are plans to support unmapping the 0 page in WASM, but there has not yet been a concrete proposal.

**Comment by z--z---z-----** [comment]
Hi Titzer,

The browser says "Runtime error", which led me to think this was a check performed by the browser, but you might be right, it may be code inserted during Emscripten compilation.
In what places would you look for the message: "The application has corrupted its heap..." ?
I want to know who is generating this message.

Thanks!

**Comment by jfbastien** [comment]
https://github.com/kripken/emscripten/search?utf8=✓&q=The+application+has+corrupted+its+heap&type=
