### ISSUE TITLE
Truncation of FP numbers to integers: inconsistency between design document and specification

### ISSUE THREAD

**Issue by ulikunitz** [WebAssembly/design#1169]
The webasm design document says in Semantics:

> Truncation from floating point to integer where IEEE 754-2008 would specify an invalid operator exception (e.g. when the floating point value is NaN or outside the range which rounds to an integer in range) traps.

This is not reflected in the specification of trunc_s,  which states that the result of the operation is undefined for NaNs, infinity and results outside the range of the target type. I'm not sure whether this language includes or excludes raising a trap.

V8 appears to raise the trap as required by the design document.  For the implementation of the Go Language this creates an issue because the Go Language Specification requires the conversion to succeed with an undefined result value. See the discussion [here](https://groups.google.com/forum/?fromgroups=#!topic/golang-dev/6Bo6dtmLC2E).

**Comment by binji** [comment]
`trunc_s` is a partial operator, so the instruction will trap as specified [here](https://webassembly.github.io/spec/core/exec/instructions.html#numeric-instructions):

> Where the underlying operators are partial, the corresponding instruction will trap when the result is not defined.

This should probably be made more clear in the spec, I think.

You may be interested in the [proposal for non-trapping float-to-int conversions](https://github.com/webassembly/nontrapping-float-to-int-conversions) as well.

**Comment by ulikunitz** [comment]
Thank you, that clarifies it. I close the issue.
