### ISSUE TITLE
🛤 Sign-extension operators

### ISSUE THREAD

**Issue by binji** [WebAssembly/design#1178]
**This is a tracking issue for a post-MVP feature**
It will be updated as the issue progresses.

**Topic** Sign-extension operators
**Champion** Ben Smith @binji
**Status** in progress
[**Phase**](https://github.com/WebAssembly/meetings/blob/master/process/phases.md) standardize the feature
**Linked issues**
**Linked repositories** [github.com/WebAssembly/sign-extension-ops](https://github.com/WebAssembly/sign-extension-ops)

# Details

This proposal adds five new integer instructions for sign-extending 8-bit, 16-bit, and 32-bit values.

  * `i32.extend8_s`: extend a signed 8-bit integer to a 32-bit integer
  * `i32.extend16_s`: extend a signed 16-bit integer to a 32-bit integer
  * `i64.extend8_s`: extend a signed 8-bit integer to a 64-bit integer
  * `i64.extend16_s`: extend a signed 16-bit integer to a 64-bit integer
  * `i64.extend32_s`: extend a signed 32-bit integer to a 64-bit integer

**Comment by lars-t-hansen** [comment]
We've implemented this and it's been in Nightly for a long time, with our own test cases and the proposed spec test cases.  We're just waiting for this proposal to advance before we ship.
https://bugzilla.mozilla.org/show_bug.cgi?id=1429818

**Comment by lars-t-hansen** [comment]
Sign extension ops are now riding the trains in Firefox and will likely be in FF62, currently scheduled to ship September 5.

**Comment by binji** [comment]
Moved to https://github.com/WebAssembly/proposals/issues/9.
