### ISSUE TITLE
🛤 Import/Export of Mutable Globals

### ISSUE THREAD

**Issue by binji** [WebAssembly/design#1179]
**This is a tracking issue for a post-MVP feature**
It will be updated as the issue progresses.

**Topic** Import/Export of Mutable Globals
**Champion** Ben Smith @binji 
**Status** in progress
**[Phase](https://github.com/WebAssembly/meetings/blob/master/process/phases.md)** standardize
**Linked issues**
**Linked repositories** [github.com/WebAssembly/mutable-global](https://github.com/WebAssembly/mutable-global)

# Details

Imported and exported globals can now be mutable. In the Web binding, exported globals are now of type `WebAssembly.Global`, rather than converted to a JavaScript `Number`.

**Comment by lars-t-hansen** [comment]
We've removed all ifdefs controlling this feature and it's riding the trains (with "type" renamed as "value" in the descriptor, the initial value as a separate parameter, and existing ref tests imported and passing).  Looks like it'll be in FF62 unless something happens.

**Comment by binji** [comment]
Moved to https://github.com/WebAssembly/proposals/issues/5.
