### ISSUE TITLE
🛤 Type Reflection for WebAssembly JavaScript API

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#1181]
**This is a tracking issue for a post-MVP feature**
It will be updated as the issue progresses.

**Topic** Type Reflection for WebAssembly JavaScript API
Champion Till Schneidereit @tschneidereit 
**Status** in progress
[**Phase**](https://github.com/WebAssembly/meetings/blob/master/process/phases.md) feature proposal
**Linked issues** https://github.com/WebAssembly/threads/issues/87 #1046
Linked repositories github.com/WebAssembly/js-types/blob/master/proposals/js-types

**Details**

WebAssembly is typed, and its types carry information that can be useful and important to clients interacting with WebAssembly modules and objects through the JavaScript API. For example, types describe the form of imports and exports, including the size limits of memories and tables or the mutability of globals.

**Comment by binji** [comment]
Moved to https://github.com/WebAssembly/proposals/issues/2.
