### ISSUE TITLE
🛤 JavaScript BigInt to WebAssembly i64 integration

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#1186]
**This is a tracking issue for a post-MVP feature**
It will be updated as the issue progresses.

**Topic** JavaScript BigInt to WebAssembly i64 integration
**Champion** Dan Ehrenberg @littledan  
**Status** in progress
[**Phase**](https://github.com/WebAssembly/meetings/blob/master/process/phases.md) proposed spec text available
**Linked issues** https://github.com/WebAssembly/spec/pull/707
**Linked repositories** [github.com/WebAssembly/JS-BigInt-integration](https://github.com/WebAssembly/JS-BigInt-integration)

**Details**

With this patch, BigInts have support for bidirectionally converting
to 64-bit integer WebAssembly values, which appears as
- Parameters and return values to exported WebAssembly functions
- Parameters and return values to host functions
- Imported and exported globals

BigInts can be read or written from WebAssembly memory using the
BigInt proposal's BigInt64Array or BigUint64Array; no additional
support is needed.

**Comment by binji** [comment]
Moved to https://github.com/WebAssembly/proposals/issues/7.
