### ISSUE TITLE
🛤 Custom Annotation Syntax in the Text Format

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#1192]
**This is a tracking issue for a post-MVP feature**
It will be updated as the issue progresses.

**Topic** Custom Annotation Syntax in the Text Format
**Champion** Andreas Rossberg @rossberg
**Status** in progress
[**Phase**](https://github.com/WebAssembly/meetings/blob/master/process/phases.md) feature proposal
**Linked issues** *none*
**Linked repositories** [github.com/WebAssembly/annotations](https://github.com/WebAssembly/annotations/blob/master/proposals/annotations/Overview.md)

**Details**

* The Wasm binary format supports custom sections to enable associating arbitrary meta data with a Wasm module.
* No equivalent exists for the text format. In particular, there is no way to
  - represent custom sections themselves in the text format, cf. WebAssembly/design#1153 and https://gist.github.com/binji/d1cfff7faaebb2aa4f8b1c995234e5a0
  - reflect arbitrary names in the text format, cf. WebAssembly/spec#617
  - express information like for host bindings, cf. https://github.com/WebAssembly/host-bindings/blob/master/proposals/host-bindings/Overview.md
* This proposal adds the ability to decorate a module in textual notarion with arbitrary annotations of the form `(@id ...)`.
* Neither the syntactic shape nor the semantics is prescribed by the Wasm specification, though the Appendix might include a description of optional support for name section annotations and generic custom sections.
* This proposal only affects the text format, nothing else.

**Comment by binji** [comment]
Moved to https://github.com/WebAssembly/proposals/issues/13.
