### ISSUE TITLE
The detail mechanism of memory alignment with "load" and "store" related instructions?

### ISSUE THREAD

**Issue by Becavalier** [WebAssembly/design#1195]
Can anyone please show me some specific cases on how dose the alignment work with those instructions (i32.store, i32.load etc)? Thanks!

**Comment by pepyakin** [comment]
Alignment is just a hint and does **NOT** affect the semantics of the execution. If pointer with different alignment is used for load/store instructions then it might affect performance, but still — it's allowed.

**Comment by Becavalier** [comment]
@pepyakin But why does the "load" instruction also have the alignment attribute? I mean alignment is just a feature determine how the byte data should be stored in the specific memory address.

**Comment by pepyakin** [comment]
As I mentioned, it is just a hint and it might be used by a VM implementation to optimize the compiled code.

**Comment by Becavalier** [comment]
I found the answer:  https://rsms.me/wasm-intro 
: )

**Comment by pepyakin** [comment]
Yeah, that's a nice explaination!
