### ISSUE TITLE
the "offset" label in memory accessors.

### ISSUE THREAD

**Issue by Becavalier** [WebAssembly/design#1196]
It seems like that the following "wat" code do not work in the "wat2wasm" online transpiler properly. 
```
(module (memory 0) (func (i32.store align=4 offset=1 (i32.const 10) (i32.const 0))))
```
Running result:
![image](https://user-images.githubusercontent.com/8282020/37762700-11665668-2df8-11e8-9228-110841082153.png)

Did I misunderstood something?

**Comment by pepyakin** [comment]
Nah, it just text format is a bit too strict. Consider this example:

```WebAssembly
(module (memory 0) (func (i32.store offset=1 align=4 (i32.const 10) (i32.const 0))))
```

(positions of offset and align was swapped)

It compiles just fine.

See [text format](https://webassembly.github.io/spec/core/text/instructions.html#text-memarg) for offset and alignment.

**Comment by Becavalier** [comment]
@pepyakin  Yes, it works!

Thanks!
