### ISSUE TITLE
Instantiate Streaming Support issue in SystemJS

### ISSUE THREAD

**Issue by guybedford** [WebAssembly/design#1197]
I'm trying to integrate the instantiate streaming approach into SystemJS (which formerly used `WebAssembly.compile`) and the issue I'm running into is a lack of reflection support for imports.

Because SystemJS is a dynamic module loader, we don't necessarily know ahead of time what imports a web assembly module is going to need. So without custom analysis of the binary first, we can't provide the `importObject` to `WebAssembly.instantiateStreaming`.

Previously `WebAssembly.Module.imports` worked well here to extract this information, but going forward perhaps a getter-based function on importObj would be useful here:

```js
WebAssembly.instantiateStreaming(source, function getImport (moduleId: string, exportName: string) {
  return Promise<importValue>;
});
```

I know there has been talk of using promises for modules on the importObj, but perhaps the above can solve both problems.

For now, I'm having to leave SystemJS using ~`WebAssemby.compile`~ `WebAssembly.compileStreaming`.

Note ideally Web Assembly should separate instantiation from execution and handle live bindings as well through the API... something along the lines of:

```js
// get a module instance, that has not been executed yet
const wasmModule = WebAssembly.instantiateStreaming(source);
// then static analysis can be applied to get dependencies
const importedModules = module.getImportIds();
const instantiatedDependencies = loadAndInstantiateModules(importedModules);
// support setting import values on a wasm module, both before and after execution for hoisting and live bindings
wasmModule.setImportValue(depId, exportName, value);
// separate synchronous execution
WebAssembly.execute(wasmModule);
```

**Comment by guybedford** [comment]
Also, if I have posted this to the wrong repo, if so please let me know where it should belong / or on which existing discussion - thanks!

**Comment by xtuc** [comment]
> So without custom analysis of the binary first

I guess that you don't always have access to the binary first? You only get your hands on at runtime?

> Note ideally Web Assembly should separate instantiation from execution and handle live bindings as well through the API... [...]

In the future WebAssembly will have the `anytype` refs, which will fix the live binding issue.

**Comment by guybedford** [comment]
> In the future WebAssembly will have the anytype refs, which will fix the live binding issue. For example you would store everything in a shared table.

Right.

The other benefit of synchronous execution is the same issue webpack has been having though - ensuring the same execution semantics across the graph between ESM and WASM within a single synchronous execution of the engine.

**Comment by guybedford** [comment]
> I guess that you don't always have access to the binary first? You only get your hands on at runtime?

Exactly, so I mean some kind of analysis in the browser itself at runtime, which would be bad of course.

**Comment by dschuff** [comment]
Some of what you want can be done today. e.g.  `WebAssembly.compileStreaming` gets you most of the benefit of overlapping compile and download, and returns you the module (and then you can use `Module.imports` and whatever else you're doing now). Of course you can also just not use a `_start` function, which will mean noting gets executed at instantiation (other than data segment fills). In the past we've kicked around ideas for something like `instantiateGroup` to instantiate a group of dependent modules. Currently ES Module integration (https://github.com/WebAssembly/esm-integration) is where most of the action is happening there, and if that ends up not being sufficient (e.g. we also want an explicit API more along the lines of what we have now) we'd probably consider it once ESM support is more nailed down.

**Comment by guybedford** [comment]
Yes that's what I've gone with in the end - the latest production build of SystemJS is to use `WebAssembly.compileStreaming` along with `new WebAssembly.Instance` to get an instantiation model that most closely resembles the JS expectations . Dependencies get loaded async before execution, with a sync WASM execution along with the JS execution. This even allows supporting features like function binding hoisting in circular references, so gets us pretty close to parity with the ES / WASM integration plans. The goal with SystemJS is to support workflows that are roughly equivalent semantically to ES modules and WASM, so tricks with the start function etc aren't suitable here either.

I heard there are performance concerns with compile streaming, so I was just hoping to find an instantiateStreaming workflow here, or at least provide feedback if the plan is for this to be the primary technique but the above approach certainly solves my problems for now. I trust neither compileStreaming or new WebAssembly.Instance will be deprecated anytime soon?

**Comment by guybedford** [comment]
Will follow up any further issues at the esm integration repo.

**Comment by dschuff** [comment]
> I trust neither compileStreaming or new WebAssembly.Instance will be deprecated anytime soon?
No. Obviously synchronous compile and instantiation can block the main thread for an unpredictable amount of time, so the general advice is "don't do that on the main thread". The browser engines also like to have compile and instantiation together in one step because it gives them the opportunity to specialize the code to the particular instance. But there are plenty of legit use cases for both of those things, so that's why they are there.

**Comment by guybedford** [comment]
Certainly I'd avoid thread blocking on execution if we could in this model. If/when top-level await lands, then having an execution tick for WASM will be ok and SystemJS will be able to move to use `WebAssembly.instantiate` as well being permitted by the semantics, although instantiateStreaming still won't work in this model without something like the request-based import API proposed above along with execution separation through some execute callback.
