### ISSUE TITLE
Reference Types

### ISSUE THREAD

**Issue by flagxor** [WebAssembly/design#1203]
**This is a tracking issue for a post-MVP feature**
It will be updated as the issue progresses.

**Topic** Reference Types
**Champion** Andreas Rossberg (@rossberg-chromium)
**Status** In progress
**[Phase](https://github.com/WebAssembly/meetings/blob/master/process/phases.md)** Implementation Phase
**Linked issues**
**Linked repositories** [github.com/WebAssembly/reference-types/](github.com/WebAssembly/reference-types/)

**Comment by binji** [comment]
Moved to https://github.com/WebAssembly/proposals/issues/10.
