### ISSUE TITLE
The IndexedDB can not save a  "WebAssembly.Module" object.

### ISSUE THREAD

**Issue by Becavalier** [WebAssembly/design#1213]
#### It seems like the indexedDB can not save this "WebAssembly.Module" object, any idea?

![image](https://user-images.githubusercontent.com/8282020/41077329-a5a07624-6a48-11e8-85ab-54bfb3b6076e.png)

![image](https://user-images.githubusercontent.com/8282020/41077333-abbf4aa8-6a48-11e8-953e-a61fbcc7d4f9.png)

**Comment by oraoto** [comment]
In Chrome, structured clone for Wasm module is disabled by default, see  discussion https://github.com/WebAssembly/design/issues/972

**Comment by Becavalier** [comment]
@oraoto I get it, thanks!
