### ISSUE TITLE
BigInt proposal and Unmanaged closures issues has wrong labels

### ISSUE THREAD

**Issue by chicoxyzzy** [WebAssembly/design#1217]
It should have label `Phase 2` according to https://github.com/WebAssembly/design/pull/1194, but it has `Phase 0` label https://github.com/WebAssembly/design/issues?q=is%3Aissue+is%3Aopen+label%3A%22🛤+tracking%22

**Comment by chicoxyzzy** [comment]
Unmanaged closures should have `Phase 1` label according to https://github.com/WebAssembly/design/pull/1183

**Comment by chicoxyzzy** [comment]
Also Web Content Security Policy proposal probably should have label `Phase 0`

**Comment by binji** [comment]
I updated the [BigInt proposal](https://github.com/WebAssembly/design/issues/1186) based on the vote to move to phase 2 in [the March 6th meeting](https://github.com/WebAssembly/meetings/blob/master/2018/CG-03-06.md).

I updated the [Unmanaged closures proposal](https://github.com/WebAssembly/design/issues/1182) to phase 1, but now that I look at the notes it seems that it was only decided to [move the repo to the WebAssembly group](https://github.com/WebAssembly/meetings/blob/master/2018/CG-02-06.md), not to move it to phase 1.

I'm not sure about CSP, we should address in a future CG meeting I think.

Thanks for taking a look!

**Comment by sunfishcode** [comment]
Web Content Security Policy has since progressed to phase 3, which is now tracked here: https://github.com/WebAssembly/proposals#phase-3---implementation-phase-cg--wg

The other issues here were fixed in #1218.
