### ISSUE TITLE
Using browser libraries within webassembly

### ISSUE THREAD

**Issue by DeusProx** [WebAssembly/design#1220]
I just wanted to ask if it is possible to utilize common libraries (like zlib, libpng, libjpeg) from the browser within webassembly or is it necessary to ship them yourself as wasm modules?

If it's not possible at the moment is there be a chance that something like that this could be introduced somehow?

**Comment by kripken** [comment]
You'd need to ship them yourself. (Letting you access native system libraries on the user's system would be a very difficult security problem.)

It's often easy to ship common libraries, though. For example the first two in your list (zlib, libpng) are in emscripten-ports, so if you use emcc they can be linked in by just setting a flag.

**Comment by DeusProx** [comment]
Okay, like I thought. That's a shame since it can end up with a lot data shipped through the wire while all libraries basically reside in the client.

Thank you for the informations!
