### ISSUE TITLE
Universal Intermediate Representation

### ISSUE THREAD

**Issue by skyne98** [WebAssembly/design#1224]
Hey everyone! 

I think we can all agree that finding a well supported and fully cross-platform (platform-independent) intermediate code representation can be very hard, if not impossible.

LLVM-IR, for example, can look and sound very promising at a first glance, but after some time you get to understand, how truly platform dependent it is, being a representation suitable for dozens of optimization steps, which might even be platform dependent.

So, the question is: can WebAssembly be used as a universal intermediate representation, which is compact, easy to understand and very portable?

**Comment by skyne98** [comment]
The only problem I can see is that WASM just ignores the existence of any kind of platform-specific apis and puts the burden of providing them on the tool exporting to WASM.
Surely, that is super good for portability, however, it might mean that a dream of using C code and making it portable alongside with your own language / environment might just be a dream and will require lots of work, providing the apis for each platform anyways. Even if the language itself will have platform specific API implementations, they won't directly map to Windows, or Linux one and won't be able to link.

**Comment by dschuff** [comment]
I think your analysis is basically correct. Wasm is meant to be a portable,
stable format and solves that problem well for expressing computation. But
it only solves that problem. To make a usable platform you need to create
an embedding that has APIs in order to interact with the environment. So
you have to either use an existing embedding (e.g. JS and the web) or make
your own, which is a lot of work and requires you to make all the hard
design tradeoffs to support your use cases.

**Comment by aardappel** [comment]
Not having any built-in APIs also means we can have multiple standards for different kinds of environments, and we're not stuck with APIs that stop being a good fit.

Essentially, "standard" APIs can be an organic, bottom up process instead of something mandated by a standards body, as using it / supporting it is entirely optional.

**Comment by rossberg** [comment]
I would love to see an implementation of e.g. some well-chosen Posix subset or perhaps a suitable microkernel interface as an API for Wasm across multiple platforms. There would also be value in standardising such a thing (or multiple ones) eventually, separately from Wasm itself.

However, I suspect that most active members of the current Wasm WG have neither the resources nor the expertise to design and build an OS layer. Nor should we, I would argue. This is an excellent task for divide and conquer. There is nothing blocking interested parties going ahead and starting to create one and/or form a special interest group.

**Comment by RyanLamansky** [comment]
@skyne98 Just as another point of reference, my [WebAssembly for .NET](https://github.com/RyanLamansky/dotnet-webassembly) project can be used to treat a WASM file similarly to a standard .NET DLL, paving the way for someone to expose .NET APIs to WebAssembly (if one were truly insane) or use, for example, some kind of WASM math library in .NET.

.NET is so wildly different than the JS world, the fact that this is even possible speaks to how truly portable WASM currently is.

**Comment by skyne98** [comment]
@RyanLamansky, yep, I have already seen your library -- good work! It is quite awesome. If this plan works out as expected, I planned to use it for reading and possibly analysing WASM for further use.

As for WASM portability -- it's great to see the evidence that it can be used in a totally different environment with a totally different set of rules. However, the idea remains and I have a new question: what about Rust? As far as I can understand, Rust has a much better possibility to abstract over OS specifics and already has a great, uniform WebAssembly support, without needing Emscripten. As far as I can see, there are lots of very useful libraries already rewritten in Rust, however I wonder if wrappers and bindings can be useful in any way.

**Comment by AhliLi** [comment]
Bitwise operations are always valid, the set of universal machine operations is a simple tree.

**Comment by skyne98** [comment]
@AhliLi I don't think I follow what you commented about, can you explain in more detail?

**Comment by kevinbarabash** [comment]
This sounds really tricky.  If you want to use native libraries defining an FFI would be a safer way to go.  Since node can execute wasm modules you could use node's FFI, but it'd probably be pretty slow.

**Comment by skyne98** [comment]
@kevinbarabash, so you mean that it will be safer to define my own FFI and just provide the bindings the existing FFIs? But what if everything is compiled down to webassembly, wouldn't it follow the common WASM FFI then?

**Comment by sunfishcode** [comment]
The discussion here seems to have subsided, and there doesn't appear to be anything actionable for WebAssembly itself. Please file new issues as needed!
