### ISSUE TITLE
libc++ for wasm

### ISSUE THREAD

**Issue by jakirkham** [WebAssembly/design#1228]
Have seen there was some discussion on creating `libc` ( https://github.com/WebAssembly/design/issues/519 ) and [some ongoing work]( https://github.com/jfbastien/musl ) in that direction. Though was curious whether there is a proposal/work being done for `libc++` in wasm.

**Comment by kripken** [comment]
Emscripten uses LLVM libc++ pretty much with no changes (only a few places where `defined(__GLIBC__)` is replaced by `defined(__GLIBC__) || defined(__EMSCRIPTEN__)`). Basically, all the interesting low-level stuff happens in libc, so libc++ is just portable C++. In other words, not really a need for a port, it's trivial/done.

**Comment by sbc100** [comment]
Outside of emscripten we also build and test libc++ continuously on the wasm waterfall:
https://wasm-stat.us/console

e.g:
https://logs.chromium.org/v/?s=chromium%2Fbb%2Fclient.wasm.llvm%2Flinux%2F34740%2F%2B%2Frecipes%2Fsteps%2Flibcxx%2F0%2Fstdout

So unless there is something specific to wasm that we need to do in libc++, I'd say this is already done.
