### ISSUE TITLE
use hot(0xflags,, priority, id, {var,} ) as compiler directive profile

### ISSUE THREAD

**Issue by AhliLi** [WebAssembly/design#1229]
use HOT as compiler directives and profile hints for efficient prioritisation.

flags: first bits should indicate
{ start/stop directive, linear sequence, iterator loop, parallel, parallel^, thread synch, (calls function), and optimisation profile (standard pattern)}
float priority: 1.0f typical, sorted by compiler
id: <></>

optional variable / register declarations

Also wise to include numeric scope for higher efficiency processing of fixed bit scope, io profile for gl and audio/video, hints on endpoint optimisation (pixel buffer, audio, webgl, etc.)

**Comment by titzer** [comment]
I generally like the idea of a hint section. However, I think it makes sense to reduce the granularity of the hints to make simple, clear signals. E.g. one proposal that has been discussed in various offline conversations is a "hint section" to specify per-function hot/cold/startup hints that basically tell an engine which tier to use for which function and whether each function is needed for "fast startup" or not.

**Comment by sunfishcode** [comment]
Wasm now has [branch hints](https://github.com/WebAssembly/branch-hinting/blob/main/proposals/branch-hinting/Overview.md), which provide some of these hints. Branch hints also show how hints can be encoded in a hint section, which could be followed by new hint proposals.

There are a lot of hints that could be theoretically added. To add new hints to Wasm, proposals should identify specific hints and explain how they'd be gainful in Wasm code, and implementable in Wasm engines.
