### ISSUE TITLE
take insparation from babel

### ISSUE THREAD

**Issue by unmellow** [WebAssembly/design#1232]
[babel](https://computation.llnl.gov/projects/babel-high-performance-language-interoperability/#page=home) is a language interoperability framework created by the scientific community although, I'm aware the goals of the projects are different,
 and that you can't just copy their design ideas,
 I believe you could still examen it to gather some ideas for wasm,
 and if possible create something based off of babel to compete with as graalvm is into java

**Comment by xtuc** [comment]
What are you proposing? Including RPC/RMI buit-in?

Note that interopability is already one of the goal of wasm, through the host. For example, what is currently done with JavaScript.

**Comment by unmellow** [comment]
I just mean to make babel as integrated into wasm as graalvm is into java
