### ISSUE TITLE
IndexedDb access?

### ISSUE THREAD

**Issue by russoturisto** [WebAssembly/design#1233]
Hi,

Q: I'm a complete wasm newb and am about to start writing a SPA in Rust using [yew](https://github.com/DenisKolodin/yew).   My project requires lots of interaction with IndexedDb.  My question is can WebAssembly interact with IndexedDb and if so does it have to go though JavaScript first?  I've read that I/O heavy applications are actually slower in WebAssembly because of the requirement to go through JavaScript and would like to put my doubts to rest.

Thank you for you time in answering this question!

**Comment by xtuc** [comment]
You can access IndexedDb through the host, you need to import JavaScript functions that interact with IndexedDb.

**Comment by russoturisto** [comment]
Understood.  Thank you! :)

**Comment by russoturisto** [comment]
A small follow up question:  Is there a proposal out there to allow direct access between WebAssembly and IndexedDb?  If there isn't should there be one?

Thanks, :)

**Comment by Pauan** [comment]
@russoturisto I believe that is covered by the [host-bindings proposal](https://github.com/WebAssembly/host-bindings) which allows wasm direct access to host APIs (including browser APIs).

You can see an overview of the proposal [here](https://github.com/WebAssembly/host-bindings/blob/master/proposals/host-bindings/Overview.md).

**Comment by russoturisto** [comment]
Awesome!  Thank you so much! :)

**Comment by jonathangurwitz** [comment]
@russoturisto
I would love to know the outcome. I am thinking about using wasm with indexeddb too
