### ISSUE TITLE
does support for socket(udp and tcp)?

### ISSUE THREAD

**Issue by csy2002** [WebAssembly/design#1251]
does support for socket(udp and tcp)? if not, has a plan? thanks.

**Comment by xtuc** [comment]
It can be archived by passing functions from the host.

**Comment by csy2002** [comment]
i want port my network program that use udp, but don't find appropriate functions.

**Comment by Pauan** [comment]
@csy2002 If you are using C or C++, you can try using [Emscripten](http://kripken.github.io/emscripten-site/docs/introducing_emscripten/about_emscripten.html).

It compiles C/C++ programs to WebAssembly, and it provides WebAssembly wrappers for the C stdlib, the C++ stdlib, SDL, OpenGL, and more.

In many cases C/C++ programs *just work* with Emscripten, without any modifications.

**Comment by Pauan** [comment]
@csy2002 I don't know C or C++, but my understanding is that Emscripten supports (basically) the entire C/C++ stdlib, so existing C/C++ functions should work just fine. So your existing code should work.

However, even though you can use existing C/C++ APIs, [it will internally use WebSockets for the connection](https://github.com/kripken/emscripten/issues/5196#issuecomment-299442038), so your server must accept WebSockets. And WebSockets are TCP only.

This is not a limitation in WebAssembly, [it is a limitation in the web browser itself: the browser only allows you to use HTTP(S), WebSockets, or WebRTC](https://gafferongames.com/post/why_cant_i_send_udp_packets_from_a_browser/). It has no support for raw sockets (UDP or TCP).

**Comment by Macil** [comment]
If you're in a browser and you need the non-reliable communication of UDP, then your only standard option is to use WebRTC. WebRTC is usually for peer-to-peer connections between users, but you could make your server be a WebRTC "peer" so that the user opens a WebRTC connection to the server. This isn't well-established territory as far as I know though, so I don't know of any full examples of this to point anyone to. ([PeerJS](https://peerjs.com/) is a simple example of WebRTC data channels being used on the client-side.) Also, not all browsers (like Edge) support WebRTC data channels, so unless you're just using WebRTC's audio+video support, then you would need a WebSocket (TCP) fallback if you want to support those browsers.

**Comment by AzazeII** [comment]
Урыл!

**Comment by lsycxyj** [comment]
I think WebAssembly or even WebAPIs should support lower-layer protocols like TCP and UDP etc. Either WebRTC or WebSocket is an upper layer protocol, which has been wrapped with so many unecessary things and limitations. For example, we couldn't make QUIC connection polyfills or use customized TCP transmission control for some caes.

If the security should be concerned, some rules we could make. For example, we could make a preflight request for CORS policies.

**Comment by Mubelotix** [comment]
> For example, we could make a preflight request for CORS policies.

Many public servers won't add support for these preflight requests. The absence of response could be treated as "there is no restriction on this server". But why don't we create a special permission? I don't think these kind of connections should be made without explicit user approval.

**Comment by lsycxyj** [comment]
> Many public servers won't add support for these preflight requests. The absence of response could be treated as "there is no restriction on this server". But why don't we create a special permission? I don't think these kind of connections should be made without explicit user approval.

I don't think whether the public servers support preflight requests or not is the problem, since the security check is only done by client (eg. browser). If the public servers don't respond with correct preflight response, the client can block the subsequent those invocations of the lower-level APIs.

**Comment by ondrejtomcik** [comment]
@Pauan any idea why this issue is not closed? Based on your comment
>This is not a limitation in WebAssembly, it is a limitation in the web browser itself: the browser only allows you to use HTTP(S), WebSockets, or WebRTC. It has no support for raw sockets (UDP or TCP).

I don't think this will be ever supported. Any comments?

**Comment by Pauan** [comment]
@ondrejtomcik I'm not a part of the WebAssembly or W3C working groups, so I can't comment on that.

But in my personal opinion this feature should go into the browser itself, not Wasm, so it would be better to open a new issue with the W3C.

**Comment by ngzhian** [comment]
As mentioned above, if you are targeting the Web (via Emscripten), you likely have to port your networking logic to use [WebSockets](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API) or try out [WebTransport](https://web.dev/webtransport/).

If you are targeting server environments, take a look at WASI, it is not implemented yet but there are feature requests (https://github.com/bytecodealliance/wasmtime/issues/70).

This is not something that goes into WebAssembly itself: it is provided by the host/embedder.

**Comment by greyltc** [comment]
The direct-sockets API is now a thing: https://github.com/WICG/direct-sockets

Here's the specification: https://wicg.github.io/direct-sockets/

This isn't just a concept either, here's a working browser telnet client: https://github.com/googlechromelabs/telnet-client

Maybe this issue could be reopened/revisited.
