### ISSUE TITLE
C auto variable semantics

### ISSUE THREAD

**Issue by BillGee1** [WebAssembly/design#1254]
In the AST local variable specification it is stated that:

```
Local variables do not have addresses and are not aliased in the globals or the heap
```

If I am interpreting this correctly, then how will a C function-local auto variable be treated?  Specifically, how could an automatic variable's address be passed to another function since that is the way to pass by reference in C?

```
void function1 ()
{
    int variable;

    function2(&variable);
}
```

**Comment by binji** [comment]
This is described in some detail [here](https://github.com/WebAssembly/tool-conventions/blob/master/BasicCABI.md#the-linear-stack). The short version is that the C compiler must generate a separate stack in linear memory that is used for address-taken local variables.

**Comment by BillGee1** [comment]
OK.  Separate stack it is.
