### ISSUE TITLE
Best lower level language to "prepare" for more mainstream adoption of wasm ?

### ISSUE THREAD

**Issue by fabm22** [WebAssembly/design#1255]
Hi,

Given that one wouldn't have any particular experience in any lower level (ie. compared to JS) language apart from the basics, which language that will be source to wasm compilation would you typically recommend to learn/get into ???

Precisely, I was hesitating between C++ and Rust, so would you say Rust will be(is?) a "typical" source language (i.e. at least at same level as C/C++) for compilation into WASM ?

Maybe another language than those two ?

Thanks a lot for your advice, hoping this 'issue' is placed conveniently.

**Comment by kripken** [comment]
[AssemblyScript](https://github.com/AssemblyScript/assemblyscript) is another good option.

**Comment by Pauan** [comment]
I don't think this is the right place to discuss this, but personally I think Rust is easier to learn than C++.

Rust has excellent built-in support for compiling to wasm. It also supports emscripten, but that tends to be a bit slower and heavier.

And it has strong support for JS interop as well, with [wasm-pack](https://rustwasm.github.io/wasm-pack/), [wasm-bindgen](https://rustwasm.github.io/wasm-bindgen/), and [stdweb](https://crates.io/crates/stdweb).

There is also an [official Rust + Wasm working group](https://rustwasm.github.io/) whose purpose is to build and ensure excellent Wasm support for Rust.

By "official" I mean actually officially a part of Rust, and run by Rust team members.

(Disclaimer: I am a part of the Rust + Wasm working group, so I'm *not* an unbiased third-party observer)
