### ISSUE TITLE
mac emcc: command not found

### ISSUE THREAD

**Issue by dxl-enter** [WebAssembly/design#1256]
mac emcc: command not found

**Comment by kripken** [comment]
How did you install it? The instructions here should work: https://webassembly.org/getting-started/developers-guide/ In particular the "activate" step is what adds it to the path, so that `emcc` is found.

**Comment by dxl-enter** [comment]
Thank you, the emcc command is ready to use, but there is a problem, the problem is "File"/dxler-doc/WebAssembly/emsdk/emscripten/1.38.23/emcc", line 6, in <module>
     From tools import python_selector
ImportError: No module named tools", what is the reason?

**Comment by dxl-enter** [comment]
@kripken

**Comment by kripken** [comment]
It sounds like something's wrong with the install, or with how python is set up. "tools" is in a folder inside emscripten/, I'm not sure how it could not find it.

**Comment by sbc100** [comment]
Please re-open in the emscripten repo if this issue persists. (https://github.com/emscripten-core/emscripten/)

**Comment by eyworldwide** [comment]
Reinstall and solved!

**Comment by playground** [comment]
> Reinstall and solved!

@eyworldwide how did you get it to install successfully?  emcc is still command not found.

**Comment by eyworldwide** [comment]
> > Reinstall and solved!
> 
> @eyworldwide how did you get it to install successfully? emcc is still command not found.

@playground  There are several reasons(or issues) for 'emcc: command not found'.  This issue can be fixed by reinstalling Emscripten.  Then I had another issue (https://github.com/emscripten-core/emscripten/issues/5696#issuecomment-494364645) and I had fixed too. I think this is the main reason of the problem. Hope helpful to you.

**Comment by playground** [comment]
Yes, that's exactly what I did.  Thanks @eyworldwide
