### ISSUE TITLE
Should JS.md be marked as deprecated and point to the new JS API spec?

### ISSUE THREAD

**Issue by ajklein** [WebAssembly/design#1258]
It's my understanding that the future of the JS API spec is the WebIDL-based approach at https://webassembly.github.io/spec/js-api/. If that is indeed the case, should JS.md be updated to point to that page (and either have the rest of what's there now removed, or at least marked as no-longer-current)?

**Comment by littledan** [comment]
Yes. I will make a patch for this. 

Is this document confusing people? To avoid that confusion, I think there are other updates to make to this repo as well.

**Comment by xtuc** [comment]
What's the advantage of keeping the document? Couldn't we just delete it in favor of the WebIDL spec?

**Comment by littledan** [comment]
I agree with xtuc's comment. I didn't do this earlier because I thought there would be some other effort to update this repo, and removing JS.md would be part of that.

**Comment by rossberg** [comment]
Is there any difference between this specific document and most of the others in the design repo? Much of the info there is not up to date nor is it normative. Whatever we decide to do we should do consistently.

FWIW, I can see the historic and documentary value of these docs, so I wouldn't remove them. However, we should add explicit notes to each page pointing out their status and a link to the respective normative specs.

**Comment by binji** [comment]
OK, this landed. Closing.
