### ISSUE TITLE
Clarify buildtime vs runtime dependencies

### ISSUE THREAD

**Issue by mcandre** [WebAssembly/design#1263]
Could we separate the prerequisites into distinct groups:

* Things required to build emscripten itself
* Things required to run emscripten

This is particularly relevant for automated build bots, where disk space efficiency is important.

**Comment by binji** [comment]
It might be better to file this at https://github.com/emscripten-core/emscripten.

**Comment by sunfishcode** [comment]
As noted above, please file issues about Emscripten in the Emscripten repository.
