### ISSUE TITLE
Is latest webassembly version allows all instruction format?

### ISSUE THREAD

**Issue by AchalaSB** [WebAssembly/design#1264]
Hi,

Is the latest webassembly version allows all instruction format (all LLVM languages) in the Virtual Machine??
What are the limitation for the instruction format??
Is there any fork for the decentralized application?

(Where can I rise my general question about WASM? Is there any community channel?)

**Comment by nidin** [comment]
You can find the WASM [spec here](http://webassembly.github.io/spec/) | [PDF](http://webassembly.github.io/spec/core/_download/WebAssembly.pdf)

You can also join [WebAssembly W3C Community Group](https://www.w3.org/community/webassembly/)

Most of the decussions are happening in github and CG meetings.

**Comment by sunfishcode** [comment]
The questions here appear answered. If there are any further questions; please file a new issue!
