### ISSUE TITLE
Import section and import_entry design

### ISSUE THREAD

**Issue by ConsciousCode** [WebAssembly/design#1265]
According to the spec, each import_entry has to specify the name of the library the item is being imported from. For small programs this isn't a problem, but consider something like linking Ogre3D into a wasm program - thousands of import_entry's, each with "libogre3d" for module_str. Isn't it more natural (and indeed, typical in many language's import syntax and semantics) to specify a library once and then list the items being imported from it? Is there something I'm missing which makes this repetition either not a problem or even desirable? Or maybe I'm misunderstanding the spec and what I propose is already the case?

For example, one possible encoding which I would expect is:

<h3>Import</h3>
<table>
 <tr><th>Field</th><th>Type</th><th>Description</th></tr>
 <tr><td>count</td><td>varuint32</td><td>count of library entries to follow</td></tr>
 <tr><td>entries</td><td>lib_entry*</td><td>repeated library entries as described below</td></tr>
</table>

<h4>Library entry</h4>
<table>
 <tr><th>Field</th><th>Type</th><th>Description</th></tr>
 <tr><td>module_len</td><td>varuint32</td><td>length of `module_str` in bytes</td></tr>
 <tr><td>module_str</td><td>bytes</td><td>module name: valid UTF-8 byte sequence</td></tr>
 <tr><td>count</td><td>varuint32</td><td>count of import entries to follow</td></tr>
 <tr><td>imports</td><td>import_entry*</td><td>repeated import entries as described below</td></tr>
</table>

<h4>Import entry</h4>
<table>
 <tr><th>Field</th><th>Type</th><th>Description</th></tr>
 <tr><td>field_len</td><td>varuint32</td><td>length of `field_str` in bytes</td></tr>
 <tr><td>field_str</td><td>bytes</td><td>field name: valid UTF-8 byte sequence</td></tr>
 <tr><td>kind</td><td>external_kind</td><td>the kind of definition being imported</td></tr>
</table>

**Comment by KronicDeth** [comment]
The tables you posted read to me that one import has 1 or more lib entries . The lib_entry then has 1 module and 1 or more import_entries and it is those import entries that have the function, const, object, etc name.  So `libogre3d` will only appear in one `lib_entry`.

**Comment by binji** [comment]
That's true, though taking a look at some large WebAssembly modules, the size of the import section is still a small fraction of the total size. A few examples:

| name | import section size | total size | percentage |
| --- | --- | --- | --- |
| UE4 demo | 14723 | 43913817 | 0.033% |
| AngryBots | 31504 | 10458914 | 0.3% |
| Unity Benchmark | 36175 | 13212198 | 0.27% |

It's also possible to compress these names, if necessary, by providing an import object to `WebAssembly.instantiate` with shorter names.

**Comment by ConsciousCode** [comment]
@KronicDeth The first table represents the Import section of which there would always only  be one, otherwise that's correct. libogre3d would only appear in one lib_entry and would list the items to import. The only potential issue is the added complexity, but the Name section has a similar subsection-based structure.

@binji So I guess for now we can say it might be an odd design choice but it's not enough of a concern to change? That works. This will probably be addressed in the layer 1 structural compression anyway.

**Comment by binji** [comment]
Yes, we couldn't change the current behavior since we need to keep backward compatibility with existing wasm modules. We could add a new section code if we really thought it was worth it, but I'm not sure it is.
