### ISSUE TITLE
Emoji in design docs are broken

### ISSUE THREAD

**Issue by maxwell-clarke-intranel** [WebAssembly/design#1266]
Expected behaviour:
![image](https://user-images.githubusercontent.com/39687678/54170916-71d8b700-44dd-11e9-9aeb-7d8aae8d0c96.png)
Observed behaviour:
![image](https://user-images.githubusercontent.com/39687678/54170850-1c9ca580-44dd-11e9-9fde-6140e7cacd0c.png)

GitHub has changed the location of the emoji images, so they 404 when viewed on the webassembly.org website.
When the .md files are viewed here on github, the correct behaviour can be seen.

The new image location is:
https://github.githubassets.com/images/icons/emoji/unicode/2b50.png
The old image location is:
https://assets-cdn.github.com/images/icons/emoji/unicode/2b50.png

**Comment by xtuc** [comment]
I would rather replace them with UTF-8 chars

**Comment by binji** [comment]
I updated the website bundles and it seems to have fixed the issue.
