### ISSUE TITLE
Define function signatures

### ISSUE THREAD

**Issue by steveluc** [WebAssembly/design#127]
It would be helpful in reasoning about ABIs if the Call section of the AST document could give some examples of function signature specifications.  

How would this proposal handle variable-length parameter lists?
How do compilers place arrays on the stack?  Looks like all of the local variable types are scalar.

**Comment by sunfishcode** [comment]
#278 is a pull request which defines function signatures.

**Comment by sunfishcode** [comment]
Function signatures are defined in #307, which is now merged, along with a note about C varargs. There are also some example functions [in the spec test directory](https://github.com/WebAssembly/spec/tree/master/ml-proto/test).
