### ISSUE TITLE
Will WASM attempt to support some equivalent of "view source"?

### ISSUE THREAD

**Issue by erlend-sh** [WebAssembly/design#1279]
I am not here to argue one way or the other, I'm just curious to what extent this is a design goal for the WebAssembly spec. And I *will* argue that it's an objectively good feature to have, at least as an option, for the teaching value alone.

**Comment by KronicDeth** [comment]
@erlend-sh are you proposing that browsers be required to support something like `wasm2wat` and have the `.wat` be pretty printed?  This might also belong in https://github.com/WebAssembly/tool-conventions and https://github.com/WebAssembly/debugging as being able to step debug at the WASM level if not the original source level requires this.

**Comment by binji** [comment]
This is one of the original design goals of the text format, see https://github.com/WebAssembly/design/blob/master/TextFormat.md#design-considerations.

> The design goals for a WebAssembly text format derive from the following use cases:
> 
> * View Source on a WebAssembly module, thus fitting into the Web (where every source can be viewed) in a natural way.
> * Presentation in browser development tools when source maps aren't present (which is necessarily the case with the Minimum Viable Product (MVP)).
> * Writing WebAssembly code directly for reasons including pedagogical, experimental, debugging, optimization, and testing of the spec itself.

**Comment by erlend-sh** [comment]
Wonderful @binji, thanks for pulling that up for me. What issue/feed/.. should I be tracking to stay in the loop on this?

**Comment by binji** [comment]
AFAIK, most engines support disassembling of WebAssembly functions already. It would be nice to be able to view the entire module as well. I don't think there's any work to do on the spec for this, so the best direction would be to file a bug on a particular browser/engine's bug tracker. Other more advanced debugging features require more design, and are the purview of the Debugging subgroup, as @KronicDeth mentioned.
