### ISSUE TITLE
negative variable

### ISSUE THREAD

**Issue by extremety1989** [WebAssembly/design#1284]
Hey,
i m trying to build sigmoid function in wat format 
how can i make negative variable ?

;;  f(x) => 1/(1+Math.exp(-x));

error: unexpected token -$x.
                    (get_local -$x)

here is my code:

(module
 (func $exp (import "Math" "exp") (result f32))
  (func $sigmoid (param $x f32)(result f32)
        (f32.div
                (f32.const 1)

                (f32.add
                    (get_local (-$x))
                    (call $exp)
                    (f32.const 1))
        )
   )

  (export "sigmoid" (func $sigmoid))
)

**Comment by rossberg** [comment]
`(f32.neg (local.get $x))`

**Comment by extremety1989** [comment]
thanks !

**Comment by extremety1989** [comment]
i get an error 

error: type mismatch in function, expected [] but got [f32]
        (f32.div

(module
(func $exp (import "Math" "exp") (result f32))
(func $sigmoid (param $x f32)(result f32)
        (f32.div
                (f32.const 1)

                (f32.add
                        (f32.neg (local.get $x))
                        (call $exp)
                        (f32.const 1)
                )
        )
)

(export "sigmoid" (func $sigmoid))
)

**Comment by rossberg** [comment]
Can I kindly suggest taking basic questions like this to a forum such as StackOverflow?

**Comment by binji** [comment]
You can write the function like this:

```wasm
(import "Math" "exp" (func $exp (param f32) (result f32)))

;; f(x) => 1/(1+Math.exp(-x));
(func (export "sigmoid") (param $x f32) (result f32)
  (f32.div
    (f32.const 1)
    (f32.add
      (f32.const 1)
      (call $exp (f32.neg (local.get $x))))))
```

**Comment by extremety1989** [comment]
@binji thank you !  i just found my mistake ,did not realise that call exp without params (f32.neg (local.get $x))

**Comment by extremety1989** [comment]
@binji oh, same error 

 error: type mismatch in function, expected [] but got [f32]
  (f32.div
   ^^^^^^^

**Comment by extremety1989** [comment]
because (local.get $x) pops value , i used tee_local 
(call $exp (f32.neg (tee_local $x)))
