### ISSUE TITLE
Passing 2d array to wasm

### ISSUE THREAD

**Issue by extremety1989** [WebAssembly/design#1285]
Hey guys,
i want to build matrix librairy using wasm, 
My first question is 
what kind of data must i provide from javascript to wasm function ?
i tried 2d array like 

```
const mat1 = [
[2,2],
[5,5]
]; 
const mat2 = [
[2,2]
,[5,5]
]; 
let result = [
[0,0],
[0,0]
]; 
```

result should be [  [4 ,4],
                              [25, 25] ]            ]

i have compiled m2x2 function to wasm
here is my C code , 

```
int m2x2(int mat1[][2], int mat2[][2], int res[][2]) 
{ 
    int i, j, k; 
    for (i = 0; i < 2; i++) 
    { 
        for (j = 0; j < 2; j++) 
        { 
            res[i][j] = 0; 
            for (k = 0; k < 2; k++) 
                res[i][j] += mat1[i][k]*mat2[k][j]; 
        } 
    }
    
    return res;  
} 
```

**Comment by binji** [comment]
As mentioned in #1284, please use StackOverflow for questions like these. Issues in this repo are meant to be used for the design of WebAssembly.
