### ISSUE TITLE
Create a collaborative benchmark repo

### ISSUE THREAD

**Issue by binji** [WebAssembly/design#1287]
We discussed this in the 2019 CG meeting and decided to create a new collaborative benchmark repository.

See https://github.com/WebAssembly/meetings/blob/master/2019/CG-06.md#collaborative-benchmark-suite--hr.

cc @titzer

**Comment by michaelvoronov** [comment]
We have recently [benchmarked](https://medium.com/fluence-network/a-standalone-webassembly-vm-benchmark-5300d534a04d) different Wasm execution environments on some [tests](https://github.com/fluencelabs/fluence/tree/master/bench/vm/tests). If you want, you could use them for your benchmark and I can help with setup. There are 8 tests:
- snappy compression of random data
- deflate compression of random data
- factorization based on the Atkin sieve
- Fibonacci computing
- recursive hash calculation
- matrix product
- SVD matrix decompostion
- QR matrix decompostion

All of these tests have some adjustable parameters set up as a environment variables.

Furthermore, we have [Redis](https://github.com/fluencelabs/redis/tree/wasm/src) with lua ported to Wasm that could be compiled without any exported functions, and it could be a good test if we predefine some Redis commands in a resulted binary like [this](https://github.com/fluencelabs/redis/blob/wasm-bench/src/wrapper.c#L218).

**Comment by kripken** [comment]
The [emscripten benchmark suite](https://github.com/emscripten-core/emscripten/blob/incoming/tests/test_benchmark.py) has a bunch of real-world codebases like poppler, bullet, box2d, lua, and sqlite. Some builds are [here](https://github.com/kripken/embenchen/tree/master/asm_v_wasm), I can update those if it would be useful.

It's pretty easy to build them too, basically edit that benchmark python file to pick which VMs to run etc., then `python tests/runner.py benchmark.test_skinning` would run the skinning benchmark for example.

**Comment by Hywan** [comment]
[Wasmer](https://github.com/wasmerio/wasmer) has a [speed center](https://speed.wasmer.io/) (see [the blog post](https://medium.com/wasmer/benchmarking-webassembly-runtimes-18497ce0d76e)).

It's open source, https://github.com/wasmerio/wasmer-bench, anybody can install it. It allows to track performance, compare between different modules (or runtimes) etc.

cc @bjfish

**Comment by sunfishcode** [comment]
The [benchmarks repository](https://github.com/WebAssembly/benchmarks) has been created! For any questions; please use that repository's issue tracker.
