### ISSUE TITLE
Why The WASM is not available to other interpreted programming languages as Python?

### ISSUE THREAD

**Issue by PROgramJEDI** [WebAssembly/design#1295]

**Comment by KronicDeth** [comment]
Are you asking why other languages don’t have VMs in WASM?  Your phrasing is unclear.

**Comment by kripken** [comment]
Python has been ported to wasm several times, for example in [pyodide](https://github.com/iodide-project/pyodide) and [micropython](https://github.com/pmp-p/micropython-ports-wasm). Portable interpreters, like CPython etc., are typically very easy to compile to wasm.

If you mean running wasm from Python, then [there are libraries for that too](https://github.com/wasmerio/python-ext-wasm).

**Comment by sunfishcode** [comment]
The question here seems answered; please file a new issue of there are more questions!
