### ISSUE TITLE
Question: invoke native code that controls a card reader in a browser

### ISSUE THREAD

**Issue by jlerbsc** [WebAssembly/design#1303]
Is it possible to drive a card reader in a browser from a webassembly module (derived from native libraries developped initially in C) and javascript functions or is there a limitation usage of webassembly module caused by the execution in a sandbox.

**Comment by KronicDeth** [comment]
WebAssembly doesn't give you access to anything outside the sandbox of the browser.  If there isn't already a Web API for it, you can't do it.

**Comment by jlerbsc** [comment]
Could you give me an exemple of WebAPI?

**Comment by jlerbsc** [comment]
Thanks for your responses.

**Comment by jlerbsc** [comment]
Another question : Can I read files from the disk by using Webassembly?
In stackoverflow (https://stackoverflow.com/questions/45535301/can-i-read-files-from-the-disk-by-using-webassembly) we can see a response "You have no access to files on disks." but there is a Web API FileReader . So what is the actual response.

**Comment by KronicDeth** [comment]
The [MDN docs for FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) explain the restrictions on FileReader:

> File objects may be obtained from a FileList object returned as a result of a user selecting files using the <input> element, from a drag and drop operation's DataTransfer object, or from the mozGetAsFile() API on an HTMLCanvasElement.

It is not the same as `fopen` or `open` in a POSIX API.  It does not have direct access to the entire file system.

**Comment by Macil** [comment]
Currently, WebAssembly can only use Web APIs by talking to Javascript code which uses the Web APIs for it. You need to write Javascript code that uses the API and then make it talk to your WebAssembly.

If you're using Rust, you can use https://rustwasm.github.io/docs/wasm-bindgen/ which will handle a lot of the process of talking to Javascript code from Rust for you.

**Comment by binji** [comment]
Closing, since it seems like this question was answered. Please reopen if there is anything else.
