### ISSUE TITLE
Build IDs to match DWARF debug files

### ISSUE THREAD

**Issue by mitsuhiko** [WebAssembly/design#1306]
Now that DWARF debug information are becoming a thing I was looking into what is necessary to provide breakpad style deferred symbolication. The initial blocker that came up was that there is no good way to match up the main wasm file and the companion wasm file containing debug info.

The way this works best normally is with GUIDs that identify the pairing. In mach we have UUIDs, in ELF the GNU build ID and on Windows the PDB signature and age.

Ideally we would have a UUID stored in WASM files as well. This would permit services like [Sentry](https://github.com/getsentry/sentry/) or [Symbolicator](https://github.com/getsentry/symbolicator) be able to fetch debug information files from external sources by knowledge of the UUID alone.

**Comment by paolosevMSFT** [comment]
I agree that it would be very useful to have a standard mechanism to uniquely identify WASM modules with a UUID and match them with symbol files. Could we add a new custom section "uuid"?

**Comment by mitsuhiko** [comment]
I'm closing this issue here for the one I opened in the tool conventions repo.
