### ISSUE TITLE
Tail call made easy

### ISSUE THREAD

**Issue by verbessern** [WebAssembly/design#1307]
I have read the tail call comments here https://github.com/WebAssembly/proposals/issues/17. I think that the problem of the tail call is that in the web assembly, there is no direct access to the call stack. I propose to put a "call_tail" function into the next versions of the specs, that will still not access the stack directly but will do:
- push the current arguments, by calculating them possibly based on the current arguments
- remove the current function arguments from the call stack, that will effectively shift the new on top
- keep the return address
- jump to the "called" function
- return from the function on the caller of the original one (yes, the 'return' is part of the instruction effect)

**Comment by rossberg** [comment]
I think what you are describing is exactly what the `return_call` instruction in the proposal does.

**Comment by verbessern** [comment]
Ah...I will check and delete this.

**Comment by verbessern** [comment]
Yes.., it seems I have missed that one. Thank you. I see no way to delete this issue however, so I will just close it.
