### ISSUE TITLE
Binary op codes

### ISSUE THREAD

**Issue by verbessern** [WebAssembly/design#1308]
I would like to express my concern that, the op codes 0x00-0xBF that are currently defined will require two byte op codes (or more) to be defined later (maybe one day, a direct byte operands will be defined). I think that, until is not too late, its a good idea to reserve the remaining range (0xC0-0xFF), total of 0x40 for "paging", or at least 0xF part of its high range. Because if the next op codes are assigned, and only 0xFF byte is let to mark the 2 bytes codes that could be a problem. I think its better to be 0xC0 0x?? as a page for all 'X' type of op codes, then 0xC1 for 'Y' types and so on. That will at least increase the total possible 2 byte codes to 0xBF + 0x40 * 0xFF = 0x407F = 16511, instead of 0xFE + 1 * 0xFF = 0x1FD = 509, and will make the op codes better organized, as it will allow any particular group to grow linearly, not to interleave with other op codes in the future.

**Comment by verbessern** [comment]
ps. The best could be an encoding that reserves the high bit like a 'continuation' bit, but its too late for that, because the op codes have grown to 0xBF already. Yes, I know that this will make the 'current' programs smaller in size, but will that be the case after some time is hard to say.

**Comment by binji** [comment]
We've discussed this in the past, and the current plan is to reserve 0xF0-0xFE as extension codes, where the following instruction is encoded as LEB128 (this has already been done in the SIMD proposal, which has > 128 instructions). In addition 0xFF itself is reserved for future expansion.

**Comment by verbessern** [comment]
Yes LEB128 is a way to be. It would be better if all opcodes were defined like this, but and this is fine I guess.
