### ISSUE TITLE
[Support] Need advice on documenting post-MVP feature availability across browsers.

### ISSUE THREAD

**Issue by carlsmith** [WebAssembly/design#1312]
I'm working a doc that covers the WebAssembly Text Format, and intend to update it over time to reflect the state of the art.

When it comes to which post-MVP features are supported in which browsers, and whether they are behind flags, there does not seem to be any obvious way to find out. The `caniuse.com` service seems to treat WebAssembly as a single feature. The vendor's various bug trackers are remarkably unclear on the status of features (unless I'm missing something), and the WebAssembly GitHub repos for each feature are no more specific.

I thought about feature testing, but having to run Safari and Edge is a pain, and it's not even clear how to implement the tests.

There's [a doc on Feature Testing][1], but it's aimed more at detecting and polyfilling a specific, needed feature, while I effectively need a table mapping each feature to each major browser, where each item can be `unsupported`, `flag-enabled` or `available`.

One other thing: Are any WebAssembly features are ever vendor-prefixed? I'm assuming not.

Any advice on this would be appreciated. Thanks.

[1]: https://github.com/WebAssembly/design/blob/master/FeatureTest.md

**Comment by tlively** [comment]
The state of the art is feature detection. https://wasm-feature-detect.surma.technology/ is the homepage for a good feature detection library and also includes a handy table that tells you what features are available in your browser. There is unfortunately not yet centralized location that has this information for all browsers (or for other engines).

**Comment by carlsmith** [comment]
@tlively, thanks for your reply - much appreciated.
