### ISSUE TITLE
Is there an expectation that we will be able to run wasm binaries from script tags directly?

### ISSUE THREAD

**Issue by alshdavid** [WebAssembly/design#1313]
Is there an expectation that web assembly binaries will eventually be runnable directly from script tags?

```html
<html>
  <body>
    <script type="application/wasm" src="/app.wasm"></script>
  </body>
</html>
```

Of course, this would not be useful without DOM access inside a program compiled to wasm.

It's my understanding that DOM bindings will eventually be introduced, allowing first class DOM access/manipulation to programs compiled to wasm (please correct me if I am wrong about this).

With that assumption being made, would it be reasonable to expect wasm binaries to be runnable from script tags?

**Comment by Pauan** [comment]
There are some plans to integrate [Wasm with ES6 modules](https://github.com/WebAssembly/esm-integration), so in that case you would be able to do something like this:

```html
<script type="module" src="/app.wasm"></script>
```

But I don't know what the status is for the esm-integration proposal.

**Comment by alshdavid** [comment]
Thanks for the reply, Is it expected that wasm will eventually have DOM access?

**Comment by Pauan** [comment]
Yes, that's what the [interface-types proposal](https://github.com/WebAssembly/interface-types) does.

You can see the Wasm proposals [here](https://github.com/WebAssembly/proposals).

**Comment by binji** [comment]
Seems like these questions have been answered, so closing. Please reopen if otherwise.
