### ISSUE TITLE
Cross linking

### ISSUE THREAD

**Issue by verbessern** [WebAssembly/design#1315]
Currently the specification states that "The start function is intended for initializing the state of a module.  The module and its exports are not accessible before this initialization has completed." and "Each import is specified by a descriptor with a respective type that a definition provided during instantiation is required to match.". That prevents two modules to import functions from each other. i.e. cross link, because none can be initialized before the other one. 

If the initialization step is defined for more then one module at a time, that could be avoided. First all tables, memories and globals are initialized, then all imports and exports are connected, then the start function is be called for all the modules in the initialization step in turn. That will allow cross linking, but all modules must be initialized together. 

To further increase the flexibility, maybe the initialization step to be split in three sub steps, first add all modules, second connect one to another and third call the start functions of already fully connected modules.

**Comment by rossberg** [comment]
What you are describing is commonly referred to as _cyclic_ or _recursive_ linking. For a multitude of reasons, cyclic linking is very complicated to perform safely, and it was a conscious decision not to support that for the time being. For example, you cannot generally initialise globals, tables, or memories before you have a module's imports, since their initialisers may refer to them. That in turn leads to questions of evaluation order, the possibility of cyclic evaluation dependencies, and the possibility of observing partially initialised module state. Once we add type import/exports things get even more interesting.

**Comment by verbessern** [comment]
Hm...i somehow can't find what you are saying. The expressions that I think you refer to are "constant expressions" that are limited in the allowed instructions and can't call functions. That makes it safe to be initialized before the imports are resolved.

**Comment by rossberg** [comment]
Constant expressions include `global.get` on imported globals and (later) things like `ref.func` on imported functions. Table element segments can also refer to imported functions. In particular, module A may init global ga with the value imported from B's global gb and vice versa, creating a black hole.

**Comment by verbessern** [comment]
I understand your argument about the globals, but that is must be a link error when there are cyclic dependencies. I agree with the argument that its more complex.

**Comment by verbessern** [comment]
Actually, when I think more, I'm not sure that what you are saying applies. The globals can still be depending from each other and in one module. Additionally, even if globals are depending from import globals, they do not need to be initialized before the start function is called. That means that after all imports are connected to exports, then the globals can be initialized and the cyclic dependencies will not be worse then now. For the tables, memories and functions is the same. So the issue stays...

**Comment by verbessern** [comment]
Actually, when I think more, I'm not sure that what you are saying applies. The globals can still be depending from each other and in one module. Additionally, even if globals are depending from import globals, they do not need to be initialized before the start function is called. That means that after all imports are connected to exports, then the globals can be initialized and the cyclic dependencies will not be worse then now. For the tables, memories and functions is the same. So the issue stays..
