### ISSUE TITLE
Some concerns about module stream compiling.

### ISSUE THREAD

**Issue by Becavalier** [WebAssembly/design#1316]
As we know, we can leverage the section size field to perform stream compiling of the module. But how can we handle the situation that just one of the section is extremely big, but the other parts are small? Curious to know is there any way we can handle this situation without the need to load the whole section byte into memory all at once?

**Comment by lukewagner** [comment]
For most wasm modules, 99% of the bytes are indeed in just one section -- the code section -- and so effectively streaming the module does indeed require doing something finer-grained: streaming by function.  The binary format supports this by having each function in the code section declare it's size up front.

**Comment by Becavalier** [comment]
@lukewagner Make sense, thanks!
