### ISSUE TITLE
Rationale behind disallowing comma in identifiers?

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/design#1324]
As of [the spec](https://webassembly.github.io/spec/core/text/values.html#text-id), the comma character is explicitly disallowed in identifiers. Curious why this is the case, considering that the text format does not use comma characters anywhere.

Asking because we are currently emitting names with commas, which didn't cause any issues so far, except with spec-compliant syntax highlighting.

![comma](https://user-images.githubusercontent.com/1136893/72819728-09667480-3c6e-11ea-909d-43876202e392.jpg)

**Comment by rossberg** [comment]
Nothing too deep, but comma traditionally has special meaning in some S-expression formats, so it arguably follows the principle of least surprise. With the annotation proposal, it also enables treating comma as punctuation more easily in custom annotation grammars (which are limited to using the same tokenisation as the rest of the Wasm syntax).

**Comment by 7ombie** [comment]
`bump` This should have been closed ages ago.
