### ISSUE TITLE
Wasm binary and text formats need shebang, magic numbers and version codes

### ISSUE THREAD

**Issue by lukehutch** [WebAssembly/design#1328]
Now that wasm is moving out of the browser, it has become an excellent target for standalone binaries. It's really important to allow an optional shebang (e.g. `#!/usr/bin/wasmer-run`, followed by a newline, strictly defined as one character `\n`) at the beginning of a binary. This allows wasm code to be directly "run" (interpreted/JITed) as an executable on Linux.

However, I have been looking for but have been unable to find information on shebang support with wasm text and binary formats.  The wasm text format uses `;;` for comments, not `#`, so a shebang header would not work out of the box. The [binary format documentation](https://webassembly.github.io/spec/core/binary/index.html) does not describe any sort header information, including shebang support.

Probably there should be a single canonical binary runtime name, and the `/etc/alternatives` system could be used to select between different runtimes, if multiple runtimes are installed. For example, maybe the shebang should be standardized to `#!/usr/bin/wasmrun` or something, and `/usr/bin/wasmrun` could link to `/usr/bin/wasmer-run` or similar.

Also I was surprised to find no mention of a wasm "magic number" or wasm API/ABI version information in a header for either the binary or text format. It is very important to include both magic numbers and version information in headers for any data or code format, so that the filetype and version can be easily detected by just reading a few bytes at the beginning of the file. (A shebang with canonical path can serve as a magic number.)

See also https://en.wikipedia.org/wiki/Binfmt_misc

**Comment by binji** [comment]
We could add shebang support for the text format, though typically the text format is so verbose that you wouldn't want to ship anything that way. Using binfmt_misc seems like a better direction, and should be doable without any changes. [The magic number and version are described here](https://webassembly.github.io/spec/core/binary/modules.html#binary-module).

```
magic ::= 0x00 0x61 0x73 0x6d
version ::= 0x01 0x00 0x00 0x00
```

i.e. magic = "\0asm" and version is 1 as a little-endian 32-bit int.

**Comment by lukehutch** [comment]
Thanks, I missed the module header fields.

Please close this if you determine that shebang for the text format is not necessary. It's never a bad idea to add this as an option though for any programming language.

**Comment by sunfishcode** [comment]
There doesn't seem to have been any other commenters here. As mentioned above, this wouldn't work for the binary format, and the text format is so verbose that one usually doesn't want to ship it anyway. Also, as discussed above, the binary format does have a magic number that can be used with binfmt_misc and similar, and that doesn't require us to standardize a "wasmrun" command-line interface.
