### ISSUE TITLE
Is there a preferred way to cite the WebAssembly standard?

### ISSUE THREAD

**Issue by NANASHI0X74** [WebAssembly/design#1329]

**Comment by binji** [comment]
I'd guess you could use the same citation as for other W3 standards. For example, the WebAssembly JS API document cites the WebAssembly Core document here: https://www.w3.org/TR/wasm-js-api-1/#normative

Though I just noticed that the URL is wrong :-) It should be https://www.w3.org/TR/wasm-core-1/ for the core spec.

Maybe @ericprud has more concrete advice here?

**Comment by ericprud** [comment]
Nope, that makes sense to me. This is what W3C REC citations look like in other W3C docs:

> [XML]
>   Tim Bray; et al. Extensible Markup Language (XML) 1.0 (Fifth Edition). 26 November 2008. REC. URL: https://www.w3.org/TR/xml

**Comment by NANASHI0X74** [comment]
thanks. I've already submitted my thesis now and cited the wasm core spec somehow.
But consider providing a bibTeX item somewhere on the website for example, I think that would make wasm more accessible for academic papers

**Comment by ericprud** [comment]
Respec allows one to [add other links](https://github.com/w3c/respec/wiki/otherLinks). There's probably something like that in bikeshed. If you submit a PR for a new file called something like `w3cspec.bib` (`thisspec.bib`? ideas?), we could set a precedent for W3C specs to include links to their own bibTeX. Maybe someday that would be automatically-generated by bikeshed but a manual one will do.

**Comment by jendrikw** [comment]
I use

```bib
@report{RossbergWebAssemblyCoreSpecification,
  title = {{{WebAssembly Core Specification}}},
  author = {Rossberg, Andreas},
  date = {2019-12-05},
  institution = {{W3C}},
  url = {https://www.w3.org/TR/wasm-core-1/},
  langid = {english}
}
```

**Comment by NANASHI0X74** [comment]
ok. If I may, I'm just going to blatantly steal your bibtex item thingy and submit a PR with it :sweat_smile:

**Comment by NANASHI0X74** [comment]
#1330

**Comment by sunfishcode** [comment]
The discussion here continued in #1330 and eventually moved to https://github.com/WebAssembly/spec/pull/1204 where it was merged. The official bibtex file is now here:

https://github.com/WebAssembly/spec/blob/main/wasm-specs.bib
