### ISSUE TITLE
C++ sleep using high cpu in node.js and browser, with web-assembly compiled from c++, using standard library

### ISSUE THREAD

**Issue by Xyncgas** [WebAssembly/design#1331]
I wanted to block EM_ASM_INT before it returns something, I can't do that hahah.
I wanted to wait a while before calling another function in c++, cpu goes up to full hahah.
I wanted to let EM_ASM's setTimeout to call my c++ function, but that missed the point.
If I had to go through all the hassle just to let my program wait a while without using lot cpu.
I wouldn't be retrieving information from the same origin.
std::this_thread::sleep_for(std::chrono::milliseconds(1000));  < - this the function I am using

**Comment by dschuff** [comment]
This kind of question is probably best to ask on emscripten's [mailing list](https://groups.google.com/forum/#!forum/emscripten-discuss)
