### ISSUE TITLE
Vectors with runtime-defined length

### ISSUE THREAD

**Issue by penzn** [WebAssembly/design#1332]
Opening to document an item added to the [agenda][a] for meeting on April 28. This came out of a number of discussion in context of the SIMD proposal, for example WebAssembly/simd#29.

[a]: https://github.com/WebAssembly/meetings/blob/master/2020/CG-04-28.md#agenda-items

The gist of the proposal is to provide a set of vector operations with runtime-constant length, which is not known at compile time, see [overview repository][r] or [slides][s].

[r]: https://github.com/penzn/wasm-long-vectors
[s]: https://penzn.github.io/wasm-long-vectors/

This is by no means a proposal to modify existing SIMD, in fact, part of the motivation to ask for phase 0 repository is to move discussions on this idea away from the SIMD proposal. Wasm SIMD serves as inspiration for this, in a way, but it should move forward without waiting for this idea to flesh out. 

Note that the proposal does not cover true vector instruction sets (as discussed #1151, for example), though are still relatively rare in consumer hardware.

**Comment by lars-t-hansen** [comment]
@penzn, on p9 and p14 of the slides the innermost "block" should be "loop".  Also, I don't understand slide 14, because I don't understand the `set_length` operation.  Apparently it returns some value, but what value?

**Comment by penzn** [comment]
@lars-t-hasen, I just got to your comment (time zone differences, sorry). Thank you for pointing out the loop typo - fixed that. I am running out of time before the meeting, might not be able to address the other comment in the PDF (though I will try) - it returns minimum between its parameter and available system length, and sets the internal vector length to that value.

**Comment by penzn** [comment]
Phase 1 proposal repository is set up: https://github.com/WebAssembly/flexible-vectors

With that, I am not sure if we should keep this issue open.

**Comment by tlively** [comment]
Probably not, let's move discussion over to the new repo.
