### ISSUE TITLE
Memory growing. The future will invalidate the present.

### ISSUE THREAD

**Issue by verbessern** [WebAssembly/design#1335]
Hi there, I'm reading the specs and something is disturbing me. The current specs is defining the memory growing to have a result: the current memory length (in pages), or -1 if the memory can't be grown for any other reason. Just over this definition there is another one, that states: "Future version of WebAssembly might provide memory instructions with 64 bit address ranges.". However, if ever 64 bits addressable memory become available to us, the result of growth by a 32 bit value will result in a 64 bits result as defined now.

**Comment by rossberg** [comment]
In the [Memory64 proposal](https://github.com/WebAssembly/memory64/blob/master/proposals/memory64/Overview.md), memories are declared with explicit index types, and parameter and result types of memory-related instructions become dependent on the referenced memory's index type. So `memory.grow` on a 64-bit memory would operate on i64.

That said, note that `memory.grow` operates in units of page size. Even for a 64-bit memory that would not overflow the 32-bit value range.

**Comment by verbessern** [comment]
Understood, thank you. Just for the protocol, the maximum addressing would be 48 bits on mem64 object.

**Comment by rossberg** [comment]
Yes, and that's only 2^16 pages, so no problem representing that in 32 bits.
