### ISSUE TITLE
2.5.6 Globals - allowed instructions

### ISSUE THREAD

**Issue by verbessern** [WebAssembly/design#1336]
Hi there. The specification is allowing a list of instructions for each global initialization. If more then one instruction is allowed, which one is the actual global initialization value from this instruction list? The first, the last,...?

It would be nice to have more then just 1 instruction for an initialization. I know from issue #1315, that later and functions should be callable. It would be nice to have "i32.const i32.const i32.add" as a list for example i.e. the result of the instructions to be the type of the global (single value). Instructions like local.get/set are not relevant, but many others are.

**Comment by rossberg** [comment]
The initialisers are interpreted as _expressions_. Their generic evaluation is defined [here](https://webassembly.github.io/spec/core/exec/instructions.html#expressions).

**Comment by verbessern** [comment]
For the evaluation yes, but it can't be actually used, because of the limitation in the allowed instructions in section 3.3.7 constant expressions.

**Comment by rossberg** [comment]
Well, that would be a feature proposal. So far, it hasn't been a priority to make this generalisation, so nobody has created a proposal for it. If you feel strongly, you could do so. I agree it would be useful.

**Comment by verbessern** [comment]
It looks like, its let to the generators to evaluate this constant expressions to a single generated value. Its unfortunate one global can't be equal to an imported global + 1, for example. I can agree to that for the moment, because of the MVP requirement for version one. Else, the constant expression should be able to use all instructions that are constant (as its currently defined, but immediately limited, both in section 3.3.7) i.e. excluding all `.set`.
