### ISSUE TITLE
Floating point textual representation grammar issues

### ISSUE THREAD

**Issue by verbessern** [WebAssembly/design#1337]
Hi there, I think that the grammar in section 6.3.2 is not as intended. It is not possible to have for example floating point `frac` as 1_2_3, because the grammar does not allow that, but only 1_23 or 12_3. For example the `num` in 6.3.1 allows this. The same is visible also in `hexfrac`.

**Comment by rossberg** [comment]
Indeed, the grammar is wrong. Fix [here](https://github.com/WebAssembly/spec/pull/1178).

Btw, issues like these would be more appropriately filed in the spec repo.

**Comment by verbessern** [comment]
Welcome. Understood for the repo, I'm new in the hub, but I will be around for quite some time.
