### ISSUE TITLE
Merging of function types in the text format.

### ISSUE THREAD

**Issue by verbessern** [WebAssembly/design#1338]
Hello, in section 6.6.3 it's defined that when an abbreviation of a `typeuse` is defined, it will receive an automatic `typeidx`, that eventually comes from the "similar" type that already exists. The issue is, that the previously defined `type` may have `id`s that are not the same as the ones into the abbreviation, so they can't be "reused". That is because the "similar" match is based on the definition at section 2.3.3, that does not take into an account the `id`s used in the text version. I would like to add, that loosing the `id`s information may lead to problems when they are referenced from the different functions: 

(type $t (func (param $a i32) (param $b i32)))
(func $f ($t) {body using $a})
(func $g (param $b i32) (param $a i32) {body using $a from the local 0, because the matching algorithm loses information, by reusing internally the type $t})

**Comment by rossberg** [comment]
I am not sure what you're asking. Function $f cannot refer to $a, and that's intentional, since bindings are meant to follow standard scoping rules. If you want to name a parameter, you have to bind the name locally, there is no global name space for locals. Correspondingly, in $g, the name $a refers to local 1, as one would expect.

**Comment by verbessern** [comment]
I apologize, the specification is somehow complex. I will be better soon. My confusion is from 6.6.3: "where 𝑥 is the smallest existing type index whose definition in the current module is the function type[𝑡*1]→[𝑡*2]". But "function type" is defined in 2.3.3 and does not take into an account the `id` from the `params` and the `results` defined in 6.4.2. 

Then if during parsing (or generation) of the textual format, one "reuses" $t instead of the abbreviated function type at $g (both have the same types) the `id`s from `$g` will be lost and their use is error prone. At least that is what I think its written "...are reused by consecutive expansions".

I think that the whole idea is to define in advance all types, then to have smaller files. But then the check of which types are `equal` must account and the `id`s.

**Comment by rossberg** [comment]
Hm, it seems like you are interpreting the spec correctly, but disagree with the semantics? But that is working as intended. The ids aren't "lost", they are simply not in scope. I'd say that it would be way more surprising and error prone if they were.

**Comment by verbessern** [comment]
So you are saying that the body of $f will see $a at local 0 (correctly), $b at local 1 (correctly), and $g will see $a also at local 0 (but should be 1, because its defined second)? Because that is what is going to happen "silently" when the abbreviated function type from $g is replaced by $t. So when I'm defining a function I can never know how my arguments will be messed up, or by defining a type, I could mess up some functions? Also if $t had $a and $c, then any reference in $g for $b would not exist, because after the "reuse" of $t from $g, $b will be no more available. That is all happening because the ids are not accounted during "reuse". Also that is only an issue for the text format, because there is no names for the parameters in the binary format.

**Comment by rossberg** [comment]
The $a and $b from $t are not in scope in either $f or $g. Parameter names in a type definition are irrelevant, they are not accessible from anywhere and serve no purpose other than documentation. Consequently, they need not be accounted for.

**Comment by verbessern** [comment]
I don't think so. The definition of `local` for example uses `localidx` defined in 6.6.1 with an `id` defined in 6.3.5. For this reason this example is valid (from https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format):

(func (param $p i32) local.get $p local.get $p i32.add)

**Comment by rossberg** [comment]
> Parameter names _in a type definition_ are irrelevant

;)

**Comment by verbessern** [comment]
I have just setup a test for that and...It seems the names are not accessible from `local.get` when a type is referenced by a function. I don't know where in the specs that was written however. I'm sorry for the lost time.

**Comment by verbessern** [comment]
I would like to add, that when a generator generates, because of the way the "reuse" algorithm works, it may have to rename all `local.get/set` instructions to indexes (`u32`) (if they are actually defined with `id`s, that is a perfectly valid thing to be), and that `must` happen always when a function type with the same parameters and return values exists. With other words, the algorithm for type `optimization` affects other already valid structures, and if I may, with respect, it smells.

**Comment by rossberg** [comment]
Sorry, I don't follow. AFAICT, the expansion of inline function types neither affects nor depends on symbolic index resolution. (And what "type `optimization`"  are you referring to?)

**Comment by verbessern** [comment]
When a generator generates, if during the generation of $g it "reuses" (optimizes) its params and returns from the type $t, (because the parameters and returns match), then the `id`s are lost (i.e. become `irrelevant` as you say), then all references to the locals by `id` (from the body of $g - local.get $a) must be renamed to indexes (`u32` - local.get 0). I use `optimize`, because it seems to me that the "reuse" is a an optimization for eventual readability and code size.

**Comment by rossberg** [comment]
Are you talking about a compiler producing text format with symbolic ids? Why would a the compiler have to bother outlining inline type signatures itself? And why do you worry about the "code size" of the text format? I don't understand.

**Comment by verbessern** [comment]
Its not about, why, its about should it, and can it. The specs allows this to be done - reusing. I'm not worrying about anything, I'm trying to help to make a better specification.

**Comment by verbessern** [comment]
What I'm trying to explain is, that I think at the textual format, the `id`s must be accounted.

`(type $t (func (param $a i32) (param $b i32)))` type
`(func $f (type $t) local.get 0 local.get 1 i32.div_u)` function using the type, but without an access to the ids is forced to use u32 indexes that for me forces a generator to lose its ids information and use indexes every time its reuses a type. I don't believe that this the right thing to be.
`(func $g (param $a i32) (param $b i32) (result i32) local.get $a local.get $b i32.div_u)` a function that divides the first argument to the second
`(func $h (type $t) (param $b i32) (param $a i32) (result i32) local.get $a local.get $b i32.div_u)`  the second divides the first, because the ids are switched

When the textual format give the ability to the generators to use ids, that must work everywhere, at least for me. I will just accept it as 'the way it is'.

**Comment by rossberg** [comment]
> When the textual format give the ability to the generators to use ids, that must work everywhere, at least for me.

It's really working like in in all programming languages: ids are scoped and can only be used in the scope of their definition. For ids occurring inside a type def, their scope is that type def, and nothing more. Just _using_ a type does not silently inject local ids from its definition into the current scope -- that would be rather error-prone and brittle.

**Comment by verbessern** [comment]
Depends how you see that reuse. I may see it as #define in C++. Its a meter of a perspective.
