### ISSUE TITLE
how build wasm of a project using meson?

### ISSUE THREAD

**Issue by MrMindHacker** [WebAssembly/design#1339]
how build wasm of a project using meson?
I am searching and trying hard but cannot find it..
do it really exists?
or we have need to build it

**Comment by KronicDeth** [comment]
Do you mean https://mesonbuild.com/ when you say meson?

**Comment by MrMindHacker** [comment]
Yes exactly I mean https://mesonbuild.com/

**Comment by tlively** [comment]
This would probably be a better question to ask on the meson repository. A quick search of their issues shows people succesfully doing emscripten builds with meson: https://github.com/mesonbuild/meson/issues/6095.
