### ISSUE TITLE
[Support] Cannot find the WASM operators documented anywhere.

### ISSUE THREAD

**Issue by carlsmith** [WebAssembly/design#1361]
The docs cover the names of the available instructions and their grammar, but I cannot find any more documentation than that.

Many operators are obvious, like `add`, but others are not. In particular, I cannot figure out the position (on the stack) of the operands to binary operations (where the order matters).

As an example, `i32.sub` (presumably) pops two values from the stack, subtracts one from the other, then pushes the result back to the stack. However, it's not clear which value is subtracted from which.

I can easily figure things out by trying them, but I was hoping there were some docs I've overlooked.

**Comment by ngzhian** [comment]
You can start from https://webassembly.github.io/spec/core/appendix/index-instructions.html.

Looking at at i32.sub, click on the "execution" link, brings you to https://webassembly.github.io/spec/core/exec/instructions.html#exec-binop

Steps 2 "Pop the value 𝑡.𝖼𝗈𝗇𝗌𝗍 𝑐2 from the stack." and 3 "Pop the value 𝑡.𝖼𝗈𝗇𝗌𝗍 𝑐1 from the stack." tells you the order of popping.

This describes how a general "binop" works, but for a specific instruction like `sub`, you can look in the Numerics section under Execution:  https://webassembly.github.io/spec/core/exec/numerics.html#xref-exec-numerics-op-isub-mathrm-isub-n-i-1-i-2 which states "Return the result of subtracting 𝑖2 from 𝑖1 modulo 2𝑁."

**Comment by carlsmith** [comment]
Thank you, @ngzhian. That's exactly what I needed. I don't know why I didn't see the index-sections in the table of contents. Also, thanks for taking the time to explain it clearly. It's much appreciated.
