### ISSUE TITLE
Indirectly (dynamically) referencing globals.

### ISSUE THREAD

**Issue by carlsmith** [WebAssembly/design#1367]
The `global.get` and `global.set` instructions (and the `local` versions) take an index that is a constant. There is no way to reference a global based on a runtime value.

The limitation forces me to either write hundreds (and potentially many thousands) of functions, one for each combination of registers, rather than one function that takes register indices as params, or just use linear memory with a bunch of extra `load` and `store` operations, which is ugly, and seems like it would be less performant.

Is there any reason not to have something like `call_indirect` for registers (basically `global.get_indirect` and `global.set_indirect` et cetera, but with better names), where the index is popped from the stack?

Please forgive my ignorance. Designing an ISA is way above my pay-grade.

**Comment by kripken** [comment]
A "dynamic" global.get/set would effectively be like linear memory, I think, in performance. Globals in general are just special locations in memory from the VM's point of view, so indexing them is what linear memory already does. But it would lose the safety that globals have, which is that you can easily tell where a specific one is used.

A "dynamic" local.get/set would prevent a lot of VM optimizations. It really helps to know which operations use which locals, so you can tell how to do efficient register allocation etc. For example when you spill registers around a call, you need to know which are live (so you can only spill the ones you actually need to), and if there is a "dynamic" local.get after it, it means all of them have to be spilled.

**Comment by carlsmith** [comment]
Thanks for explaining the issue, @kripken. You're right: What I'm suggesting doesn't really make sense, given the purpose of Wasm.

I'm writing Wasm by hand (with WAT), where dynamic register access would make more sense (just as a language feature). I understand Wasm is purely intended to be a compiler target.

Again, thanks.

**Comment by binji** [comment]
> What I'm suggesting doesn't really make sense, given the purpose of Wasm.

I don't think that's true, we just want to make sure we only add features to Wasm when we know that they'll provide sufficient value. For each of the core Wasm external types (func, global, table, memory), it may make sense to provide mechanisms for accessing them with a dynamic index (as you can with `call_indirect`), or even accessing them as a value (as you can with typed function references and `call_ref`). It's just not clear to me why you'd want to do that with `global` values.

**Comment by rossberg** [comment]
As @binji says, there would be ways to provide dynamic indexing, e.g. an indirection through tables or references. However, all the index spaces in a module themselves are very intentionally static. It is crucial that you can never address them dynamically, as that would break all sorts of rewriting transformations that various tools have to perform on indices.
