### ISSUE TITLE
Directly link to the proposal repos from the Future Features doc

### ISSUE THREAD

**Issue by carlsmith** [WebAssembly/design#1370]
It would be helpful if the table in [`FutureFeatures.md`][1] included links to the repos for the corresponding proposals (not just the tracking issues in this repo).

A quick aside: The table has a *Status* column that just says *in progress* in every row. Is there any other status? How is the status distinct from the phase?

In any case, linking the text in the *Status* or the *Phase* column to the repo for that proposal would be helpful.

I would have personally benefitted from a line that makes it clear that proposals even have their own repos, as that was lost on me for a while.

Thanks.

[1]: https://github.com/WebAssembly/design/blob/master/FutureFeatures.md

**Comment by conrad-watt** [comment]
If you're not aware already, you can find more up-to-date tracking in the proposals repo (https://github.com/WebAssembly/proposals).

It looks like that table has become a little out-of-date. A few of those proposals have already been standardised, and I believe we're no longer creating tracking issues for new proposals. Maybe the table should just be replaced with a link to the proposals repo?

**Comment by carlsmith** [comment]
Thank you, @conrad-watt. Much appreciated.
