### ISSUE TITLE
The WAT syntax does not seem to distinguish between int and float literals.

### ISSUE THREAD

**Issue by carlsmith** [WebAssembly/design#1376]
According to the spec, [the abstract syntax for floats][1] allows a literal to be formed from just one or more digits. The dot is optional, even when the `(‘𝙴’ | ‘𝚎’)` part is omitted too. So `0` can be 𝚞𝑁 or 𝚏𝑁 .

The spec defines 𝚗𝚞𝚖 as just one or more digits (with optional single-underscores in between), and the dot after the 𝚗𝚞𝚖 is optional for 𝚏𝑁:

    float  ::=  𝑝:𝚗𝚞𝚖 ‘.’?    =>    𝑝

The [*Tokens* section of the lexical format][2] describes a token like this:

    token  ::=  𝚔𝚎𝚢𝚠𝚘𝚛𝚍 | 𝚞𝑁 | 𝚜𝑁 | 𝚏𝑁 | 𝚜𝚝𝚛𝚒𝚗𝚐 | 𝚒𝚍 | ‘(’ | ‘)’ | 𝚛𝚎𝚜𝚎𝚛𝚟𝚎𝚍

Is is correct to infer that a tokenizer should distinguish three kinds of token for number literals: 𝚞𝑁 and 𝚜𝑁 for unsigned and signed integers and 𝚏𝑁 for floats (whether signed or not)?

Even if the tokenizer was contextual, that would still seem to imply that the token `0` should be 𝚏𝑁 when preceded by `f32` or `f64`, and 𝚞𝑁 otherwise, or something like that. That just seems wrong.

Sorry for such a basic question, but what am I not getting here?

[1]: https://webassembly.github.io/spec/core/text/values.html#floating-point
[2]: https://webassembly.github.io/spec/core/text/lexical.html#tokens

**Comment by binji** [comment]
You might find [the reference interpreter](https://github.com/WebAssembly/spec/blob/7526564b56c30250b66504fe795e9c1e88a938af/interpreter/text/lexer.mll#L124-L135) to be helpful here:

```ocaml
let nat = num | "0x" hexnum
let int = sign nat
let frac = num
let hexfrac = hexnum
let float =
    sign? num '.' frac?
  | sign? num ('.' frac?)? ('e' | 'E') sign? num
  | sign? "0x" hexnum '.' hexfrac?
  | sign? "0x" hexnum ('.' hexfrac?)? ('p' | 'P') sign? num
  | sign? "inf"
  | sign? "nan"
  | sign? "nan:" "0x" hexnum
```

> Is is correct to infer that a tokenizer should distinguish three kinds of token for number literals: 𝚞𝑁 and 𝚜𝑁 for unsigned and signed integers and 𝚏𝑁 for floats (whether signed or not)?

Yes, but there is some overlap here. `0` is a valid as any of `f32`, `f64`, `u32`, `u64`, `s32`, `s64`. Similarly, `+0` is valid for `f32`, `f64`, `s32` and `s64`.

The reference interpreter chooses to say that a `float` literal token only includes the literals that are not `nat` or `int`, even though those are also valid `f32`/`f64` values. Then when parsing, [the reference interpreter allows any of these](https://github.com/WebAssembly/spec/blob/7526564b56c30250b66504fe795e9c1e88a938af/interpreter/text/parser.mly#L267-L270):

```ocaml
literal :
  | NAT { $1 @@ at () }
  | INT { $1 @@ at () }
  | FLOAT { $1 @@ at () }
```

But [validates them](https://github.com/WebAssembly/spec/blob/7526564b56c30250b66504fe795e9c1e88a938af/interpreter/text/parser.mly#L39), [based on the constant instruction used](https://github.com/WebAssembly/spec/blob/7526564b56c30250b66504fe795e9c1e88a938af/interpreter/text/lexer.mll#L166-L174), (e.g. `i32.const`, etc.)

```ocaml
let literal f s =
  try f s with Failure _ -> error s.at "constant out of range"
  ...
```

```ocaml
      CONST (numop t
        (fun s -> let n = I32.of_string s.it in
          i32_const (n @@ s.at), Values.I32 n)
        (fun s -> let n = I64.of_string s.it in
          i64_const (n @@ s.at), Values.I64 n)
        (fun s -> let n = F32.of_string s.it in
          f32_const (n @@ s.at), Values.F32 n)
        (fun s -> let n = F64.of_string s.it in
          f64_const (n @@ s.at), Values.F64 n))
```

**Comment by carlsmith** [comment]
I see. Thank you for explaining things so clearly.

> The reference interpreter chooses to say that a float literal token only includes the literals that are not nat or int, even though those are also valid f32/f64 values. Then when parsing, the reference interpreter allows any of these...

OK, but then the reference interpreter cannot tokenize the source properly, and is forced to guess, and requires the parser to allow for float literals that are misclassified as signed and unsigned integer tokens.

May I ask why? It complicates everything and there doesn't seem to be any practical advantage at all. Being able to write `0.0`, `.0`, `0.` and just `0` isn't very useful. It complicates tokenization in a multiple ways, and makes fully correct tokenization impossible.

**Comment by binji** [comment]
> OK, but then the reference interpreter cannot tokenize the source properly, and is forced to guess, and requires the parser to allow for float literals that are misclassified as signed and unsigned integer tokens.

That's not true, you can classify the tokens like the reference interpreter does, then have the parser accept one or more of those tokens depending on the construct. See [my implementation in wasp](https://github.com/binji/wasp/blob/master/src/text/read.cc#L79), for example. I imagine the reference interpreter does it this way for convenience more than anything.

> May I ask why? It complicates everything and there doesn't seem to be any practical advantage at all. Being able to write 0.0, .0, 0. and just 0 isn't very useful.

I think it's useful to be able to write both `i32.const 0` and `f32.const 0`, as an example.

> It complicates tokenization in a multiple ways, and makes fully correct tokenization impossible.

What do you mean by "fully correct" tokenization?

**Comment by carlsmith** [comment]
> That's not true, you can classify the tokens like the reference interpreter does, then have the parser accept one or more of those tokens depending on the construct. 

OK, but what if there is no parser? If I have a string of arbitrary tokens (as an annotation allows), then, according to the WAT spec, a token like `123` could be a float or an int. The token's class is ambiguous.

> I think it's useful to be able to write both `i32.const 0` and `f32.const 0`, as an example.

It's a very small convenience though, when writing `i32.const 0` and f32.const `0.0` is all that's required to have unambiguous number literals.

> What do you mean by "fully correct" tokenization?

I mean that every token in a valid WAT source string can be correctly classified without parsing the entire token stream to establish the context of the individual tokens, especially when the Annotations proposal will effectively remove the context.

**Comment by taralx** [comment]
I suppose it depends on what you think the WAT format is for. If it's for humans, either for writing or debugging, then conveniences like polymorphic numeric literals are absolutely worthwhile.

What is the Annotations proposal, and why does it not have the context?

**Comment by carlsmith** [comment]
Annotations basically allow you to create a parenthesized (properly nested) array of arbitrary tokens (even including Reserved tokens), in any order. They begin with `(@<identifier><space> ` and end with a simple closing paren:

    (@id foo bar)

The [proposal][1] is mature, and almostly certainly will be standardized now.

[1]: https://github.com/WebAssembly/annotations/blob/master/proposals/annotations/Overview.md

**Comment by carlsmith** [comment]
To be clear, this is not a problem I'm predicting. I'm currently working on Wasm tooling, and ambiguous literals are a problem now. It's only a hobby project for my own education, but the problems I'm having will affect serious projects in much the same way.

Also, there's an improvement to WAT's exponentiation syntax that I'd like to put forward. If implemented, it would not break anything that works now, but having ambiguous floats would make any proposal along those lines more complex, by creating more edge cases that would not need addressing otherwise.

Explicitly documenting edge cases always complicates the documentation too, and just leaving them implicit is not always a good idea.

**Comment by taralx** [comment]
> ambiguous literals are a problem now

I don't understand this. In the current format, every time a literal appears, the type is known from context. You appear to believe that it should be possible to know the type of everything in a context-free manner, but as previously stated, there are important use cases of WAT that prevent it being context-free typeable. Not to mention that making "0" not a float would be a backwards-incompatible change.

I suggest Annotations change their format to make types explicit in the syntax, the same way they are in all existing cases.

**Comment by conrad-watt** [comment]
> I suggest Annotations change their format to make types explicit in the syntax, the same way they are in all existing cases.

That would be a slight shame, since annotations are just meant to be made up on arbitrary tokens. Maybe the formal grammar could be slightly refactored so that `uN | sN | fN` are all special cases (with overlaps) of an undistinguished `literal` token. Then it becomes the job of whatever is interpreting the custom section to decide on a convention for how any ambiguous `literal` tokens are disambiguated if necessary (an explicit annotation could be required at that level, or it could choose a default).

**Comment by taralx** [comment]
I don't see anything wrong with the formal grammar. uN and fN overlap, and that isn't a problem, since the tokens are resolved by the lexical syntax, and there are no cases where uN and fN are both acceptable at the same point in the language.

If you don't want to make the types explicit, then define the annotations as being token streams and let the reader of the annotations define what types they expect.

**Comment by conrad-watt** [comment]
> I don't see anything wrong with the formal grammar. uN and fN overlap, and that isn't a problem, since the tokens are resolved by the lexical syntax, and there are no cases where uN and fN are both acceptable at the same point in the language.

Looking at the proposed definition of annotations:
```
annot ::= "(@"idchar+  annotelem* ")"
annotelem ::= keyword | reserved | uN | sN | fN | string | id | "(" annotelem* ")" | "(@"idchar+ annotelem* ")"
```
It is technically true that both `uN` and `fN` can occur at the same point. To be clear, I think forbidding `f32.const 0` in response would be the tail wagging the dog. The ability to tokenise annotations down to the last detail of the spec's formal grammar isn't important, since their meaning is entirely defined by the conventions of the tool interpreting them.

> If you don't want to make the types explicit, then define the annotations as being token streams and let the reader of the annotations specify what types they expect.

This is what I was meaning to advocate for. Sorry if that wasn't clear.

**Comment by taralx** [comment]
I'm still not sure what problem you're trying to solve. `annotelem` is basically `token - ('(' | ')')`, but allowing negative assertions in grammars is complicated, so it's just spelled out. But the alternatives in a grammar rule, including `annotelem`, aren't discriminated -- that's the job of the semantic layer on top of the grammar. So changing the grammar to add a new `literal` terminal won't actually do anything.

**Comment by conrad-watt** [comment]
> But the alternatives in a grammar rule, including annotelem, aren't discriminated -- that's the job of the semantic layer on top of the grammar.

That's not necessarily true. Consider that one might try to build a lexer that tokenises a given WAT file in a way that 100% precisely corresponds to the definitions of the spec. I think this is why @carlsmith made this issue in the first place - because this lexing is no longer unambiguous given the grammar of annotations. To be clear, I don't think this is an important problem.

I think we agree that being unable to lex annotations this way is not a big deal at all. I'm mainly trying to articulate @carlsmith's point, and at the very most float a change (which I am not particularly attached to) so that `annotelem` is defined as
```
annotelem ::= keyword | reserved | literal | string | id | "(" annotelem* ")" | "(@"idchar+ annotelem* ")"
```

**Comment by taralx** [comment]
> lexing is no longer unambiguous given the grammar of annotations

But it *is* unambiguous. It is quite clear what is an `annotelem` and what isn't. The ambiguity only happens if _the thing you feed it to_ needs to discriminate uN from fN without being able to specify which one it wants. But that isn't defined by that spec or any other, so it's not (yet) a problem.

Consider that the output of the lexer is basically a sequence of strings (tokens). The ability to push down some of the semantic processing is convenient, but the inability to do so doesn't make the grammar ambiguous.

**Comment by conrad-watt** [comment]
> The ambiguity only happens if _the thing you feed it to_ needs to discriminate uN from fN without being able to specify which one it wants.

Some syntactic checks still have to be done at the pure Wasm level on an `annotelem` body, which can only be made up of a sequence of Wasm-allowed tokens. It's not unreasonable to think that this could be done with a regular Wasm lexer, and the lexed tokens then passed into the part of the tool that handles annotations.

For example, the following would each cause a parse/lex error just from the core Wasm definition (assuming they occur in an otherwise well-formed WAT file).
```
(@a xxx , yyy )
(@a xxx " yyy )
(@a xxx ; yyy )
```
Again, acknowledging the above does not mean we _have_ to change the spec's grammar.

**Comment by carlsmith** [comment]
Thanks for considering this.

I was thinking about going in the opposite direction, and generalizing things more, which would also avoid breaking anything.

Forgetting floats completely for a moment, is there a good reason to distinguish between `1` and `+1` at all? Wasm does not have signed and unsigned *values*, and the literals are not really *signed* and *unsigned*, so much as *explicitly*  and *implicitly* signed.

There are places that require unsigned number tokens for stuff like offsets, that can only be positive, but would having a parser that *tolerated* an index expressed like `+1` be so bad?

In a similar way, the only advantage of float literals, as a distinct token class, seems to be forbidding tolerable things. Basically, it allows `f32 1` to be idiomatic, while ensuring that `i32 1.0` will not parse.

Tolerating `i32 1.0` (while never expecting to see it in practice) would permit generalization of all WAT number literals to a generic `number` type that could be used to express any numeric value anywhere.

If every number literal was just classified as a `number`, there would be no problems with ambiguous token classes, and nothing else would really change. Stuff like `i32 1.5` would now be handled like `i32 1e10` (both are grammatically valid, but their values would not validate), and stuff that used to throw (like giving a memory `+1` page or expressing an int as a real integral) would now work, but nobody should need to know or care.

This approach also makes it clear that literals must be subclassed by the consumer if they want tokenization to anything more specific than numbers and strings.

**Comment by conrad-watt** [comment]
> If every number literal was just classified as a number, there would be no problem (however small) with ambiguous token classes, and nothing else would really change. Stuff like i32 1.5 would now be handled like i32 1e10 (both are grammatically valid, but their values would not validate), and stuff that used to throw (like giving a memory +1 page or expressing an int as a real integral) would now work, but nobody should need to know or care.
>
> This approach also makes it clear that literals must be subclassed by the consumer if they want tokenization to anything more specific than numbers and strings.

Currently, the Wasm text format spec doesn't make a strong distinction between lexing and parsing, leaving things open for interpretation. For example, the definition of `i32.const` in [numeric instructions](https://webassembly.github.io/spec/core/text/instructions.html#numeric-instructions) requires that the associated literal is clamped to an `i32` size. There's no specification about whether this has to be enforced at a lexing or parsing stage.

This issue doesn't seem to be about whether it's possible to sensibly lex a Wasm program in abstract, but whether its possible to lex a Wasm program into tokens which have the precise grammatical types defined in the spec. I think it's reasonable to say that this is a non-goal of the spec (given the `i32` example above). It's already possible to build a lexer which lexes all literals as generic `numbers`, then discards invalid ones in a separate parse stage.

**Comment by carlsmith** [comment]
> It's already possible to build a lexer which lexes all literals as generic numbers, then discards invalid ones in a separate parse stage.

I agree. I'm suggesting that the spec be explicitly defined that way?

**Comment by carlsmith** [comment]
Making it *possible to lex a Wasm program into tokens which have the precise grammatical types defined in the spec*  is not such a bad thing, and simplifies the Annotations proposal and tools that work with token streams.

**Comment by conrad-watt** [comment]
In the end, given the ambiguities I mentioned above, any change to the grammar will be more like a "helpful nudge" than a cast-iron guarantee that tools could depend on.

For example, we could change the top-level definition of [tokens](https://webassembly.github.io/spec/core/text/lexical.html#tokens) (likewise `annotelem`) to
```
token ::= keyword | number | string | id | "(" | ")" | reserved
...
annotelem ::= keyword | reserved | number | string | id | "(" annotelem* ")" | "(@"idchar+ annotelem* ")"
...
number ::= uN | sN | fN
```

without changing any other definitions. Is this the kind of thing you're advocating for? Note that this still wouldn't represent a specification of whether things like `i32.const 1e10` must be successfully lexed (which is beyond our current scope).

**Comment by carlsmith** [comment]
@conrad-watt Yep. That's exactly what I'm (now) advocating for.

Generic token classes are fine, so long as every token is unambiguously *classifiable*.

**Comment by carlsmith** [comment]
> without changing any other definitions.

Sorry, no. Some other definitions would need to change, as they currently require something specific, like an unsigned number, but would now only ever require `number` (grammatically). The `uN`, `sN` and `fN` definitions would no longer exist at all.

What I'm suggesting basically involves combining the integer and float lexical grammars into a single definition for `number`, then doing a find-and-replace that swaps every `uN`, `sN` and `fN` for `number`.

This would have implications beyond the spec, as implementations would need to accept a generic `number` in places that currently expect `uN` or  `uN|sN` - that kind of thing.

This doesn't break anything, but it does legalize things that were illegal before, mainly explicitly signed offsets and integers defined with literals like `1.0`. It can therefore be implemented exactly like a new feature, except that it's a feature no one will use. It only exists to allow other interrealted things to be simplified.

**Comment by conrad-watt** [comment]
That seems like kind of a headache, since various tools and implementations would need to change to ensure they stayed conformant. Given that we've established that it's acceptable to lex undifferentiated `number` tokens and apply any restrictions afterwards, what additional benefits would this change accomplish that would outweigh the disruption caused?

**Comment by carlsmith** [comment]
It would basically allow annotations to unambiguously classify tokens, without needing a slightly different grammar. It also allows tools that consume WAT token streams to do the same. It also just simplifies everything. Numbers are just numbers, and the value they express is only become valid or invalid when it is validated.

**Comment by carlsmith** [comment]
This would simplify the lexer they have already, and the parser as well. It should just make things a bit lighter in places. If it was implemented as part of the Annotations proposal, I can't see why it'd be a problem. The affected tools are generally very actively developed, and ecosystem stuff (docs, syntax highlighters etc) doesn't need to change.

**Comment by conrad-watt** [comment]
You're always able bring a proposal to a future community group meeting, where it might be more widely discussed, and tool developers can give feedback on how much appetite there is to make this change.

As I said before, it's possible to unambiguously lex numbers as `number`. Just by changing the definition of `token` and nothing else, it can even be argued that this is 100% conformant to the spec's grammatical types. The parse-time restrictions on number formats could be viewed as somewhat separate - so it doesn't necessarily follow that relaxing such parse-time restrictions would make the lexer more "spec-faithful".

**Comment by carlsmith** [comment]
> As I said before, it's possible to unambiguously lex numbers as number. Just by changing the definition of token and nothing else.

How? The rest of the grammar has many places where (for example) a `uN` is required, and it will choke on an `fN` token. Even if `number` includes `fN`, the required `uN` does not include `fN`, despite now both being types of `number`.

**Comment by carlsmith** [comment]
> You're always able to bring a proposal to a future community group meeting, where it might be more widely discussed, and tool developers can give feedback on how much appetite there is to make this change.

To be honest, that's pretty unlikely to happen. I'm happy to discuss things on GitHub, but I'm not up for community group meetings. Thank you for taking the time to consider it though. I'll find a work around for my own project. All the best.

**Comment by conrad-watt** [comment]
> How? The rest of the grammar has many places where (for example) a `uN` is required, and it will choke on an `fN` (or `sN`) token. Even if `number` includes `fN`, the required `uN` does not include `fN`, despite now both being types of `number`.

As I mentioned earlier, the grammar of modules not only requires `uN` in some places, but specifically (e.g.) `u32` - so it's already the case that the parse tree for modules enforces more restrictions than are captured by having the lexer type certain numbers with `uN`. In an implementation with a separate lexer and parser, checking that such lexed numbers are actually (e.g.) `u32` would already be part of the parsing process - so there is a precedent for these kind of checks.

**Comment by carlsmith** [comment]
@conrad-watt - Ah, I see. Thank you for your patience with that. I wasn't getting it, but you are correct.

The people working on the Annotations proposal have yet to respond, and may have something interesting to say still, but there's [an issue on their tracker][1] already, so it may make sense to close this one.

I've raised the issue, and you obviously understand it (better than me) now, and you don't think there's a problem (that's more than conceptual), so I'm personally happy to see this closed.

[1]: https://github.com/WebAssembly/annotations/issues/12

**Comment by conrad-watt** [comment]
I'm glad you found my comments helpful :)

I wouldn't be against making the small change I floated in https://github.com/WebAssembly/design/issues/1376#issuecomment-691675967, since that would at least make the shallow definition of `token` correspond to unambiguous lex-time types - but let's see how people more connected to the annotations proposal respond in the proposal repository.
