### ISSUE TITLE
Proposal: Extended Constant Expressions

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/design#1392]
IIRC the set of valid instructions in constant expressions was designed to be extended over time.  Currently we only allow `global.get` and `t.const` (e.g. `i32.const`).  

For llvm's dynamic linking (and PIC in general) ABI it would be very useful to at least be able to do `i32.add` and `i64.add`.   In the (currently experimental) PIC ABI we model function and data addresses as wasm globals storing absolute table and memory offsets.    Because we can't to addition in the constant expressions we are forced to mark these globals as mutable (even though logically they are immutable after initialization) and generate startup/relocation code to set them to their correct values.  This is done by adding offsets to `__memory_base` and `__table_base` which are imported globals.  

For this use case we only need integer addition but I would probably make sense to consider wider set of instructions. e.g. all arithmetic operations. 

(sorry if this is a duplicate issue, I tried searching for constant expressions but couldn't find anything).

**Comment by RossTate** [comment]
Coincidentally, I've been running into a closely related problem in working through some use cases for garbage collection and/or for dynamic linking. In general, there is a very common pattern of having an initialization phase after which things become immutable. Often the code in the initialization phase isn't translated from user-defined code but rather is the infrastructure-setup that the language runtime takes care of. So it might be more generally useful to incorporate this notion of initialization phase into WebAssembly's design.

**Comment by sbc100** [comment]
I agree this would be a useful concept and certainly something llvm could take advantage of.     I think there has been some discussion of being able to mark globals as "immutable after instantiation", which would allow the global to be exported as immutable.   I imagine that optimizing the module code itself might be hard though since we don't know what code might be run from the start function.

Other concepts such as immutable data, bss data , and immutable tables (most C/C++ programs define the table statically and don't need to mutate it at runtime) could also be useful.   In ELF we have a special section called `.data.rel.ro` for data that is logically immutable but contains relocations so needs to be writable during startup but is marked as read-only before any user code runs.

Having said all that and I don't think that any of this should stop us from also extended constant expressions.  Is that what you are suggesting?

**Comment by RossTate** [comment]
Ah, sorry, didn't mean to suggest extending constant expressions would be problematic. That seems like the appropriate short-term solution. Just wanted to raise the need for a better long-term solution. Thanks for the interesting examples along that line!

**Comment by rossberg** [comment]
Strongly in favour of extending constant expressions -- we have run into the same limitation, and working around it by introducing artificial extra imports is both cumbersome and sometimes an abstraction leak.

Based on my experience, I would like to see at least linear operators (`iNN.add`, `iNN.sub`, `iNN.mul`). But I could also imagine use cases for bit operators, comparisons, and `select` as a simple conditional, all of which would be very easy to support.

In addition, I think I'd want the ability for `global.get` to refer to previous globals, not just imported ones.

**Comment by sbc100** [comment]
Would somebody with the powers (@dtig @dschuff @rossberg ?) mind creating an `extended-constant-expressions` fork for me?  I have https://github.com/WebAssembly/proposals/pull/95 ready to go.

**Comment by rossberg** [comment]
I created https://github.com/WebAssembly/extended-const

**Comment by sbc100** [comment]
Closing now that ttps://github.com/WebAssembly/extended-const is up and running (I guess continued discussions should happen in issues there?).
