### ISSUE TITLE
How long does it take for JavaScript to communicate with webassembly???

### ISSUE THREAD

**Issue by a6965921** [WebAssembly/design#1404]
How long does it take for JavaScript to communicate with webassembly??? How to improve communication time

**Comment by ExE-Boss** [comment]
This is something where you should ideally run your own benchmarks on your own code in whatever engine you’re using.

---

Some information about how **SpiderMonkey** optimises this can be found in this **Mozilla Hacks** blog post: [Calls between JavaScript and WebAssembly are finally fast 🎉](https://hacks.mozilla.org/2018/10/calls-between-javascript-and-webassembly-are-finally-fast-%F0%9F%8E%89/).

**Comment by sunfishcode** [comment]
The question here seems to be answered; please file a new issue if there are any further questions!
