### ISSUE TITLE
True meaning of 0xFC opcode

### ISSUE THREAD

**Issue by helins** [WebAssembly/design#1405]
What is the true meaning of the 0xFC opcode? At first it was about saturated truncation but newer specs add memory and table instructions there so it fills like an "post hoc junk opcode". I was wondering if there was a justification somewhere regarding this weird-looking gathering.

**Comment by dcodeIO** [comment]
[This one?](https://github.com/WebAssembly/nontrapping-float-to-int-conversions/blob/master/proposals/nontrapping-float-to-int-conversion/Overview.md#encoding)

**Comment by helins** [comment]
Yes it is indeed "miscellaneous" but I was wondering why. For instance, why is the new "memory.fill" op considered "miscellaneous"  (0xFC  11) while another mem operation such as "memory.grow" has its own "non-miscellaneous" opcode (0x40)?

**Comment by dtig** [comment]
The memory.grow operation was included as one of the default operations in the original WebAssembly spec as a part of the MVP, the memory.fill operation on the other hand was introduced in the [bulk memory operations proposal](https://github.com/WebAssembly/bulk-memory-operations/blob/master/proposals/bulk-memory-operations/Overview.md), and all the operations included in this proposal use the 0xfc prefix. In general, most operations included as a part of post-MVP proposals are encoded with a prefix byte.
