### ISSUE TITLE
Constant expressions for settings memory/table limits?

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/design#1410]
Perhaps I'm missing something but it seems like maybe an oversight that one can set segment locations based on (for example) an imported global but one can't set memory or table limits this way.

**Comment by rossberg** [comment]
Wasn't this because compile time memory limits potentially enable more efficient bounds checking under certain implementation strategies?

**Comment by sbc100** [comment]
I had though that might be possibility yes.   However, in practice did any engine ever come up with a bounds check scheme that could take advantage of specific bounds information at compile time?  (also allowing const expressions here doesn't preclude modules from statically specifying their limits, just adds more flexibility).

When I noticed this issue, I was looking at trying to transition a use case in emscripten/llvm from a fully imported memory, to an internal memory whose initial size is set by a global import, so in this case it could be giving the engine more compile-time knowledge of the memory rather than less.

Details: Specifically I was looking at the `-pie` executable case where the static memory and table segment locations are not known until runtime.  This is the only remaining case in emscripten where the application imports its memory from JS.   We already pass `__memory_base` and `__table_base` as imports, it would be nice to be have to module calculate its own initial  memory size based on `__memory_base + __memory_size` (It already dynamically places its data segment based on the `__memory_base` import).

**Comment by eqrion** [comment]
> I had though that might be possibility yes. However, in practice did any engine ever come up with a bounds check scheme that could take advantage of specific bounds information at compile time? (also allowing const expressions here doesn't preclude modules from statically specifying their limits, just adds more flexibility).
> 

SpiderMonkey uses the minimum memory limit to omit bounds checks when the address is a known constant [1]. We also use the maximum memory field to decide whether a memory's byte length might not fit in a 32-bit field, on wasm32 on 64-bit systems.

I don't have an opinion on whether to generalize or not, both of these cases might not be significant. And as long as we can usually determine the static value of these fields, then we can still do these optimizations for some content.

[1] https://searchfox.org/mozilla-central/rev/a8b75e4ba3f8ddf0e76b42681d0a7b7e78e67730/js/src/wasm/WasmBaselineCompile.cpp#12232
[2] https://searchfox.org/mozilla-central/rev/a8b75e4ba3f8ddf0e76b42681d0a7b7e78e67730/js/src/wasm/WasmIonCompile.cpp#1060

**Comment by sbc100** [comment]
Interesting,  thanks for the info!

**Comment by aardappel** [comment]
Related: https://github.com/WebAssembly/extended-const/issues/4

**Comment by sbc100** [comment]
> Wasn't this because compile time memory limits potentially enable more efficient bounds checking under certain implementation strategies?

Doesn't this argument only apply to the `max` in the case that we specify a `max`.   i.e. in the case were we specify a fixed `max`, could we specify the `initial` via a const expressions without loosing any possible optimizations?

Today we have an optional `max`, could we ad an optional const expr for `initial` (only allowed i `max` is also specified)?

**Comment by sbc100** [comment]
@eqrion, just to confirm, your optimizations are all based on the max rather than the initial part of the limits?

**Comment by lars-t-hansen** [comment]
As Ryan said, we elide explicit bounds checks for constant-address offsets that are below the min (initial) value.

**Comment by sbc100** [comment]
ah yes that makes sense, sorry I misunderstood there.  

Rethinking, perhaps what I'm really asking for is that ability to set the *initial* memory size that is separate from *min* or *max* (and potentially based on global import).    We set the min and max memory size at build time, and those limits are static so we can do optimization like your.   But the initial memory could be more dynamic and based on import for example (i.e. it could be const expression).  Obviously it would need to be checked at instantiation time that is lies within the statically declared limits, but that already happens for imported memories.

**Comment by lars-t-hansen** [comment]
What would the rules be?

- if the module's `initial` is greater than the current size of the memory, then grow the memory to `initial` (what happens on oom?)
- do this before the processing of `data` sections

Since the `initial` value is presumed to be imported (otherwise it's not very interesting) then somebody outside the module could also read that value and grow the memory to the appropriate size before instantiation.  Is this something eg current emscripten-generated JS code does?

**Comment by sbc100** [comment]
There would be no growing...  This would be for declaring your own memory within the module, a memory which would then need to be exported before anyone else would have access to it

My use case is that I want the external dynamic linker to decide the actual initial size of the memory the module creates and exports.   Right now I can achieve this only by have the dynamic loader create the memory itself and wasm module import it.     But for consistency (with the static linking case) and codesize it would be nice if I could completely remove the JS code for wasm memory creation and just pass in an i32.   

We already pass in `__memory_base` which is the dynamic location at which the module is to place its own memory.  This is used in the segment initializer, so there is no time for the module to grow the memory prior to segment loading (since the segments are active).   As an alternative, I could do make the segment(s) passive and have the linker generate a few instruction to do `memory.grow` and `memory.init(s)` in the start section function? 

Having explained all this,  I see that perhaps its not worth it.  We can probably just stick to creating the memory outside the module (in JS) when we need to.

**Comment by sbc100** [comment]
Closing since I can see now its probably not worth the effort.

**Comment by 7ombie** [comment]
Is this something that will (more or less) definitely not happen now?

I don't personally have any preference, but would be grateful of anyone could express the likelihood of it happening at some point.
