### ISSUE TITLE
The spec for `br_table` seems to contain a minor error.

### ISSUE THREAD

**Issue by 7ombie** [WebAssembly/design#1416]
The grammar for the `br_table` instruction is expressed in the spec like this: **𝖻𝗋_𝗍𝖺𝖻𝗅𝖾 𝑙∗ 𝑙**
IIUC, it should just be this: **𝖻𝗋_𝗍𝖺𝖻𝗅𝖾 𝑙+**

**Comment by rossberg** [comment]
Well, `l+` would be equivalent, but the current formulation is meant to indicate the distinction between the jump vector and the out-of-range fallback.

**Comment by 7ombie** [comment]
@rossberg - Ahh, I see. That makes sense. I was unsure I was reading it correctly, but the abstract grammar (here) is pretty hard to misinterpret, so wanted to ask about it. Thank you for taking the time to explain.
