### ISSUE TITLE
Switch from 'master' to 'main' branch

### ISSUE THREAD

**Issue by kripken** [WebAssembly/design#1417]
Most of the other `WebAssembly/` repos have done this already.

Any concerns? I can't think of any CI or other factors that could be broken by this, but maybe I'm missing something.

**Comment by dtig** [comment]
No concerns,  though taking a quick look through the repositories there are quite a few repositories that still use `master` as the default branch. Perhaps we can use this issue for tracking?  

All the new repositories use `main` as the default branch, but the older repositories will need to be renamed. The only thing that would be affected is folks may run into local repos being out of date after the rename, but that should be fairly straightforward to fix.

**Comment by rossberg** [comment]
I see, thanks!

**Comment by kripken** [comment]
Ok, sounds like there are no objections. Making this change requires one of the repo owners to go to Settings->Branches->Default Branch and click the "Switch to another branch" icon (two arrows in different directions).

I'm not sure who is a repo owner here, but perhaps @dschuff or @dtig ?

**Comment by dtig** [comment]
The design repository has now been renamed, this re-targets any open PRs, but does not update local environments. Any local branches will have to be updated to pull from the `main` branch.

To switch to using main in an existing local checkout - 
- `git branch -m master main`
- `git fetch origin`
- `git branch -u origin/main main`

Update existing branches to use main as the parent branch - 
- `git branch -u origin/main <branch`

I'm keeping this issue open for tracking as we rename other repositories.

**Comment by kripken** [comment]
Thanks @dtig !

**Comment by dtig** [comment]
The default branch for several proposal repositories has been changed to main. There are some proposals that haven't been renamed yet as they are under active development, cc'ing the champions of the proposals to rename the branches in the way they find least disruptive. Happy to help too, so feel free to reach out if there are any questions or concerns. 

cc: @rossberg, @aardappel, @aheejin, @conrad-watt, @yuri91, @lukewagner, @penzn, @fgmccabe

**Comment by yuri91** [comment]
I just switched [branch hinting](https://github.com/WebAssembly/branch-hinting) from master to main.
Hopefully I didn't mess anything up.

**Comment by aheejin** [comment]
[exception handling](https://github.com/WebAssembly/exception-handling) repo's default branch has been switched to main too.

**Comment by conrad-watt** [comment]
I don't appear to have permission to do this in the [threads](https://github.com/WebAssembly/threads) repo, possibly because I took over championship after the repo was created.

**Comment by dtig** [comment]
Thanks @aheejin and @yuri91. @conrad-watt Sorry about the permissions issue, should be fixed now.

**Comment by conrad-watt** [comment]
done!

**Comment by aardappel** [comment]
Created a new `main` branch for Memory64, but I too don't have the privileges to change the default branch in the GitHub settings.

Following instructions from https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/

**Comment by penzn** [comment]
I've changed the default in flexible-vectors, but not deleting `master` yet, since there are important pull requests still open against it.

**Comment by dtig** [comment]
@aardappel Permissions should be fixed now. The official instructions on how to rename are [here](https://github.com/github/renaming). @penzn This also automatically updates open PRs, the only thing this would not update are local environments, so if you have existing branches with state in them, but there's probably local state associated with the PRs, so it makes sense to keep the `master` branch around as needed.

**Comment by aardappel** [comment]
@dtig thanks, all done. `master` deleted.

**Comment by penzn** [comment]
> there's probably local state associated with the PRs, so it makes sense to keep the `master` branch around as needed.

Looks like the diff is still tied to the branch it was made against originally: https://github.com/WebAssembly/flexible-vectors/pull/27. Maybe Github would clean this up eventually, but a any rate we will repoint the change before merging.

**Comment by lukewagner** [comment]
done!

**Comment by fidanticaret** [comment]
> Most of the other `WebAssembly/` repos have done this already.
> 
> Any concerns? I can't think of any CI or other factors that could be broken by this, but maybe I'm missing something.

**Comment by sunfishcode** [comment]
Most of the repos have migrated. Here is the list of repositories still using `master`:
 - [benchmarks](https://github.com/WebAssembly/benchmarks)
 - [bulk-memory-operations](https://github.com/WebAssembly/bulk-memory-operations)
 - [conditional-sections](https://github.com/WebAssembly/conditional-sections)
 - [conditional-segment-initialization](https://github.com/WebAssembly/conditional-segment-initialization)
 - [debugging](https://github.com/WebAssembly/debugging)
 - [decompressor-prototype](https://github.com/WebAssembly/decompressor-prototype)
 - [JS-BigInt-integration](https://github.com/WebAssembly/JS-BigInt-integration)
 - [lld](https://github.com/WebAssembly/lld)
 - [memory-control](https://github.com/WebAssembly/memory-control)
 - [multi-value](https://github.com/WebAssembly/multi-value)
 - [mutable-global](https://github.com/WebAssembly/mutable-global)
 - [proposal-type-imports](https://github.com/WebAssembly/proposal-type-imports)
 - [reference-types](https://github.com/WebAssembly/reference-types)
 - [sign-extension-ops](https://github.com/WebAssembly/sign-extension-ops)
 - [testsuite-js](https://github.com/WebAssembly/testsuite-js)
 - [wasm-c-api](https://github.com/WebAssembly/wasm-c-api)
 - [wasmint](https://github.com/WebAssembly/wasmint)
 - [wasm-jit-prototype](https://github.com/WebAssembly/wasm-jit-prototype)
 - [webassembly.github.io](https://github.com/WebAssembly/webassembly.github.io)
 - [website](https://github.com/WebAssembly/website)
 - [workloads](https://github.com/WebAssembly/workloads)

**Comment by penzn** [comment]
Are we going to switch branches in archived repositories? 😉 A good portion of those are, for exmple `bulk-memory-operations`, `lld`, and `multi-value`.

**Comment by sunfishcode** [comment]
I've now separated the list into Not Archived and Archived.

**Comment by dtig** [comment]
Repositories are merged and archived, so those weren't updated: 
 - [bulk-memory-operations](https://github.com/WebAssembly/bulk-memory-operations)
 - [conditional-sections](https://github.com/WebAssembly/conditional-sections)
 - [multi-value](https://github.com/WebAssembly/multi-value)
 - [JS-BigInt-integration](https://github.com/WebAssembly/JS-BigInt-integration)
 - [mutable-global](https://github.com/WebAssembly/mutable-global)
 - [reference-types](https://github.com/WebAssembly/reference-types)
 - [sign-extension-ops](https://github.com/WebAssembly/sign-extension-ops)
 - [lld](https://github.com/WebAssembly/lld)
 - [wasm-jit-prototype](https://github.com/WebAssembly/wasm-jit-prototype)
 - [workloads](https://github.com/WebAssembly/workloads)

Repositories that are for inactive proposals, or parts of proposals that are merged are now archived:
 - [conditional-sections](https://github.com/WebAssembly/conditional-sections)

Recent repositories that defaulted to Organization defaults (which are now updated to use main as well):
 -  [memory-control](https://github.com/WebAssembly/memory-control)

For repositories that have been inactive for the past year, I've updated them to default to main: 
 -  [benchmarks](https://github.com/WebAssembly/benchmarks)
  - [debugging](https://github.com/WebAssembly/debugging)
  - [proposal-type-imports](https://github.com/WebAssembly/proposal-type-imports)
  - [testsuite-js](https://github.com/WebAssembly/testsuite-js)
  - [wasmint](https://github.com/WebAssembly/wasmint)
  
Repositories that have seen activity recently and were not updated:
 - [wasm-c-api](https://github.com/WebAssembly/wasm-c-api)
 - [website](https://github.com/WebAssembly/website)

For the repositories in the last section, please reach out if there are any concerns with updating them, if not I'll update the repos end of this week.

**Comment by dtig** [comment]
Thanks for the ping, renamed the last two repositories. I'm closing this issue for now, please reopen if I've missed something!
