### ISSUE TITLE
Question about hardware limitations

### ISSUE THREAD

**Issue by Arcalise08** [WebAssembly/design#1423]
So just gonna start off saying I haven't used much web assembly.I heard about it several months back when blazor went production ready. 

So my current use case is I'm needing to access some native drivers for a label printer & nfc reader. We are attempting to retarget a corporate desktop project written in VB to a react or blazor webapp. The issue is, the label printer interface is written in .net 4.7. Our current fix for this is a desktop webserver that listens to signalr and relays native commands however that isn't the best experience

It's unclear to me if this is something webassembly can solve.  As a web developer it seems unlikely as I can see the security risks in allowing such things. However I am seeing people say it can reference some native dlls so I'm not sure.

**Comment by fgmccabe** [comment]
The only resources a WebAssembly module can access are those provided to it explicitly via imports. So, Wasm modules cannot reference 'native dlls' unless they are also accessible to JavaScript (in the browser that is).
If your webapp can access the label printer, then your Blazor webapp will also be able to.
Hope that this helps to clarify your questions.

**Comment by Arcalise08** [comment]
Yes, That is exactly what I thought. 

I did wonder if native devices could be granted access to by the sandboxed browser. It looks like webHID does allow for this.

**Comment by sunfishcode** [comment]
It appears the question here is answered; if there are any future questions, please file new issues!
