### ISSUE TITLE
Block comment matching '(;' and ';)' in strings and line comments

### ISSUE THREAD

**Issue by CraigWesbrook** [WebAssembly/design#1430]
The following examples don't parse according to the spec, which could be surprising or inconvenient. The issue is that the parser will try to match '(;' and ';)' in strings and line comments if it is in the process of matching a block comment.

```
(module $bad-string
  (import "imports" "printStr" (func $print-str (param i32)))
  (; memory (export "mem") (data "*Winks* ;) \00") ;)
  (memory (export "mem") (data "Wanted to say hello instead!\00"))
  (func $wink-at-the-world (export "wink")
    (call $print-str (i32.const 0))))

(module $bad-line-comment
  (; func (export "addTwo") (param i32 i32) (result i32) ;;not a great way to perform addition ;)
    local.get 0
    local.get 1
    i32.sub ;)
  (func (export "addTwo") (param i32 i32) (result i32) ;;a better way to add
    local.get 0
    local.get 1
    i32.add))
```

Is it possible/desirable to discount the contents of strings and line comments when matching block comments? Assuming the parser takes the first match, something like this?

```
comment       ::= linecomment | blockcomment
linecomment   ::= ‘;;’  linechar∗  (U+0A | eof)
linechar      ::= c:char (if c ≠ U+0A)
blockcomment  ::= ‘(;’  blockchar∗  ‘;)’
blockchar     ::= string
                | linecomment
                | c:char  (if c ≠ ‘;’ ∧ c ≠ ‘(’)
                | ‘;’     (if the next character is not ‘)’)
                | ‘(’     (if the next character is not ‘;’)
                | blockcomment
```

**Comment by rossberg** [comment]
This is standard behaviour for block comments, cf. C++, Pascal, Java, JavaScript, Haskell, Scheme, ...

If you were to change it, you'd get the dual problem: using a quote character in a comment would create parse errors. You'd actually have to require all quote chars in comments to form well-formed string literals -- that is even more annoying in practice. The only language I'm aware of that chose that path is OCaml.

**Comment by CraigWesbrook** [comment]
Ty, I agree. I hadn't considered single quotes in comments.
