### ISSUE TITLE
every feature not "MVP" should be through an API

### ISSUE THREAD

**Issue by PaperPrototype** [WebAssembly/design#1432]
Think about it. We need a way to define API's within WASM without having to add them directly to the base interpreter. If we want Threads or access to the DOM we should do it through an external independent API.

Say we decide to implement WebGPU (a graphics API from apple), but then 5 years later WebGPU becomes obsolete (much like WebGL did). To prevent the WASM interpreter from accumulating crud, and legacy features we should implement a "feature testing" system in the WASM interpreter for testing against external API's. It seems there is [already a plan to do something like this](https://github.com/WebAssembly/design/blob/main/FutureFeatures.md#feature-testing )

Another reason to "API testing" is that WASM is likely to become the universal runtime for well... everything from [OS's, to mobile/desktop apps](https://github.com/WebAssembly/design/blob/main/NonWeb.md). In the link provided there is even the following paragraph

> Non-Web environments may provide different APIs than Web environments, which feature testing and dynamic linking will make discoverable and usable.

So let's not get carried away and mess this up. I think it would make sense to implement everything that5 is not currently part of the MVP as a "API", because you never know ["Threads" may not exist in the future.](https://github.com/WebAssembly/proposals#phase-2---proposed-spec-text-available-cg--wg)

Also there is already a [proposal for "Feature Testing"](https://github.com/WebAssembly/feature-detection/blob/main/proposals/feature-detection/Overview.md) but I think the mindset behind it will not prevent from building up crud in the WASM interpreter, and "API querying/testing" would benefit (and ensure) a long lasting future to WASM.

EDIT: I probably came on pretty strong :), I just read [this](https://github.com/WebAssembly/design/blob/main/NonWeb.md) and it seems the WASM community has already gotten a good idea of how to deal with external library's (make sure to check that link out)

**Comment by tlively** [comment]
I think this pretty much agrees with how we have developed Wasm so far. Everything added to the core spec is purely computational, and any access to APIs of any sort always goes through imports. Even the threads proposal just adds concepts of shared memory and atomic operations, but doesn't actually define any way to create a new thread without calling some external API.

**Comment by PaperPrototype** [comment]
@tlively  Ah thanks! Thats reassuring! I'm so excited by the future of WASM
