### ISSUE TITLE
Threads are old + have huge overhead, we should use goroutines!

### ISSUE THREAD

**Issue by PaperPrototype** [WebAssembly/design#1435]
I've been perpetually somewhat disturbed by the idea of threads... they are a software/OS primitive, and they have a large overhead! Goroutines are a huge step in the righthdirection, and I think we shouldn't ignore this, and end up implementing "threads", in what is going to probably be the biggest movement in software (aka WASM, and its endless possibilities + its immediate widespread adoption).

What I am saying is we should remove threads from the accepted/to be implemented features of WASM, and instead look at the future and go with goroutines as the alternative (pun not intended).

I don't profess to be an expert in this area, but I think this makes sense (to me), and seems like an obvious direction to be going + in the future OS's could provide goroutines as primitives (thus giving us lighter and faster parrallelism capabilities)!

Or... maybe just have the "threads" api use goroutines (rathaer than actual threads?), is this possible?

**Comment by PaperPrototype** [comment]
EDIT: looking/thinkig back on what I said, I am realizing that threads are already a common primitive, thus foring evertying to not be able to use them woudln;t make sense.

**Comment by fgmccabe** [comment]
We we actively work on a stack switching feature. Stay tuned. Better yet; get involved

**Comment by PaperPrototype** [comment]
@fgmccabe I'd love to get involved, although I probably can't right now due to circumstances, but good luck!

**Comment by sunfishcode** [comment]
The stack switching proposal now has a repository: https://github.com/WebAssembly/stack-switching

Please follow up there with any questions!
