### ISSUE TITLE
Uncaught RuntimeError: Aborted(Assertion failed: exceptfds not supported)

### ISSUE THREAD

**Issue by sjjia** [WebAssembly/design#1453]
HELP ME!!

Is it a socket problem?

![image](https://user-images.githubusercontent.com/39543586/181728886-b14622cf-00ab-4a19-a9fb-cb0e71feb8c1.png)

    Uncaught RuntimeError: Aborted(Assertion failed: exceptfds not supported)
        at abort (api.js:1040:11)
        at assert (api.js:509:5)
        at ___syscall__newselect (api.js:5195:7)
        at _emscripten_receive_on_main_thread_js (api.js:15730:19)
        at api.wasm:0x2b197d
        at api.wasm:0x2b8e6a
        at api.js:1084:22
        at executeNotifiedProxyingQueue (api.js:7922:9)
        at worker.onmessage (api.js:3823:13)

I don't  know why, and how can I fix it.

**Comment by kripken** [comment]
This looks like an emscripten issue, so it should be transferred to there. I don't seem to be able to do that - maybe transferring only works inside a github org? Anyhow, I'll close this here, @sjjia you should open an issue or discussion here if you want emscripten support: https://github.com/emscripten-core/emscripten
