### ISSUE TITLE
Memory Safety for WebAssembly

### ISSUE THREAD

**Issue by huangh-git** [WebAssembly/design#1458]
WebAssebmly now losts source code information such like bounds. So how does WASM improve memory safety now? Garbage collection proposal may be able to improve memory safety,  but is there a more efficient way? I mean a more lightweight way, like just bounds checking every memory access.

**Comment by amin141972** [comment]
Confirm

**Comment by amin141972** [comment]
> WebAssebmly now losts source code information such like bounds. So how does WASM improve memory safety now? Garbage collection proposal may be able to improve memory safety, but is there a more efficient way? I mean a more lightweight way, like just bounds checking every memory access.

**Comment by sunfishcode** [comment]
[MSWasm](https://arxiv.org/abs/2208.13583) is a research paper about a memory-safety system for Wasm, which might be of interest.
