### ISSUE TITLE
Import indices go before indices in other index spaces in what sense?

### ISSUE THREAD

**Issue by hydroper** [WebAssembly/design#1481]
I'd like a clarification. Does this mean that if I've an `import` function, then...

- Its index is _0_?
- The index of the first function in the code section (of the binary format) is _1_?
- The first function type in the function type section, the index 0, belongs to that import function?
- The second function type in the function type section, the index 1, belongs to the first function (index 1 as I asked) in the code section?

**Comment by eqrion** [comment]
If you import `N` functions and have `M` functions defined in a module then the first `N` indices refer to those imported functions, and the following `M` refer to the ones defined in the modules. So to refer to the first defined function, you would index it at `M`. So your first two bullets are correct.

Every function specifies its type using an index into the type section. So there is no correlation between function indices and type indices.

**Comment by sunfishcode** [comment]
Closing, as the questions have been answered.
