### ISSUE TITLE
Dead PNaCl link in FAQ

### ISSUE THREAD

**Issue by Randomno** [WebAssembly/design#1487]
https://github.com/WebAssembly/design/blob/main/FAQ.md?plain=1#L121

**Comment by penzn** [comment]
I don't think GCC produces Wasm either (the line below), though unadulterated Clang does, but with some caveats.

**Comment by dschuff** [comment]
The point of the original text is not that those compilers produce wasm, it's that we hope that compilers such as GCC might eventually produce wasm, but we decided to work on LLVM ourselves because we were already familiar with it.
