### ISSUE TITLE
Is it possible to run tcptraceroute with wasm

### ISSUE THREAD

**Issue by SachiaLanlus** [WebAssembly/design#1491]
I know the ordinary traceroute use ICMP to do the route trace.
And the ICMP is not supported in wasm or say the web browser itself.
But when using tcptraceroute, it use TCP SYN to do the route trace.

Is it possible to do the tcptraceroute inside the webbrowser with wasm?
I think it would be very helpful for the people who need to do the route trace but not familiar with network related tools.

**Comment by sunfishcode** [comment]
No, this is not possible, because browsers do not have APIs that support emitting TCP SYN packets directly.
