### ISSUE TITLE
Link in "About" sidebar is broken.

### ISSUE THREAD

**Issue by fwip** [WebAssembly/design#1494]
The sidebar links to [https://webassembly.github.io/](https://webassembly.github.io/), which appears to be the correct domain, but Github Pages returns a "Site Not Found" 404.

I'm not sure if there's a specific design page to link to for this repo.

Screenshot of link in sidebar:
<img width="257" alt="Screenshot 2023-12-27 at 11 25 15 AM" src="https://github.com/WebAssembly/design/assets/190414/a6046094-7e99-4446-a6cf-b99b575fd0d6">

**Comment by sunfishcode** [comment]
webassembly.github.io doesn't appear to be working at the moment, but [the repo for it](https://github.com/WebAssembly/webassembly.github.io) just redirects everything to webassembly.org, so I've now changed the sidebar to webassembly.org. Thanks for the report!
