### ISSUE TITLE
Going public launch bug

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#150]
The current plan is to go public on the 17th of June, 9AM Pacific time.

On that date we'll have:
- [Blog post](http://blog.mozilla.org/luke/2015/06/17/webassembly) by @lukewagner.
- [Blog post](https://brendaneich.com/2015/06/from-asm-js-to-webassembly/) by @BrendanEich.
- [Blog post](http://blogs.msdn.com/b/mikeholman/archive/2015/06/17/working-on-the-future-of-compile-to-web-applications.aspx) on @MikeHolman's blog.
- [Tweet](https://twitter.com/jfbastien/status/611201861245399041) @jfbastien (replies only on blink-dev / native-client-discuss).
- [Email to emscripten-discuss](https://groups.google.com/d/topic/emscripten-discuss/k-egXO7AkJY/discussion) by @kripken.
- [Email to llvm-dev](https://groups.google.com/d/topic/llvm-dev/PkDjkA-LgFk/discussion) by @sunfishcode / @jfbastien.
- [WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=146064) by @pizlonator.

**Comment by jfbastien** [comment]
I created the [public announcement](https://github.com/WebAssembly/design/releases/tag/public-announcement) release.

**Comment by jbondc** [comment]
Fascinating, it would be great to add a history section to understand how the collaboration came about. Over some :beers: ? Not an expert in compilers but this sort of diversity looks like the future :+1:
