### ISSUE TITLE
"a few exceptions" link is broken

### ISSUE THREAD

**Issue by rmcloughlin** [WebAssembly/design#1525]
In this section:  https://webassembly.org/docs/portability/#assumptions-for-efficient-execution there is a link titled "a few exceptions" which goes to:

https://webassembly.github.io/spec/core/exec/index.html#floating-point-operators

but it should go to

https://webassembly.github.io/spec/core/exec/numerics.html#floating-point-operations

**Comment by dschuff** [comment]
Thanks, this is acutally a pass-through to the design repo, so I moved the issue.
