### ISSUE TITLE
Link checker: suggest using `https`

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#170]
Based on #168, the [URL checker](https://github.com/WebAssembly/design/blob/master/tools/generate.py) could automatically suggest using `https` if `http` was used but `https` works just as well for that URL.

**Comment by johnku1** [comment]
This may sound like a silly question, but which URL checker?

**Comment by jfbastien** [comment]
@johnku1 good point, I updated the issue with a link.

**Comment by BigBoneDaddy** [comment]
@jfbastien Good catch Joshua!

**Comment by sunfishcode** [comment]
The link checker was removed in #1177.
