### ISSUE TITLE
Reference Interpreter

### ISSUE THREAD

**Issue by MikeHolman** [WebAssembly/design#183]
During our meeting yesterday, we discussed some future stuff, including having a reference interpreter which could be used as an oracle. I was talking about this with @LouisLaf afterwards, and now I'm curious what we have in mind for this. A standalone reference interpreter for a pure wasm environment wouldn't be so difficult for MVP, but when we add in features like GCable objects and threading it seems like a reference interpreter will become pretty big burden. So is the plan to actually support this, GC and all, or am I thinking about this in the wrong way?

**Comment by Teemperor** [comment]
I'm not sure if it helps, but I made a interpreter here: https://github.com/Teemperor/wasmint . It's making some assumptions on how the binary presentation of a module will be, but I otherwise try to implement the draft as close as possible. It has enough functionality to load a binary module, parse the sections and then run the "main" function in it. It also does type checks for the AST and that fancy stuff.

**Comment by sunfishcode** [comment]
@Teemperor Interesting. I have also started an experimental reference interpreter. Mine's not published yet, but hopefully it will be soon, and then we can compare notes.

**Comment by MikeHolman** [comment]
Interpreters are fun so I was thinking of starting on one as well, but considering there are already at least 2 I should probably hold off.

@sunfishcode Feel free to publish when you get something of a skeleton (scanner/parser/bytecodegen/interpreter which has a few instructions). I'd be happy to help to flesh it out.

**Comment by sunfishcode** [comment]
I checked in an extremely early incomplete experimental prototype interpreter here:

https://github.com/WebAssembly/interpreter-prototype

It isn't anywhere near functional yet, and major important pieces are still missing. Some of my main ideas were the organization of the code to put everything related to the state of a running program together, everything related to a WebAssembly module together, and make it clear where implementation-specific behavior is defined. Comments and questions of all kinds are welcome.

**Comment by sunfishcode** [comment]
The current path forward for an official reference interpreter is spelled out in #287.
