### ISSUE TITLE
w3c community group link 404

### ISSUE THREAD

**Issue by m4b** [WebAssembly/design#198]
The [w3c community group link](https://github.com/WebAssembly/design/blob/master/w3.org/community/webassembly) 404s here at https://github.com/WebAssembly/design/blob/master/Contributing.md

**Comment by MikeHolman** [comment]
#197 will resolve this issue.

**Comment by m4b** [comment]
Apologies, that issue didn't come up in a cursory search.

**Comment by MikeHolman** [comment]
No problem, just merged the PR, so closing this issue as fixed.
