### ISSUE TITLE
Is IRC good for collaboration?

### ISSUE THREAD

**Issue by timakin** [WebAssembly/design#203]
Joined and saw the IRC of #webassembly, but it don't have archive and readable UI.
How's adoption of Gitter to collaborate?

**Comment by blakmatrix** [comment]
I run Seattle Nodeschool and have been involved in some of the node/io.js working groups. gitter has been mostly decent for the groups that are new and not used to existing IRC channel collaboration. 

I enjoy that I get email notifications from gitter and its integration with git, and it has worked great on a per repo basis, but it can quickly outlive its usefulness if the repo channel users get less off topic, perhaps the same could be said of any medium though...

For collaboration with the idea of archives and a GUI, `slack`, albiet another webapp that you have the issue of getting people on, has been much more beneficial than gitter esp. with channel creation within the slack "organization"--unfortuneately only paid slack accounts keep an archive of the logs, and to make it open to all you need a sort of automated bot/manual to add people to the org - the integrations are nice too.

**Comment by Teemperor** [comment]
We had the same problem at [elementary](https://elementary.io/) and moved to Slack. In retrospective it was a bad decision because we also had no archive (due to the limited messages in the free version) and we forced everyone to use the webinterface (what a lot of people including me hated).

I could setup some public channel logging like [this](http://logs.teemperor.de/) if the channel admins allow me to do so.

**Comment by abustin** [comment]
+1

Please can we enable a log for #WebAssembly channel

**Comment by belph** [comment]
https://botbot.me seems to be a popular logging option for many channels (e.g. Rust, Racket, Python). No idea what (if any) overhead is involved in using it, though.

**Comment by sunfishcode** [comment]
As mentioned above, at present the places for serious discussions are github issues and pull requests in any case. IRC is currently serving for quick conversations, but we really want summaries of interesting conversations rather than just a bunch of chat logs.

**Comment by timakin** [comment]
For now, the platform for neither of quick conversations and summarizing are sufficient.
To communicate instantly and flexibly change topics, Slack is nice, but it's not so when we'd like to stock that summary.
So how about create Slack channel for WASV, and create other original platform for OSS conversation summarization.
In my opinion, this miscommunication by the inefficiency of summarization is common among all OSS conversation.

**Comment by timakin** [comment]
Hey, I just opened WASM slack invitation page.
https://webassembly-slack-channel.herokuapp.com/

We need to discuss how to stock summary.

**Comment by sunfishcode** [comment]
You are welcome to discuss WebAssembly in any medium you choose. If you have an interesting discussion, please summarize it and post the summary in a github issue here, so that everyone in the project can read it.
