### ISSUE TITLE
Assembler Prototype

### ISSUE THREAD

**Issue by ncbray** [WebAssembly/design#207]
http://ncbray.github.io/wassembler/

Play with it, and tell me the first missing feature you run into.

The goal is to support prototyping and experimentation.  I am aiming for "easy to modify" rather than "performant."  I am not proposing any particular syntax.

**Comment by lskyum** [comment]
I really like it, but I'm wondering if the goal is that people hand-write this or it is just for nice looking generated code? 

For hand-writing it would be nice with things like structs and local/stack arrays.

**Comment by titzer** [comment]
It's mostly a stepping stone to get some code into the backend (v8-native
right now) before the LLVM->wasm backends are built.

**Comment by ncbray** [comment]
@titzer - not entirely true, I suspect it's going to persist as part of the ecosystem.  Compilers will need inline assembly.  There also needs to be a textual representation of bytecode for the "view source" case.  To rephrase what I think you were trying to get at: we aren't designing for the case where someone hand writes a large program in this language.  The goal is to have a textual representation of the bytecode that is tolerable for hand writing small chunks of code.  Inline WASM, conformance tests, experiments, the demo scene, etc.

@lskyum - I thought about structs, but have deprioritized them because of the complexity they add at the language level (struct declarations, pointer types, and casts, mainly) yet are just sugar that completely disappears when you compile into bytecode.  There is currently some sugar in the language (i8 and i16 ==> i32 with shifts, while loop ==> infinite loop with break, a > b ==> !(a <= b) ) but is has less pervasive effects than structs.

We'll see where the ecosystem evolves.  Maybe there will be a "high level WASM" language layered on top of this language.  Maybe the inline WASM use case will show structs make interacting with C easier.  Keeping things simple for now, however.

**Comment by lskyum** [comment]
It seems like a really nice language for inline optimizations. In a C++ program it may however be a little confusing how you could reference arguments and variables, because they would probably be placed in the linear memory and not the actual js/wasm stack. Maybe a C++ compiler would have to re-write the code a bit?

**Comment by kg** [comment]
> Maybe a C++ compiler would have to re-write the code a bit?

This is already necessary to target asm.js, so it's pretty reasonable to keep it as a constraint. This and some other compromises make it eas(y|ier) to maintain stack safety.

**Comment by sunfishcode** [comment]
Further discussion of the wassembler project can take place [in the context of the repo itself](https://github.com/ncbray/wassembler). Thanks!
