### ISSUE TITLE
For inspiration, you could study SPIRV (OpenCL/Vulkan binary format)

### ISSUE THREAD

**Issue by cheery** [WebAssembly/design#212]
[SPIRV](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.pdf) consists of flat sequence of 32-bit integers, stored as an array in a file. It's feeling like fairly pleasing format to handle.

Supposedly it doesn't directly fit to WebAssembly use though?

**Comment by kg** [comment]
I would be surprised if post-compression or pre-compression file size was a
high priority for them during the design process. Size matters a lot to us.
It's certainly an interesting effort either way.

**Comment by jfbastien** [comment]
This is a pretty open question. Are there specific things about SPIRV that you think WebAssembly would benefit from? We have a pretty extensive list of requirements that led to the current approach, as @kg points out it would be great to know which of these overlap with SPIRV.

**Comment by cheery** [comment]
Peeking into [HighLevelGoals](https://github.com/WebAssembly/design/blob/master/HighLevelGoals.md), and then into SPIRV goals. They do not intersect. That format is still noteworthy because it succeeds GLSL, and it seems to do it well.

Particularly I enjoy about how clear the SPIRV format is. It starts with fixed size header, then forms sequence of commands. First byte in each command tells its length, so each command can be recognized apart without having to determine what they mean. The decoding of instructions is straightforward to do without special case for each instruction.

**Comment by sunfishcode** [comment]
It is also a goal of WebAssembly to be clear and easy to decode, though as you observe, WebAssembly's other goals differ from SPIR-V's goals. Prepending each command/instruction/etc. with a length byte is likely to be detrimental to compression, so it isn't likely to be suitable for WebAssembly. WebAssembly will likely have a concept of sections with headers specifying their length, so it will be possible to skip over entire sections without decoding them. If you have other specific suggestions, please file a new issue.
