### ISSUE TITLE
C static local variable semantics

### ISSUE THREAD

**Issue by m4b** [WebAssembly/design#213]
In the [AST local variable specification](https://github.com/WebAssembly/design/blob/master/AstSemantics.md#addressing-local-variables) it is stated that:

> Local variables do not have addresses and are not aliased in the globals or the heap

If I am interpreting this correctly, then how will a C function-local static variable be treated?  I.e.:
````c
int f (int x){
  static int y = 0;
  y++;
  return x + y;
}
````

 It's scope, and hence visibility, is local to the function, but it doesn't have local memory.  Typically at the compilation level, it is treated as a BSS or data variable, and hence global, but its local scope is "enforced" by compiled code never accessing it outside of function scope, because source compilation rules enforces this.

Perhaps this won't be an issue, since WebAssembly is presumably the target of C code, and hence the same enforcement of function-local static variables can be done?

**Comment by kg** [comment]
WebAssembly isn't narrowly scoped to C to the extent that static locals would really merit special treatment. Compiling them down to globals (just like on existing native architectures) should work just fine.

**Comment by m4b** [comment]
OK, that's what I figured, just thought having this issue on record would be good.  Thanks!
