### ISSUE TITLE
Question, is this like js-ctypes?

### ISSUE THREAD

**Issue by Noitidart** [WebAssembly/design#216]
Is this like js-ctypes? It would be nice to get js-ctypes to the other browsers as well so we have more open source work in it.

**Comment by kg** [comment]
As I understand it, js-ctypes is a FFI for calling out to external native code. WebAssembly will provide JS <-> native code interop, but the native code will have to be compiled to WebAssembly and running inside the wasm runtime.

**Comment by Noitidart** [comment]
Thanks @kg so WebAssembly cant work in runtime stuff like addons huh? But I can use them in firefox addons if I compile it first?
