### ISSUE TITLE
exports should declare size

### ISSUE THREAD

**Issue by m4b** [WebAssembly/design#218]
In the description of [modules](https://github.com/WebAssembly/design/blob/master/MVP.md#modules), I was extremely pleased to note that imports were given a strict definition through a tuple structure, providing important information, specifically:

> A module can declare a set of imports. An import is a tuple containing a module name, export name, and the type to use for the import within the module. The host environment controls the mapping from module name to which module is loaded.

One of the best aspects of mach-o binaries is that their imports and exports are strictly defined: there is never any doubt whether a symbol is exported (they are in the export trie), and how to find it (walk the trie); similarly, there is never any doubt whether something is an import (a record in the import FSA), whether it's a reexport, and furthermore, where that import comes from, and how to find the imports (run the FSA opcodes).

The latter point is in contrast to the ELF format, which does **not** require each imported symbol to declare its exporting library.  This makes static binary analysis slightly more involved for ELF imports.

As such I was quite happy that WebAssembly is following in mach-o's footsteps by using the tuple structure to provide this kind of information for imports.  Conversely however, one thing ELF _did_ get right (and unfortunately mach-o did _**not**_ get right) is that ELF symbols declare their size.

However, there does not seem to be any mention of requiring exports to declare a size field for each exported symbol: 

> A module can declare a subset of its functions and global variables to be exports. The meaning of exports (how and when they are called) is defined by the host environment. For example, _start and init can be the only meaningful exports.

I would _strongly_ encourage the adoption of a tuple to define exports, perhaps consisting of something like `(symbol name, offset, size)`, where size is either:

* the number of bytes if the instruction encoding is variable length (like x86)
* a multiple of the instruction size if the instruction encoding length is constant (like ARM)

and offset is the export's offset into the module.

Determining function size is an extremely difficult problem, and undecidable in general, and as such I encourage making static analysis easier (in addition to other tools) by including a size tag for exports mandatory, at the very least.

**Comment by titzer** [comment]
On Wed, Jun 24, 2015 at 12:00 AM, m4b <notifications@github.com> wrote:

> In the description of modules
> <https://github.com/WebAssembly/design/blob/master/MVP.md#modules>, I was
> extremely pleased to note that imports were given a strict definition
> through a tuple structure, providing important information, specifically:
>
> A module can declare a set of imports. An import is a tuple containing a
> module name, export name, and the type to use for the import within the
> module. The host environment controls the mapping from module name to which
> module is loaded.
>
> One of the best aspects of mach-o binaries is that their imports and
> exports are strictly defined: there is never any doubt whether a symbol is
> exported (they are in the export trie), and how to find it (walk the trie);
> similarly, there is never any doubt whether something is an import (a
> record in the import FSA), whether it's a reexport, and furthermore, where
> that import comes from, and how to find the imports (run the FSA opcodes).
>
> The latter point is in contrast to the ELF format, which does *not*
> require each imported symbol to declare its exporting library. This makes
> static binary analysis slightly more involved for ELF imports.
>
> As such I was quite happy that WebAssembly is following in mach-o's
> footsteps by using the tuple structure to provide this kind of information
> for imports. Conversely however, one thing ELF *did* get right (and
> unfortunately mach-o did *not* get right) is that ELF symbols declare
> their size.
>
> However, there does not seem to be any mention of requiring exports to
> declare a size field for each exported symbol:
>
> A module can declare a subset of its functions and global variables to be
> exports. The meaning of exports (how and when they are called) is defined
> by the host environment. For example, _start and init can be the only
> meaningful exports.
>
> I would *strongly* encourage the adoption of a tuple to define exports,
> perhaps consisting of something like (symbol name, offset, size), where
> size is either:
>
>    - the number of bytes if the instruction encoding is variable length
>    (like x86)
>    - a multiple of the instruction size if the instruction encoding
>    length is constant (like ARM)
>
> and offset is the export's offset into the module.
>
> Determining function size is an extremely difficult problem, and
> undecidable in general, and as such I encourage making static analysis
> easier (in addition to other tools) by including a size tag for exports
> mandatory, at the very least.
>
For static analysis tools, it should be cheap to compute the size of a
function's body in wasm. The body must consist of exactly one statement,
which forms exactly one syntax tree node. Decoding amounts to "parsing"
this tree, but this is very simple with an explicit stack since the tree is
laid out in pre-order. Other than that, I don't think the size of a
function's code (i.e. the representation of its syntax tree) is needed
dynamically.

**Comment by m4b** [comment]
Correct me if I'm wrong, but the AST is _not_ the transmitted binary, correct?  We still receive a sequence of instructions, which we can decode to a textual representation.  Or perhaps I'm misunderstanding something.

**Comment by MikeHolman** [comment]
The transmitted binary is a preorder representation of the AST (though a few of us were discussing yesterday making this postorder).

**Comment by m4b** [comment]
A point of clarification, the transmitted binary can't be the AST correct ? Because it has bookkeeping data, like the import tuples, the export declaratikons, I assume a module name, etc.  I.e., it's a module/container.  In the module are somewhere the preorder representations of the AST, which all taken together make up the executable code.

Now by preorder representation, I assume you're talking about mathematical preorders.

But does this mean that the actual binary sequences which begin the function are not encoded in a manner like ARM or x86, i.e., instruction opcodes whose bitfields define the semantics of the operation?

**Comment by titzer** [comment]
There is a table of all the functions that have bodies, with offsets into
the binary where the ASTs are stored. The ASTs are stored as a serialized
binary format. When we say preorder, we mean that an expression like "a +
b", which forms a tree with a node representing "+" at the root, and "a"
and "b" as children, is represented in bytes as a byte to encode "+", then
the byte(s) to encode "a", then the bytes to encode "b". If "a" and "b" are
complex expressions, they are encoded similarly.

This will become clearer when we get closer to agreeing on a binary format,
but you can take a look at the v8-native prototype or the polyfill
prototype to see two incarnations of the idea.

**Comment by m4b** [comment]
>  When we say preorder, we mean that an expression like "a +
b", which forms a tree with a node representing "+" at the root, and "a"
and "b" as children, is represented in bytes as a byte to encode "+", then
the byte(s) to encode "a", then the bytes to encode "b". If "a" and "b" are
complex expressions, they are encoded similarly.

Oh prefix (or postfix) or polish notation; this is what I thought you meant, but wasn't sure.

> This will become clearer when we get closer to agreeing on a binary format,

Yea, it's still a little fuzzy for me.  I'm not sure how storing your functions in pre or postfix representations solves the size problem.  I'm actually even more confused now, because, for example, I assume arbitrary jumps are allowed?  If so:

* what does that even look like?
* it seems like computing the body size is undecidable (in general), since it amounts to computing the function with every possible branch case.

Something like this lispy example:
```
(+ (const 5) (jmpz 0x5000 x))
```

I'm not even sure how arbitrary jumps are supposed to work with the AST, come to think of it?

> but you can take a look at the v8-native prototype or the polyfill
prototype to see two incarnations of the idea.

I will take a look again; I cloned the v8-native-prototype and didn't see a Makefile, build instructions, or a usage guide; I attempted to compile a few times, but didn't put much effort into it.  But I'll go back and take a look again.

**Comment by kg** [comment]
'arbitrary jumps are allowed' is probably the wrong mental model here. When we say AST we're referring to something akin to a JavaScript AST (not JavaScript though, obviously): Mostly trees of statements and substatements and expressions. Hypothetically:
* An 'if' statement with true/false blocks under it as children, along with a condition expression.
* A binary expression with an operator and lhs/rhs.
* A 'continue' statement with a target label name (this would be the closest thing to a goto)
* A 'loop' statement with a label and a body inside it.

A function body would be a block containing one or more statements in the above model.

So in that sense, things like arbitrary jumps (other than labelled break/continue) might not exist at all, and 'size' is not really a meaningful concept either. You just have the AST for the function, and you decode it by decoding the format. Individual functions in the tables have an on-disk size in bytes, but they don't necessarily have a size header that would be used in the way you would use a size header in ELF or PE. In native assembly languages you're doing your analysis &c by disassembling a series of raw bytes into instructions; wasm is strongly typed and well-formed such that you are just decoding a data structure with a well-defined format, using a well-defined algorithm. On the other end after decoding you have internal IR inside a javascript engine or data structures inside your analyzer or javascript source inside your polyfill. Make sense?

There will definitely be a deterministic way to find individual entries in tables like the function table, since encoders and decoders will need a way to simply and reliably do this.

**Comment by m4b** [comment]
> 'arbitrary jumps are allowed' is probably the wrong mental model here. When we say AST we're referring to something akin to a JavaScript AST (not JavaScript though, obviously): Mostly trees of statements and substatements and expressions. Hypothetically:
>
>    An 'if' statement with true/false blocks under it as children, along with a condition expression.
>    A binary expression with an operator and lhs/rhs.
>    A 'continue' statement with a target label name (this would be the closest thing to a goto)
>    A 'loop' statement with a label and a body inside it.
>
> A function body would be a block containing one or more statements in the above model.

Thank you for the explanation, but I think I'll need to see the on-disk encoding format and examples of decoders generating the AST.  But I see now from the AST doc on control flow:

>  Break and continue statements can only target blocks or loops in which they are nested.

Which would prevent the worry I suggested above about computing arbitrary branch conditions.

However:

> [...] and 'size' is not really a meaningful concept either

I wouldn't go that far; the size (on disk, or since the ASTs are trees, perhaps the strahler number) tells you a ballpark complexity of the function at the very least, and there are many other things you can do when you have the function size.  

But as far as keeping the functions size in the module book-keeping (similar to the tuples for the imports), and hence an on-disk increase of the binary size, then given all of your responses, it does seem like export size isn't necessary, if it can be computed easily.

I'll close this issue, if no one else objects.

**Comment by kg** [comment]
The more relevant distinction is that the export isn't a blob of bytes with a size, but instead a function entry point with a known type signature, if that makes sense? Another wasm module isn't importing the bytes, it's importing the *function*, from the module it lives in. So at runtime the two modules are compiled and the imports & exports are glued together. Thus, the size of the export doesn't matter.

**Comment by m4b** [comment]
No, this doesn't make sense to me.  The function (exported or not) _is_ a blob of bytes; if you remove the blob of bytes, you remove the function; if I alter those bytes, I alter the function.  From the reversers perspective, that's all there is.  Perhaps you meant to make a distinction between the export's declaration (i.e., that it's exported, and where it's entry is, along with it's type signature) and the definition of the export (i.e., the actual blob of bytes that does what the function does), which is an important distinction.

Secondly, I'm not sure of the semantics of static linking in wasm (or if there even is any), but did you mean at _runtime_ the modules are glued together, or at _compile time_ they're glued together?  This also assumes static linking (whereas post MVP, dynamic linking is being considered as I understand it).

I'm not sure how you conclude from this that the size of the export doesn't matter, or what it is exactly that doesn't matter, but, again, there are many things you can do with the size of the function (note I also mentioned the [strahler number](https://en.wikipedia.org/wiki/Strahler_number), which is not a quantificaiton of the number of bytes, but a higher level measurement of size, more suited to ASTs and such).

While I agree the size of the export isn't as important in a statically linked binary, because in some sense, there are no imports/exports, just a fused binary with functions, again, this is also assuming static linking; there are many cases in static analysis where I might want to examine a module, or multiple modules in conjunction, and look at what they declare as exported, compute or estimate their size, and compare this with other features and data I've gathered, all without ever compiling a binary with those exports.  I do this [here](http://github.com/m4b/rdr), in the system symbol map.

As such, for the reasons above, the export size _can_ matter, very much so.

But that's not what this issue is about, since it's been clarified that requiring export declarations to define size isn't required, because it can ostensibly be computed; so if it's not something you care about, then you don't need to care about it :)
