### ISSUE TITLE
Adding a "void*"/dedicated pointer type to WebAssembly

### ISSUE THREAD

**Issue by ala53** [WebAssembly/design#220]
As best as I can tell, WebAssembly is not platform independent insofar as it depends on either an int32 or an int64 to represent a pointer. By creating a separate, platform-dependent and non-fixed-sized data type, it is possible to guarantee full platform independence for the memory model. Is it viable to add, for example, a "intptr" or "memptr" data type to the bytecode format?

 * It would avoid either limiting to a 32 bit addressable space.
   * 64 bit for all pointers could solve this, but it would increase compilation complexity if one has to remap all of the allocations based on platform (what about 128 bit architectures or some bizarre 46 bit one?)
 * Having it alias int32 or int64 would reduce compiliation complexity
 * It would increase bytecode complexity because of needing to add intptr_load, intptr_store, intptr_add, intptr_subtract, and the related instructions.
 * It would provide a semantic difference between numbers and pointers/references, reducing the risk of bugs (`int32_load var1` where var1 was actually just a number).
 * The compiler could optimize better because it could guarantee that a pointer is valid in many cases (presumably at compile time) and avoid emitting guard clauses.

**Comment by titzer** [comment]
The decision not to have a pointer type was deliberate. The program gets one large readable/writable memory and not individual malloc'd chunks, so C-level pointers are represented as byte offsets into this memory. By not having a defined pointer size, it's up to programs to decide whether to use 32-bit or 64-bit offsets, depending on whether they expect to use a very large heap or not.

**Comment by ala53** [comment]
Will that not have a significant performance overhead? By my understanding, you will have to go through several steps to access a memory location. First, you'll have to check if the memory at that byte offset is allocated yet. Then, you'll have to resolve which real-world memory chunk the memory is in (as the underlying runtime will `malloc` the memory) and then, you will access the address.

That is two extra steps to access a memory address, because of needing to map byte offsets to actual chunks of allocated memory. Alternatively, will programs have to declare the amount to memory to allocate at compile time? If so, are they able to allocate more, because I see that running into the same end issue.

**Comment by ala53** [comment]
Would that not cause a lot of overhead with an implementation, as one would have to dynamically allocate the memory if a pointer access is out of range in addition to computing the real world address of the pointer from the bytecode address?

Even with an optimized implementation (which limits you to quite a small address space), you'd still have the following extra code by my math(poor assembler skills, sorry!):
```
mov ecx, dword ptr [webasm_pointer]
idiv ecx, 1048576 ; compute the chunk it is in - chunk in eax, offset in edx (by my memory)
cmp eax, dword ptr [<address of number of chunks allocated>] ; check if allocated
jgt <allocator function>
mov ecx, dword ptr [<address of array of memory chunks allocated> + [eax]] ; get the memory block's address
iadd ecx, edx ; and the actual address

;do stuff with the address in ecx (versus in native, you go directly here)
```
Now, I know this is an implementation issue and that a fair portion of accesses could be inlined and thereby be much, much faster, but it still seems like a poor design choice. Am I misunderstanding the way the memory model works (e.g. compile time memory allocation), is there a usability reason for this that outweighs the performance overhead, or something else?

**Comment by kg** [comment]
There's one heap. All your addresses are in one heap. They're just ints instead of void*. As I understand it. This is how asm.js works right now.

**Comment by ala53** [comment]
Ok, I see. I thought there were several heaps in native memory being aliased as one in WebAssembly memory (which was what the above complaint about extraneous code was about).
