### ISSUE TITLE
Web Assembly, to make games?

### ISSUE THREAD

**Issue by ArionDeno** [WebAssembly/design#224]
Hello I would suggest if possible of course

support the Api Web assembly. OpenGL and a window api to my suggestion, one Api structured as C, eg Allegro and SDL. But a light version. it does not get in the way of game programming. maybe .. you create a standard example SDL 2.0 + WebGL. like C / C ++ in Web Assembly. helps porting games to the web, there is Adobe Alchmist, gcc and C / C ++ compiler for * .swf for flash player.

I have many ideas. for an api for web games in C / C ++. thanks for listening

**Comment by jfbastien** [comment]
Right now WebAssembly doesn't tackle the API problem (and it's a big problem!). MVP merely punts the problem to the embedder, and we'll more likely address this problem full-on once we support dynamic linking.

On the Web we only plan to support the browser's own APIs for now (e.g. WebGL). Eventually WebAssembly may drive new browser APIs too, and things like Vulcan may become mainstream in browsers if a security model can be enforced.

Windows APIs could be usable if someone created a WebAssembly sandbox that runs specifically on Windows, but I don't think this is likely.

**Comment by sunfishcode** [comment]
Emscripten has support for OpenGL and SDL APIs, and you don't need to wait for WebAssembly; you can develop C/C++ code that uses them and run it on the Web today!

And, when [Emscripten is extended to support WebAssembly](https://github.com/WebAssembly/design/blob/master/FAQ.md#whats-the-story-for-emscripten-users), code developed with Emscripten will be easy to port to WebAssembly.

There are also some example programs available which help show how to use these APIs on the Web, such as:
 - https://hacks.mozilla.org/2012/04/porting-me-my-shadow-to-the-web-c-to-javascriptcanvas-via-emscripten/
 - http://kripken.github.io/emscripten-site/docs/porting/multimedia_and_graphics/OpenGL-support.html
