### ISSUE TITLE
WebAssembly will be able to communicate with each other? 

### ISSUE THREAD

**Issue by Sumeet001** [WebAssembly/design#225]
Wanted to ask if there will be any communication model between two or more Web Assemblies.
and how data shall be shared between them? Can a single webpage will be able to load multiple Web Assemblies and if so how they will scope? Will there be any standard if they want to talk cross tabs?

**Comment by MikeHolman** [comment]
WebAssembly modules will be able to directly communicate with dynamic linking. It's also possible to share data between modules using javascript as glue. For example you can call from wasmModule1 into javascript, which then calls wasmModule2. I don't think there is any way for javascript to directly communicate between different tabs, and WebAssembly will have a similar model to javascript, so it cannot do so either.

**Comment by Sumeet001** [comment]
Got it !! :+1: Thank you so much for clarifying !!
