### ISSUE TITLE
Naming consistency for conversions: extensions, truncations, rounding and wrapping

### ISSUE THREAD

**Issue by titzer** [WebAssembly/design#228]
We are somewhat inconsistent in the naming of the AST operations at the moment. In particular, we use a lot of different terms but haven't defined exactly what we mean by them. Also, the naming w.r.t. signed/unsigned integer operations is slightly inconsistent.

I'll use the generic term "conversion" to refer to all operations that take a single value of one type and produce a single value of the same or different type where the result is an approximation or different representation of the same value. Conversion operations C generally have these properties:

1. Pure function. Neither reads nor writes mutable state, always returns the same result for the same input.
2. Unary. One input, one output.
3. Mostly-invertable. For a large number of inputs v, there exists an inverse conversion R where R(C(v)) == v.

Our operations could be broken down as follows. The ones that are fully invertable (i.e. an inverse function exists for all input values v) are noted, while the others are mostly invertable.

1. Integer extension. For example, converting a smaller integer to a larger integer by sign extending or zero extending. Fully invertable.
2. Integer wrapping. For example, converting a larger integer to a smaller integer by discarding the upper bits. Only invertable when the upper bits are the sign-extension or zero-extension of the lower bits appropriately.
3. Floating point rounding. For example, one of the IEEE 754 rounding modes. Inverse only exists when the output is equal to the input.
4. Floating point nearest integer. A special case of floating point rounding to integers.
5. Integer to floating point extension. For example, converting an integer to a floating point number where there can be no loss of precision, such as int32 to float64. Fully invertable.
6. Integer to floating point conversion. For example, converting an integer to a floating point number where there could be loss of precision, such as int32 to float32. Only invertable when the discarded lower bits are all 0.
7. Integer/floating point reinterpretation. For example, reinterpreting the bits of an integer as a floating point number or vice versa. Fully invertable if NaN bit patterns are not canonicalized.
8. Floating point to integer truncation with saturation. For example, converting a floating point to a number where values too large or too small to represent are clamped to -MIN_INT or MAX_INT, and NaN is interpreted as some integer value, e.g. 0. Only invertable if there are no fractional bits, there is no overflow, and the input is not a NaN.
9. Any of the variants of the above that trap when an inverse function does not exist. Invertable, by definition, if the input does not cause a trap.

**Comment by titzer** [comment]
I'll take a first stab at naming some of the operations we have so far, somewhat along the lines we've been following, using a convention where the local type of the result comes first:

result_type.operation[input_type]

Strawman proposal below.

1. int64.(sext|uext)_int32
2. int64.wrap[int32]
3. float32.round[float64]
4. int32.sround[float32|float64] int32.uround[float32|float64]
5. float64.(sext|uext)[int32]
6. float32.(sapprox|uapprox)[int32] float64.(sapprox|uapprox)[int32|int64]
7. float32.reinterpret[int32] int32.reinterpret[float32] float64.reinterpret[int64] int64.reinterpret[float64] 
8. (int32|int64).(ssat|usat)[float32|float64]
9. above names with suffix: _t

**Comment by sunfishcode** [comment]
Distinguishing between int32-to-float32 which may overflow and int32-to-float64 which may not has its appeal.

There are presently no saturating conversions. Are you proposing we add them?
There are presently no float-to-int-type to-nearest conversion operators. Are you proposing we add them?

**Comment by titzer** [comment]
No, I just included them for completeness, to see if the model fits.

**Comment by kg** [comment]
I like saturating conversions, but they're relatively uncommon outside audio/video.
Though I guess once we introduce SIMD, we'll have saturating operations...

Having the knowledge that an operation will never overflow stated in the docs is pretty nice. It makes things much easier on developers when debugging or authoring a polyfill.

**Comment by sunfishcode** [comment]
On the other hand, making int32-to-float32 different from int32-to-float64 has the disadvantage of having different operator names between float32 and float64. One way of looking at is is that it's the same conceptual operator, it's just that with int32 and float64 the ranges of the types happen to mean that overflow never occurs. And being able to say that float32 and float64 support all the same operations is nice, if it works out.

It's confusing to have 'round' mean truncated rounding in sround/uround, and to-nearest rounding in float32.round[float64].

**Comment by titzer** [comment]
Yeah, you're right. I'll have to check if hardware instructions actually round when converting int32 to float32 or not. If it doesn't then, truncation is probably a better name.

Do we want the term "truncate" to always refer to the act of discarding low-order bits without rounding?

We could then say that "wrap" always means to discard high-order bits (e.g. with integers).

**Comment by titzer** [comment]
I'd also argue that float32.strunc[int32] really is a different conceptual operation than float64.sext[int32], since the latter is invertable and doesn't lose precision. Somehow, holes in the conversion matrix seem unavoidable. We can still "cheat" and say that "float32 and float64 have the same arithmetic operations, but slightly different conversions".

**Comment by sunfishcode** [comment]
I'm curious why you're interested in invertibility here. Is this an implementor's desire to optimize away F'(F(x)) sequences? From a developer perspective, some of the relevant use cases I can think of are:

 - Changing a float32 algorithm to float64 - if all the operators are the same, you can just switch the types and everything works exactly as you expect.
 - Changing a float64 algorithm to float32 - Conversion from int32 may overflow when it didn't before, but then again, *all* of your floating point operations now have the risk of overflowing when they didn't before. Conversion from int32 isn't special here.
 - Trying to determine the source of an overflow - Overflow can happen in all of your floating point operations, so highlighting conversions from int32 is just helping one small part of a problem that wants different tools anyway.

**Comment by jfbastien** [comment]
I like the proposal. Consistency is good.
Personal preference: truncate sounds more familiar than wrap.

**Comment by titzer** [comment]
On Thu, Jun 25, 2015 at 5:08 PM, Dan Gohman <notifications@github.com>
wrote:

> I'm curious why you're interested in invertibility here. Is this an
> implementor's desire to optimize away F'(F(x)) sequences? From a developer
> perspective, some of the relevant use cases I can think of are:
>
>    - Changing a float32 algorithm to float64 - if all the operators are
>    the same, you can just switch the types and everything works exactly as you
>    expect.
>    - Changing a float64 algorithm to float32 - Conversion from int32 may
>    overflow when it didn't before, but then again, *all* of your floating
>    point operations now have the risk of overflowing when they didn't before.
>    Conversion from int32 isn't special here.
>    - Trying to determine the source of an overflow - Overflow can happen
>    in all of your floating point operations, so highlighting conversions from
>    int32 is just helping one small part of a problem that wants different
>    tools anyway.
>
> It's not necessarily the invertability itself property that is interesting
to producers or developers, but being explicit about when precision is lost
or rounding occurs makes this unambiguous for everyone. I don't expect a
lot of folding of F`(F(x)) to actually occur, or for that to show up in
particular hot loops, but it's really nice to reason about compiler
optimizations not changing semantics. E.g. in TF we distinguish conversions
that are simply representation changes from those that truncate; the former
ones can be introduced at any time and optimized away without any fanfare,
while it's pretty much always a bug for the compiler to introduce or remove
the latter ones.

**Comment by sunfishcode** [comment]
Highlighting that int32-to-float64 doesn't round doesn't seem urgent outside of contexts like JS optimization because rounding happens on most operations that return floating point values anyway. If a developer chooses to use float32 instead of float64 for a particular computation, they're asking for greater artifacts (in exchange for greater performance).

**Comment by sunfishcode** [comment]
I should also mention that earlier in this conversation I was mistaken in thinking that integer to floating point conversions overflow. Instead, they round.

**Comment by binji** [comment]
Just for comparison, here are the names in LLVM bitcode:

1. sext/zext
2. trunc
3. fptrunc
4. fptoui/fptosi
5-6. uitofp/sitofp
7. bitcast
8-9. Don't exist?

There's also fpext for float32 -> float64 conversion.

**Comment by sunfishcode** [comment]
LLVM's "fptrunc" name is wrong, because truncating for floating-point means discarding the fractional part, and that's not what that operator actually does. WebAssembly is presently calling this operation "demote", although that's not necessarily a final name. Using "trunc" to mean something different for integers than it means for floating point is also confusing, so WebAssembly is calling that "wrap", which is more descriptive of its semantics.

**Comment by sunfishcode** [comment]
Here's my take on the major differences between the strawman above and what's currently in the repo:

sext/uext vs extend_signed/extend_unsigned: I'd be ok either way.

float32.round[float64] vs float32.demote[float64]: I like `demote` better, since `round` can be misinterpreted (this `round` is different from both C's `round` and JS's `Math.round`, which differ from each other, woo), but I'm open to other suggestions too.

sround/uround vs trunc_signed/trunc_unsigned: I like having `trunc` in the name since it indicates what kind of conversion this is. `round` is again ambiguous. I could be convinced to go with `strunc` and `utrunc` if shorter names are preferred.

sext/uext/sapprox/uapprox vs cvt_signed/cvt_unsigned: I think consistency between int32 and int64 and between float32 and float64 is more important than consistency between non-lossy conversions of various kinds. I'm not attached to the names `cvt_signed` or `cvt_unsigned` though.

**Comment by lukewagner** [comment]
I think this has been resolved by a number of PRs refining naming in [design](https://github.com/WebAssembly/design/blob/master/AstSemantics.md#datatype-conversions-truncations-reinterpretations-promotions-and-demotions) and the [sexpr language](https://github.com/WebAssembly/spec/blob/master/ml-proto/README.md#external-syntax).
