### ISSUE TITLE
Add a Primer document that teaches by example

### ISSUE THREAD

**Issue by qwertie** [WebAssembly/design#232]
I'm having some difficulty getting a clear picture of "where we currently stand" and how things fit together. I realize there's no WebAssembly spec and many things are undecided, but I think there should be a document that gives newcomers (myself included) a more concrete picture, even for those with minimal experience with asm.js.

I think the design repo should contain a document that introduces the Wasm text and binary formats using a small concrete example, along with how it might be polyfilled and how a web page would use a webasm file (since this last part is user-oriented, perhaps it should go in a separate document, but for now it's okay to put both in a single document, since we have only one audience: those interested in WebAsm's design). For example, the document could look something like this:

## Introduction to WebAssembly format & workflow

This document briefly introduces a _prototype_ WebAssembly text and binary file format, shows how code written in a high-level language (C) might be translated to this format, and the expected manner by which WebAssembly modules (`*.webasm) can be used in an HTML page.

**Note**: The format shown here is merely a starting point for discussion. The specification for WebAssembly's minimum viable product (MVP) is in flux; we expect the final file format will be different and **incompatible** with what is shown here. Even the file extensions could change!

### Source code

Consider this C code `lowercase.c`:

~~~c
    char toLower(char c)
    {
      return c >= 'A' && c <= 'Z' ? c + ('a' - 'A') : c;
    }

    void strToLower(char* buf)
    {
      for (int i = 0; buf[i]; i++)
        buf[i] = toLower(buf[i]);
    }
~~~

One will be able to compile `lowercase.c` to a `lowercase.webasm` binary file which can be executed in a web browser. The tool for compiling C to Wasm isn't written yet. 

TODO: add instructions for how to use the prototype to get from C to Wasm.

### WebAsm text format (`*.wat`)

In addition to the binary WebAsm format that is normally used, a text format is defined for humans to read. The textual webassembly code for `toLower` and `strToLower` might look something like this:

(NOTE: This code is using [LES syntax](https://github.com/qwertie/LoycCore/wiki/Loyc-Expression-Syntax), a "universal" syntax tree representation that I invented. The LES language has no keywords; by convention, # marks words with special meaning, although it's a bit noisy. All those # signs could be omitted, we would just need some way to distinguish whether `int32_add(x, y)` is an opcode or a function call.)

~~~c
    #header { /* TODO */ };
    #code {
      // My understanding is that the binary format doesn't include local variable 
      // and param names and I'm not even sure what the deal is with function
      // names. I disagree - IMO WebAsm files *need* a way to put this metadata
      // into the same binary. In any case, I think the text format should always 
      // permit human-readable names. Slot numbers could be assigned to local
      // variables according to the order in which they are declared.
      #fn toLower(c::i32)::i32 locals()
        // There are about a zillion ways to represent the code in text form, 
        // but for starters, I'm thinking most loads could be implicit, e.g. `c` 
        // is short for `#get_local(c)`. LES permits characters like 'A', which 
        // could be interpreted as 32-bit constants. Notice: since there is no 
        // opcode defined for operator &&, the "else" branch must be duplicated.
        #conditional(#int32_ule('A', c), 
          #conditional(#int32_ule(c, 'Z'),
            #int32_add(c, 32), c),
          c);
      
      #fn strToLower(buf::i32)::void 
        locals(i::i32) { // Braces = block of statements (or expressions - issue #223)
        i = 0;  // shorthand for #set_local(i, 0)
        #if #int32_load_zx_int8(#int32_add(buf, i)) {
          #do_while {
            #int32_store_int8(#int32_add(buf, i), 
              toLower(#int32_load_zx_int8(#int32_add(buf, i)));
            i = #int32_add(i, 1);
          } #int32_load_zx_int8(#int32_add(buf, i));
        };
      };
    };
~~~

TODO: explain what the code means; explain core concepts.

### Binary

This code is usually compiled to a binary format, like this:

    TODO: add hex editor view of binary format

TODO: pick apart and explain the binary format

### Relationship with asm.js

The polyfill (emulation code for browsers that don't support WebAssembly directly) will reconstruct the following asm.js code from the WebAssembly binary:

    TODO: asm.js equivalent

### Access from HTML/Javascript

TODO: explain how to import and call the code from HTML. Specifically mention any additional pieces of the puzzle, no matter how small, and how they fit together, to give the reader a solid mental picture.

### More information

TODO: add links to documents that explain things in more detail

**Comment by qwertie** [comment]
How it might look without all the `#`s (using `.toLower`, with a dot, to indicate a function call):

    header { /* TODO */ };
    code {
      fn toLower(c::i32)::i32 locals()
        conditional(int32_ule('A', c), 
          conditional(int32_ule(c, 'Z'),
            int32_add(c, 32), c),
          c);

      fn strToLower(buf::i32)::void 
        locals(i::i32) {
        i = 0;  // shorthand for #set_local(i, 0)
        if int32_load_zx_int8(int32_add(buf, i)) {
          do_while {
            int32_store_int8(int32_add(buf, i), 
              .toLower(int32_load_zx_int8(int32_add(buf, i)));
            i = int32_add(i, 1);
          } int32_load_zx_int8(int32_add(buf, i));
        };
      };
    };

And I think shorter opcode names would be a good idea, or shortcut operators. Here's how it looks if we use a few shortcuts, like `+` for add, `L8sx32` for `int32_load_zx_int8` ("sign-extend 8-bit into 32-bit"), `S8` for `int32_store_int8`, and `<|=` for unsigned less than (note: the text-format assembler could infer the operand size and pick the correct opcode for `S8`, `+` and `<|=`; and under LES rules, `<|=` has the same precedence as `<=`, unlike my first choice `|<=|`, which would have the same precedence as `||`.)

    header { /* TODO */ };
    code {
      fn toLower(c::i32)::i32 locals()
        conditional('A' <|= c, 
          conditional(c <|= 'Z',
            c + 32, c),
          c);

      fn strToLower(buf::i32)::void 
        locals(i::i32)
      :{
        i = 0;
        if L8sx32(buf + i) {
          do_while {
            S8(buf + i, .toLower(L8sx32(buf + i));
            i = int32_add(i, 1);
          } L8sx32(buf + i);
        };
      };
    };

**Comment by sunfishcode** [comment]
The answer to "where we currently stand" is that we're in an early design phase and we're not quite ready for a great level of syntactic detail yet.

Concerning LES in this context, if we're going to have a C/JS-like syntax, the likely preference will be for a natural C/JS-like syntax, rather than one that makes several compromises.

Even the friendlier syntax given above:
```
do_while {
   ...
}, expr;
```
is still significantly less pretty than this:
```
do {
  ...
} while (expr);
```
by the criteria that are likely to be applied here.

Also, [non-obvious whitespace rules](https://github.com/qwertie/LoycCore/wiki/Loyc-Expression-Syntax#less-dirty-little-secret-space-sensitivity), [overbearing semicolon requirements](https://github.com/qwertie/LoycCore/wiki/Loyc-Expression-Syntax#the-forgotten-semicolon-problem), and [operator precedence rules that differ from C/JS](https://github.com/qwertie/LoycCore/wiki/Loyc-Expression-Syntax#precedence-rules) all are significant obstacles.

Instead of, or in addition to, a C/JS-like format, obvious candidates are s-expressions, because they're pretty great, and/or linear sequences of instructions organized in a stack-machine-like fashion, because they're nice for reasoning about program behavior. Both of these would completely avoid all ambiguity due to operator precedence and syntax sugar and be extremely simple to produce and parse. However, nothing is decided yet.

**Comment by qwertie** [comment]
@sunfishcode I anticipated a response of this flavor. Luckily, since (AFAIK) LES isn't used in major applications yet, there's still time to change it. I've been working on ways of simplifying/eliminating rules about whitespace, and simplifying the precedence rules, which are overly numerous. In my new plan, the rules will allow

    do {
      ...
    }, while (expr);

With a comma to say "hold on! this isn't the end of the statement". (I used `do_while {...}, expr` above simply because `do_while` is the current name of the opcode.)

At the same time I'll drop the need for a semicolon at the end of statements like

    forever {
       ...
    };

See [here](https://github.com/qwertie/LoycCore/issues/3) for complete details. Note: I haven't actually implemented the plan yet - I must of course do some testing to ensure the new rules work as well as I anticipate.

The only significant differences between operator precedence in C/JS and LES concern the operators `>> << & | ^ ->`, but these differences were mainly motivated by my experience in those same languages. In C you often want to write `x & MASK == 0`, but the precedence rules mean the code will behave in an unexpected way—you must write `(x & MASK) == 0` instead. Meanwhile, `->` has a lower precedence than `.` to accommodate functional languages where `->` represents a function type; of course, this is not an issue if our assembler doesn't use the `->` operator.

It's possible to detect operator mixing that may lead to unexpected behavior. I'm open to a compromise, where `x & MASK == 0` emits a warning or error, but I strongly believe K&R's original decision was incorrect and don't think the original precedence should be kept. I don't feel as strongly about `<< >>` - I personally think they should have the same precedence as multiplication and division, but if others feel strongly about the original precedence, I'm open to that.

#### Why LES?

We can, of course, write a special-purpose parser for the text format. But the world is already filled with numerous standards and parsers - isn't it nice to be able to use a generic parser that is suited to many different tasks outside the WebAsm? The only other existing standard that seems appropriate is s-expressions, which are simpler than LES, but also unfamiliar to the majority of the world's programmers (especially the lexing rules e.g. `#xa ≡ 0xa`, `#\$ ≡ '$'`). LES provides instant familiarity to all JS/C/C#/Java programmers, and as I mentioned, I'm working on simplifications to improve learnability and decrease parser complexity (especially with respect to areas that are not already familiar to JS/C/C#/Java programmers).

**Comment by abustin** [comment]
@qwertie I would have proposed LES in another thread. It looks like you're shoehorning this in a thread about documentation. The "intro doc" will be useful once details are fleshed out.

I think the current level of documentation is grokkable given the status of the project.  It would set the wrong expectation to use a syntax that's placeholder. Defining a file format/spec seems low priority given the other fundamental issues open.

@sunfishcode +1 s-expressions seems like a natural choice given the current AST proposal.  Are there any issues in converting IIVM IR (SSA) to a CPS format? Would it be simpler to use a LLVM IR inspired SSA format?

**Comment by qwertie** [comment]
@abustin you're right, I should have created two separate issues instead of one, but I do think of the text format as a medium of communication, and I really don't think an intro document can communicate about WebAsm effectively without one. Note that the proposed document has a clear disclaimer that all described file formats are temporary.

**Comment by sunfishcode** [comment]
@abustin SSA/CPS are semantic attributes rather than just syntactic so that's something of a different topic. But yes, it is pretty easy to convert from WebAssembly to SSA form. WebAssembly's AST form means that one doesn't even need to compute dominantor trees to do so.

@qwertie
> isn't it nice to be able to use a generic parser that is suited to many different tasks outside the WebAsm?

Isn't it nice to use simple solutions for simple tasks, rather than one generic solution that exposes many different tasks to the constraints of all the others? :-)

(And btw, it's spelled "WebAssembly".)

WebAssembly is in an early design phase, so while we'll eventually want the kind of introductory material outlined above, we don't need to rush it.

And, we don't really have any more free attention to spend iterating on LES here. If you want LES to be considered for WebAssembly, please step back, make the changes discussed above, and any others we're likely to want based on the preferences outlined above, and update all the documentation accordingly. When everything is ready, please file a new issue, and we will consider it. I can't make any guarantees about the outcome though. LES is aiming to solve a problem which is not one that WebAssembly necessarily needs to solve.

**Comment by qwertie** [comment]
I redesigned [LES](https://github.com/qwertie/LoycCore/wiki/Loyc-Expression-Syntax) (LESv2), by the way, to address the issues raised by @sunfishcode... and I'm considering a further design change that would allow you to omit the semicolon after a closing brace so that `if foo {...} else {...} return;` would count as two statements rather than one.
