### ISSUE TITLE
Questions about the FAQ re. compilers

### ISSUE THREAD

**Issue by rauschma** [WebAssembly/design#234]
https://github.com/WebAssembly/design/blob/master/FAQ.md#what-compilers-can-i-use-to-build-webassembly-programs

> WebAssembly initially focuses on C/C++, and a new, clean WebAssembly backend is being proposed for upstream clang/LLVM, which can then be used by LLVM-based projects like Emscripten and PNaCl.

The following points are not entirely clear to me:

* I thought Clang was always based on LLVM.
* Emscripten compiles C/C++ to asm.js (or asm.js-like) code. How would it profit from a backend for Clang?
* How would PNaCl profit? Would it compile PNaCl code to LLVM and then to wasm?

**Comment by sunfishcode** [comment]
Clang is [not always](http://www.prweb.com/releases/2013/12/prweb11390430.htm) [used with LLVM](http://blogs.msdn.com/b/vcblog/archive/2015/05/01/bringing-clang-to-windows.aspx) these days.

Emscripten's asm.js backend and PNaCl's backend are not in upstream LLVM. The interesting thing happening here is that the new backend is being developed upstream. Does that answer your questions, or is there something we could further clarify here?

**Comment by rauschma** [comment]
Thanks for the answers! I know the term “upstream”, but don’t understand how it relates to LLVM in this case.

Also: If you can compile C/C++ to wasm via Clang, why do you need Emscripten?

**Comment by sunfishcode** [comment]
Upstream here means in the official LLVM repository. Right now, Emscripten and PNaCl have separate repositories.

Emscripten is more than just a compiler; it's a complete toolchain and SDK for compiling C/C++ code to the Web. The new WebAssembly backend may eventually replace the asm.js backend that Emscripten currently has, but it would still just be one piece of a much larger package of functionality.

**Comment by sunfishcode** [comment]
If you have any further questions, please file a new issue!
