### ISSUE TITLE
Question about features to support JIT

### ISSUE THREAD

**Issue by lskyum** [WebAssembly/design#235]
Will WebAssembly support features that allows VM's to use some kind of JIT? For example to fully support .NET the VM will need to create new versions of methods at runtime, because of the way generics works in .NET. (At least to avoid full AOT compilation that has some limitations.)

I believe this is an essential feature if WebAssembly shall be a good target for many existing languages.

**Comment by jfbastien** [comment]
[Yes](https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#platform-independent-just-in-time-compilation).
