### ISSUE TITLE
MMIX: Should WebAssembly have MOR and MXOR?

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/design#247]
MMIX's MOR and MXOR are described [here](http://mmix.cs.hm.edu/doc/instructions-en.html#Bit_Operations)

These operations essentially interpret an int64 as an 8x8 bit matrix, and allow one to do matrix transformations. These can be used to perform a wide variety of bit rearranging and manipulation operations, including things like byte-swaps and bit-reversals.

I don't view these as essential for the MVP, but they're interesting to think about.

**Comment by abustin** [comment]
Interesting architecture. I'd like do see C examples that leverage these ops,

And unless the hardware has operations that map closely to this, it seems like unnecessary optimization. I'd like to see these ops result in an optimization opportunity in x86/ARM/MIPS.  Do any MMIX implementations exist outside of academia (now and in the future)?

**Comment by sunfishcode** [comment]
This is added to FutureFeatures.md in #347.
