### ISSUE TITLE
Math functions - Instruction or JavaScript Math

### ISSUE THREAD

**Issue by lskyum** [WebAssembly/design#262]
Will math functions like cos, sin, ect. all be included as instructions or will they only be provided through JavaScript's Math object? I see some listed as instructions but not all...

If they are to be called through JavaScript Math, will that introduce overhead or can it just be optimized away? Since Math functions can be overridden it may be hard to optimize?

**Comment by jfbastien** [comment]
Math functions, especially trigonometric ones, will initially be unavailable in WebAssembly, and instead be obtained through libm and shipped with your .wasm binary. Dynamic linking will make this very cheap (just one libm shared by all wasm libraries, across sites).

This allows us to avoid pitfalls in defining precision versus speed tradeoffs that one might make with these functions. This tradeoff is often very application-specific.

An argument was made for better optimization when these aren't simple function calls in WebAssembly, but the discussion is still open on this.
