### ISSUE TITLE
AstSemantics: Add support for inc/dec

### ISSUE THREAD

**Issue by eminemix** [WebAssembly/design#293]
Hello,

Any reason why inc/dec operations are excluded from 32/64-bit Integer operations?

I'd like to add them with the following description:

int32.inc - sign-agnostic increment of the operand by one.
int32.dec - sign-agnostic decrement of the operand by one.

Does that seem reasonable?

**Comment by sunfishcode** [comment]
Inc and dec functionality can be achieved by the pattern of adding or subtracting with a literal 1 operand. While this is a fairly common pattern, the advantages of making a dedicated opcode for it don't seem to be strong; the pattern is already simple, fairly compressible, easy to optimize, and easy to read.

**Comment by jfbastien** [comment]
Agreed with @sunfishcode.
