### ISSUE TITLE
Type segregated local space

### ISSUE THREAD

**Issue by MikeHolman** [WebAssembly/design#309]
This is something I thought we had earlier, but right now the design says:

>The details of index space for local variables and their types will be further clarified, e.g. whether locals with type  int32  and  int64  must be contiguous and separate from others, etc.

I think separate index spaces for different local types is a win all around. It allows for smaller AST encoding in some places (formal parameter lists and local space declarations), and it seems like it would reduce work required for type-checking as well.

**Comment by kg** [comment]
Yes, I believe we should have separate index spaces for locals by type.

**Comment by titzer** [comment]
That means the local type becomes part of the GetLocal/SetLocal bytecodes,
unless I am missing something.

**Comment by kg** [comment]
Was that not the proposed behavior already? I thought everyone wanted explicitly typed opcodes

**Comment by titzer** [comment]
I assume that we'll add many local types in the future, and with user
structs and typed function pointers, there is an unbounded number of local
types.

**Comment by kg** [comment]
Good point.

Does that mean there's an unbounded number of type-specialized opcodes for things like equality-comparing function pointers or reading a user-struct value from memory? That seems problematic. If so, we should probably file a follow-up issue on that...

**Comment by MikeHolman** [comment]
Sounds reasonable.
