### ISSUE TITLE
Bikeshedding: Rename LocalType to ValueType

### ISSUE THREAD

**Issue by rossberg-chromium** [WebAssembly/design#319]
I think LocalType is not the best name, for at least two reasons:

1. A name should reflect its definition, not its _uses_.

2. And it doesn’t even match those uses: e.g. it is used for globals; or for function parameters and results, which aren’t exactly local either.

So, I’d like to propose renaming LocalType to ValueType. That would accurately reflect its meaning as a classifier for the different forms of values that exist in WASM.

**Comment by titzer** [comment]
On Sat, Aug 29, 2015 at 2:18 PM, rossberg-chromium <notifications@github.com
> wrote:

> I think LocalType is not the best name, for at least two reasons:
>
>    1.
>
>    A name should reflect its definition, not its *uses*.
>
> I think the distinction is not the "uses" per se, but the scope. E.g.
memory types are limited to dealing with memory.

>
>    1.
>
>    And it doesn’t even match those uses: e.g. it is used for globals; or
>    for function parameters and results, which aren’t exactly local either.
>
> Well, parameters are local variables, and calls are expressions which get
the result type of the called function, so it seems local enough to me.

Also, globals have memory types. So maybe we should rename "memory type" to
"storage type"...although I fear C has muddied that notion already.

> So, I’d like to propose renaming LocalType to ValueType. That would
> accurately reflect its meaning as a classifier for the different forms of
> values that exist in WASM.
>
Despite "value" normally having a pretty clear meaning in PL speak, the
term "ValueType" doesn't have a similarly clear meaning.

**Comment by lukewagner** [comment]
I agree that "local" is not the right adjective; I think we currently have "local" type simply because, when the name was first chosen it was just the type of locals.

As long as we continue to have the type of expressions match the type of what you can store in locals/globals, "value types" I think has the right connotation, even outside of academic PL (what else do expressions e*valuate* to but a value?).  If we do need a split (e.g., this was one of the multi-return ideas), then it might make sense to further cleave the names ("var type" for locals/globals vs. "value types" for expressions), but I'm thinking that might not happen.

**Comment by rossberg-chromium** [comment]
On 31 August 2015 at 17:51, Luke Wagner <notifications@github.com> wrote:

> I agree that "local" is not the right adjective; I think we currently have
> "local" type simply because, when the name was first chosen it was just the
> type of locals.
>
> As long as we continue to have the type of expressions match the type of
> what you can store in locals/globals, "value types" I think has the right
> connotation, even outside of academic PL (what else do expressions e
> *valuate* to but a value?). If we do need a split (e.g., this was one of
> the multi-return ideas), then it might make sense to further cleave the
> names ("var type" for locals/globals vs. "value types" for expressions),
> but I'm thinking that might not happen.
>

Yes, this suggestion was not about PL practice at all, academic or
otherwise. It seems pretty intuitive to define ValueType = the type of
individual values, and Expr(ession)Type = the result type of expressions.
In a setting with multi-values you would have ExprType = Seq(ValueType),
which seems as obvious as it can get. Without multi-values, you'd have
ExprType = Maybe(ValueType).

**Comment by rossberg-chromium** [comment]
Did we actually resolve this?

**Comment by titzer** [comment]
Not dismissing the issue. I think what's in the spec and what's in the design are fine, no?

**Comment by rossberg-chromium** [comment]
Well, the spec defines value and expression types, it doesn't say "local" anywhere. Do we mind the discrepancy with AstSemantics' terminology?

**Comment by lukewagner** [comment]
Oh, whoops, I was telling @titzer we'd fixed this but I was confusing this with something else.  Yeah, we still say "local types" in AstSemantics.md (as the only subsection of the "Types" section...) and I agree it'd be good to change to "value types".  I'll whip up a PR.

**Comment by lukewagner** [comment]
Arg, I just pushed the [change](https://github.com/WebAssembly/design/commit/19f8871d6efa4f4ce3496fc3683463587fc911fb) to master instead of a remote branch.  I can easily revert, but any disagreement?
