### ISSUE TITLE
Import/export binding by name vs index

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/design#330]
[Modules.md](https://github.com/WebAssembly/design/blob/master/Modules.md) describes exporting as declaring and naming a subset of the functions in a module, and describes an import as a tuple containing module and function names along with a signature. In the spec, exports have string names as well (import is nothing more than a lexer token at this point). However the design says that the interpretation of those names is completely outside the scope of wasm; in other words they have no  meaning to wasm itself.
As another reference point, in asm.js the exports just go out as JS objects which map the names to callables, and the imports are JS objects with particular requirements as well.

I'm wondering if we want to consider whether we should make this named-binding be a first-class part of wasm, or if it should be a function of the FFI. 
This design aspect touches several others:
* It affects what kind of capabilities we need from our specified container format (as opposed to what is built inside of it). In other words, will the container format need to specify symbol tables (see also the discussion in #74)
* It affects what would be required of a non-JS wasm runtime (e.g. one that generated machine code fully AOT).
* It affects how dynamic linking is implemented. In particular, whether the naming/binding mechanism is expressive and/or extensible enough that it can be reused for dynamic linking, or whether some or all of the machinery will have to be in user space. (As a concrete example, as written in Modules.md today, only functions can be exported, whereas dynamic linking will also need a way to import and export address-taken data objects).

For example a minimalist strawman version could have an interface that looks more like a syscall table where the imports and exports are just arrays of functions, and a separate convention would specify their meaning. 

Another point in the space would be to add enough to the wasm system directly to allow dynamic linking (although the meaning of the module names would still have to be determined by the embedder). This would avoid a weird system where we either try to re-use system parts that exist (e.g. for importing functions from DSOs) but have to build other parts in userspace (e.g. objects), or ignore the system parts entirely and just build in userspace.

We could also try to be more explicit about adding some extensibility, since even if we add enough for dynamic linking, users could invent a new use case and be in the same position of partial re-use or full DIY.

See also discussion on https://github.com/WebAssembly/spec/issues/47

**Comment by lukewagner** [comment]
> I'm wondering if we want to consider whether we should make this named-binding be a first-class
> part of wasm, or if it should be a function of the FFI. 

I don't quite understand what specifically you're proposing (or what "FFI" means in this context).

> For example a minimalist strawman version could have an interface that looks more like a syscall 
> table where the imports and exports are just arrays of functions, and a separate convention would 
> specify their meaning. 

How is that different than what's proposed now?  "a separate convention would specify their meaning" sounds a lot like making the meaning of imports/exports host-dependent.  Does [this plan](https://github.com/WebAssembly/spec/issues/47#issuecomment-137542803) help clarify?

> It affects what would be required of a non-JS wasm runtime (e.g. one that generated machine
> code fully AOT).

Since non-JS wasm runtimes define the meaning of imports/exports, they can generate code fully AOT by defining the semantics of importing to be sufficiently static.  This would, e.g., be the case if the wasm runtime only defined builtin imports (which, recall, are basically syscalls) which is what I'd expect for a simple shell-like environment.  I expect having the ability for imports to load separate wasm modules will be somewhat unique to the Web, but even on the Web, we can (demonstrably, see asm.js) do AOT compilation in the presence of dynamic imports; it just means the code for calling imports is a little less specialized to the callee (the signature is known, which is the important thing, but dispatch goes through 1 indirection).

**Comment by dschuff** [comment]
On Fri, Sep 4, 2015 at 6:51 AM Luke Wagner <notifications@github.com> wrote:

> I'm wondering if we want to consider whether we should make this
> named-binding be a first-class
> part of wasm, or if it should be a function of the FFI.
>
> I don't quite understand what specifically you're proposing (or what "FFI"
> means in this context).
>
> For example a minimalist strawman version could have an interface that
> looks more like a syscall
> table where the imports and exports are just arrays of functions, and a
> separate convention would
> specify their meaning.
>
> How is that different than what's proposed now? "a separate convention
> would specify their meaning" sounds a lot like making the meaning of
> imports/exports host-dependent. Does this plan
> <https://github.com/WebAssembly/spec/issues/47#issuecomment-137542803>
> help clarify?
>
It's not so much that the meaning is host-dependent, as that they have
names at all (strings), instead of numbers. Equivalently, you could ask
"will the binary format require a symbol table or its equivalent?"  If the
answer is yes, then the wasm module exports "foo" and "bar" and it's up to
the JS environment to decide what "foo" means. If no, then the exports are
just 0 and 1 and the JS environment knows that when JS code wants to invoke
module.foo, they need index 1. Moving from names to numbers requires the JS
interface to keep more information, but makes the wasm system simpler, even
if a bit less JS-like. (by that I just mean that e.g JS functions are
identified by name, but in formats like ELF, names are optional in linked
executables).


To add some context, this is kind of thing what we did with PNaCl (although
PNaCl modules don't really have exports), and I think PNaCl's simplicity in
some of these related aspects made things much easier for us. So I thought
it was worth at least asking the question.

**Comment by kg** [comment]
I don't think named imports/exports are a good idea. What specific use-case do they address? Is the concern that the symbol table will be too large?

**Comment by lukewagner** [comment]
I think it's important to note that *within* a module, both imports and exports are referenced via index (just like everything else).  The names only exist for external linking.  One use case is being able to write:
```
import foo from "bar.wasm"
```
in JS and have that trivially work for the trivial module
```
// bar.wasm
(module (func (return 42)) (export 0 "foo))
```
More generally, string names are good for avoiding the sorts of ambiguities and fragility that you get with indices.  We've observed and avoided this problem with opcode indices using strings, as described [here](https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#backwards-compatibility).  Naturally modules would have the same problem (You ship module A, people depend on `foo` at index I.  You update A, add/remove some functions, `foo` happens to get different index, and now old code is broken.
