### ISSUE TITLE
Imported global constants

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/design#333]
asm.js supports global constants, and these can be initialized from imported value, but this seems to be lacking in wasm. For example, these can be used to pass in index masks that are based on the chosen linear memory length, and currently v8 and jsc can specialize on these and bake them into optimized code. For Odin these need to be initialized with literals to have them baked in. Without this support the MVP would not be viable for runtime chosen linear memory sizes using index masking.

**Comment by sunfishcode** [comment]
While explicit address masking may have performance advantages for asm.js implementations on some platforms today, WebAssembly is a new platform being designed with long-term goals as well. Since explicit address masking is limited to power-of-two sizes, making it a mandatory part of the platform would be an onerous limitation, and making it an optional part of the platform would mean that implementations have to support multiple addressing modes, which would add complexity to the platform and constrain long-term flexibility.

**Comment by JSStats** [comment]
I have been exploring this path and understand the matter well, and for those that do not know the history this has been a matter of dispute for some time, I had to split the the Emscripten support away from the main code base, and I was excluded from the early wasm development. I believe there is little technical merit in the opposition to this support and that the opposition will damage the wasm project.

The use of index masking is a matter for the application developer to choose. For example, a developer might choose to use this style to take advantage of pointer tagging, using the masking to both strip the tag and ensure the index is within bounds. This is a performance optimization that the developer chooses. This is an application specific optimization that requires some minimal support from wasm. If wasm is to have a good future then I believe it needs to support this code style well.

A wasm implementation that does not have the address space to allocate a 4G+ region and use page protection to avoid inline bounds check will need to use inline bounds checking. Masking an index before use is an easy way to prove to the compiler that the index is within bounds and that the index mask is not needed. I have implemented this on Odin, v8, and jsc, and the performance is competitive - an application developer may well want to use this style for balanced performance. Index masking is also relatively easy to hoist.

Being able to pass in constants, based on the chosen linear memory size is very important for the compiler to be able to optimize away bounds checking. It is important even without the use of index masking. For example, a function may want to compare an index to a constant based on the linear memory size on entry and with the propagation of constraints (such as ABCD style constraints) bounds checks might be optimized away.

Somewhere in the future systems will likely be able to just allocate a large area of address space for each wasm application, in fact some browser could already do this either because they have ample address space or because they can only run a demanding application by going all-in. The resizeable linear memory support will be a historical joke, and compilers will optimize for a fixed length. Wasm should anticipate this so that applications deployed now have a good future, and that the runtime can dictate to them now and in the future that they can not resize the linear memory allowing the runtime to better optimize their performance.

I see 64 bit addressing support being added. The '32-bit indexes in 64-bit address space with memory protection' scheme for avoiding bounds checks does not scale to this, does it? Can we move on now and recognize the importance of the type system and optimizing away bounds check to the future of wasm?

**Comment by qwertie** [comment]
@JSStats Everything you've been saying in recent issues makes a lot of sense to me - which totally doesn't matter 'cause I don't work for Google or Mozilla. Anyway, welcome! Just don't forget that the performance and constraints of _today_ are quite important to these guys. One of those constraints is the need to have numerous wasm modules (whose memory requirements may go up and down) running in a single 32-bit address space - and I wouldn't expect that need to disappear very soon. Any plan has to account for this reality.

**Comment by lukewagner** [comment]
Independent of heap-masking, we have talked about [imports](https://github.com/WebAssembly/design/blob/master/Modules.md#imports-and-exports) allowing both functions and globals to be imported.  The current docs only mention functions, so I filed #337 to mention globals.

**Comment by JSStats** [comment]
This was being considered for https://github.com/WebAssembly/design/issues/331 and https://github.com/WebAssembly/design/issues/334

It would seem adequate to insert the constants into the literal pool and reference them with existing opcodes, so closing. The matter of how they can be inserted can be considered elsewhere.
