### ISSUE TITLE
Tweak: switch to short type names in op names

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/design#356]
One significant remaining divergence between ml-proto and design is that ml-proto uses short type names (`i32` instead of `int32`).  We've agreed that we want opcode names to exactly match AstSemantics.md, so one side needs to change.  I actually like the short names better (shorter and no added ambiguity), so rather than changing ml-proto to match, how about we change design to use the short type names?

**Comment by sunfishcode** [comment]
sgtm

**Comment by jfbastien** [comment]
Agreed.

**Comment by lukewagner** [comment]
Making a new issue for this was probably overkill.  I'll close this issue and we can discuss in #357.
