### ISSUE TITLE
Syntax mismatch between the design and spec's conversion operation

### ISSUE THREAD

**Issue by yurydelendik** [WebAssembly/design#368]
The AstSemantics.md list a conversion operation with "[]" is its attribute vs "/", e.g. [`i32.wrap[i64]`](https://github.com/WebAssembly/design/blob/master/AstSemantics.md#datatype-conversions-truncations-reinterpretations-promotions-and-demotions), but in the spec's repo it is parsed as [`i32.wrap/i64`](https://github.com/WebAssembly/spec/blob/master/ml-proto/src/host/lexer.mll#L211). Is the latter a desired syntax?

**Comment by rossberg-chromium** [comment]
The reason for not using `[]` in the prototype is that the use of brackets
does not suite S-expression syntax, where `(i32.wrap[i64] exp)` would
usually be parsed as `(i32.wrap (i64) exp)`, while the `i64` is really
meant to be part of the opcode tag. Even though we do not currently allow
square brackets in the prototype at all, it seems ill-advised to be
incompatible with common convention.

The `/` in the prototype was a temporary choice. We could use something
else, e.g. `_`. In any case, I agree we should make design and proto sync
up.

**Comment by sunfishcode** [comment]
This was fixed in ae2a1179a13197d819c7f68ec8477c0070a35a59, which changed the design documents to use `/`.
