### ISSUE TITLE
A binary opcode table will block streaming.

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/design#369]
There has been discussion of having an opcode table at the start of the wasm binary, and perhaps per-module. However this approach will block streaming of the wasm binary where a presently unused opcode is inserted in the pipeline. Perhaps there needs to be a way to introduce a new opcode use inline.

**Comment by kg** [comment]
I don't understand how having a table would block streaming.

**Comment by ncbray** [comment]
It would block streaming generation of the binary.  (This is a slightly different definition of streaming than usual.)   You'd need to do a global pass to determine what opcodes were used before you could generate function bodies.  A scenario where a server compiles a binary on the fly is a little far fetched at this point, but I think the unspoken motivation is linking speed.  (?)  A naive model of linking is that the compiler would loops though all the object files collecting what ops are used, and then "stream" the object files together while rewriting the op numbers.  However, there's no requirement that the opcode table be minimal, so a compiler could simply declare all the opcodes it could possibly use upfront and live with the inefficiency.  The impact of "pruned" and "unpruned" op tables TBD with tests, I suspect.

**Comment by JSStats** [comment]
@kg Given that transforms could be placed in the pipeline. One solution would be to allow  an opcode to be defined inline when it it first used, or another solution could be to allow the transform to amend the table at the start adding an opcodes that it might insert.

@ncbray It would be good to support pipelined transforms on the client side. E.g. Macro alternatives.

**Comment by JSStats** [comment]
Actually it would probably be adequate for the transform to amend the output table as it streams it through. Thank you for the feedback.
