### ISSUE TITLE
Consider removing the optional maximum memory size

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#372]
See discussion in #370: we believe that developers giving us an optional maximum memory size may allow engines to optimize things, potentially being more intelligent about bounds checks and reducing virtual memory fragmentation.

@sunfishcode is concerned that this is difficult for some developers to evaluate, and we'd be forcing them to guess at a limit that may be incorrect if they want the best performance.

Revisit this as we get closer to MVP.

**Comment by lukewagner** [comment]
Resolved by #431.
