### ISSUE TITLE
Specify resize_memory to not be able to shink below the minimum memory.

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/design#385]
It does not appear to be specified that `resize_memory` can not shrink the linear memory below the modules defined minimum. Odin makes good use of a known minimum and so could other wasm compilers. It can help avoid bounds checks for access to locations below the minimum, and some of these are expected to be hot such as locations of global variables.

**Comment by lukewagner** [comment]
This sounds fine to me.  Technically what we have now is `initial`; I'd be inclined to have a separate `min` (with `min` defaulting to `initial`, just like `max`).

**Comment by AndrewScheidecker** [comment]
Does this need an explicit minimum? It seems like a runtime that wants to implement this optimization can always reserve some minimum address-space (probably derived from the module initial memory size), and then rely on page faults to catch out-of-bounds accesses below that size.

**Comment by lukewagner** [comment]
@AndrewScheidecker Depending on impl, that could require extra bookkeeping metadata and code paths for constant-offset accesses that otherwise couldn't possibly fail.

**Comment by JSStats** [comment]
@AndrewScheidecker Yes, but if the implementation needs to keep this area of VM reserved anyway then resizing below the minimum does not free up any VM, so there seems little practical difference to using `dont_need`. Some implementations will choose inline bounds checks and it will help these to have a guaranteed minimum. If an application really wants to be able to shrink the memory below the initial size then a separate `minimum` and `initial` size seems to handle this case.

**Comment by jfbastien** [comment]
At some point we had discussed making `resize_memory` return the value that the memory was actually resized to. This allows implementations to overallocate when it makes sense for them, and would also allow them to do what you describe (enforce a sensible minimum).

Could we instead do this?

**Comment by lukewagner** [comment]
@jfbastien There was not agreement on whether to allow that nondeterminism in `resize_memory`.

**Comment by jfbastien** [comment]
@lukewagner indeed, but this seems like a great reason to revisit. :-)

**Comment by JSStats** [comment]
@jfbastien Yes that would seem to be fine to. So the code could ask `resize_memory` to shrink the memory and `resize_memory` could return the new size with zero difference rather than failing.

**Comment by lukewagner** [comment]
@jfbastien As we've agreed in so many other cases, nondeterminism has to be *justified* by some significant improvement over what you can do deterministically and there seems to be no strong new reason here.

**Comment by flagxor** [comment]
It seems like having an implicit contract with the code generator and the wasm implementation over magical sizes that result in better performance is undesireable.

Not sure that having variable results from resize_memory (which already has system dependent behavior in terms of exhaustion), is particularly introducing significant non-determinism.

If we're going to have performance behavior where the code generator will pick certain values to bake in, it seems like specing the properties of what values will "guarentee" improved performance would be desirable.

**Comment by lukewagner** [comment]
> It seems like having an implicit contract with the code generator and the wasm implementation over 
> magical sizes that result in better performance is undesireable.

There is an [explicit requirement](https://github.com/WebAssembly/design/blob/master/AstSemantics.md#resizing) that arguments to `resize_memory` must be a multiple of `page_size` which is host-defined.  This should be sufficient for VMs to behave predictably well without introducing unbounded "the VM can resize to anything, or not resize at all".

**Comment by JSStats** [comment]
The issue of the behaviour of `resize_memory` on a request to shink below the minimum seems within the scope of this issue too. Will `resize_memory` just ignore the request, or throw? How will it handle other error cases, a such as non-page-sized offsets, or an OOM?

**Comment by lukewagner** [comment]
`resize_memory` is specified to [trap](https://github.com/WebAssembly/design/blob/master/AstSemantics.md#traps) when not a multiple of `page_size`, so it would make sense to have it do likewise when resizing below `min` or above `max`.

**Comment by jfbastien** [comment]
@flagxor's point wasn't w.r.t. `page_size`, that's not a magical number that's agreed upon implicitly.

He's referring to the min size startup parameter, which is magical in that choosing a "wrong" value will prevent a VM from pulling clever tricks, but choosing a "good" value allows a VM to optimize better.

That does suggest another solution: add a `minimum_memory` call, similar to `page_size` but is a per-instance value (still a per-instance constant). If you `resize_memory` below that then you get `minimum_memory` with the "slack" zeroed out. That allows the VM to bake a "nice" value into the code it generates, knowing it'll never go below that.

It avoids awkward questions such as:
* What if min size was zero?
* What if the resize start running into the `NO_ACCESS` pages near zero?

**Comment by lukewagner** [comment]
@jfbastien It seems like that could cause wildly divergent `minimum_memory` values which would lead to portability issues, with some engines not caring and choosing `0` and others picking "the highest constant that could be useful".

Another case to consider is constant accesses in dynamically-linked modules.  While you can imagine a scheme where some modules (esp. load-time-linked) can stick their data in low memory below `min` (by coordinating with the main module a priori), this won't work in the general case and so we'd have fallible constant heap accesses in the general case.

I was remembering, though, that due to normal heap fragmentation, no ordinary apps will use `resize_memory` to shrink in practice (rather, the malloc impl would release pages from the working set via `dont_need`/`discard`).  So what if we disallowed shrinking, at least in the MVP?  If we did find a compelling use case for shrinking, we could require some opt-in that avoided deoptimization.

**Comment by jfbastien** [comment]
Punt to post-MVP sgtm.

**Comment by flagxor** [comment]
Punting shrinking sounds good.

**Comment by titzer** [comment]
sgtm too.

**Comment by sunfishcode** [comment]
With #389 merged, the address space can now only grow, rather than shrink.
