### ISSUE TITLE
Order of evaluation for child nodes is not specified.

### ISSUE THREAD

**Issue by Teemperor** [WebAssembly/design#399]
It seems the spec is missing how child nodes are evaluation. Problems that could arise through that are:

1 . Child nodes with side effects would make the program behave differently on different platforms like in:

    (set_local $x (i32.const 8))
    (int32.div (get_local $x) (set_local $x (i32.const 4))

div could either return 1 or 0 in this case.

2 . Unnecessary locals to clarify the order of evaluation. Example from above with clear order but unnecessary locals:

    (set_local $x (i32.const 8))
    (set_local $right (set_local $x (i32.const 4))
    (int32.div (get_local $x) (get_local $right)

**Comment by AndrewScheidecker** [comment]
I thought I saw it define evaluation to occur in lexical order somewhere, but I can't find the reference now. Maybe it got lost in the shuffle?

**Comment by pjuftring** [comment]
[TestingTodo](https://github.com/WebAssembly/spec/blob/master/ml-proto/TestingTodo.md) says, that operands have to be evaluated from left to right.

**Comment by jcbeyler** [comment]
Tests for this already exist by the way:
https://github.com/WebAssembly/spec/pull/119

Not saying this should not be stated :); just saying we have tests for it now

**Comment by lukewagner** [comment]
The intention is indeed for evaluation order to be [deterministic](https://github.com/WebAssembly/design/blob/master/Nondeterminism.md), in the order defined by the [spec](https://github.com/WebAssembly/spec/blob/master/ml-proto/spec/eval.ml#L211).  I agree it would be good to note this explicitly in AstSemantics.md, though.

**Comment by lukewagner** [comment]
Merged #401.
