### ISSUE TITLE
"opcode" or "operation"?

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#406]
#405 leads me to want to standardize between one of "opcode" or "operation".

Preferences? Other suggestions? "bikeshed"?

**Comment by JSStats** [comment]
Opcode is short for 'operation code'. If the code (a number) is not being discussed then use 'operation'?

**Comment by rossberg-chromium** [comment]
Agree with @JSStats that 'opcode' only makes sense when talking about an encoding.

However, I think the right substitute is 'operator', whereas 'operation' is the application of such an operator to actual arguments (and its execution).

**Comment by lukewagner** [comment]
"operators" sgtm

**Comment by titzer** [comment]
operator

**Comment by jfbastien** [comment]
There was no PR addressing this issue.

**Comment by titzer** [comment]
Thanks.

**Comment by jfbastien** [comment]
Actually I only addressed half of this: we also use "operation" inconsistently with what @rossberg-chromium was suggestion. Re-opening, I'll send a PR to fix this soon (it's not hard, but isn't mechanical either so I need to pay attention and can't just do this as a tiny interrupt).

Sorry about that!

**Comment by titzer** [comment]
Created https://github.com/WebAssembly/design/pull/426/ to address the rest.

**Comment by jfbastien** [comment]
Thanks for doing the grunge work! :-)
