### ISSUE TITLE
Caching input to the final wasm raw stage.

### ISSUE THREAD

**Issue by ghost** [WebAssembly/design#419]
Discussions in https://github.com/WebAssembly/design/pull/412 raise the problem of caching the compiled code based on the wasm source input (the input to the upper layers). It would seem unfortunate to have to spec all the upper layers in order to allow the runtime to cache compiled code effectively - this would prolong the spec process and limit the flexibility of wasm.

It might be possible to leave the choice to use a particular cached version of raw wasm up to the user defined upper layers - they would have generated the raw input before anyway so could do so again so it does not seem a runtime safety matter if the user defined code has an error in its choice.

The runtime could keep an optional store of its lower layer raw input and compiled code for this, and return a unique key to the upper layer that could offered back to the runtime to request the same raw input again. If the runtime does not implement this store or there is a cache miss then the upper layers need only then re-generate the source input.

This means that `has_feature` could just be a regular runtime operation available to the upper layer user code to do as it wishes with when generating the raw wasm input, and would not need to be noted by the runtime itself. Any upper layers using `has_feature` would be responsible for re-checking features when re-using a cache reference  - they might need some store for this purpose.

Perhaps this would add some lower layer cache support at the raw wasm runtime layer, and a store for the upper layers, that would be far simpler to spec and more generally useful than having to spec the upper layers just to have an efficient cache.

Might there even be a way to have the polyfill implement this too? Can it store its asm.js output somewhere and load from there so that the JS compiler can cache its compilation without regeneration the source?

**Comment by jfbastien** [comment]
I'm not sure I understand the layer at which you want a discussion. Would serviceworker cache work for your concerns? Or is this not web-specific?

**Comment by JSStats** [comment]
It would have implications for all layers. The caching would be done at the lower layer, the code that the implementation natively reads and compiles, and that the implementation could cache. For the polyfill this would be the asm.js source. For v8-native this would be your bytecode. For a native wasm it would the 'raw' wasm.

For example, could you have WASM.instantiateModule return a key (or call a callback) when it caches the compiled code for a given input byte code buffer, and then if the caller want to request the same compiled code could it call WASM.instantiateModule (or another related function) with this key and only on a cache miss would then need to regenerate the byte code buffer. This is obviously not wasm, but gives an example of what might be developed into a solution to this challenge.

It would demand that the caller (upper layer user code) and callee (implementation compiler) have consistent results and expectations for `has_feature` and any other inputs that the compiler depends on. This might not be too demanding a restrictions to spec.

The service work cache does not seem suitable on a quick look, but I really don't know that area well and I am not suggesting a particular cache implement here, just that this might be a path forward.

I'm note sure if Odin can avoid re-loading/re-generating the asm.js source at present, but it does have a compilation cache.
