### ISSUE TITLE
generating traps

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/design#430]
Hello, can you generate a trap on purpose? How would use  represent something a c++ `throw`  in wasm?

**Comment by kripken** [comment]
I suppose you could execute a command you know will trap, like reading from an invalid memory location.

But if you want something like a c++ throw which can be caught, you would need to do something else. One option is to call out to an external JS function that does a throw (and other external JS could catch that). In the longer-term, it is a planned to add exception handling to wasm.
