### ISSUE TITLE
Is there any formal file extension for WebAssembly?

### ISSUE THREAD

**Issue by jasonwilliams200OK** [WebAssembly/design#436]
If there isn't any, it would be nice to have one for text representation of language, such as, `.wasm` or `.webasm` to filter code files for (future?) disassemblers etc.

Why is it even relevant?

Extensions give unique personality to technology. If this is not standardized from the beginning, then everyone (especially the book authors) will start coining their own extensions and we may end up with disparities like `.asm`, `.s`, `.S`, `.a` for Intel/AMD assembly code files and `.cpp`, `.cxx`, `cc`, `.h`, `.hpp`, `.hxx` for C++ sources and headers.

**Comment by jfbastien** [comment]
We've been using .wasm for the binary format, .wast for the textual representation, and .wack for LLVM's assembly output. See:
* https://github.com/WebAssembly/spec/
* https://github.com/WebAssembly/wasm-e2e/

**Comment by sunfishcode** [comment]
LLVM's assembly-syntax output should really use .s, as is used for every other target in LLVM.

Also, we should keep in mind that .wast isn't the *official* textual representation. It's a special file format designed specifically for writing conformance tests, so it has special features like S-expression syntax, multiple modules per file, and a custom script command language.

**Comment by lukewagner** [comment]
Agreed on `.wasm` for binary format and `.wast` as being a temporary unit test file.  For the real text format, a long time ago, we threw around the idea of `.was` (which has nice associations with `.as` or `.s` files and looks nice next to `.wasm`).
