### ISSUE TITLE
Load units

### ISSUE THREAD

**Issue by kripken** [WebAssembly/design#447]
`i32.load8_s align=1` means "load 8 bits, with 1-byte alignment". Perhaps this could be simpler if the same units were used? That is, either

 * `i32.load8_s align=8` (meaning bits in both cases), or
 * `i32.load1_s align=1` (meaning bytes in both cases)

? I like the second.

**Comment by rossberg-chromium** [comment]
The second now has a unit inconsistency between the target size (32 bit) and the source size (1 byte), which I think is even worse.

**Comment by kripken** [comment]
Good point, I am so used to reading `i32.*` now that my mind ignores it ;) Then it looks like the only consistent option is 1, that is, `i32.load8_s align=8`.

**Comment by MikeHolman** [comment]
Agreed. Consistently using bit makes sense instead

**Comment by MikeHolman** [comment]
Oops didn't mean to close

**Comment by sunfishcode** [comment]
The address operand remains in units of bytes though, so inconsistency is unavoidable.

The align field's semantics concern only the address operand, so it's most naturally expressed in the same units as the address operand.

**Comment by rossberg-chromium** [comment]
I agree. What we currently have still seems like the least inconsistent: units related to operand sizes in bits, units related to addresses in bytes. The only real way to make it more consistent would be to rename the types to i4/i8/f4/f8, but that would be breaking with standard practice too much.

**Comment by kripken** [comment]
Good points, I'm convinced.

**Comment by sunfishcode** [comment]
To pedantically correct my earlier comment, the align field also relates to the size of the access, because we define a "natural" alignment concept. However, sizes already need to be converted from bits to bytes for the memory semantics, so I think it's still natural to consider alignments to be most naturally expressed in units of bytes.
