### ISSUE TITLE
Explicit trap operations

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/design#448]
Should we add an explicit `trap` operation?

The semantics could be that if executed, `trap` would raise a trap similarly to bounds check failure or divide by zero. For the purposes of type-checking, it would be allowed in any context.

This could be used anywhere that a producer such as LLVM would have its own `unreachable`/`notreached`-style IR construct. For example, for code which calls a no-return function such as `exit()` could result in a function body such as
```
(import $exit "" "exit" (param i32))
(func $foo (param i32) (param i32) (result i32)
 (if (i32.eq (get_local 0) (i32.const 0)
  (get_local 1)
  (call_import $exit (get_local 1))
 )
)
```
This fails the type check because the `call_import` expression has the wrong type. To fix this today the producer would have to materialize a bogus return value just to make the type check pass, even if it knew that exit could never return. This could be required for any expression. Using an explicit trap for this purpose would have well-defined explicit and easy-to-implement semantics, would probably have a smaller encoding than a bogus expression value, and could allow some optimization opportunities for the wasm engine.

**Comment by JSStats** [comment]
This seems a good idea. I have the following in mind `(trap_if (i32.le_u (get_local <n>) <const addr limit>))` to assert that local `<n>` is within a known range to support bounds check elimination. Also to allow an application to assert internal safe limits. This is not necessary here, but might be lighter and more efficient than other patterns.

**Comment by JSStats** [comment]
Another case for a trap noted recently is explicitly checking that a function pointer refers to a function with the expected signature. This is in support of the producer being able to identify function indexes from separate homogeneous tables (a requirement in some C code). For example, the top bits of a function pointer encode the signature.

`(trap_if (i32.neq (i32.and <fp-tagged> 0xf0000000) 0x50000000))
(call-indirect <homogeneous-fn-table> (i32.and <fp-tagged> 0x0fffffff) ...)

**Comment by jfbastien** [comment]
+1

**Comment by AndrewScheidecker** [comment]
I think it makes sense to have an `unreachable` operation in the MVP. But maybe we want to have user trap handlers that can resume execution, so `trap` doesn't seem specific enough.

`trap` also makes sense, but IMO it shouldn't be added until there's a story for user trap handling, so it can have useful parameters. It should be more like POSIX `raise` or Windows `RaiseException` than LLVM's `trap`.

**Comment by jfbastien** [comment]
Trap handling should be in future features (complimentary to signal handling). It may not be clear (we should clarify if not) but the way we've specified "trap" was to avoid specifying what it does, so for MVP it aborts execution, but later we can do different things for different trap mechanisms.

**Comment by AndrewScheidecker** [comment]
Yeah, I was referring to the future signal handling feature. My point is that if this `trap` operation can be handled and resumed from (as I assume it could be once signal handling is added), then it's not useful as an operation that never returns, so you need a more specialized operation: e.g. `unreachable`.

**Comment by dschuff** [comment]
Yeah I think we should make it clear in the design that this particular trap is not intended to be handleable, even when other signals/traps/exceptions may be. I debated calling it `trap` vs something like `unreachable` (which is what LLVM uses). `trap` has the advantage that the name reflects what actually happens if it gets executed, but `unreachable` reflects the intent better (and as we've seen from the discussion, it is actually significant that "unreachable" is the desired effect and that execution can't continue). I'd be happy either way.

`trap_if` is an interesting idea and sounds like it might be useful; for this use case, something like `(trap_if (i32.const 1))` could be used for unreachable, although it would require just a bit more of a consumer that wanted to optimize it.

**Comment by lukewagner** [comment]
Unconditional `unreachable` sounds good to me.  I think it would be useful for polyfilling, rather than having to mock up something equivalent that will take more bytes and might not be as optimizable.

**Comment by rossberg-chromium** [comment]
It's also relevant for typing. An `unreachable` would have polymorphic type, which might be crucial to allow it in certain positions. Currently, the only way to emulate that would be a trapping operation nested into a redundant infinite loop, I think.

**Comment by dschuff** [comment]
Created PR #454
