### ISSUE TITLE
AUTHORS, CONTRIBUTORS

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/design#458]
Some repositories in the WebAssembly organization have AUTHORS files, such as the spec and wasm-e2e repositories. Of particular note is the spec AUTHORS file, which doesn't currently represent many of the people who have contributed significant amounts of code. Should it? Do we need AUTHORS files?

The wasm-e2e repository additionally has a CONTRIBUTORS file, which describes that people must agree to a Google-specific agreement before contributing patches. This isn't mentioned in the repository's Contributing.md file, and doesn't have a clear purpose. Contributors to all WebAssembly projects must agree to the W3C Community Group agreements, which is sufficient for all other important repositories in the organization. Is this insufficient for some purposes?

**Comment by binji** [comment]
@ncbray suggested that AUTHORS is for copyright ownership, and CONTRIBUTORS is more like a list of patch authors. It probably should not include anything about the Google CLA however.

**Comment by JSStats** [comment]
For contributions made under the W3C CLA to the Specification it appears that only an attribution to the Specification is necessary, so there appears to be no need to list authors and so there should be not AUTHORS file.

The supporting code is not really part of a Specification so the CLA probably does not apply anyway, so I would just follow usual copyright practices, and would not demand contributors even accept the CLA except for contributions to the Specification. Importantly the Specification seems poorly define at present, and perhaps the W3C have a template that could be used to make it start looking like it should.

Perhaps someone should get some legal eyes on this to get it organized properly. It might be mixing work together that should be separate. Some thought might need to be given to the Essential Claims which might not be so trivial given the performance objectives of wasm. I think performance is essential, and so any implementation details need to be spelled out in the Specification to avoid performance critical claims being disputed in future.

This clause might be a catch: 'Contribution will be null and void, and I will not incur any obligation as a result of it, if that Contribution is not included in the Specification within 150 days of the date of that Contribution.' So perhaps there should be a note not to merge anything more than 150 days old!

**Comment by ncbray** [comment]
What's in those files is copied boilerplate and not intended to be permanent.  There were only CONTRIBUTORS to that repo from Google when I added it, so it was close enough until we got more contributors.  I suspect that each and every repo will need to specify copyright ownership and how contributions are handled, even if the terms are the same for every repo.  What are those terms?  We should now figure it out by asking a lawyer (dannyb?), rather than speculating.  Copyright law is tricky.

**Comment by sunfishcode** [comment]
Additional related questions:
 - Some, and not all, of the source files in the spec repo bear their own copyright notice; what is the policy regarding copyright notices in source files?
 - These notices have the form "(c) 2015 <name of individual>" with no mention of licensing or commitment of rights; is this appropriate?
 - These notices name an individual by name as the copyright holder, however this individual seems to be doing this work on behalf of an employer; is this appropriate?

**Comment by rossberg-chromium** [comment]
No, these should all be removed. I simply forgot about it when I moved over the repo.

**Comment by jfbastien** [comment]
I sent a ping to Scott, our go-to lawyer.

IIRC we should just have the Apache 2.0 license in a top-level LICENSE file, and then follow its instructions on claiming copyright (from the appendix).

I don't think we should have AUTHORS / CONTRIBUTORS files.

**Comment by sunfishcode** [comment]
The spec AUTHORS file and the spec copyright notices have now been resolved to the satisfaction of this particular issue. That leaves the wasm-e2e issues.

**Comment by jfbastien** [comment]
This now seems consistent. Closing.
