### ISSUE TITLE
Select not well defined?

### ISSUE THREAD

**Issue by jcbeyler** [WebAssembly/design#465]
The definition of the select operator in the design document is:
select: a ternary operator with a boolean (i32) condition and two additional operands, which must have the same type as each other. select returns the the first of these two operands if the condition operand is non-zero, or the second otherwise.

However, the spec assumes both sides will be executed before the test when I read:
  ;; Check that both sides of the select are evaluated
  (func $select_trap_l (param $cond i32) (result i32)
   (i32.select (get_local $cond) (unreachable) (i32.const 0)))
  (func $select_trap_r (param $cond i32) (result i32)
   (i32.select (get_local $cond) (i32.const 0) (unreachable)))

After talking to Mitch Bodart, he said this is the normal behavior but should we not better defined the design document to at least make this explicit or is this just assumed?

**Comment by rossberg-chromium** [comment]
That is absolutely intended, since it is the only thing that makes select different from `if_else`.

**Comment by jcbeyler** [comment]
Should we not then update the design description? Want me to make a PR to at least explicit it?

**Comment by jfbastien** [comment]
Agreed that a PR clarifying this in the design would be helpful.

**Comment by jcbeyler** [comment]
Done here: https://github.com/WebAssembly/design/pull/469

**Comment by sunfishcode** [comment]
This is done.
