### ISSUE TITLE
Arithmetic with carry and overflow

### ISSUE THREAD

**Issue by fmccabe** [WebAssembly/design#466]
The integer arithmetic operators add.* and sub.* should have 'carry' versions: add with carry and sub with borrow. In addition, the mul.* and div.* operators should generate some form of overflow signal.

This permits arbitrary precision arithmetic as well as just being safer - with no automatic overflow of integer operations.

**Comment by JSStats** [comment]
Good point, what happened to the 32x32=>64 multiplication operations, and the add/sub with carry, etc?

**Comment by sunfishcode** [comment]
This is currently [in FutureFeatures.md](https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#integer-overflow-detection).

**Comment by sunfishcode** [comment]
Closing, as this is already listed in FutureFeatures.
