### ISSUE TITLE
What's the plan for ffi support in WebAssembly?

### ISSUE THREAD

**Issue by lygstate** [WebAssembly/design#472]
Cause sometimes, we need to access native OS level functions, (Linux/Windows/MacOS)
And that's can not be sandboxed, for example, running WebAssembly in Server application.

**Comment by jfbastien** [comment]
Right now the entire API surface is left pretty open: whatever the embedder specifies. It looks like an import (i.e. used as a function call) but beyond that we've punted API specifications until later.

Does that make sense, or did you have a specific example in mind?

**Comment by lygstate** [comment]
@jfbastien We already have reference implementation, such as node-ffi & mozilla's js-ctypes.
We could use these as reference implementation.

**Comment by sunfishcode** [comment]
Closing, as the question here has an answer. Please re-open if you wish further clarifications, or file a new issue for new questions.

**Comment by lygstate** [comment]
@jfbastien, For example, calling Vulkan API from WebAssembly

**Comment by jfbastien** [comment]
Please see the WebGPU notes from this November's TPAC meeting. They discussed this with the WebAssembly group, specifically the host bindings proposal.

**Comment by brandonros** [comment]
I think this is worth reopening because the progress with WASI has only covered a subset of the actual functionality required to interact with the host operating system. dlopen / dysym functionality/interfaces are still not outlined clearly from what I can tell.

**Comment by sbc100** [comment]
Its the equivalent of FFI in the WebAssembly world WebAssembly interface types: https://hacks.mozilla.org/2019/08/webassembly-interface-types/
