### ISSUE TITLE
Specify how invalid modules are handled

### ISSUE THREAD

**Issue by Teemperor** [WebAssembly/design#473]
It seems the design document leaves it up to the implementation what will happen with an invalid wasm module (that is known to be invalid after parsing it).

Examples for such implementation-defined situations are:
- AST pieces that are violating the type system such as: `i32.abs (f32.const 1.0)`
- `br` to a label in a non-enclosing construct.

Implementations could handle those case in many different and incompatible ways (error during parsing, error when entering the specified function, error when executing the malformed instructing), so it would be beneficial for the future wasm ecosystem if we specify a common behavior for such situations.

The spec testsuite is already providing a few checks <sup>[1](https://github.com/WebAssembly/spec/blob/55bff0afc5b79b8fcb5372e8ede045a674692fb3/ml-proto/test/labels.wast#L100)</sup> against those cases that are expected to be compile time errors.

**Comment by kg** [comment]
Without precisely specifying this it will also be impossible to do robust polyfill fallback.

**Comment by jfbastien** [comment]
Agreed that we need to specify this.

We had similar discussions when discussion feature detection, especially when considering new types and opcodes such as SIMD. I don't think we had achieved any consensus though. There are a few issues about this IIRC, I think it would be worth going back and summarizing the tradeoffs.

**Comment by lukewagner** [comment]
I think the best the spec can do is to say *when* there is an error and leave it up to the host environment for how to interpreter errors.  For the Web, for `WASM.eval`/`instantiateModule`, the obvious thing would be for an exception to be reported to the JS caller.  For `<script type='module'>`, it seems like we'd do the symmetric thing as ES6 module syntax errors (e.g., there's an `onerror` callback on each script).

**Comment by rossberg-chromium** [comment]
@Teemperor, the implicit assumption is that validation is performed atomically for the entire module, not for individual functions. But I agree it might be worth stating that more explicitly.

**Comment by jfbastien** [comment]
While clarifying, I think it would be useful to discuss developer-side solutions for this, e.g. when wasm supports dynamic linking or JIT code generation it'll be easier to feature detect and do the right thing.

**Comment by jfbastien** [comment]
This is done.
