### ISSUE TITLE
When the first public release is planing?

### ISSUE THREAD

**Issue by bubnenkoff** [WebAssembly/design#476]
I have seen mentions that first public release of WASM is planing at begin of 2016, but is there any roadmaps?

**Comment by jfbastien** [comment]
There currently isn't a roadmap. MVP will be called "ready to try out" at some point, presumably be available behind a flag on multiple browsers, and then we'll move everything to an official standards body. It would be released as usable when the standards process is done, and we hope all browsers are ready to ship by then.

So, no official target for now.
