### ISSUE TITLE
Default NaN bit pattern requirement not compatible with x86

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/design#477]
wasm currently requires that when the platform has to produce a new NaN value, the sign bit is 0. @AndrewScheidecker pointed out that x86 sets the sign bit to 1. Other platforms, such as ARM, do use 0 though. It will likely be necessary to make wasm's sign bit be nondeterministic. I believe this is still compatible with NaN boxing techniques.

**Comment by jcbeyler** [comment]
Are there tests done now in the spec implementation to ensure this by any chance?

**Comment by AndrewScheidecker** [comment]
The tests in nan_propagation.wast cover this.

**Comment by jcbeyler** [comment]
Interesting because I did nothing special in this regard and yet I pass that test file. I'll have to go check if it is valid then and do I take this into account :)

**Comment by jcbeyler** [comment]
This can be closed now since it merged no?
