### ISSUE TITLE
Getting Started with WebAssembly

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#478]
In a discussion today we were talking about #471 and it seems like a complimentary PR would also add a GettingStarted.md document, or make webassembly.github.io the place where that content goes.

The idea would be to guide people through the slight mess that is https://github.com/WebAssembly and help them figure out what's going on where. We're separately working on buildbots (e.g. @flagxor's [LLVM bot](https://build.chromium.org/p/client.wasm.llvm/console)) and are discussing a dashboard.

Thoughts on where this should live, and what it should contain? I can sign up to do some of this, @s3ththompson also expressed interest.

**Comment by lukewagner** [comment]
Putting the intro/getting-started/dashboard on webassembly.github.io sounds like a great idea to me.

**Comment by s3ththompson** [comment]
:+1: I'll try to take a stab at this this week, but @jfbastien and others feel free to pitch in if you get to it first

**Comment by sunfishcode** [comment]
This has landed, and [webassembly.github.io](https://webassembly.github.io/) now points to it! Please file new issues for work on additional documentation.
