### ISSUE TITLE
Elaborate on JIT, code unloading, fragmentation

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#49]
Opening a bug to write down concrete wording from discussion in:
https://github.com/WebAssembly/spec/pull/32

**Comment by sunfishcode** [comment]
I believe the intend link is to #32.

Clearing the "bug" label (but leaving this issue open of course) since this is about ideas described in FutureFeatures.md not being fully fleshed out, which is not unexpected in FutureFeatures.md.

**Comment by sunfishcode** [comment]
This was fixed in #125.
