### ISSUE TITLE
Code verification

### ISSUE THREAD

**Issue by fmccabe** [WebAssembly/design#492]
# This is a plea for code verification 

Given that WebAsm programs will be executing in 'hostile' environments, I believe that there is a strong case to be case for requiring that implementations of WebAssembly be able to formally verify certain safety aspects of programs.

My suggestion would be to use something inspired by JVM's code verifier or .Net's use of proof carrying code as inspiration to ensure the following:

1. No WebAssembly program attempts to overwrite areas of memory that do not belong to it
2. No program attempts to 're-interpret' data as executable code

There are many other potential security questions to ponder; but these are the most fundamental.

I understand that this is a non-trivial request. I also understand that it interposes an additional step in the decoding process. 

Browser vendors have an interest in ensuring that only 'safe' programs are allowed to execute. Furthermore, 'done carefully', there is no reason why this cannot be done efficiently.

There *are* implications for the machine though. Mostly these refer to meta-data aspects:

1. All functions/variables need a 'correct' type
2. The binary encoding needs to maintain this information
3. Functions need meta-data about expected memory utilization

It may also be that not all C/C++ programs would be suitable sources for WebAssembly; and it also likely requires some non-trivial extensions to compilers.

**Comment by rossberg-chromium** [comment]
I'm confused. All this is already the case, AFAICS.

**Comment by jfbastien** [comment]
This would be met by the task in #205. This is our intent, we simply haven't explained it very well.
