### ISSUE TITLE
Grammar Syntax

### ISSUE THREAD

**Issue by jbondc** [WebAssembly/design#493]
I'm working on a grammar syntax parser (will support EBNF, BNF or ABNF too) and trying to come up with the ```wast.dbnf``` syntax.

Here's a shortened sample so far:
```
// terminating characters (ascii)
space = " " | "\t" ;
digit = "0" ... "9" ;
sign = ("+" | "-")? ;
letter = "a" ... "z" | "A" ... "Z" ;
base16 = digit | "a" ... "f" | "A" ... "F" ;
symbol = "+" | "-" | "*" | "/" | "\" | "^" | "~" | "=" | 
         "<" | ">" | "!" | "?" | "@" | "#" | "$" | "%" | 
         "&" | "|" |":" | "`" | "." ;
tick = "'" ;
escape = "n" | "t" | "\" | "'" | '"' ;

control = "\x00" ... "\x1f" | "\x7f" ;
character_exclude = control | "'" | "\" ;
character = ascii - character_exclude | "\" . escape | "\" . base16 . base16 ;

// exclusion out of ascii character set?
// let character =  [^'"''\\'] | '\\'escape | '\\'hexdigit hexdigit

// terminating expressions
digits = digit+ ;
hexdigits = base16+ ;
hex = "0x" . hexdigits;

int = sign . (digits | hex);
float = number . "." . digits
  | number . ("." . digits)? . ("e" | "E") . number
  | sign . hex . ("." . hexdigits)? . "p" . sign . digits
  | sign . "infinity"
  | sign . "nan"
  | sign . "nan:" . hex;
```
- My first question is about the ML code:
https://github.com/WebAssembly/spec/blob/master/ml-proto/host/lexer.mll#L88

What does ```[^'"''\\']``` match in ML?

- Second question is about the signed hex:
https://github.com/WebAssembly/spec/blob/master/ml-proto/host/lexer.mll#L97

Don't understand what ```0x8000``` or ```-0x8000``` would mean. Is it the same? I expect it would represent -32 768.

Makes more sense to me if the hexadecimal numbers are unsigned, upper most bit represents if it's signed or not.

**Comment by jbondc** [comment]
Think it should be:
```
hex = "0x" . hexdigits;
number = sign . digits;
int = (sign . digits) | hex;
float = number . "." . digits
  | number . ("." . digits)? . ("e" | "E") . number
  | hex . ("." . hexdigits)? . "p" . sign . digits
  | sign . "infinity"
  | sign . "nan"
  | sign . "nan:" . hex ;
```
So the hex version of an integer or float can never be signed.

**Comment by binji** [comment]
> What does [^'"''\\'] match in ML?

`[^'"''\\']` is a character set with `"` and `\` removed.

> Don't understand what 0x8000 or -0x8000 would mean. Is it the same? I expect it would represent -32 768.

`-<num>` is always equivalent to `~<num> + 1` in two's complement. This requires knowing the number of bits being stored. So -0x8000 as a 16-bit integer is 0x8000, but as a 32-bit integer is 0xffff8000.

> Makes more sense to me if the hexadecimal numbers are unsigned, upper most bit represents if it's signed or not.

Numbers do not have a sign. Certain operations specify that their arguments are treated as signed or unsigned values. e.g. `(i32.lt_u (i32.const -1) (i32.const 0))` is false.

**Comment by sunfishcode** [comment]
The sign syntax is necessary in floating point literals, including those using hex syntax, because they use a significand and exponent system where there is no other way to express negative values.

It's true that the sign syntax is not strictly necessary for integer literals (hex or otherwise), however it's a reasonably inexpensive convenience.

The other questions have been answered here; if there are further questions or concerns, please file a new issue. Thanks!
