### ISSUE TITLE
IRC bots

### ISSUE THREAD

**Issue by kripken** [WebAssembly/design#502]
(Not sure where to file this, but this seems the most "central" place...)

Some of the projects under `WebAssembly/` have irc bots that report to `#webassembly`. However, we do have quite a bit of projects on our github repo now. Do we have any thoughts on criteria for bots that report to that channel? I ask because I considered adding a bot for one of my repos, but then wondered if maybe some people think the amount of bot messages in the main channel shouldn't increase.

Thoughts?

**Comment by jfbastien** [comment]
My preference is to either:
 - Have bots report activity to each repo's master as long as the bot only has wasm-related content.
 - Create a separate channel, with the same policy.
In either case people can opt-out with `/ignore`.

**Comment by kripken** [comment]
What do you mean by "repo's master"?

**Comment by jfbastien** [comment]
master branch for the repo: I think we want to avoid traffic from other branches such as development branches.

**Comment by kripken** [comment]
Oh, right, got it.

**Comment by jfbastien** [comment]
This is probably done :)

**Comment by kripken** [comment]
Actually a technical problem remains, we've not managed to make an irc bot for binaryen, despite copying the settings from the design repo. Anyone have ideas?

**Comment by jfbastien** [comment]
Fixed :)

**Comment by kripken** [comment]
Thanks :)
