### ISSUE TITLE
uninitialized variables  

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/design#505]
I would *assume* that uninitialized variables are all 0. If that is true I think it probably should go in the design docs.

**Comment by jcbeyler** [comment]
Isn't that the same type of conversation I opened here: https://github.com/WebAssembly/design/issues/504

Basically, all local variables are set to 0 by default. But I wonder if that is a good idea :) Though I might be alone there ;-)

**Comment by wanderer** [comment]
@jcbeyler yep thanks for pointing it out! I'll close this to avoid duplication.
