### ISSUE TITLE
Consider adding a copy_local operator.

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/design#507]
Just looking at some code the `(set_local <v1> (get_local <v2>))` pattern has a relative high frequency and might warrant a separate operator unless the encoding layer optimizes this well.

**Comment by jfbastien** [comment]
What's the code generator you're looking at? I'd like to make sure we're not optimizing for silly code generation either!

**Comment by JSStats** [comment]
@jfbastien That is a good point, and it's the binaryen asm2wasm output. Just filed this issue as it's something I noticed, and this is a common operation in machine codes too so it might not be just poorly optimized code.

How far off is the llvm wasm pipeline? Looking at the output suggests it needs another pass to clean up the output. For example, it's using too many local variable to hold intermediate expression values. I've not worked out how to put together larger benchmarks (is there a linker, or workaround)?

As noted `copy_local` encoding optimization might just be handled in the binary encoder, but handling patterns such as this does not seem to have been explored yet. There are other common patterns to, analogies to the machine code addressing modes.

**Comment by jfbastien** [comment]
Bitcode linking is the easiest way to go for now, similar to what PNaCl and Emscripten do. We'll have real linking eventually.

In the case of LLVM the coloring algorithm may need some work if too many copies happen.

**Comment by JSStats** [comment]
Turns out that there are lots of operations for which specialized encoder symbols for distinct argument combinations of local/constant/expression might help the encoding efficiency. This one was just relative high frequency. So closing this as it seems likely to be subsumed by a more general solution that might look like `(set $i1 $i2)` and be encoded as the symbol `set/local`, or `(set $i1 10)` as `set/const`.
