### ISSUE TITLE
Is there any sandbox feature in web assembly?

### ISSUE THREAD

**Issue by jerry4chen** [WebAssembly/design#510]
Web assembly claims that it will run web assembly bytecode securely. 
I am wondering if there is any sandbox feature or mechanism like Google NaCl does(fault isolation, bundle alignment...etc.)?
If it does, where can I find these design document.
If it doesn't, what is the security mechanism that web assembly work under.

Thanks in advance.

**Comment by alkchr** [comment]
From the [README.md](https://github.com/WebAssembly/design/blob/fb900db5159ba96dff14699204adfd27f0670c23/README.md#overview):
> WebAssembly describes a memory-safe, sandboxed [execution environment](https://github.com/WebAssembly/design/blob/fb900db5159ba96dff14699204adfd27f0670c23/AstSemantics.md#linear-memory) that may even be implemented inside existing JavaScript virtual machines. When [embedded in the web](https://github.com/WebAssembly/design/blob/fb900db5159ba96dff14699204adfd27f0670c23/Web.md), WebAssembly will enforce the same-origin and permissions security policies of the browser.

[FAQ.md](https://github.com/WebAssembly/design/blob/fb900db5159ba96dff14699204adfd27f0670c23/FAQ.md#why-create-a-new-standard-when-there-is-already-asmjs):
> WebAssembly minimizes costs by having a design that allows (though not requires) a browser to implement WebAssembly inside its existing JavaScript engine (thereby reusing the JavaScript engine's existing ... security sandboxing ...). Thus, in cost, WebAssembly should be comparable to a big new JavaScript feature, not a fundamental extension to the browser model.

[Nondeterminism.md](https://github.com/WebAssembly/design/blob/cbda5090f775df257c1f56eb5c69d2161ec71e24/Nondeterminism.md)
> WebAssembly is a portable sandboxed platform with limited, local, nondeterminism. 
>
> The limited, local, nondeterministic model implies:
> - Applications can't access data outside the sandbox without going through appropriate APIs, or otherwise escape the sandbox.

**Comment by jfbastien** [comment]
What @alkchr points at is correct. Note: this text means that WebAssembly doesn't preclude an implementation in NaCl (or a NaCl-like sandbox). The precise implementation of the sandbox ins't specified, but the observable behavior from within the sandbox is.
