### ISSUE TITLE
Allow imports in functions tables.

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/design#517]
The v8 implementation and encoding allows imports in function tables. I thought there was some discussion about this but could not find it, and that there seemed to be consensus to allow this. The v8 encoding appears to be pending being accepted as the working experimental binary encoding. So is there consensus to allow imports in function tables for now?

**Comment by sunfishcode** [comment]
This is essentially covered in WebAssembly/design#421. See also WebAssembly/design#522.
