### ISSUE TITLE
binary encoding: remove the function name-present flag and require a name for imports and exports.

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/design#521]
The encoding (still being imported) has separate function decl flags for the function being an import and export, and a separate name-present flag. There is only one name for each function, and for imports and exports that name would be the external name not the internal label name. It seems that all imports and exports would require an external name to be specified, and that other functions have only internal labels. So the separate name-present flag appears to be redundant and a foot-gun see  https://github.com/WebAssembly/binaryen/issues/124 and perhaps could just be removed and a name would be include if and only-if the function is an import or export.

**Comment by weilianglin** [comment]
Do we need a lightweight, optional "debug symbol" section in the binary which associates names with each indexed entity?　Stated in [TextFormat.md#debug-symbol-integration] (https://github.com/WebAssembly/design/blob/master/TextFormat.md#debug-symbol-integration)

**Comment by JSStats** [comment]
@weilianglin Yes, but it's not clear yet how it will be integrated. The existing encodings function name just does not appear appropriate, and will not work as-is for import and exports. We could just add another function decl flag for a separate label name, but there are also local variables and branch targets to name. Also there seems support for having the import and export names inlined along with the sections near the start of the file to allow early planning when streaming in the file, but the meta information could be at the end of the file to optimize runtime latency.

**Comment by kg** [comment]
> Do we need a lightweight, optional "debug symbol" section in the binary which associates names with each indexed entity?　Stated in TextFormat.md#debug-symbol-integration

This was assumed in past design discussions, though I don't think we had decided whether we would formally spec it until later on. It improves the usability of view-source and debugging.

**Comment by lukewagner** [comment]
Coincidentally, I was just [commenting](https://github.com/WebAssembly/design/issues/522#issuecomment-173591172) on this in #522.

**Comment by JSStats** [comment]
With imports moving to a separate section, that leaves only the exports that seems to need a name and perhaps it is even clearer that the name-present flag can be removed and a name only included when the function is an export.

**Comment by JSStats** [comment]
Basically addressed now. Imports still need naming.
