### ISSUE TITLE
Another look at removing the `return` operator.

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/design#524]
Dealing with 'return' is a slight complication for producers, and consumers, see https://github.com/WebAssembly/binaryen/issues/139

Looking at this again, it seems that `return` could be considered just an encoding layer optimization for a `br` to an implicit function block. Producers could currently add a function level block, translate `return` to a `br` to this block, do their processing without special cases for `return` and then rewrite `br` to the outer block back to `return` and remove the block. But if this is the patten that will be easiest for producers then why not just remove `return` from the spec and add an implicit function block?

Even if `return` were removed from the AST, there is talk of an encoding layer, and it could then still be an encoding option, an optimization of a `br` with a target being the function block irrespective of the depth.

Can live with it either way, if someone wants to close this quickly!

**Comment by titzer** [comment]
I had actually removed it from v8 briefly, and found that writing WASM code
was significantly more of a pain, requiring me to track the nesting level
very carefully. That's not a problem for a tool (with no bugs), but it is
tricky to get right. Thus it was left in.

**Comment by JSStats** [comment]
I had noticed all the v8 hand written bit code tests. Surely you will need to abstract these to handle expected changes to the encoding. Could you accept leaving it in the v8 implementation for now just for your internal tests and let it be remove from the actual spec?

**Comment by kg** [comment]
If every ```return``` in a function is replaced with ```br x``` where ```x``` is some arbitrary nesting depth, you're definitely going to hinder compression. And ```return``` is an ABSURDLY COMMON primitive. So this isn't a worthwhile optimization unless you can prove it's a big win somewhere.

**Comment by JSStats** [comment]
Ok, thank you for the feedback.
