### ISSUE TITLE
Move the `br_if` label to be the first argument.

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/design#529]
The v8 encoding has the branch depth as an immediate and encoded as the first argument. It corresponds nicely to the label, but unfortunately the label is currently second in the wast format. It would avoid a special case (or reordering of immediates) in an opcode table to move the branch to be the first argument in the sexp format too?

Any support for this or objections?

**Comment by sunfishcode** [comment]
This was implemented as part of https://github.com/WebAssembly/spec/pull/234 .
