### ISSUE TITLE
Asking for clarifications on data segments and module memory

### ISSUE THREAD

**Issue by mildred** [WebAssembly/design#531]
I wanted to create a function in webassembly that returns a pointer to a string constant (much like a `char*` in C) and I al wondering how it works in wasm. I understood that the way to store string constants in a module was to define a segment. Something like:

    (module
      (memory 1024 (segment 10 "Hello World"))
      ...)

I assume the module is asking the loader to put the string "`Hello World`" at the address `10` of its virtual memory. Am I right ?

If so, what happens if another module ask to load something at the same address ?

Would the wasm program fail to load? Will one module override another? Is it possible to declare a segment to be loaded at any available location and access it using a logical symbol? Do module have separate address spaces, and if so, how to share pointers between modules?

Also, is it possible to declare a memory segment read only?

I don't see any documentation about `memory` and `segment` in [AstSemantics](/WebAssembly/design/blob/master/AstSemantics.md). Perhaps we could improve this.

**Comment by lukewagner** [comment]
> I assume the module is asking the loader to put the string "Hello World" at the address 10 of its virtual 
> memory. Am I right ?

Yup, check out this [test file](https://github.com/WebAssembly/spec/blob/master/ml-proto/test/memory.wast)

> If so, what happens if another module ask to load something at the same address ?

Good question.  In the MVP, there is no dynamic linking (in the familiar C/C++ sense) and so every loaded module is in its own [instance](https://github.com/WebAssembly/design/blob/master/Modules.md) and thus gets its own, disjoint, linear memory.  When we add dynamic linking, my expectation is that we'll have a new module-level flag/section which enables the module to be linked into an existing instance (effectively flagging it as a "`.dll`") and for these `.dll`s, `segment`s wouldn't have constant offsets but, rather, each `segment` would introduce a readonly symbol whose load-time-determined value would be the offset of the `section` in instance's linear memory.  This symbol could be read by some new AST operator (say `symbol`) to compute addresses to load/store.  Then loads/stores to these globals in the `.dll` would look like `(i32.load offset=100 (symbol $data))` (where `$data` gets assembled into an integer index in the binary encoding).

**Comment by mildred** [comment]
> every loaded module is in its own instance and thus gets its own, disjoint, linear memory

If so, how do a module can call a function from another module and pass data to it (a buffer for instance)?

**Comment by lukewagner** [comment]
@mildred The feature you are describing is dynamic linking.  It requires more than just sharing linear memory, but also the [indirect function table](https://github.com/WebAssembly/design/blob/master/AstSemantics.md#calls).  Until dynamic linking, the best a module can do is allow the outside world to [alias its linear memory](https://github.com/WebAssembly/design/blob/master/Modules.md#linear-memory-section).
