### ISSUE TITLE
Add a principle that the binary encoding should minimize redundant information and otherwise validate canonical form.

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/design#533]
As discussed here https://bugzilla.mozilla.org/show_bug.cgi?id=1232011, and also a matter that would be helpful for the WLL https://github.com/wllang, the principle that 'the binary encoding should prefer less redundant encodings and otherwise hold non-canonical encodings to be invalid' could be added as a guiding principle for the development of the binary encoding.

For example, the function names would be placed one after the other in the order they occur (or some order that would be expected to be already represented in a text format anyway), rather than allowing them to be placed randomly out of order. This would limit redundancy by design.

For example, the LEB128 encoding would canonicalize on the smallest encoding, and other encodings would be invalid, or we should find another encoding that avoids the redundancy by design.

The property that this would support is that a text format should be able to maintain the property that `encode(decode(binary))=binary` without too onerous side-information. For example if the leb128 is not canonicalized and validated then such a text format would need to represent any non-canonical leb128 encodings, and if the function names could be in any order wrt their use then their order would need to be separately defined in side information.

**Comment by lukewagner** [comment]
It's more work to detect non-canonical binary encoding (for example, that an LEB128 integer is encoded using the least number of bits) and would inhibit various streaming encoding schemes that want to use backpatching, so I'd rather not add this principle.

**Comment by JSStats** [comment]
Produces should not be back-patching leb128, and the encoding should not be limited by this requirement. It's a trivial matter to check that an leb128 is in minimal form.

**Comment by titzer** [comment]
I agree with @lukewagner; it's not really the decoder's job to check that
the encoder has put the module into the most efficient form. E.g. should it
check that the producer uses ExprI8Const instead of ExprI32Const whenever
possible?

**Comment by jfbastien** [comment]
Besides being more work to check, forcing a "canonical" encoding may also defeat compression: some other encoding of the same information may compress better with gzip / brotli. We want to allow this.

**Comment by JSStats** [comment]
@titzer Yes, it should check that the producer uses 'ExprI8Const instead of ExprI32Const whenever possible'.

@jfbastien That is a big 'may'. Redundant information means more information to encode. Take the case of the function name strings. If they can be in any order then the offset within the file needs encoding, 32 bits for each name, whereas if they are one after the other then a one bit flag is all that is need plus perhaps one start_of_names offset. The per-name offset might allow re-use of names, but we already expect them to be unique. I expect similar outcomes for leb128 redundancy.

This would not be a principle for the layer-1 and upper layers, just for the layer-0 uncompressed encoding. It would be trivial to show that many upper layer variations should be possible, different compression algorithms etc, but these would not be represented in a text format - not even in a lossless format.

Another small reason to avoid redundancy is to allow comparison of the output of independent tools as a cross check.

Not designing to minimising redundancy at layer-0 will frustrate a text format. It adds a lot of complexity to lossless text representations of the binary code. If other decisions added this much complexity to your runtimes I am confident you would not support them. Designing to minimize redundancy is a good principle in my opinion.

A possible compromise might be to somehow cast the encoding areas people want to allow variations to be an upper layer, that wasm defines them as encoding layer decisions, and that they transform to a canonical wasm encoding. Then a lossless text representation could operate at this canonical layer, and producers wanting to use more redundant forms could. But still some consideration would want to be given to the complexity of transforming to the canonical form. E.g. would you want to have to sort all the function names? E.g. canonicalizing leb128 and 'ExprI8Const instead of ExprI32Const` might be trivial.

So this principle might be recast a defining a canonical encoding and adding a principle to minimise the canonicalization complexity.

**Comment by JSStats** [comment]
If this community group does not want the burden of defining canonical binary representations then it could potentially be done elsewhere, so I concede that the checking for canonicalized forms is not necessary for the use case of a lossless text representation. I don't think it harms a compression prediction model either as that would be upstream - producers using these redundant encodings pay this price alone.

However if this group does not follow a principle of minimising the canonicalization burden by designing to avoid redundant encodings then it creates more work elsewhere defining canonicalization strategies. I also guess we could deal with encoding decisions case-by-case rather than having a principle which people might consider too general.

**Comment by JSStats** [comment]
The opinion on the compression implications applies only if producers using redundant encodings have separate compression algorithms. Clearly a compression algorithm optimized for particular canonical encodings will do better with data in that canonical form than a compression algorithm optimized for more general encodings or one optimized for alternative canonical encodings. Sorry, for the extra noise.
