### ISSUE TITLE
Allow providing more initial memory than specified by the module

### ISSUE THREAD

**Issue by Teemperor** [WebAssembly/design#540]
The testsuite contains a [test](https://github.com/WebAssembly/testsuite/blob/master/address.wast#L29) that a module with the memory start size 1024 traps when accessing more than those 1024 bytes. I think it should be allowed that the implementation provides more memory than the specified by the module (e.g. rounding up to the next page size).

**Comment by titzer** [comment]
The long term solution is to require the memory size to be specified in
pages which are defined to be 64k in size.

**Comment by lukewagner** [comment]
There was actually consensus (which it seems hasn't been reflected in ml-proto yet) for wasm to have a fixed virtual 64k page size of which `memory_size` must always be a multiple (including the initial size).  So that would require updating this test case.  With this, I think we shouldn't need any nondeterministic rounding by the VM.

**Comment by Teemperor** [comment]
The only real-world use case I had for this was rounding up to the 64 KiB page size, so that solution sounds fine to me.

**Comment by jfbastien** [comment]
There also are usescases around:

* Allowing the JIT to emit clever test masks by allocating more.
* Allowing the runtime to allocate huge pages, and use clever page mappings around that.

**Comment by Teemperor** [comment]
I missed that large page feature. Maybe we should allow rounding up, but by default only to the next 64 KiB page. The program can specify if it can handle different page sizes than 64 KiB (some flag in the header?), which should allow the larger page size optimizations.

**Comment by jfbastien** [comment]
Huge page is a CPU thing which the OS has to enable, so it's not up to the program to decide whether to use it. The program could opt-in, but without CPU+OS support nothing will happen :-)

**Comment by lukewagner** [comment]
We've talked about a possible future extension wherein, in the memory section, a module could opt-in to larger page sizes in which case the wasm engine would require that the initial memory size and `resize_memory` deltas were multiples of the declared page size.  The important thing is that there is no nondeterministic rounding performed by the VM; everything is specified by the module.

I should also add that a wasm engine can always user larger pages under the hood.  Having the linear memory size be a multiple of OS page size is only useful for enabling engine optimizations (such as removing bounds checks).

**Comment by JSStats** [comment]
@Teemperor This particular case would be handled by the pending change to require the initial and maximum memory sizes to be multiples of the 64k page size. It is almost ready to go, some PR's still to review, and perhaps you could take a look:
https://github.com/WebAssembly/spec/pull/209
https://github.com/WebAssembly/sexpr-wasm-prototype/pull/21
https://github.com/WebAssembly/binaryen/pull/121
https://codereview.chromium.org/1597163002#

I would also like more flexibility for negotiating a memory size with the runtime, but it's a big topic and a difficult one.

**Comment by binji** [comment]
I understand there is consensus on `memory_size` being a multiple of the page size, but is that reflected in AstSemantics.md? All I see is a mention that grow_memory must be a multiple of the page size.

**Comment by JSStats** [comment]
@binji https://github.com/WebAssembly/design/pull/542

**Comment by sunfishcode** [comment]
With #542 merged, the original issue here is fixed, at least on the design side. To discuss huge pages or other ideas, please file new issues. Thanks!
