### ISSUE TITLE
'The Specification'?

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/design#548]
We seem to have 'The Specification' sprawled out over two repos, the 'spec' and 'design' repos.

The 'design' repo describes itself as 'contains documents describing the design and high-level overview of WebAssembly.' which does not sound like 'The Specification' to me, yet it includes the specification for the binary encoding which seems central to  'The Specification' to me.

Further the specification of the binary encoding is incomplete, and seems to depend on 'AstSemantics' which is in the 'design' repo.

Perhaps it's just me and baggage expectations, but it just does not seem to heading towards what I would call 'The WASM Specification'.

Would anyone else like to see a single document with 'The WASM Specification' that describes the binary encoding and the semantics of the encoding?

**Comment by jfbastien** [comment]
The intent is for the spec repo to be The Specification. It's intended to be executable.

The design repo is intended as The Design, with English explanations of The Specification and extra non-normative fluff that explains things more and has rationales for why things are that way, as well as details on what may happen in the future.

**Comment by JSStats** [comment]
Thank you, that makes sense. That does suggest that the 'spec' repo would be an implementation of the future text format and the evolving binary format.

Just an observation, but binaryen seems likely more familiar for most people, and already has support for the binary format, and perhaps the binary decoder and checker and simulator could be split out to be a credible alternative to the ml-proto.

Still not sure it meets my personal expectations for a web specification, by that seems to be entirely my issue if everyone is happy with an 'executable' spec in a language not familiar to most people.
