### ISSUE TITLE
Unary `eqz` operator

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/design#554]
WIthout `br_unless`, reversing a branch without reorganizing basic blocks requires adding two instructions, an `i32.const 0` and an `i32.eq` operator. This is a very common pattern which adds clutter. A unary not operator would be trivial to implement, make pattern-matching of branching easier, and reduce clutter for a common pattern.

**Comment by titzer** [comment]
It appears in the binary format, and we've implemented in V8. Also in favor of `br_unless`, but we haven't implemented that.

**Comment by sunfishcode** [comment]
Ok, great. I'll submit PRs adding unary not to ml-proto and AstSemantics.md then so that we're all in sync.

**Comment by sunfishcode** [comment]
Design PR: https://github.com/WebAssembly/design/pull/555

**Comment by sunfishcode** [comment]
Design is done; spec PR: https://github.com/WebAssembly/spec/pull/259

**Comment by rossberg-chromium** [comment]
Spec landed as well, closing.
