### ISSUE TITLE
Guidance on patching a WebAssembly module while streaming it.

### ISSUE THREAD

**Issue by ghost** [WebAssembly/design#558]
Issue https://github.com/WebAssembly/design/issues/416 on feature detection closed offering to 'offer guidance on the alternative to patch a WebAssembly module while streaming it, observing there are challenges to this approach.'

Patching the wasm while streaming it seems the outcome we need, even for MVP. Either that or being able to patch it in chunks and hand the chunks to the runtime.

The solution in https://github.com/WebAssembly/design/issues/416 of 'Developers will store on server side a separate WebAssembly binary for each combination of features they decide to support' seems a very bad outcome compared with being able to 'patch a WebAssembly module while streaming it' on the client side for the following reasons:
1. If the client features are not static then it will force re-downloads that might be very significant. There are use cases where much more dynamic decisions need to be made.
2. It is not cache or offline friendly. Even a doubling up of the binary could be significant. This will be a real blocker for people wanting to distribute wasm code for offline use, such as a remote school or community. They might be force to use only a lowest-common-denominator wasm binary and thus not be able to take good advantage of it.

There has been mention of a stream-api, but realistically what are the chances of this being widely supported in the near term?

I have not looked into it, but could a service worker allow the community to explore alternatives? What about extensions? Can these re-write binary content such as wasm while streaming? Does a secure wasm source stream block any of these options for the community to explore.

If there were some support for linking modules then might this help on this issue by allowing some feature dependent code to be put in smaller separate modules to be selected?  But even this does not solve existing use cases that require patching much of the code.

**Comment by lukewagner** [comment]
As soon as [Streams](http://streams.spec.whatwg.org/) ship, it definitely makes sense for `Wasm.compile` (or whatever the async-compile-a-module JS function gets named) to accept a stream and return a promise resolving to a module.  I don't think that will be in time for the MVP, though.

For the MVP, other than shipping multiple binaries (not always a good option, but could be if there is a small set of possibilities), I think the approach used by polyfill-prototype-1 would work: download into 1 ArrayBuffer, decode (in a single pass, doing patching while decoding) into another ArrayBuffer (of .wasm bytes), then feed that ArrayBuffer into `Wasm.compile`.  This of course isn't optimal, but I think it would be viable in the short-term.

**Comment by sunfishcode** [comment]
Is the question here answered?

**Comment by JSStats** [comment]
Could we leave this open for now.

1. The first reason is that the 'guidance' has not been published - apart from here, or not somewhere I am aware of?.

2. The second reason is that people (myself anyway) seem focused on just getting something working and on the wasm encoding definition, and might not have had time to actually test how 'viable' it is to re-generate the wasm into an 'ArrayBuffer into Wasm.compile'. There are some reasons to doubt how 'viable' this is: a) it adds latency as the entire wasm file seems to need to be generated before passing it to `wasm.compile`. b) it needs to be re-generated each time it is used adding latency and overhead, or stored locally and efficiently somehow.  Perhaps there is a way to made this more viable, but I personally have not had time to explore it and the guidance does not make this clear.

Even if MVP could address the 'caching' matter it might help - users might still see more latency on the initial start up but avoid it on subsequent uses. Might MVP stretch to address this?

**Comment by JSStats** [comment]
With the opcode table conceded then good support for recoding the wasm while streaming is looking more important.
