### ISSUE TITLE
When embedded in the web, clarify how export/import names convert to JS strings

### ISSUE THREAD

**Issue by pizlonator** [WebAssembly/design#569]
When embedded in the web, the exports and imports of a module are represented as JS objects.  JS objects are keyed by JS strings, which can be any UCS16 (roughly) sequence.  WebAssembly uses sequences of bytes.  Therefore, we need to specify conversion rules from WebAssembly byte sequence names to JS strings.  There will be JS strings that don't convert gracefully to bytes and vice-versa, so we also need something sensible to happen when the conversion fails.

**Comment by titzer** [comment]
SGTM, wanna take a stab at updating Web.md?

**Comment by jfbastien** [comment]
Do we want simple failure on the web when conversion fails, or do we want to try to "fix" things? Failure is fine IMO.

**Comment by pizlonator** [comment]
Yup!

-Filip

**Comment by pizlonator** [comment]
I was thinking eager failure at module compile time.

-Filip

**Comment by s3ththompson** [comment]
Fixed in 04c63fb2b26f25b2bfd88569baf8711f146e4d06
