### ISSUE TITLE
Clarification on module headers in binary format

### ISSUE THREAD

**Issue by naturaltransformation** [WebAssembly/design#577]
I am confused about the version number in module headers. Does this assume that a wasm binary only contains exactly one module? If not, does it mean that we must expect to handle a single binary with modules with different wasm binary versions?

**Comment by MikeHolman** [comment]
Yes, a wasm binary should contain exactly one module.

**Comment by naturaltransformation** [comment]
So does that mean much of the spec test suite should be reorganized to be consistent with that?

**Comment by JSStats** [comment]
Tools are splitting the spec tests into individual modules - it does seem a bit of a hack.

**Comment by lukewagner** [comment]
On this subject, I've been consider the .wast files to be the wasm *test* format (the 't' is for 'test').  A long long time ago when we talked about file extensions, we talked about .wasm for binary and .was for text (for symmetry with classic assembly .s or .as extensions).  If we still kept this distinction, then a .was would contain only a single module so it'd correspond 1:1 with a .wasm, and the .wasts would only live in the test suite.

**Comment by rossberg-chromium** [comment]
Right, and .was would be used for the official text format, whatever that will be.

**Comment by lukewagner** [comment]
I realize there is some confusion on this currently with various tools emitting a .wast that contains a single `(module ...)` top-level command and nothing else.  @kripken @binji, maybe it would help to have the tools start generating/consuming .was files instead?

**Comment by kripken** [comment]
I thought we said that the s-expression `.wast` format was always a temporary thing, and we'd get rid of it when there was a proper text format, using a tool to automatically convert existing tests etc. to it. In that case, why do we need both `.wast` and `.was`?

**Comment by lukewagner** [comment]
When we switch to the "real" text format, I was imagining we'd keep the .wast files but switch the (module ...) s-expressions to instead embed the real text format for a module.  For the other commands (assert et al), we could either keep the s-expressions or switch to something more consistent with the real text format.

Essentially, we need two things here: "just a module" and "a script that you execute that lets us test everything".  Two alternatives:
 * Use .js for testing scripts (that's what we're [doing in SM](http://hg.mozilla.org/mozilla-central/file/tip/js/src/jit-test/tests/wasm/basic.js) until we support .wasts directly).  JS has limitations that make it hard to test things like i64 and non-canonical NaN so we'd have to work around those somehow.
 * Extend the .was to have a "testing commands" section in which we could embed commands (like the asserts et al) that would be executed by a test runner.  The only downside I see is that it's more annoying to test tons of invalid cases ([as we do](https://github.com/WebAssembly/spec/blob/master/ml-proto/test/memory.wast)), but maybe that's fine.

**Comment by rossberg-chromium** [comment]
@lukewagner, please no dependency in JS -- that would be extremely painful, esp for the spec interpreter.

Not quite sure there is a problem that needs solving right now. The current .wast format simply is a superset of what a regular module file can contain, and other consumers than testing tools can just restrict it to the subset with a single module. Until we have agreed on an "official" text format, is there any need for action?

**Comment by lukewagner** [comment]
@rossberg-chromium I'm not proposing it :)  We will, of course, need to *have* .js tests to test JS/wasm interop, but they don't need to run on the ref interp.

**Comment by sunfishcode** [comment]
The original question here is now answered; thanks! Please file new issues for new questions.

@rossberg-chromium This issue is another example of confusion arising about the relationship between .wast script files and .wasm modules. Of course, part of it is just that we don't have have a regular text module format yet. However, talking about .wast files as being a superset of .wasm files feels like it unnecessarily conflates these two distinct kinds of things, to me at least, even if there is a theoretical sense in which it can be true.
