### ISSUE TITLE
Encode load/store offsets as signed

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/design#584]
Currently, load/store offsets are encoded as unsigned, since we don't currently wish to support negative offsets, to simplify sandboxing. However in the future, we may want to support negative offsets, because they are useful.

A way to keep this option open without making our sandboxing more complicated today would be to represent load/store offsets with signed-LEB128, and for now just semantically constrain them to be in the range of a uint32_t (for wasm32).

Also, note a subtlety here: I'm claiming we want to continue to support the full range of a uint32_t, and not just the non-negative range of a signed int32_t. This is important so that (in wasm32) we can encode any absolute address in the offset field. This means that toolchain linkers won't be burdened with complexities like ensuring that certain objects are allocated in the low 2 GiB of memory, creating annoying and obscure special cases.

**Comment by JSStats** [comment]
It's not clear how it can be non-wrapping yet still wrap a negative offset to an unsigned address base?

Could alternatively add a separate bit to encode a negative offset in future.

Or are you proposing another leb128 variant that encodes -2147483648 to 4294967295 ?

I see some uses for negative offsets but I recall they were problematic for bounds checking.

Do you have a bounds check strategy that works well with negative offsets? Both memory protection and inline tests.

Even using memory protection for bounds checking might be problematic with negative offsets. For example, placing the linear memory at absolute zero might not be possible with only memory protection for bounds checks. Perhaps the runtime could use explicit inline tests for a negative offset that looks problematic.

**Comment by sunfishcode** [comment]
It can be non-wrapping as follows: zero-extend the base to a mathematical real number, sign-extend the offset to a mathematical real number, and do the add.

I'm suggesting standard signed-LEB128 with an appropriate size or range constraint. I would not want a custom integer encoding or a separate "negative" bit somewhere.

I didn't propose we support negative offsets; the idea here is just to extend the encoding to support the option of supporting negative offsets in the future should we ever wish to.

**Comment by lukewagner** [comment]
This seems like the conservative right thing to do seeing as we don't give up anything (since signed-LEB128 will impose no range constraints other than what engines impose internally (we'd probably write some `bool Decoder::readSLEB128AsUint32(uint32_t*)` to allow the full `uint32_t` range in MVP which we'd generalize later if negative was supported).

**Comment by JSStats** [comment]
Thank you for the clarification. So it's effectively a signed 33 bit leb128 encoding, and the wasm64 offset encoding would be a signed 65 bit leb128?

**Comment by sunfishcode** [comment]
To be specific, under this proposal, 33 is the least number of bits needed for a signed integer type that can hold any semantically permitted value in wasm32. This is not to be confused with the encoding, which is signed leb128, or the semantically permitted range, which is [0, 2<sup>32</sup>).

**Comment by sunfishcode** [comment]
Ping :-). Any other thoughts on leaving ourselves room to support signed offsets in the future?

**Comment by jfbastien** [comment]
Sounds fine. I wonder if we should allow negative values outright, instead of just leaving the possibility open?

**Comment by dschuff** [comment]
LGTM, I like this idea too.

**Comment by sunfishcode** [comment]
@jfbastien We're prohibiting negative offsets for now because it simplifies several popular sandboxing strategies. You're welcome to open a new issue if you want to discuss changing that :-).

**Comment by flagxor** [comment]
Implementors have discussed this and decided we should do this.

**Comment by sunfishcode** [comment]
Implementors have discussed this and have now decided not to do this. It would require a new LEB128 decoding path to decoders, which adds a small amount of complexity. If negative offsets are ever desired in WebAssembly, they could be supported by the addition of new load/store opcodes.
