### ISSUE TITLE
Should imports also have an internal name?

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/design#593]
Imports have not been named when adding the `names` section which assigns names for function indexes but imports are not in the same index space.

A view-source formatter could use the import function name to create a usable internal name, but the same could be said for exports, and might it have been an oversight to not name the imports?

**Comment by JSStats** [comment]
A suggestion here https://github.com/WebAssembly/design/pull/596

**Comment by JSStats** [comment]
Is this still an issue or have the design changes made this obsolete or addressed this?

**Comment by lukewagner** [comment]
Since the names section assigns names to function indices and #682 puts function imports into the function index space, then this issue is addressed.
