### ISSUE TITLE
(Web Embedding) Exporting i64 functions to JS 

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/design#616]
Since JS numbers are 64-bit Floating Point, how are i64 numbers represented? This is reposted from [here](https://github.com/WebAssembly/v8-native-prototype/issues/41). 

possible solutions:

1. break down i64 outgoing params to a pair of ints, but what about return values.
2. round i64 to doubles, losing precision, but getting an answer that is "more correct".
3. bitcast i64 to double, but might lose NaN bits.
4. Box i64 as objects that have high and low properties.
5. Wait on JavaScript acquiring a bonafide i64 for itself.
6. use ArrayBuffer to represent i32 and i64 values 
7. reinterpret the bits of the 64-bit integer as a 64-bit float

**Comment by jfbastien** [comment]
Within wasm you can use 64-bit integers as you want. It's only when wasm communicates to a browser embedding that we currently plan do disallow 64-bit integers. In non-browser embeddings this is totally fine.

This should probably be in Web.md. JS will eventually get int64.

**Comment by wanderer** [comment]
@jfbastien added note in Web.md in pr #618 

>plan do disallow 64-bit integers

should this be more explicit? currently v8 reduces them to i32.

**Comment by titzer** [comment]
We plan to disallow i64 in imports/exports to JavaScript in V8, but simply
haven't done it yet.

**Comment by wanderer** [comment]
ok updated the pr. Side note: how much of wasm's JS API goes in the design docs?

**Comment by jfbastien** [comment]
For now we've explicitly not spec'd any. Most web-specific things are in Web.md, I think it would make sense to create WebAPI.md or something when we get there. We're not standardizing APIs yet, so I'm not sure it makes sense pre-MVP.

**Comment by wanderer** [comment]
> For now we've explicitly not spec'd any

@jfbastien can i close this then?

**Comment by jfbastien** [comment]
Dup for #515?

**Comment by wanderer** [comment]
yep i think so
