### ISSUE TITLE
Non-preemptive multi-tasking (async/await ; generators, etc)

### ISSUE THREAD

**Issue by brandyn** [WebAssembly/design#622]
Is there any plan or provision for non-preemptive multi-tasking in wasm?  Consider any language that wants to directly (compile to wasm, not interpret) support co-routines, generators, or cooperative (non-preemptive, ultra-light-weight) threads.  This would seem to be impossible in wasm's (implicitly) stack-based model without some explicit wasm support.  Typically to implement this, one would do heap-based (instead of stack-based) allocation of frames for any waitable function, and then provide some sort of suspend operator which acts like a return but first archives transient state (registers, etc, as well as current instruction-pointer/program-counter location) and returns that in a way that can be resumed later.  From a cursory glance, I don't see any way to do this within the current wasm instruction set, even inefficiently (at a minimum one would need to be able to branch into the middle of nested blocks/loops, in order to "resume" via jump dispatch from a function head).

As a language feature, this has been (imo) under-utilitized in the past, but is increasing in popularity as it greatly cleans up control flow in UI, game agent logic, and so on (because independent actors are able to have their own control "loops" and yet stay trivially synchronized in simulated/game/UI time, and without any of the headaches or overhead of true thread any-time preemption).  It is especially useful/relevant to game design with large numbers (potentially thousands) of autonomous agents (NPCs, but even simple dynamic objects as well).  Having this ability properly available in the core language of the game eliminates the need for an embedded interpreted language within the game which is often the solution here.

Personally I think this is an increasing trend/pattern in language design/use, a long time coming, and will eventually become the norm, so it seems prudent to plan for (if not immediately support..) it in any emerging platform standard like wasm.

See, e.g.:
Javascript - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators
C# - https://msdn.microsoft.com/en-us/library/hh191443.aspx
Python - https://www.python.org/dev/peps/pep-0492/

**Comment by svick** [comment]
[Coroutines are already considered to be supported in a future (post-post-MVP) version.](https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#coroutines)

**Comment by jfbastien** [comment]
Yes, I believe this is covered through the link @svick provides as well as stack inspection and manipulation. If any part of the design repo aren't clear we're happy to clarify, or better yet merge pull requests!
