### ISSUE TITLE
Use WebKit's FTL B3 JIT

### ISSUE THREAD

**Issue by gwicksted** [WebAssembly/design#624]
Just a consideration -- has anyone on the WebAssembly team looked at B3?

Positives:

They ported to ARM64 now so support is much wider.

Bare Bones Backend (B3) IR and Air (Assembly IR) are the two intermediate formats before machine code generation -- I assume Air would be the preferred format for WebAssembly.

Secondary bonus is it would be much easier to get a runtime going for WebKit-based browsers like Safari, Opera, Chrome, Chromium, and spin-offs like NWJS and Electron.

Negatives:

Not a binary AST format; however, enterprise applications that wish to keep code private would have nearly as much protection as native executables.

--
Perhaps WebAssembly and BBB could join forces?

Links:

https://webkit.org/blog/5852/introducing-the-b3-jit-compiler/

https://webkit.org/docs/b3/

**Comment by jfbastien** [comment]
@pizlonator wrote B3, and it is indeed well suited to *implement* WebAssembly. It's an implementation detail, though, and WebAssembly shouldn't specify B3. For sure any compiler magic learned from B3 can be taken into account when evolving the WebAssembly design.

So, closing for now :-)

**Comment by pizlonator** [comment]
Agreed. :-)

-Filip
