### ISSUE TITLE
Explicit br_table semantics

### ISSUE THREAD

**Issue by bnjbvr** [WebAssembly/design#625]
In AstSemantics.md:

```
Branches that exit a block, loop, or br_table may take a subexpression that yields a value for the 
exited construct. If present, it is the first operand before any others.
```

Each case in `br_table` is defined by a label to an enclosing construct. Reading the above sentence made me wonder: can each label in `br_table` yield its own value, like this:

```
(br_table (i32.const 0) $0 (i32.const 2) $1 (i32.const 1337) $default (; index value ;))
```

Or do all labels in the `br_table` yield a unique value, attached to the `br_table` itself and thus independent from the index value? The tests in the spec repo seem to confirm the latter.

```
The nop, if, br, br_if, and return constructs do not yield values.
```

Shouldn't we add `br_table` to this list?

The paragraph just below this one, named `br_table` doesn't even mention the yielded value at all. Should we add something there, for consistency?

**Comment by sunfishcode** [comment]
> Or do all labels in the br_table yield a unique value, attached to the br_table itself and thus independent from the index value? The tests in the spec repo seem to confirm the latter.

The latter is what's intended.

> > The nop, if, br, br_if, and return constructs do not yield values.

> Shouldn't we add br_table to this list?

There is a family of outstanding questions here, including https://github.com/WebAssembly/spec/issues/227, and they affect br_if as well as br_table.

**Comment by JSStats** [comment]
@bnjbvr A part answer on only the return values: `nop` returns zero values. The current spec `if` can return values so it probably no longer belongs on this list.  `br_if` currently returns zero values, the same as `nop`. `br` and `return` return the unreachable type (the empty set using set theory) and the same as `unreachable` and should probably be on a separate list as it is subtly different to zero-values. `br_table` also returns the unreachable type and could be on the same list as `br` and `return` and `unreachable`.

**Comment by sunfishcode** [comment]
The relevant text in (what is now) Semantics.md has since been substantially rewritten, and the specific text highlighted above is no longer present. If anything remains unclear, feel free to re-open this issue or file a new one.
