### ISSUE TITLE
Have the select operator be the unreachable type if either argument is unreachable.

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/design#647]
Working on the bottom up type system suggested some merit in changing the type checking rules for the `select` operator, so that if either of the true or false value arguments are the unreachable type then the result is also the unreachable type. This change would be visible in the follow test which would then pass.

```
(func $tst1
  (i32.eqz (select (f32.const 1) (unreachable) (i32.const 0))))
```

The sexpr-wasm single pass compile with a bottom up type system benefits from setting a workable actual type on seeing the first parametric argument, but if this is the unreachable type then this is not possible. Perhaps this would show up in a SSA transform too where it might be easier to just not consume both the true of false argument values if either is the unreachable type.

The `select` operator control flow passes through all arguments, in contrast to `if_else` which might succeed at runtime even if one branch were the unreachable type and for which a compiler can simply ignore stack value depth matching on the unreachable exit path.

Unlike typed binary operators that would always want to return their typed result type even if both arguments were the unreachable type (to support top down typing), the `select` operator is parametric.

This change might block top-down type checking, so perhaps a decision to move to a bottom up type system is needed.

I see a similar issues in the multiple-value constructor where if any of the arguments were the unreachable type then it might help for the result to be the unreachable type too. Also other potential operators for which top down typing might not be possible, for example building a set of values by concatenating argument values for which a top down type system would not know the require number of values for each argument rather just the total number of arguments.

**Comment by rossberg-chromium** [comment]
There is no unreachable type in the type system, so I'm not sure what you are saying. Bottom-up vs top-down is an implementation detail of an inference algorithm, not the type system per se.

**Comment by JSStats** [comment]
@rossberg-chromium The spec uses a top down procedure for typing so it can just not check the expected type when the result of the operation is unreachable, and thus the spec implementation has conveniently not needed to use this type. Please consider a bottom up type system, for example the `unreachable` `br` `return` operation result type in a bottom up type system, and the rules needed to validate these operations used in various contexts, and then the utility of a type for this purpose might be clear. SM calls it the `Any` type. This issue relates to how this type is propagated bottom up though the `select` operation.

Using set theory and a subset relation for checking it is the empty set, so I call it the empty type. Either way it's the result type of `unreachable` so I thought it might help to name it in this way for now.

The sexpr-wasm interpreter compiler is relatively small and might allow us to quickly explore some of these issues with a concrete implemtation, what do you think? If you could consider a single pass compiler use case like this, with a bottom up type system, then we might be working on the same issues.

This compiler would not appear to work nearly as well with a post-order encoding, which might be something people want to consider - personally I don't think an extra pass would be a show stopper but it's nice to know the design issues.

**Comment by rossberg-chromium** [comment]
You are asking for introducing a Bottom type into the type system, plus adding a 3-way case distinction to the typing rule for `select`. The only effect of these extensions would be that you'd allow some useless programs, like
```
(i32.add (select (...) (f64.const 0) (unreachable)) (i32.const 1))
```
What's the benefit? What code generator would want to produce something like that? And why is it worth additional complexity?

**Comment by JSStats** [comment]
@rossberg-chromium Working on the bottom up code generator for the sexpr-wasm interpreter compiler suggested that the code generator would want to bail out and ignore both arguments if either were the 'unreachable' type. So it's actually simpler from this perspective allow the above. Lets swap the order of the arguments in your example (also the condition is last):

```
(i32.add (select (unreachable) (f64.const 0) (cond)) (i32.const 1))
```

Now on a single pass bottom up type validator after seeing the first `(unreachable)` argument the code generator already knows to give up on code generation for the `select` operator. It can't emit any code as the `select` operator is parametric and it does not know the type. It knows that the result of the `select` operator is always unreachable (unlike `if_else` for which one exit might still return at runtime). From this perspective the simple thing to do is to just record the result type of `select` as the unreachable type.

It seem possible for it to keep two derived types, one for internal use which would be the unreachable type in the above case, and another which would be f64 in the above case which would be passed bottom up for validating the parent, but this adds extra complexity. This extra complexity for bottom up type systems might be warranted if it supports top-down single-pass typing too, but there might be other reasons to abandon top-down typing in which case the change suggested here might be the simplest solution. 

I think it would help us all work on the same page if the spec moved to a bottom up single pass type system, rather than top down. V8 seems to already use a bottom up type system and if the encoding moves to a post-order then this will be even more compelling. It seems to be a design goal for support single pass validation and SSA conversion, even if not also being able to balance stacks on a single pass for compiling to stack machines, so there seems good reason that the spec should be aligned with this focus.

I'd like to leave this open for now while the post-order encoding and bottom up type systems are explored and until the spec includes a bottom up single pass type system or the issue is otherwise superseded.

**Comment by rossberg-chromium** [comment]
Every code generator has to be able to deal with
```
(select (if (expr-returning-1) (unreachable) (f64.const 0)) (f64.const 0) (cond))
```
which is equivalent to your `select`, and short of solving the halting problem has the same "problem". I don't see how special-casing one corner case helps.

Moreover, a code generator is already free to apply short-cuts in the case you describe, because the resulting code would be observationally equivalent.

**Comment by JSStats** [comment]
@rossberg-chromium Your example is not equivalent. The actual type of `(if (expr-returning-1) (unreachable) (f64.const 0))` is `f64` in wasm as a constant condition is not considered, and this is not the same as the actual type of `(unreachable)`, would you agree?

My argument does not depend on proving reachability of code, just the type system with it's i32 type with no range limits. We could add range limits to the i32 type and then define the result type based on this and derive that the result of `if` in this example is the same as `unreachable`, but still don't need to exhaustively proving reachability?

If it were not for the strong typing on the results of most operators then wasm could propagate the unreachable type up, for example we could specify `(i32.add (unreachable) (i32.const 1))` as returning the unreachable type too, and compilers will probably want to do so internally for DCE anyway, but a simple wasm compiler might just materialize a fill value for the purpose of avoiding this. For example, effectively emitting `(i32.add (block (unreachable) (i32.const 0)) (i32.const 1))` and continuing with the code generation even though it is not reachable.

This issue is just a note that for the parametric `select` operator that the result is known to be unreachable based on the already defined wasm types if either argument is unreachable. To be specific we already know the following are equivalent (do you agree on these?)

`(select (unreachable) (unreachable) (cond)) == (unreachable)`
`(select (unreachable) (i32.const 2) (cond)) == (unreachable)`
`(select (i32.const 1) (unreachable) (cond)) == (unreachable)`

But the current rules are giving the follow which is not as precise:
`(select (unreachable) (i32.const 2) (cond)) => type i32`
`(select (i32.const 1) (unreachable) (cond)) => type i32`

**Comment by rossberg-chromium** [comment]
On 12 April 2016 at 12:23, JSStats <notifications@github.com> wrote:

> @rossberg-chromium <https://github.com/rossberg-chromium> Your example is
> not equivalent. The actual type of (if (expr-returning-1) (unreachable)
> (f64.const 0)) is f64 in wasm as a constant condition is not considered,
> and this is not the same as the actual type of (unreachable), would you
> agree?
>
Aren't you assuming your conclusion? Currently there is no difference in
typing `if` vs `select`, and the `unreachable` is assigned the type `f64`
in both examples. Which is my point. You are proposing to change one, but
we can't change the other anyways, so compilers still have to be able to
handle this kind of case.

FWIW, maximal precision is never the goal of a type system -- you can
always increase precision indefinitely for the price of more complexity. A
type system is a trade-off between utility and simplicity. And in this case
utility seems tiny at best.
