### ISSUE TITLE
Reconsider the order of evaluation of the value and address arguments to the store operators?

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/design#651]
Looking at the sexpr-wasm stack machine, in relation to the store operators, shows that it has to pop the value and then push it back on the stack at the end of the operation since the value is returned. If the value were before the address then this could be avoided.

With multiple-value expressions the result of a store needs to be defined as either a single value or all the values of the store-value expression? If all the values were passed through then this stack machine would need to move them all.

There is a similar issue in defining the result of the `set_local` operator. Should it return a single value or all the values of the argument value expression? But in this case there is no address argument to work around.

It would not appear to match the asm.js style well for the values to be evaluated before the address as the JS precedence rules seem to evaluate the left-hand-size address first, and the same might apply for translated C. But might there be any merit in changing the order of evaluation of the value and address?

**Comment by rossberg-chromium** [comment]
I think there has been consensus all along that even with multi-values, we don't want to introduce multi-value variables or loads/stores. For one, they would add a lot of complexity to the memory model, esp considering threads.

**Comment by JSStats** [comment]
@rossberg-chromium Yes I agree regarding multiple values, but this issue is not about storing multiple values in local variables. This issue is just as relevant for a single value. In a stack machine, having the value after the address requires it be pushed back on the stack at the end of the operation, whereas if the value were first then only the address would need to be popped.

**Comment by JSStats** [comment]
In support of the current order, the last argument being the value helps from the perspective of using the result type of the last operator to help predict store operator. The preceding operator will likely load the value so its type predicts a f32 or f64 store or one of three i32 or i64 stores. This might be useful for a compressor of a post-order encoding or a linear sequence of register operators. Changing the store operators to return no values would also have addressed the concern here https://github.com/WebAssembly/design/issues/655
