### ISSUE TITLE
export of memory

### ISSUE THREAD

**Issue by kpmy** [WebAssembly/design#673]
Hi, i'm making a tool for handling with wast entities, with some validation within, etc. So I'm reading /design repo and /spec repo, but I still can not find any information about `(export <string> memory)` expression for module. 
What should it mean for runtime environment?

**Comment by lukewagner** [comment]
You're right that the explanation of memory exports is pretty spotty in the design repo.  Right now, `export` corresponds to marking linear memory as [externally aliasable](https://github.com/WebAssembly/design/blob/master/Modules.md#linear-memory-section).  After #659 merges, my next target is to give a full account of aliased memory, in particular describing it via exports (and, additionally, imports).

The basic answer, though, is that, like imported/exported functions, the interpretation of exported (and, soon, imported) memory is up to the host environment.  On the web, if you export memory, then JS will be able to get an `ArrayBuffer` that aliases linear memory.  But a different host environment might represent exported memory differently or ignore it entirely.

**Comment by kpmy** [comment]
OK, I see. Is it possible that syntax of memory export expr will change after these changes?

**Comment by lukewagner** [comment]
Within the s-expr language, it shouldn't change but note that the whole current s-expr text format is [temporary](https://github.com/WebAssembly/design/blob/master/TextFormat.md#official-text-format), so I'd plan for a major shift at some point in time over the next few months.
