### ISSUE TITLE
Opcode Expansion Plans?

### ISSUE THREAD

**Issue by BSalita** [WebAssembly/design#688]
Are there plans for how new opcodes will be implemented? I'm sure new opcodes will be added after V1. The most obvious way to implement new opcode ranges is to specify one or more opcode bytes that signal a 2nd byte range follows.

**Comment by jfbastien** [comment]
Yes, the binary format is still changing but before MVP we intend to have an opcode table so each .wasm defines its own numbering. We'll likely use LEB128 for opcodes, so no need for any more extension scheme.

FF already has the SIMD opcodes supported, which pushes it past single-bytes.

Closing for now, feel free to reopen if that doesn't address questions.
