### ISSUE TITLE
make shifts counts i32

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/design#699]
would it make sense to make all shift counts i32? and rotate counts as well?

**Comment by taisel** [comment]
I'm assuming this won't blow up ISA specific optimizations? In particular, ARM's embedded shift/rotate constants in the instruction itself.

**Comment by sunfishcode** [comment]
I think we would get efficient code either way, on x86, ARM, and other popular architectures.

Having shift count operand types match the shift types, as we do now, makes them consistent with most other binary operators, which is slightly nice. Are there other advantages or disadvantages to consider?

**Comment by wanderer** [comment]
mem ops for wasm32 always take i32 for the location since i32 can address the entire mem range. It was my natural tendency to try and use i32 for shifts to since I thought same idea would appl... so i guess its more of a human thing

**Comment by sunfishcode** [comment]
wasm32 memory uses 32-bit indices, wasm64 memory uses 64-bit indices. That is somewhat similar to how i32 uses 32-bit shift counts, and i64 uses 64-bit shift counts.

Admittedly, that's not a particularly strong argument, but overall there don't seem to be strong arguments here either way.
