### ISSUE TITLE
JS API - make modules chainable

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/design#700]
It would be nice if you could easily chain wasm modules together with import/exports. Like so
```
const modA = WebAssembly.compile(buffer) 
const modB = WebAssembly.compile(buffer) 

const instA = new WebAssembly.Instance(modA)
const instB = new WebAssembly.Instance(modB, instA, ...)
```
And optionally namespace could be used
```
const instB = new WebAssembly.Instance(modB, {mymod: instA})
```

**Comment by lukewagner** [comment]
IIUC, that use case is supported by what's in JS.md today, with a few tweaks:
* `WebAssembly.compile` returns a promise; if you want synchronous compilation like in your example, you'd write `new WebAssembly.Module(buffer)`.
* Exports are available on the `exports` property of a `WebAssembly.Instance`, so to chain together you need to pass `instA.exports`, not `instA`.
* Namespacing is mandatory, so you have to write `{mymod: instA.exports}`.

Putting that together, JS.md should let you write:
```
const modA = new WebAssembly.Module(buffer1);
const modB = new WebAssembly.Module(buffer2);
const instA = new WebAssembly.Instance(modA);
const instB = new WebAssembly.Instance(modB, {mymod: instA})
```

**Comment by wanderer** [comment]
@lukewagner  JS.md make it looks like namespacing is optional in the sample API usage. So we can do this now
```
const instB = new WebAssembly.Instance(modB, {mymod: instA.exports})
```
which is cool..  But it might be nice if `WebAssembly.Instance` could take and use `instA` directly somehow.  One reason is for i64 params and returns... we can't use them now and perhaps for awhile in JS. If `WebAssembly.Instance` could use another module directly for imports then ideally i64 values would work between the two modules.

**Comment by lukewagner** [comment]
Actually, when I said namespacing is "mandatory" above that wasn't quite right; JS.md allows you to write either:
```
{foo:() => {}, bar:() => {}}
```
or
```
{foo:{p1:() => {}, p2:() => {}}, bar:{p1:() => {}, p2:() => {}}
```
But I think that's orthogonal to what you're talking about: a `WebAssembly.Instance` *can* use `instA` "directly", that's what I'm showing in my example above.  To be clear: if one wasm instance imports the exports of another wasm instance, there is no thunk through JS.

**Comment by wanderer** [comment]
thanks @lukewagner
