### ISSUE TITLE
Bitwise (inversion/negation/not) or one's complement

### ISSUE THREAD

**Issue by cjlarose** [WebAssembly/design#701]
Bitwise NOT is a pretty common operation. It'd be nice to have `i32.not` and `i64.not`. Right now, this can be calculated by `(i32.sub (i32.sub (i32.const 0) $x) (i32.const 1))`, or more concisely by `(i32.xor $x (i32.const -1))`, if the representation of `-1` is guaranteed to be the bitstring of all `1`s, though I don't know if this is true.

**Comment by sunfishcode** [comment]
Bitwise not can indeed by implemented by `xor` with `-1`.

See https://github.com/WebAssembly/design/issues/379 for further discussion of this issue.
