### ISSUE TITLE
add reference for "two-level namespacing"

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/design#706]
... and reference it anywhere we refer to that term in the docs.

**Comment by flagxor** [comment]
Can we clarify what this issue is for?

**Comment by jfbastien** [comment]
@flagxor: https://github.com/WebAssembly/design/pull/682#discussion_r66512116

**Comment by jfbastien** [comment]
@lukewagner tag :)

**Comment by lukewagner** [comment]
As the original requester, do you have a particular reference in mind?  I don't see any canonical-looking Wikipedia entry or other search result.  I'm fine closing this since I don't think people are stumbling over this.

**Comment by jfbastien** [comment]
OK sounds good.
