### ISSUE TITLE
GC struct and array types passing to and from JS and Typed Objects proposal status

### ISSUE THREAD

**Issue by chicoxyzzy** [WebAssembly/design#715]
It's [said](https://github.com/WebAssembly/design/blob/master/GC.md#native-gc) that

> The GC struct and array types could be passed to and from JavaScript by reflecting the WebAssembly GC objects in JavaScript using the Typed Objects proposal.

Typed Objects proposal [was removed](https://github.com/tc39/ecma262/issues/223) from stage 0 as inactive because there is currently [no champion for it](https://github.com/dslomov/typed-objects-es7/issues/16#issuecomment-224898130).

I've created this issue to track progress of Typed Objects proposal.

**Comment by lars-t-hansen** [comment]
There has been some work on TO at Mozilla during the last half year, but not enough to present it.

There have also been some objections to TO as being redundant relative to optimized representations for JS, but I expect WebAssembly will change the calculus on that.

**Comment by jfbastien** [comment]
The [GC proposal](https://github.com/WebAssembly/gc) should take care of this.

**Comment by milindsmart** [comment]
Can anybody shed light on what proposal is tracking adding direct DOM access to wasm? [GC is already done](https://github.com/WebAssembly/proposals/issues/16) and everyone seems to refer to GC as synonymous with DOM. Now where is the DOM?

**Comment by mrgzi** [comment]
@milindsmart I've been wondering the same thing all day, and came across to your comment :)

**Comment by rossberg** [comment]
@milindsmart, @mrgzi, the relevant part that got split off from the GC proposal early on and already made it into Wasm 2.0 as released a few years ago are _reference types_. In particular, _externref_ was added as a new value type that allows JavaScript objects to be handed to Wasm code and back.

That addresses the first bullet in the issue you linked to. Addressing the second bullet was never intended to be part of the GC proposal itself, but rather be enabled by it — the issue description is a bit misleading in that regard.

Based on externref, there is an active [proposal](https://github.com/WebAssembly/js-string-builtins/blob/main/proposals/js-string-builtins/Overview.md) for providing direct access to JavaScript strings. This isn't DOM objects, but the notion of _builtins_ that it introduces is a blueprint for further embedder-specific functionality, like other JavaScript or Web interfaces.

Of course, for something like a full DOM interface to happen concretely, somebody would need to volunteer to start the actual work of designing, implementing, and championing it. Wasm is an open standard, so if either of you is interested in taking the initiative, the group would certainly be interested. :)

**Comment by milindsmart** [comment]
Thanks @rossberg, this info on current situation wasn't available till now (or maybe just not easy to grasp from existing material for lurkers/observers rather than implementers - like that issue description). 

[Another](https://github.com/WebAssembly/component-model/issues/31) [couple](https://github.com/WebAssembly/gc/issues/346) of issues where I commented on similar lines.

I would need to read up/gear up a lot more to try :)
