### ISSUE TITLE
More regularity in the bytecode order

### ISSUE THREAD

**Issue by drom** [WebAssembly/design#722]
Current order of bytecodes inthe WASM binary format looks spontaneous. Operations of different classes / types / arity are wildly interleaved. I think it might be beneficial to group them by similarities and align these groups to the  more natural bit boundaries. Here are some potential benefited I see:
- simplified decoding process. Where certain group of bytecodes can be decoded by applying binary mask.
- easier to add / remove optional instruction subsets for machines with/without floating point? SIMD?
- having some extensibility margin in each subgroup for the additional operations to come.
- aesthetics?

Here is current 2D bytecode table to illustrate the point.
https://github.com/drom/wast-spec/blob/master/isa-table.svg

**Comment by taisel** [comment]
I presumed they should be grouped by serial execution association (for cache line reasons) in general code rather than legibility, although the two probably go hand-in-hand. Any charts for contemporary performance analysis of table ordering vs. unordered?

**Comment by titzer** [comment]
They are roughly grouped into control, miscellaneous, and then simple operators.

It's probably a good idea to regroup them based on some measured data, like compressability. I doubt the order makes any difference for decoding performance.

**Comment by jfbastien** [comment]
This has been fixed.
