### ISSUE TITLE
Clarify start value of index spaces

### ISSUE THREAD

**Issue by ddcc** [WebAssembly/design#724]
AFAIK, index spaces start at zero, but I don't believe this is explicitly stated anywhere. The closest I've found is in discussion of the [start section in Modules.md](Modules.md#module-start-function), which states that the given start node number `is the function index starting from 0`.

**Comment by sunfishcode** [comment]
FWIW, I've now added an explicit mention of this to the prose spec proposal here: https://github.com/WebAssembly/spec/blob/md-proto/md-proto/WebAssembly.md#module-index-spaces

**Comment by flagxor** [comment]
@ddcc Are there other places (like in design), that should be updated?

**Comment by ddcc** [comment]
I think it would also be good to prepend "zero-indexed" to "index spaces" in [Modules.md](../blob/master/Modules.md#modules), but otherwise it looks good to me. (I'm not sure if the prose spec is a replacement for the design repo?)

**Comment by binji** [comment]
Closing, as this is specified [here](https://webassembly.github.io/spec/syntax/modules.html#syntax-index) now.
