### ISSUE TITLE
Remove mutable globals?

### ISSUE THREAD

**Issue by AndrewScheidecker** [WebAssembly/design#732]
I think we should limit globals to immutable values, and translate all mutable globals to immutable addresses into linear memory.

This makes the global functionality entirely orthogonal to the functionality of loads and stores; it supports any data that can be stored in memory: e.g. 8- and 16-bit signed and unsigned integers, structs, arrays; it ensures that future threading support is orthogonal to globals; it means simpler code generation for global variables; and it simplifies WebAssembly runtimes.

The argument for mutable variables seems to be dependent on the future addition of GC reference types, since those types could not be stored in linear memory. However, such an addition remains speculative, and would have a large impact on how globals are implemented; not to mention other parts of a WebAssembly runtime! I believe it would be best to start with immutable globals only, and only add mutable globals when necessary to support types that can't be stored in aliased memory.

If mutable variables are removed, then it's also no longer necessary to support the explicit declaration of globals. Instead, immutable globals could be introduced by other declarations: e.g. relocatable data segments and imports.

```
(segment $global_var_addr "\00")
(export $global_var_addr ...)
(import $imported_global_addr ...)
...
(i32.store8
    (immutable $global_var_addr)
    (i32.load16_s offset=100 (immutable $imported_global_addr))
    )
```

**Comment by titzer** [comment]
Mutable globals have the advantage that they cannot be aliased to the linear memory. When WASM gets threads, we'll want to add thread-local storage (TLS), and it would complete a natural hierarchy of storage locations: local to a function, local to a thread, and global. It makes sense to me that these don't alias each other and all use the same type system.

**Comment by AndrewScheidecker** [comment]
Yes, mutable globals that don't alias linear memory permit some additional optimization, but the primary use case for that are things like the aliased stack pointer; which needs to be a thread-local rather than global anyway.

Do you mean to say that thread-local memory shouldn't alias the "global" linear memory? I can see how there might be some small optimization opportunities there, but I don't see how that would work with, for example, taking the address of a C thread-local variable.

I think thread-local variables can be implemented through immutable global values in the same way as mutable globals. However, instead of being immutable global addresses, they are immutable global offsets relative to a thread-local memory base address. A data segment would have a flag that should be allocated in thread-local memory. A dynamic loader would look at the thread-local data segments in a module, allocate offsets for them within thread-local memory, and bind the corresponding immutable values to those offsets. Whenever a thread is created, it would iterate over the loaded thread-local data segments, and clone their data into the memory allocated for the thread's thread-local storage.

I saw an interesting trick in Cliff Click's [Bits of Advice for the VM Writer](https://ia601503.us.archive.org/32/items/vmss16/click.pdf) (slide 37). He allocates stacks aligned to 2MB, and puts thread data at the bottom, which allows deriving TLS addresses by just masking off the bottom bits of the stack pointer. Using this trick, it would be possible for WebAssembly to support thread-local storage entirely through the above mentioned data segment flag, and a single built-in thread-local variable: the aliased stack pointer.

**Comment by lukewagner** [comment]
While, in the general case, we'll need to keep aliased globals and thread-local variables in memory, I think in the more-common unaliased case, we can store the thread-local directly in the engine's internal TLS array (that it'll need to maintain anyway for various other impl-specific thread-locals).  I don't think we'll be able to do that with the scheme you're describing.

**Comment by JSStats** [comment]
I also support limiting the globals to being immutable. The use case under which they are being added appears to have them initialized as constants, and there appears to be no use case for them being mutable that can not be handled by storing them in the linear memory?

It will cost implementations to have to support mutable globals. They will need a pointer to the area in which they are stored and this pointer can not be shared with the thread local storage and for performance this will require a dedicated register which is a very high cost for a unnecessary feature. If mutable globals are supported and web developers use them then all wasm runtimes will have to carry this cost.

The points raised about threat local storage are just not relevant, they are different types of storage, and we will want mutable thread local storage, and no use case for immutable thread local storage comes to mind that could not be handled by immutable globals.

Mutable globals could always be added in future and might be more appropriate for a wasm variant with support for objects, but in any case being able to define constant globals would remain a useful feature.

If there is an objective use case for mutable globals then please articulate it? if there is an objective and compelling performance benefit then please demonstrate it?

**Comment by AndrewScheidecker** [comment]
BTW the [future feature for mutable globals](https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#mutable-global-variables) is out of sync with the recent return of mutable globals.

**Comment by pizlonator** [comment]
It's too late for this.
