### ISSUE TITLE
Do we require NaNs that come from JavaScript to be canonicalized?

### ISSUE THREAD

**Issue by gahaas** [WebAssembly/design#746]
As far as I understand the design docs we do not require at the moment that NaNs which come from JavaScript are canonicalized. Is this intentional or should we add to the spec that NaNs which come from JavaScript to WebAssembly have to be canonicalized?

**Comment by sunfishcode** [comment]
Correct, WebAssembly doesn't require that NaNs which come from JS (or any other external environment) are canonicalized. This is intentional; WebAssembly is ok with non-canonical NaNs everywhere, and doesn't even define a canonical form for itself.

**Comment by lukewagner** [comment]
Even in JS, NaNs aren't required to be canonicalized and for the most part it's unobservable; [GetValueInBuffer](https://tc39.github.io/ecma262/#sec-getvaluefrombuffer)/[SetValueInBuffer](https://tc39.github.io/ecma262/#sec-setvalueinbuffer) just *allow* for some amount of NaN canonicalization to happen in engines that use NaN-boxing.

**Comment by gahaas** [comment]
When I said canonical NaN, I meant a NaN where the most significant bit of the fraction field is, and all remaining bits of the fraction field are zero. All other NaNs I call non-canonical NaNs.

The rationale doc says that we want to support NaN boxing, which means in my opinion that we should state clearly where non-canonical NaNs in the state of a WebAssembly instance can come from.

Assume a state of a WebAssembly instance (memory + stack) which does not contain any non-canonical NaNs. If there is no interaction with JavaScript, then the only ways a non-canonical NaN can enter the state of a WebAssembly instance is by reinterpreting an integer value as a float, either with the reinterpret instructions, or by loading an integer value from memory as a float. If there is some interaction with Javascript, then return values or parameters from JavaScript can also be non-canonical NaNs.

Are you saying that if someone wants to keep control over all non-canonical NaNs in the state of their WebAssembly instance, that they have to canonicalize all NaNs that come from JavaScript by themselves? Should we say that in the rationale?

**Comment by rossberg-chromium** [comment]
In particular, an individual module cannot distinguish, and has no direct control over, which imports are JS functions and which are Wasm functions at runtime. If the model is that all such NaN canonicalisation is ensured by producers, wouldn't they potentially need to defensively canonicalise _all_ results from import calls?

**Comment by sunfishcode** [comment]
Yes, I agree that it'd be useful to document this, with something like: The places a non-canonical NaN can be materialized are:
 - load
 - reinterpret
 - a return value of a call to an imported function
 - an argument of an exported function

And, arithmetic operations given non-canonical inputs can return non-canonical results.

The rationale for having this many places where canonical NaNs can be created is primarily that it's a tradeoff; we don't want to pay the costs of canonicalization in applications that don't need it.

And, there are situations where canonicalization is undesirable. If someone is using NaN boxing and wishes to divide their application up into multiple modules (eg. as libraries), or marshal non-canonical NaNs through linear memory for some reason, enforced NaN canonicalization at module boundaries would limit their flexibility. As another example, it's desirable that load+store be bit-preserving operations in all cases.

**Comment by jfbastien** [comment]
Has this been addressed? IIUC some tests are still missing from the spec repo?

**Comment by sunfishcode** [comment]
I submitted #955 to document that NaNs coming from JS may not be canonicalized.

**Comment by sunfishcode** [comment]
This is now fixed in https://github.com/WebAssembly/design/pull/955.
