### ISSUE TITLE
Consolidating info on the type system and its semantics

### ISSUE THREAD

**Issue by distransient** [WebAssembly/design#747]
Information on the type system is scattered across each of the documents, would it be a good idea to put it all in one section/file?

**Comment by jfbastien** [comment]
What do you have in mind exactly? [AstSemantics](https://github.com/WebAssembly/design/blob/master/AstSemantics.md) seems to hold everything, but is indeed spread out in that document. Or are there things outside that you'd consolidate?

**Comment by distransient** [comment]
Consolidating the type information in AstSemantics would be helpful but also (possibly briefly) mentioning the type requirements of things like indirect calls and module definitions in that section could help as well.

**Comment by distransient** [comment]
Going to give a stab at this once 0xc lands.

**Comment by distransient** [comment]
Ok I lied... After reading through what's on the plate in #813, I'm going to wait a *little* longer before giving this a try.

**Comment by binji** [comment]
The type system is now fully described in the [text spec](https://webassembly.github.io/spec/).

**Comment by distransient** [comment]
Yep, this is from a ~land before time~ time long past!
