### ISSUE TITLE
Discuss implementation defined behavior

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#75]
Opening this bug so I go back and write documentation about this.

We want to avoid all forms of undefined behavior which can lead to nasal demons, and instead discuss how the wasm platforms allows for implementation defined behavior and what acceptable behavior is.

C/C++ UB is progressively refined by the compiler, and can be affected by tools such as sanitizers. The wasm platform then nails down some behaviors and leaves other open to the implementation. The implementation can then decide, based on the OS/ISA it's executing on, what the behavior is.

Note that behaviors include: "what happens if an enum is out of range", "shift by bitwidth or larger", "what do out-of-bounds accesses do", "what about unaligned accesses", "data races", and much more exciting things!

As a reference PNaCl has a [non-comprehensive list of undefined behavior](https://developer.chrome.com/native-client/reference/pnacl-undefined-behavior).

**Comment by binji** [comment]
Closing along with #107 being closed.

**Comment by jfbastien** [comment]
This issue was actually addressed by the following text:
https://github.com/WebAssembly/design/blob/master/CAndC%2B%2B.md#undefined-and-implementation-defined-behavior
