### ISSUE TITLE
Include types, tables, labels, globals, and memories in binary format name section

### ISSUE THREAD

**Issue by AndrewScheidecker** [WebAssembly/design#750]
I realize the name section is probably seen as a stopgap for a more expressive metadata section, but it would be nice if it could round trip the names that are in the text format. At a glance, it's missing names for imports, types, tables, and labels.

**Comment by sunfishcode** [comment]
It's also missing names for globals and memories.

And as a minor nit, there are no distinct names for imports; imports are imported into their respective entities' index spaces, such as the function index space, so for example the existing "name" section covers imported functions.

So to summarize, the wasm binary format currently doesn't have names for:
 - types
 - tables
 - labels
 - globals
 - memories

**Comment by wllang** [comment]
Yes the import names would be converted by the function names. Could this issue subsume https://github.com/WebAssembly/design/issues/861 and close that? Could the local names for functions be applied to the function arguments and thus also the import argument names? None of this is a show stopper.

**Comment by jfbastien** [comment]
@AndrewScheidecker could you file a PR for this?

**Comment by AndrewScheidecker** [comment]
> @AndrewScheidecker could you file a PR for this?

Will do.

**Comment by nomeata** [comment]
JFTR, this seems to have evolved into a proposal at https://github.com/WebAssembly/extended-name-section

**Comment by binji** [comment]
Thanks for that info @nomeata! Let's close this issue then.
