### ISSUE TITLE
call_import removed in version 0xC

### ISSUE THREAD

**Issue by wibblymat** [WebAssembly/design#757]
The binary encoding of `call_import` [was removed](https://github.com/WebAssembly/design/commit/e3c2bcc6c33727bee95d0fa0621eb32bb19d33b4#diff-7c076c52f23f4a770974fb209259f34bL379) in the 0xC branch, but there was no corresponding documentation update.

I see lots of changes to imports and tables, but none that suggest that you would now be able to `call` or `call_indirect` an imported function.

Was this removed by mistake, or is the new way to call an imported function undocumented?

**Comment by lukewagner** [comment]
[Function imports](https://github.com/WebAssembly/design/blob/master/Modules.md#imports) are now added to the [function index space](https://github.com/WebAssembly/design/blob/master/Modules.md#function-index-space) which is indexed by [`call`](https://github.com/WebAssembly/design/blob/master/AstSemantics.md#calls), the [elements section](https://github.com/WebAssembly/design/blob/master/Modules.md#elements-section) (so you can place function imports into tables that you can then call via `call_indirect`), and [function exports](https://github.com/WebAssembly/design/blob/master/Modules.md#exports).

**Comment by wibblymat** [comment]
Ah, got it, thanks!
