### ISSUE TITLE
Unify local variables with stack values?

### ISSUE THREAD

**Issue by qwertie** [WebAssembly/design#759]
Having little experience with Wasm and stack machines, this idea may be silly so feel free to shoot it down. The idea is to "unify" the local variables with the new value stack, sharing a numeric space. `get_local $N`  and `set_local $N` would be able to read from parameters _and_ from the value stack. If there are 5 parameters and 15 other values on the stack (say, 8 "locals" and 7 "transient values"), the parameters are numbered 0..4, and the rest are 5..19. New values are added to the end of the list, so `f64.const 2.5`  effectively creates a new variable `$20 = 2.5`.

The value N could be negative or non-negative;
- non-negative integers would access "local variables". if there are M parameters, `get_local (M-1)` reads the last parameter and `get_local M` reads the first local variable that is not a parameter.
- negative integers would access "stack items". If there are 20 items numbered 0..19, then `get_local -1` is an alias for `get_local 19`.

Having a single "place" to store "local values" might make Wasm interpreters easier to write (no need for `pick` as a distinct concept from `get_local`). Having two ways to refer to the same "variable" keeps Wasm easy to produce (because a producer can continue imagining that "locals" and "stack values" are separate concepts), while also aiding compression, because most indices will be close to zero (either positive or negative).

**Comment by JSStats** [comment]
@qwertie A possible performance problem is that once the stack values are allowed to be mutated the need to be all checked at each control flow merge point, just as all the local variables are checked. The reason to have stack values is to optimize for single use values consumed in stack order. If the stack elements are just as flexible as the local variables (but of dynamic depth) then perhaps some of the efficiency is lost.

The sexpr-wasm-prototype interpreted might have put the locals on it's internal stack, but an interpreter does not have the cost of checking them all at control flow merge points.

Perhaps the `pick` operator could use the sign to select between an index relative to the start of the function versus and index relative to the top of the stack. I think such encoding decisions are somewhat of a separate matter than deciding to add `pick`.

**Comment by rossberg-chromium** [comment]
@qwertie, this suggestions boils essentially moves one bit of information from the opcode to the index immediate. That is weird because that bit is _not_ orthogonal to the opcode -- in particular, `set_local` and `tee_local` are not applicable to the stack, only `get_local` would be. It also introduces aliasing into the index space, which seems very undesirable.

**Comment by JSStats** [comment]
@rossberg-chromium From what I understand of the proposal it to move the locals onto the stack (to unify the stack and locals) such as done here https://github.com/WebAssembly/sexpr-wasm-prototype/blob/master/src/wasm-interpreter.c#L688 where `set_local` modifies a value on the stack. Then `tee_local` would write to the stack and not pop a value.

Having two different relative index spaces seems useful for `get_local` `set_local` and `tee_local` and it might help encoding efficiency as indexes relative to the top-of-stack and start-of-function-stack are likely the most common.

Problem I see is that it will require the SSA decoder to check all stack elements and track them at each control flow merge point. Also not sure about a structure text format, but it might be possible, perhaps it just introduces lexical variables.

**Comment by qwertie** [comment]
@rossberg-chromium I assume you're saying that `set_local` and `tee_local` _shouldn't_ be applicable to the stack, only to "locals". Note that the "aliasing" is only an illusion; when decoding the instruction stream you'll know at any given point how many variables exist and therefore could normalize the indices into negative or positive, whatever works best for the implementation. Anyway, thanks guys for letting me know what's wrong with my idea.
