### ISSUE TITLE
Will possible make compiled functions in webassembly?

### ISSUE THREAD

**Issue by acterhd** [WebAssembly/design#760]
Hello. WIll possible do like this? 
```
let func = wasm("..."); //some hieroglyphs with webassembly code, that means simple add operation
```

**Comment by lukewagner** [comment]
Yes, if you're talking about JS, you can do that with the API described in JS.md which is part of the wasm MVP in browsers. E.g., assuming `codeBytes` is a module exporting a function `foo`:
```
let foo = new WebAssembly.Instance(new WebAssembly.Module(codeBytes)).exports.foo;
```

**Comment by acterhd** [comment]
I read some spec, but not found about Uint8, Uint16, Int8, Uint8.... Where?

**Comment by lukewagner** [comment]
WebAssembly doesn't have these as local types.  Instead, 1- and 2-byte values can be loaded from memory and sign-extended appropriately into the primary `i32` and `i64.  See [Linear Memory Accesses](https://github.com/WebAssembly/design/blob/master/AstSemantics.md#linear-memory-accesses)

**Comment by acterhd** [comment]
How many symbols required for minimal wasm function?

**Comment by acterhd** [comment]
I heard early been "ui32", where is now?!

**Comment by binji** [comment]
> How many symbols required for minimal wasm function?

Not sure what you mean by symbols. A WebAssembly function cannot be compiled in isolation, it needs to be defined in a WebAssembly module. In the current binary format, the minimal module is just the 8-byte header, as all sections are optional. See [High-level structure](https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#high-level-structure).

> I heard early been "ui32", where is now?!

WebAssembly does not have unsigned types, just operators that treat their operands as unsigned. See for example [32-bit Integer operators](https://github.com/WebAssembly/design/blob/master/AstSemantics.md#32-bit-integer-operators).

**Comment by acterhd** [comment]
Would be better will if JS improved (added operator overloading, etc. )  and hybridized with webassembly. Will cool language. :)

**Comment by jfbastien** [comment]
Looks answered?
