### ISSUE TITLE
Adding support for JS ASTs. 

### ISSUE THREAD

**Issue by carlsmith** [WebAssembly/design#762]
This is something that has presumably been discussed already, but I'm struggling to find anything, so would like to apologise for any noise, and ask of anyone could point me in the right direction please.

It would be a lot easier to create projects like CoffeeScript if we could parse our code into a JavaScript AST, and pass that to the JS engine, especially if the engine supported executing the AST for testing, and compiling it to bytecode that could also be executed later, for production.

Is there a discussion of something along these lines?

Thanks for your time, and again sorry for posting this here.

**Comment by JSStats** [comment]
fwiw a binary AST encoding of JS does not seem part of wasm.

**Comment by carlsmith** [comment]
Thanks. I couldn't find anything either, but just assumed it would've come up before. It's not directly to do with WASM, but still seemed relevant here.

I don't understand this stuff very well, but thought that WASM is basically going to support languages like C first, and later hopefully add features like GC to maybe support something like Python, and thought that languages that are similar to JavaScript should continue to compile to JS. It seems natural that there'd then be something like WASM for doing that, but perhaps not.

It should be relatively easy for browsers to support accepting a JavaScript AST instead of source code, and would make AltJS languages lighter and easier to get right.

It's a shame that serving ASTs as JSON text would make scripts much bigger. If we were able to use JavaScript engines to compile JS ASTs to JS bytecode, it would solve that problem, but you'd need to do something about view-source again.

It might be possible for developers to bundle an AltJS parser with each application, cache it in local storage, and use it to parse their source code directly. The parser could be written in C now days, but it'd be nicer if we could still use JS and a native parser API that provides generic constants like `uppers` and `digits`, just so custom parsers can be smaller, and helper functions like `isName`, so they can be reasonably fast still too.

It's late, I'm bikeshedding, and you get the idea. It just seems like there should be an effort to make AltJS languages feel more first class.

**Comment by JSStats** [comment]
@carlsmith There might be scope in the pipeline to be pondered for the upper layers of wasm to help support pipelines that target JS rather than wasm, not sure. Perhaps some streaming extensions, and caching extensions etc.

**Comment by kripken** [comment]
@carlsmith: the idea of browser support for JS ASTs has come up in the past (in a non-wasm context), and the main downside is that it's not clear which AST should be used - different JS engines have different ones. Standardizing one might constrain some JS engines by basically mandating something about their internal implementations. Or, if they ignore it internally and just treat it as a way to compress downloads, it's not clear the gzipped AST would be significantly smaller than gzipped JS anyhow.

Standardizing an AST also means additional work as the JS language evolves, it's another thing to spec out for each new feature.

**Comment by rossberg-chromium** [comment]
Standardising a JS AST would be a task for TC39 (where it actually has been discussed already), not WebAssembly.

**Comment by carlsmith** [comment]
@rossberg-chromium - You're right, and I did manage to find the discussion in the end too. Again, sorry for the noise in this repo, and thanks to everyone for their time here, and for the awesome work you guys are doing with WASM.
