### ISSUE TITLE
Debugging WebAssembly

### ISSUE THREAD

**Issue by konsoletyper** [WebAssembly/design#773]
I have a question, which is a little irrelevant to this particular repository, but it's completely unclear to me where I can ask such questions. Currently, there's no official way to debug WebAssebly, except for one PR on this repository. But what about early adopters outside of WebAssembly community who want to make their own compilers emitting WebAssembly? They have to debug WebAssebmly generated by their compilers. There are several tools like reference implementation `wasm` or `wasm-shell` from `binaryen`, but they are poorly documented and I could find no way to debug my compiler's WebAssembly output, except for calling `spectest.print` which only prints numbers. It's quite hard to debug application inserting `spectest.print` invocations and then parsing megabytes of stdout logs. I'd like to have something similar to `gdb`, allowing me to put breakpoints and watchpoints, examining memory, etc. Is there something I'm missing?

**Comment by jfbastien** [comment]
This is being tackled incrementally with name section, source map, and eventually something like DWARF. Closing.
