### ISSUE TITLE
Swap f64 and f32 opcodes.

### ISSUE THREAD

**Issue by mbebenita** [WebAssembly/design#776]
The order in which `f64` and `f32` are defined seems wrong. I would have expected `i32.const`, `f32.const`, `i64.const` and `f64.const`. Or even `i32.const`, `i64.const`, `f32.const` and `f64.const`. Currently, these are defined as:

| Name | Opcode | Immediates | Description |
| ---- | ---- | ---- | ---- |
| `i32.const` | `0x10` | value : `varint32` | a constant value interpreted as `i32` |
| `i64.const` | `0x11` | value : `varint64` | a constant value interpreted as `i64` |
| `f64.const` | `0x12` | value : `uint64` | a constant value interpreted as `f64` |
| `f32.const` | `0x13` | value : `uint32` | a constant value interpreted as `f32` |

**Comment by sunfishcode** [comment]
This is also being tracked in https://github.com/WebAssembly/design/pull/696. It's currently not scheduled to be fixed in 0xc, but should be easy to fix after that.
