### ISSUE TITLE
Is explicit call arity necessary?

### ISSUE THREAD

**Issue by AndrewScheidecker** [WebAssembly/design#777]
In the binary encoding, the arity of `call`, `call_import`, and `call_indirect` is provided as an immediate operand. However, compilation of the call must check the exact signature of the callee's function, so this arity immediate is both redundant and insufficient. Can it be removed?

**Comment by titzer** [comment]
It is slated to be removed in binary_0xc along with the other stack machine changes.

**Comment by AndrewScheidecker** [comment]
Great!
