### ISSUE TITLE
Silly question about alignment

### ISSUE THREAD

**Issue by wibblymat** [WebAssembly/design#782]
I'm coming from a position of relative ignorance about this sort of thing, so apologies if this is either trivial or very difficult to explain to a newbie.

The load and store operators accept an alignment value. It explicitly doesn't make any difference to the *semantics* of the operation, according to the design.

Looking at it, I also can't see how it makes any difference to *performance*. As best I can tell, if I load an i32 from address 16 then that will ultimately generate an instruction like `MOV EAX, DS:[16]`. Surely this is naturally aligned, regardless of what I set alignment to. If I load an i32 from address 18, that is not naturally aligned. The CPU will have to load two i32s (or an i64) and manipulate it to get the correct value - again, regardless of what I set alignment to.

I assume that alignment really does make a difference, or it wouldn't be in here. Could somebody explain why?

**Comment by sunfishcode** [comment]
On typical x86 hardware architectures, indeed the alignment value doesn't make a difference. However, on some hardware architectures, unaligned accesses can be very slow, or can even trap (which a WebAssembly engine would theoretically have to handle, making it very very slow). On these platforms, the alignment hint tells the engine to use different instructions (if the hardware has different instructions for unaligned accesses) or to explicitly split the access up into smaller parts, to avoid the penalties associated with unaligned accesses.

**Comment by wibblymat** [comment]
Thanks for the explanation!
