### ISSUE TITLE
Polymorphic operators

### ISSUE THREAD

**Issue by AndrewScheidecker** [WebAssembly/design#784]
I count 174 opcodes in use right now. It seems inevitable that there will eventually be more than 256, but in the mean time the number could be reduced substantially by making more operators polymorphic. In addition to freeing up some index space, making the opcodes polymorphic allows the operators to be extended to new types added in the future: e.g. _f16_, _i8_, or _f32x4_.

This would be ad-hoc polymorphism; a little bit different from the existing _parametric_ operators like `get_local` and `select`. However, numeric, integer, and float type classes can be used to specify the domain of some of these operators.

Here's an example that replaces 125 of the opcodes with 56 (which would reduce the total to 105):

| new (polymorphic) | old (i32) | old (i64) | old (f32) | old (f64) |
| --- | --- | --- | --- | --- |
| **num.add** | _i32.add_ | _i64.add_ | _f32.add_ | _f64.add_ |
| **num.sub** | _i32.sub_ | _i64.sub_ | _f32.sub_ | _f64.sub_ |
| **num.mul** | _i32.mul_ | _i64.mul_ | _f32.mul_ | _f64.mul_ |
| **num.div_s** | _i32.div_s_ | _i64.div_s_ | _f32.div_s_ | _f64.div_s_ |
| **num.neg** | _i32.neg_ | _i64.neg_ | _f32.neg_ | _f64.neg_ |
| **num.eq** | _i32.eq_ | _i64.eq_ | _f32.eq_ | _f64.eq_ |
| **num.ne** | _i32.ne_ | _i64.ne_ | _f32.ne_ | _f64.ne_ |
| **num.lt_s** | _i32.lt_s_ | _i64.lt_s_ | _f32.lt_ | _f64.lt_ |
| **num.le_s** | _i32.le_s_ | _i64.le_s_ | _f32.le_ | _f64.le_ |
| **num.gt_s** | _i32.gt_s_ | _i64.gt_s_ | _f32.gt_ | _f64.gt_ |
| **num.ge_s** | _i32.ge_s_ | _i64.ge_s_ | _f32.ge_ | _f64.ge_ |
| **int.div_u** | _i32.div_u_ | _i64.div_u_ |  |  |
| **int.rem_s** | _i32.rem_s_ | _i64.rem_s_ |  |  |
| **int.rem_u** | _i32.rem_u_ | _i64.rem_u_ |  |  |
| **int.and** | _i32.and_ | _i64.and_ |  |  |
| **int.or** | _i32.or_ | _i64.or_ |  |  |
| **int.xor** | _i32.xor_ | _i64.xor_ |  |  |
| **int.shl** | _i32.shl_ | _i64.shl_ |  |  |
| **int.shr_u** | _i32.shr_u_ | _i64.shr_u_ |  |  |
| **int.shr_s** | _i32.shr_s_ | _i64.shr_s_ |  |  |
| **int.rotr** | _i32.rotr_ | _i64.rotr_ |  |  |
| **int.rotl** | _i32.rotl_ | _i64.rotl_ |  |  |
| **int.lt_u** | _i32.lt_u_ | _i64.lt_u_ |  |  |
| **int.le_u** | _i32.le_u_ | _i64.le_u_ |  |  |
| **int.gt_u** | _i32.gt_u_ | _i64.gt_u_ |  |  |
| **int.ge_u** | _i32.ge_u_ | _i64.ge_u_ |  |  |
| **int.clz** | _i32.clz_ | _i64.clz_ |  |  |
| **int.ctz** | _i32.ctz_ | _i64.ctz_ |  |  |
| **int.eqz** | _i32.eqz_ | _i64.eqz_ |  |  |
| **int.popcnt** | _i32.popcnt_ | _i64.popcnt_ |  |  |
| **fp.min** |  |  | _f32.min_ | _f64.min_ |
| **fp.max** |  |  | _f32.max_ | _f64.max_ |
| **fp.abs** |  |  | _f32.abs_ | _f64.abs_ |
| **fp.copysign** |  |  | _f32.copysign_ | _f64.copysign_ |
| **fp.ceil** |  |  | _f32.ceil_ | _f64.ceil_ |
| **fp.floor** |  |  | _f32.floor_ | _f64.floor_ |
| **fp.trunc** |  |  | _f32.trunc_ | _f64.trunc_ |
| **fp.nearest** |  |  | _f32.nearest_ | _f64.nearest_ |
| **fp.sqrt** |  |  | _f32.sqrt_ | _f64.sqrt_ |
| **i32.trunc_s** |  |  | _i32.trunc_s/f32_ | _i32.trunc_s/f64_ |
| **i32.trunc_u** |  |  | _i32.trunc_u/f32_ | _i32.trunc_u/f64_ |
| **i64.trunc_s** |  |  | _i64.trunc_s/f32_ | _i64.trunc_s/f64_ |
| **i64.trunc_u** |  |  | _i64.trunc_u/f32_ | _i64.trunc_u/f64_ |
| **i32.wrap** | _i32.wrap/i64_ |  |  |  |
| **i64.extend_s** | _i64.extend_s/i32_ |  |  |  |
| **i64.extend_u** | _i64.extend_u/i32_ |  |  |  |
| **f32.convert_s** | _f32.convert_s/i32_ | _f32.convert_s/i64_ |  |  |
| **f32.convert_u** | _f32.convert_u/i32_ | _f32.convert_u/i64_ |  |  |
| **f64.convert_s** | _f64.convert_s/i32_ | _f64.convert_s/i64_ |  |  |
| **f64.convert_u** | _f64.convert_u/i32_ | _f64.convert_u/i64_ |  |  |
| **f64.promote** |  |  | _f64.promote/f32_ |  |
| **f32.demote** |  |  |  | _f32.demote/f64_ |
| **f32.reinterpret** | _f32.reinterpret/i32_ |  |  |  |
| **f64.reinterpret** |  | _f64.reinterpret/i64_ |  |  |
| **i32.reinterpret** |  |  | _i32.reinterpret/f32_ |  |
| **i64.reinterpret** |  |  |  | _i64.reinterpret/f64_ |

**Comment by JSStats** [comment]
See also https://github.com/WebAssembly/design/pull/620 and https://github.com/WebAssembly/design/issues/678

The counter argument might be that it adds a little to the decoder overhead, that it will need to dispatch on the type of arguments. Someone needs to prototype this in a high performance decoded and double check the overhead.

It might help the text format too, because then `+` can be used for `num.add` irrespective of the types. A present the text format might need to present `i32.add` rather than `+` if the types are not valid.

**Comment by sunfishcode** [comment]
One mitigating factor here is that potential future types such as `f16` and `f32x4` are expected to be relatively infrequent, relative to the MVP operators, even in programs that use them. It may make sense to put all SIMD opcodes somewhere safely into the multiple-byte opcode space anyway, because many programs don't use SIMD, and even in those that do it's often not a significant percentage of overall size.

**Comment by JSStats** [comment]
It should help the compression too as it eliminates redundant information. A higher level compressor would be doing this anyway so would have the decoding overhead anyway.

**Comment by AndrewScheidecker** [comment]
As mentioned in #791, memory operators could be polymorphic in the address size. This could either be based on an explicit address-size in the type of the memory object, or by simply making work with either 32-bit or 64-bit addresses.

**Comment by AndrewScheidecker** [comment]
Here's a strawman encoding for a polymorphic operator set (I mean this to be illustrative rather than a concrete proposal): https://docs.google.com/spreadsheets/d/1vBiBjNfvoCy2ChGILA7xXe720iJTe_0Nzu5cBizVIzs/edit#gid=898725473

The top 4-5 bits of the first byte of the opcode are a category. If the top bit of the category is 1, then the signature of the operator (including immediates) is independent of the other bits of the opcode.

If the bottom 3 bits of the first opcode byte are `111`, then it is followed by another opcode byte. If the top bit of the second byte is 1, then it is followed two more opcode bytes. This provides 224 1-byte opcodes, 4K 2-byte opcodes, and 268M 4-byte opcodes. I think that having a larger 1-byte opcode space is worth a departure from the use of LEB128 in other parts of the standard.

> It may make sense to put all SIMD opcodes somewhere safely into the multiple-byte opcode space anyway, because many programs don't use SIMD, and even in those that do it's often not a significant percentage of overall size.

Yes; my proposed application of polymorphic operators in a SIMD extension is that a polymorphic operator like `num.add` could be extended to be an element-wise addition of two SIMD vectors. `f32x4.load` should probably be a 2-byte opcode, but `f32x4.add` doesn't need to be a distinct opcode from `f32.add` or `i64.add`. However, I can see that some of the current scalar operators wouldn't be worth implementing for SIMD types, so this would require a bit more precision than just extending all the polymorphic operators to vectors.

**Comment by JSStats** [comment]
One interaction I did not realise is that `(num.add (unreachable))` would then not have a specific type, or a union type, which would add a little more complexity to the validator, probably more than people want to take on, and probably an area for significant 'spec' challenges getting agreement!

Would this proposal also back out the typing on block signatures, bring them back to just an arity, as the type can be derived.

**Comment by AndrewScheidecker** [comment]
I don't think that this would interact with unreachable code or block signatures any differently than `select`, or even `i32.add`.

> Would this proposal also back out the typing on block signatures, bring them back to just an arity, as the type can be derived.

I think the explicit signatures on control structures are justified, because they can otherwise only be derived from the code following the block start. Resolving polymorphic operators only needs to look at the types of values on the stack pushed by preceding code.

**Comment by pizlonator** [comment]
It's too late for this.
