### ISSUE TITLE
Design document does not conform with ml_proto (but does conform with browsers)

### ISSUE THREAD

**Issue by konsoletyper** [WebAssembly/design#788]
Is binary encoding used by [spec](https://github.com/WebAssembly/spec) repository relevant? It seems it does not agree with design repository, but browser engines do not follow _spec_ as an authoritative source.

Here are issues I found:
1. _design_ states that first `varuint32` field of function in `code` section is the length of function body, then arguments and body, whereas _spec_ states that arguments go first, then length followed by body.
2. _design_ and _spec_ mess 0x12 and 0x13 opcodes.
3. _design_ states that alignment in memory operations is encoded as log2, whereas _spec_ treats alignment as is.

**Comment by rossberg-chromium** [comment]
Spec and design should match, but we're going through a sequence of changes where one or the other has not caught up yet, and where some stuff accidentally landed on master although it should have been on the 0xc branch. (And of course, there might be bugs or oversights.) The goal definitely is that the respective 0xc branches are sync'ed up again before we merge them into master.

**Comment by binji** [comment]
There is now a [spec](https://webassembly.github.io/spec/) that defines this behavior, if there are still concerns it is probably best to create a new issue at https://github.com/WebAssembly/spec.
