### ISSUE TITLE
Relative depth in binary encoding of `br`, `br_if`, etc opcodes is not described clearly

### ISSUE THREAD

**Issue by konsoletyper** [WebAssembly/design#789]
It's a little unclear from the description what `relative_depth` is. I supposed (and was correct) that it's `currentDepth - targetDepth`, where `currentDepth` increases every time we enter a block and decreases every time we leave the block, and `targetDepth` is `currentDepth` recordered as we met the block (but before we incresed `currentDepth`). Also it was not obvious that `loop` increases `currentDepth` by two, as well as `if` increases `currentDepth` as if it was a block. Assuming that `spec`, which states this clearly, is [de-facto not authoritative](https://github.com/WebAssembly/design/issues/788), it's necessary to clarify `relative_depth` in _design_.

**Comment by rossberg-chromium** [comment]
`block`, `loop` and `if` deterimine depth.We recently decided to remove the second label from `loop`, but that's an 0xc change.

**Comment by binji** [comment]
There is now a [spec](https://webassembly.github.io/spec/) that defines this behavior, if there are still concerns it is probably best to create a new issue at https://github.com/WebAssembly/spec.
