### ISSUE TITLE
Support inc_local/dec_local

### ISSUE THREAD

**Issue by axic** [WebAssembly/design#790]
There was as discussion about `i32.inc`/`i32.dec` [here](https://github.com/WebAssembly/design/issues/293).

I would like to revive this issue with the following question: since many CPUs support inc/dec as a separate opcode, are we expecting JITs to do static analysis and replace `(set_local $x (i32.add (get_local $x) (i32.const 1))` with an inc opcode? Or would it make sense considering the inclusion of `inc`/`dec` one more time?

More specifically having `inc_local` and `dec_local` (as opposed to `i32.inc`/`i32.dec`). I think it would be really useful in loops.

**Comment by jfbastien** [comment]
Same as for the other one: I don't think there's much of a point to this. It's easy to detect add / sub with immediate 1 (the JIT doesn't get better with a wasm instruction for it), and inc / dec instructions aren't necessarily a win in performance (so the JIT may not even want to emit inc / dec depending on architecture, e.g. inc / dec cause partial flag sets by preserving CF while add / sub touch all the flags, and lea touches none, and then check Agner for latencies / uops).
