### ISSUE TITLE
Add address type field to memory/table types

### ISSUE THREAD

**Issue by AndrewScheidecker** [WebAssembly/design#791]
I have been thinking that 32-bit vs 64-bit WebAssembly would be a module-level flag, but I realized that it can be done by adding an address type field to the memory type. The signature of `*.load*`, `*.store*`, `grow_memory`, and `current_memory` would change to take an address of the type specified by the memory object. That memory object is implicit right now, but if operators were added that had an immediate operand to specify different memory objects, this would allow access to both 32-bit and 64-bit addressed memory objects in the same module. Making the address size a component of the memory type scales to 0, 1, or N memory objects.

Same thing for table objects. Adding index size to the table type would allow 64-bit indices without requiring them when using 64-bit addresses (and vice versa). 64-bit Emscripten may need 64-bit table indices for compatibility with C programs that expect `sizeof(void*)==sizeof(void(*)())`, but it's a nice option to have.

**Comment by titzer** [comment]
On Tue, Sep 6, 2016 at 4:59 PM, Andrew Scheidecker <notifications@github.com
> wrote:

> I have been thinking that 32-bit vs 64-bit WebAssembly would be a
> module-level flag, but I realized that it can be done by adding an address
> type field to the memory type. The signature of *.load*, *.store*,
> grow_memory, and current_memory would change to take an address of the
> type specified by the memory object. That memory object is implicit right
> now, but if operators were added that had an immediate operand to specify
> different memory objects, this would allow access to both 32-bit and 64-bit
> addressed memory objects in the same module. Making the address size a
> component of the memory type scales to 0, 1, or N memory objects.
>
> Same thing for table objects. Adding index size to the table type would
> allow 64-bit indices without requiring them when using 64-bit addresses
> (and vice versa). 64-bit Emscripten may need 64-bit table indices for
> compatibility with C programs that expect sizeof(void*)==sizeof(void(*)()),
> but it's a nice option to have.
>
I was thinking that it'd be nicer if we just added new load/store opcodes
to access memory with 64-bit indexes. That way, it's still easy for a
decoder to tell exactly what the expected types to every opcode are.

**Comment by AndrewScheidecker** [comment]
> I was thinking that it'd be nicer if we just added new load/store opcodes
to access memory with 64-bit indexes. That way, it's still easy for a
decoder to tell exactly what the expected types to every opcode are.

I think that's a fine option, but at least for my implementation, address-size polymorphic operators is easier than twice as many monomorphic operators.

Another argument against this is that the memory type already includes an optional maximum number of pages. A module that uses 32-bit addresses can use this to import a memory object that can't grow past what can be accessed with 32-bit addresses. A 32- or 64-bit address size option on the memory object would then only be relevant to enabling address-size polymorphic memory operators.

Since the only benefit to this seems to be to enable address-size polymorphic operators, I'm going to fold this into #784.
