### ISSUE TITLE
JS imports are overconstrained to be objects

### ISSUE THREAD

**Issue by rossberg-chromium** [WebAssembly/design#797]
The second step of processing an import in JS.md is:

> - If Type(v) is not Object, throw a TypeError.

That does not make sense for globals, which you typically want to provide as a number value.

**Comment by wibblymat** [comment]
I'm reading it slightly differently. At this step `v` is the _module_, which should be an `Object` whose properties are the actual imports.

On the next step `v` is, confusingly, redefined to be the particular property of the object with the correct name.

**Comment by lukewagner** [comment]
Oops, I missed this issue initially, sorry.  Agree with @wibblymat.  (Also agree it'd be clearer to use a separate identifier for the result of getting `export_name`.)

**Comment by lukewagner** [comment]
I believe this was addressed in #817.
