### ISSUE TITLE
Tagged versions

### ISSUE THREAD

**Issue by distransient** [WebAssembly/design#812]
It'd be useful to have a tag for each version change.

**Comment by jfbastien** [comment]
What do you mean? Pre-MVP when we go from e.g. 0xB to 0xC? Post-MVP there shouldn't be version changes (only feature detection), and before MVP I don't expect much more than 1 or 2 version bumps.

**Comment by distransient** [comment]
`0xc` at 453320eb21f5e7476fb27db7874c45aa855927b7, `0xb` at 7c8be53bad55836ac5f0c6d1de70006552162901, and `0xa` at 5c49b34d3562ec32228177fb71f17a85e583a60b (which, from what I can tell, is the first versioned pre-release commit).

I wouldn't think a github "release" would make sense (this is for real "releases", like you said, maybe one or two version bumps) but just git tags for these commits would be nice for looking at how the format changed over time! Maybe titled something like "pre-0x#", or whatever you all think is right.

I don't think I can exactly make a pull request for this though 😅 the tags just have to be pushed by someone with commit access.

**Comment by jfbastien** [comment]
OK gotcha! Thanks for digging these up, I've now pushed the 3 tags as suggested.
