### ISSUE TITLE
If-without-else value ambiguity

### ISSUE THREAD

**Issue by tsavola** [WebAssembly/design#819]
It's not clear from the Semantics document that if-followed-by-end can't yield a value. It's also not clear if it's legal for such an if to specify a type signature.

**Comment by JSStats** [comment]
Ok, I see your point. It could be invalid to give a signature to `if` that specifies a value when there is no `else`. Perhaps these will be split into two opcodes anyway so the signature does not need to even be encoded with `if-end`.

**Comment by tsavola** [comment]
Separate opcode would make it clearer.

But should `block` and `loop` then be split into valueful and valueless opcodes aswell, for symmetry? That seems excessive.

**Comment by titzer** [comment]
If-without-else cannot yield a value, since `if X end` is equivalent to `if X else end`, and both blocks have to match the if's type. Thus all if-without-end (sometimes called one-armed-if) constructs must have declared type of the empty block type.
