### ISSUE TITLE
Ast.module?

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#822]
https://github.com/WebAssembly/design/blob/master/JS.md#webassemblymodule-objects mentions Ast.module under `WebAssembly.module`. This isn't valid anymore and needs to get fixed.

**Comment by rossberg-chromium** [comment]
Updated this and a few other outdated spec xrefs.

**Comment by jfbastien** [comment]
It's still called "AST" and links to an ast.ml, shouldn't that be fixed as well?

**Comment by rossberg-chromium** [comment]
Well, we still have an AST, esp for the structure of modules. It's just much flatter than it used to be for functions.
