### ISSUE TITLE
JS API: WebAssembly{Compile,Runtime}Error constructors without new

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#825]
JS.md currently says:
- `WebAssembly.CompileError` : a `NativeError` which indicates an error during WebAssembly decoding or validation
- `WebAssembly.RuntimeError` : a `NativeError` which is thrown whenever WebAssembly specifies a trap.

What's expected from this code:

```
let e = WebAssembly.CompileError();
```

I get that ye olden JS errors support calling the constructor as a function for legacy reasons, but do we want this for new error types? As a reference, `DOMError()` requires new, so I think WebAssembly should as well.

**Comment by rossberg-chromium** [comment]
`DOMError` is deprecated. It's replaced by `DOMException`, which supports ordinary function calls.

So I don't think we should change anything.

**Comment by kmiller68** [comment]
@rossberg-chromium: Your statement does not appear to be true. Neither `DOMError` nor `DOMException`can be called without new in any browser I tested. For reference:

Safari:
DOMException() // throws TypeError: Constructor requires 'new' operator
DOMError() // Is not supported

Chrome:
DOMException() // throws TypeError: Failed to construct 'DOMException': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
DOMError() // throws TypeError: Failed to construct 'DOMError': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

Firefox:
DOMException() // throws TypeError: Constructor DOMException requires 'new'
DOMError() // throws TypeError: Constructor DOMError requires 'new'

**Comment by lukewagner** [comment]
I don't really care whether the non-new calls throw or not, but it seems kindof annoying to not be able to simply say that the wasm errors are `NativeError`s like all the rest defined by the JS spec and reuse all that spec/impl machinery.

**Comment by jfbastien** [comment]
@rossberg-chromium 
> `DOMError` is deprecated. It's replaced by `DOMException`, which supports ordinary function calls.
> So I don't think we should change anything.

What @kmiller68 said: I just used `DOMError` as an example because it's the first to autocomplete. Witness the Chrome JS console:

<img width="552" alt="screen shot 2016-10-19 at 13 26 52" src="https://cloud.githubusercontent.com/assets/298127/19536234/f0aad624-95ff-11e6-9265-31195a313a6b.png">

@lukewagner it's consistent with the semantics of the other constructors, though. It seems weird to perpetuate a design flaw of JS for types which users shouldn't construct anyways (they can, but it's useless).

**Comment by lukewagner** [comment]
Yes, but this is the *JS* API, not core wasm semantics, so I think we should just match JS whose exceptions all explicitly share the same [semantic definition](https://tc39.github.io/ecma262/#sec-nativeerror-object-structure).

**Comment by pizlonator** [comment]
Agree with @lukewagner, NativeError makes the most sense, and following JS callability/constructibility rules for exceptions is best.

**Comment by kmiller68** [comment]
I disagree, AFAIK, the only reason that JS does not require new is for backwards compatibility. Every new class added to ES6, for instance, throws a type error when not constructed. One cannot even use the class syntax to create a constructor that doesn't require new. 

@lukewagner Just because ECMAScript uses the same semantic definition for all the exceptions does not indicate what the ECMAScript committee would do if they were to add a new exception. It only indicates the ECMAScript committee thought using the same semantic definition was the best way to represent the current specification. I can't say with any certainty but given that the DOM already requires that exceptions use new, I would guess that the ECMAScript committee would require new on any new exception subclass they add.

Ultimately, I don't think this matters much, however, since I highly doubt any user of wasm is going to actually create their own `WebAssembly.CompileError` or `WebAssembly.RuntimeError` objects.

**Comment by rossberg-chromium** [comment]
Here is what the current WebIDL spec says:

https://heycam.github.io/webidl/#es-DOMException-call

The call does not throw if NewTarget is undefined (step 2), which it is in case of a normal call. Why browsers disagree I don't know, but I'm not surprised either.

In any case, I don't think we should get into the business of "fixing JavaScript flaws". Believe a TC39 veteran when I tell you that that's a dangerous swamp, likely to upset some people, und ultimately futile. You don't want to go there. Hence, where the ECMAScript spec sets a clear precedent we should simply follow it. And JS Error constructors set a clear precedent, AFAICS.

(And FWIW, DOM semantics tends to be far more random and broken than even JavaScript proper; in general, it's the last place where you want to look for precedent.)

**Comment by rossberg-chromium** [comment]
The current behaviour is consistent with JS (and the DOM spec), we shouldn't diverge.

**Comment by jfbastien** [comment]
Unfortunate, but fine.
