### ISSUE TITLE
Stack behaviour for each instruction

### ISSUE THREAD

**Issue by johannesauer** [WebAssembly/design#831]
I think the stack behaviour for each instruction should be included in this doc:
- how many values are consumed?
- how does the order of the stack values map to the operands of the instructions?
- how is the stack mutated?

**Comment by titzer** [comment]
Popping values off the stack is described in the second paragraph of the semantics document. Instructions pop their arguments off the stack, apply an operator, and push the result(s) onto the stack. There isn't a description of the types of operands to each instruction, but I think most people just assumed that we'd add this to the formal specification when we get around to starting it.

**Comment by rossberg-chromium** [comment]
In the mean time, you might be able to read some of the [typing rules in the spec interpreter](https://github.com/WebAssembly/spec/blob/master/interpreter/spec/valid.ml#L204).

**Comment by johannesauer** [comment]
Thanks for the hints!

**Comment by jfbastien** [comment]
Seems resolved.
