### ISSUE TITLE
Language Types in BinaryEncoding lists i32 twice

### ISSUE THREAD

**Issue by tsavola** [WebAssembly/design#851]
i64 is missing:

| Opcode | Type constructor |
|--------|------------------|
| `-0x01` (i.e., the byte `0x7f`) | `i32` |
| `-0x02` (i.e., the byte `0x7e`) | `i32` |
| `-0x03` (i.e., the byte `0x7d`) | `f32` |
| `-0x04` (i.e., the byte `0x7c`) | `f64` |
| `-0x10` (i.e., the byte `0x70`) | `anyfunc` |
| `-0x20` (i.e., the byte `0x60`) | `func` |
| `-0x40` (i.e., the byte `0x40`) | pseudo type for representing an empty `block_type` |

**Comment by titzer** [comment]
Looks like a simple typo.

**Comment by titzer** [comment]
Fixed.
