### ISSUE TITLE
JS API: Compilation hinting

### ISSUE THREAD

**Issue by hackcasual** [WebAssembly/design#863]
Provide a way for a developer to request the WebAssembly backend fully compiles the module.

Trying not to get too far into the weeds of individual implementations, but having a high level flag that indicated a desire to fully AOT a module would be useful in cases where a dev wants to trade off startup time for more stable execution performance. A game engine with a large asset download would be a good example. 

Adding it as an argument to `Module.compile` would allow implementations to fulfill the promise after the full optimization pass had happened.

**Comment by jfbastien** [comment]
The separation of the `compile` command basically hints non-normatively at that desire. I don't think we want to add more hinting.

**Comment by hackcasual** [comment]
Ok, I think this may be a misreading on my part. WebAssembly.compile is not required to interact with a module?

**Comment by jfbastien** [comment]
Yes, you need a module but it doesn't instantiate it.

**Comment by hackcasual** [comment]
Got it, thanks
