### ISSUE TITLE
503 href/Link in the CodeOfConduct page.

### ISSUE THREAD

**Issue by MarcMcIntosh** [WebAssembly/design#868]
The link to the WC3 code of ethics and professional conduct, 
<https://www.w3.org/Consortium/cepc/>
in
https://github.com/WebAssembly/design/blob/master/CodeOfConduct.md
results in a 503 error page.

Nice work by the way

**Comment by distransient** [comment]
"503" just means "service unavailable", w3's server that publishes that page is likely just down, as all the places they link to it haven't changed the url either

**Comment by distransient** [comment]
[Here](https://webcache.googleusercontent.com/search?q=cache:o2mSCvOGJXcJ:https://www.w3.org/Consortium/cepc/+&cd=1&hl=en&ct=clnk&gl=us)'s the cached version, so you can read until their server is back in good health

**Comment by MarcMcIntosh** [comment]
wow that was quick,

thanks.

**Comment by distransient** [comment]
It's back up now. This can be closed.
