### ISSUE TITLE
Export uniqueness

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#873]
Should WebAssembly exports be uniquely named? It doesn't seem useful to allow the Module to be created, but then having the JS API pick the latest export (IIUC that's the current behavior). I think it would be better if we fail at Module creation time if the exports aren't unique byte strings.

**Comment by rossberg-chromium** [comment]
This isn't an open question. See spec and test suite.
https://github.com/WebAssembly/spec/blob/master/interpreter/test/exports.wast#L30

**Comment by jfbastien** [comment]
Ah that's great. It doesn't seem to be detailed in the design repo though, could you update it accordingly?

**Comment by wllang** [comment]
Why not make it a feature that duplicates are given a unique suffix, a monotonically increasing count, skipping any conflicts.

**Comment by jfbastien** [comment]
> Why not make it a feature that duplicates are given a unique suffix, a monotonically increasing count, skipping any conflicts.

I don't think this helps the developer: if they collided then it's likely a mistake. If they wanted renaming... why not rename themselves?

**Comment by wllang** [comment]
@jfbastien It might help compression a little if there are a relatively large number of exports and the code is minimized. It might not very important for the export names but perhaps this would be a general strategy to adopt for names in wasm and it could be a big help for the names section for the case in which names were effectively sparsely defined in which case the effectively non-assigned function names could use a short prefix with the decoder filling a suffix.

**Comment by lukewagner** [comment]
JS.md now [mentions](https://github.com/WebAssembly/design/commit/053ade0aa5bfd663f3b8fb755c0b72fd9274ca2d#diff-4ee5b445d03c05545d4fba583d856eccR372) the uniqueness as well.  @jfbastien think we can close now?

**Comment by jfbastien** [comment]
Yup, thanks.
