### ISSUE TITLE
Pondering the Stack and Globals

### ISSUE THREAD

**Issue by ncbray** [WebAssembly/design#88]
There's no direct question here, just pondering how things fit together.

For the most part, variables will live in the "shadow stack" (the JS stack, for many implementations).  Manipulation of this stack is entirely implicit.  Do a function call?  New frame on the shadow stack.  There will be some cases where the shadow stack insufficient, however.  For example, address taken of a stack local variable.  To support this, a "user space" stack is needed that lives in the visible heap.  OK... so how is this user space stack implemented?  Is it explicitly compiled into the program?  Or is it supported by the system and are there special opcodes?

If the user stack is an explicit part of the program, then how do you implement it?  I believe Emscripten uses a global variable: STACKTOP.  OK, that's kind of weird if you think about it... it's sort of a "shadow global".  Can't take the address of it.  Spiritually similar to the stack pointer on CPUs.  A virtual register that is not confined to a particular stack frame?  OK, how do those virtual registers get initialized?  For example, when you launch a thread?  I suppose they could be parameters passed in to thread initialization.  (Although this raises the question of what the system/user interface for thread creation looks like.)  Alternatively, you could just store STACKTOP in the user visible heap.  Much simpler, doesn't require a separate concept.  (The concept of shadow globals may be desirable.  It isn't necessary, however.)

On the other hand - where do you store the thread-local STACKTOP global in user space?  Some implementations may lower shadow globals into the heap, anyways, so the question of where the globals are allocated is relevant in multiple situations.  If memory allocation is an explicit part of the program... how does the allocator know what parts of memory are safe to use vs. grabbed by some lower-level part of the system?  Does there need to be a system-level "page allocation" API that user-level memory allocators build on top of?

JF mentioned an example of split stacks being added to LLVM: http://reviews.llvm.org/D6095

**Comment by sunfishcode** [comment]
Are there questions left that need answers here that aren't covered by #104, #126, and #154?

**Comment by ncbray** [comment]
If there are lingering questions, they'll bubble back up in later discussions.
