### ISSUE TITLE
Documenting the opcode extension plan.

### ISSUE THREAD

**Issue by kmiller68** [WebAssembly/design#881]
Is it documented anywhere what the plan is for opcode extensions past the initial set? I was under the impression the plan was to use LEB for opcodes but that doesn't appear to be the case as many of the opcodes set the most significant bit.

Also, what was the reasoning for not using LEB?

**Comment by lukewagner** [comment]
That was the original plan during [LEB128-all-the-things](https://github.com/WebAssembly/design/pull/592), but it was [reverted](https://github.com/WebAssembly/design/pull/592#r55480082) in favor of biasing the opcode encoding towards fitting more ops in the 1 byte space.  You're right that it should be documented.  I expect it doesn't matter in practice either way as long as the 20-or-so actually-hot opcodes are <127 so we could discuss more here, but it would require a version bump to fix.

**Comment by jfbastien** [comment]
The `0xD` encoding is: `0xff` is the continuation byte?
That seems to fall on its face past `510` ops, no?

**Comment by jfbastien** [comment]
Unless `0xff` means "this is an LEB instruction", and then there's an LEB after it?
Ew.

**Comment by lukewagner** [comment]
Until we get near the end of the one byte space, we actually have a whole space of options (e.g., using two sentinel codes would double the number of ops that fit in two bytes...).  That being said, setting SIMD ops aside, I can't imagine us having more than 511 ops; even 256 seems like a stretch.  For SIMD ops, it might even make sense to use a custom encoding scheme where there are only a few SIMD prefix opcodes (that go in the general opcode space) and these SIMD prefix opcodes are then followed by type×operation as a pair of immediates.  With this sort of scheme, we may not even hit two bytes.  So many options here going forward.  But if we do LEB128 now, then we're already in the two-byte space.

**Comment by jfbastien** [comment]
SIMD.js added ~50 ops per SIMD type, and with only 128-bit wide SIMD it had 12 types. We'll slice these differently (signed / unsigned, etc) but we may have greater-than-128-bit and I expect we'll have more ops such as horizontals.

We're then going to add other ops for atomics, GC, exception-handling, etc...

Agreed that we can be clever, but I'd really like to see something solid that we believe in before we commit MVP.

**Comment by rossberg-chromium** [comment]
I would avoid spamming the opcode space with too many rare opcodes. For SIMD we had discussed to use a prefix/escape byte, such that it only takes up a single value in the regular opcode space. In general, we should perhaps allocate such escape bytes at the upper and of the u8 space. E.g., 0xFF for misc, 0xFE for SIMD, and going down from there in case we introduce other large extensions.

**Comment by jfbastien** [comment]
A most `VEX`ing proposal? 🙃

**Comment by lukewagner** [comment]
So it seems like we have a number of options that could keep us in the 1-byte space for a long time, if not forever.  Would the resolution to this issue then be to add some new subsection of BinaryEncoding.md#function-bodies that mentions that the encoding of opcodes is currently just 1 byte but then mention plans for future extension?

**Comment by jfbastien** [comment]
Yes, that sounds good.

**Comment by lukewagner** [comment]
Should be resolved by #926

**Comment by Kardax** [comment]
There isn't a better place to discuss this right now but I'll throw out another proposal: use `varuint32` for opcodes but allow them to be remapped globally and at the function level based on the program's actual usage patterns.  This will allow for thousands of opcodes directly selectable from a 1-dimensional table, while preserving 1 byte per opcode even for complex apps like AngryBots13.wasm, which only uses 92 opcodes.

**Comment by wllang** [comment]
@Kardax I think such mapping support would be prudent too, and at least globally. There was past work on an opcode table and it seemed to have been dropped and people were mentioning the cost of an extra indirection (could decoding really be that tight).

This begs how the map is defined? Are there some standard maps, or can they be included in the wasm file, and if so could they have the option of being named by a string to open up the format even further.

The expected distribution might still suggest encodings other than `varuint32`.

**Comment by Kardax** [comment]
@wllang  An opcode table isn't needed _yet_; there are (small) performance disadvantages to implementing one now.  I think of it as a forward-thinking feature for a near future time when we have SIMD and other specialized opcodes added to the core spec and parsing suddenly gets complicated and inefficient to deal with these exotic multi-part opcodes.  Then, opcode tables can be a real win, but now it's a breaking change from WASM 1.0, so implementation requires extra code to deal with both the old way and the new way.

**Comment by wllang** [comment]
@Kardax I am sorry if you have been mislead that the CG as a whole has agree to a 'WASM 1.0' release any time soon, that is not the case. If you could let me know the source of this misinformation then I will deal with it promptly so you fell free to continue the good design work without such constraints?

**Comment by eholk** [comment]
@Kardax If we add a layer-1 compression layer, that could be one place to define opcode remappings. @KarlSchimpf is working on a [decompressor prototype](https://github.com/WebAssembly/decompressor-prototype) that I think may be general enough to do these sorts of things.
