### ISSUE TITLE
Block fall-through exits would be best to unwind the stack.

### ISSUE THREAD

**Issue by wllang** [WebAssembly/design#884]
As it stands the semantics of blocks and loops are:
"Executing a `block` or `loop` instruction has no effect on the value stack."

But a branch out of the block unwinds the values stack.

The case for having the block and loop fall-through paths also unwind the values stack seem compelling. The producer could end a block with a branch to have it unwind, but there is no utility in not unwinding which just adds an extra case to validate.

The number of values returned by a block and their type is defined in the block header, so for the fall-through to validate when not modify the values stack requires that the values stack on exit exactly match that which would be expected. This creates a significant burden for the producer and the encoding to drop values and do the unwinding in the instruction encoding. Where the values can not be dropped in stack order, values will need to be moved into local variables and reloaded after clearing the stack, which is not only a burden for the encoding and producer, it is also a burden for a baseline compiler because these definitions will remain live in the local variables after the exit of the block in contrast to remaining on only the values stack. These extra live definitions are likely also a burden for an optimizing compiler which may need extra resources to track and eliminate them, which could be obvious where it creates more local variables to track.

Looking ahead, to the addition of a `pick` operator, the common case at a block exit will be to unwind the stack. The values stack works out well for block exit paths for a wasm SSA style encoding that does not use local variables, and definitions created within a block that are needed outside its scope can be passed out on the values stack. This could be done in future with a branch out on exit, but why not clean up this corner of the language now and give a more efficient encoding going forward.

**Comment by pizlonator** [comment]
It's too late for this.
