### ISSUE TITLE
Why is there both a memory section and a memory import?

### ISSUE THREAD

**Issue by saambarati** [WebAssembly/design#891]
I'm unclear what the semantics of a memory definition is in the memory section. During instantiation, are we supposed to create a memory according to the definition to attach it to the instance? 

What if there is *both* a memory import and a memory definition. Is this allowed? If so, must they be consistent? If so, what does this mean during Instance creation.

Why doesn't memory just exist as an import?

Related links:
https://github.com/WebAssembly/design/blob/master/Modules.md#linear-memory-section
I believe the above link tries to clear things up, but things are still left quite ambiguous in my reading. I see no reference to the linear memory inside Instance creation:
https://github.com/WebAssembly/design/blob/master/JS.md#webassemblyinstance-constructor

**Comment by binji** [comment]
> What if there is both a memory import and a memory definition. Is this allowed?

From that link:
> In the MVP, every memory is a default memory and thus there may be at most one linear memory import or linear memory section.

You're right that it doesn't say what should happen, but the spec interpreter makes this an error: https://github.com/WebAssembly/spec/blob/master/interpreter/spec/valid.ml#L438

> I see no reference to the linear memory inside Instance creation

There a number of references to `memory`, `memories`, and `WebAssembly.Memory` at this link. See https://github.com/WebAssembly/design/blob/master/JS.md#webassemblymemory-objects which specifies that `WebAssembly.Memory` contains linear memory.

It does seem that that link doesn't mention that multiple memories is not allowed.

**Comment by saambarati** [comment]
@binji Inside WebAssembly.Instance constructor, where does it say what to do if we have a *defined* memory (from the memory section, not an import). I don't see anything inside the constructor function that addresses this:
https://github.com/WebAssembly/design/blob/master/JS.md#webassemblyinstance-constructor

Also, at a higher level, why are there these two ways of declaring memory? Why isn't there *only* an imported memory.

**Comment by rossberg-chromium** [comment]
@saambarati, JS.md states that the `Eval.init` function from the spec is executed to create the instance. That creates the memory (along with other initialisation steps) if a module defines its own.

One reason for allowing module-defined memories is that it allows a module to encapsulate its memory: when a module defines its own memory and does not export it then it is guaranteed (by memory safety) that nobody else can mess with it. In addition, a local memory also enables additional optimisations, because all the code accessing it is known and vice versa.

**Comment by saambarati** [comment]
@rossberg-chromium So does this mean then that if you have a locally defined memory, which isn't exported, that the memory belongs *to the module*? Or will every new instance of that module create a new memory?

**Comment by rossberg-chromium** [comment]
@saambarati, yes, every instance gets its own copy.

**Comment by saambarati** [comment]
Ok I now agree that having a Memory definition along with a memory Import is a good thing. Thanks for clarifying.
