### ISSUE TITLE
Can start functions be imports?

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#896]
The [current wording](https://github.com/WebAssembly/design/blob/master/Modules.md#module-start-function) isn't so clear about this:

> If a module contains a start node, the function must be defined in the module

I want to clarify some of the other wording in this entire section, but this question merits a bit more thought I think.

**Comment by lukewagner** [comment]
Good find; I believe that wording predates the unification of the function index space should be updated to say "any function in the [function index space](https://github.com/WebAssembly/design/blob/master/Modules.md#function-index-space)".  This is what we've implemented and I believe there is a spec test covering this as well.

**Comment by jfbastien** [comment]
Either is fine with me. Let's leave this open until next week, to make sure other browser folks have time to chime in.

**Comment by jfbastien** [comment]
FWIW this also implies that start can be from a table.

**Comment by binji** [comment]
@lukewagner Hm, there doesn't seem to be a spec test for this. It is tested that an imported function can be called from the start function, but not that the start function can be an imported function.

**Comment by lukewagner** [comment]
Ok, maybe my memory is failing me; ISTR we had to comment out a start-function spec test until I implemented the func-index unification.  @bnjbvr do you recall?

**Comment by jfbastien** [comment]
Also, if the start function is an import / table value, does it have the same object identity when called as start than when called as an import / table thing?

**Comment by lukewagner** [comment]
Sorry, how can the start function be a table value?  I know you can assign imports *into* tables via elem section; but not a way to read something *out* of a table.  But to answer your question for imports: that's a good question and should be clarified.  We treat calling the start function as simply calling an export by func-index and this calls the object identity of the exported wasm function (not the imported JS function).

**Comment by rossberg-chromium** [comment]
@lukewagner, not sure I follow, how would the identity of the start function be observable?

**Comment by rossberg-chromium** [comment]
PR for adding spec test: WebAssembly/spec#398

**Comment by Cellule** [comment]
It was also my understanding that when we merged the index space for functions it was possible to have imported functions used as start function.
