### ISSUE TITLE
What is Table for?

### ISSUE THREAD

**Issue by saambarati** [WebAssembly/design#898]
I don't see any way of accessing the Table's elements via the actual wasm binary code besides through the elements section which *assigns* into the Table. Am I missing something? If so, what's the purpose of Table? It is only allowed to be assigned values from the function index space:
https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#element-section

If this is true, why do we have Table at all? Couldn't we just do this via an export since we can export anything from the function index space?

**Comment by saambarati** [comment]
Ok, after talking with @jfbastien, I may have a better idea what tables are for.
@jfbastien indicates to me that call_indirect can call into tables:
https://github.com/WebAssembly/design/blob/master/Semantics.md#calls

Does this mean that tables logically go at the end of the function index space? If so, this should be written in the spec somewhere (or maybe it is and I couldn't find it).

The JS API says that `WebAssembly.Table.prototype.set(index, value)` allows `value` to be JavaScript `null`. Does this cause that slot being called inside wasm to trap?
https://github.com/WebAssembly/design/blob/master/JS.md#webassemblytableprototypeset

The reason I ask is that the spec on the Elements section says that Table is initialized with things that trap when called:
https://github.com/WebAssembly/design/blob/master/Modules.md#elements-section

**Comment by saambarati** [comment]
Another random thought:

If we allow the `Exported Function Exotic Object` to be able to change what internal closure it points to, we basically get what Table is (without resizing).

**Comment by pipcet** [comment]
> Does this mean that tables logically go at the end of the function index space?

I don't think so. I think the table index space and the function index space are entirely separate. In particular, when dynamically linking several modules, I use a single shared table but function index assignment is per-module. (There are probably other ways to do this, though.)

> The JS API says that WebAssembly.Table.prototype.set(index, value) allows value to be JavaScript null. Does this cause that slot being called inside wasm to trap?

I think so, but I can't find anything that actually says so explicitly.

**Comment by saambarati** [comment]
@pipcet If the two index spaces aren't shared, how does call_indirect call into a function in the table?

**Comment by pipcet** [comment]
@saambarati `call_indirect` only ever calls table entries, never other functions.

> The call_indirect operator takes a list of function arguments and as the last operand the index into the table.

**Comment by dschuff** [comment]
The spaces are separate. The immediate on a `call` instruction is an index into the function index space (which is a static property of the module). The `call_indirect` instruction operand is a dynamic index into the table, which is a dynamic property of the instance (I'm using "property" in the informal sense). The elements of the table are values in the function index space, so `call_indirect` (indirectly) calls functions or imports in the function index space.

**Comment by saambarati** [comment]
@dschuff @pipcet Thanks for clearing it up. This makes total sense. I've been thinking that call_indirect was a way to call into the function index space. It makes much more sense that it's just a way to call into a table index.
