### ISSUE TITLE
What are the errors for Table import during instantiation

### ISSUE THREAD

**Issue by saambarati** [WebAssembly/design#899]
- JS.md isn't specific on what validation/consistency the errors are (similar to how importing a Memory isn't very well specified, either). I'm assuming there are the same size consistency errors as Memory has. Should we also use the proposed WebAssembly.LinkError for that here?

- When linking a table, to check the consistency of its minimum size, do we care about its *current* size, or its *original* size? Since a Table import can be grown before being imported, I want to make sure I get this right. I'm guessing we don't care about original size, and only dynamic size, but I just want to be sure this is how things are specified.

**Comment by rossberg-chromium** [comment]
The rules for tables should definitely be in sync with those for memories, so in that sense this is a duplicate for #889.

The check for import limits always looks at the actual size, for both memories and tables. No need to remember their initial size.

**Comment by saambarati** [comment]
@rossberg-chromium sounds good to me.
