### ISSUE TITLE
Feature detection and feature requirement fallback

### ISSUE THREAD

**Issue by kg** [WebAssembly/design#90]
Re: issue #84, we need a strategy for how to do feature detection and fallback when a required feature is unavailable.

I propose a small set of solutions for this:

First, we want to be able to fall-back on a polyfill when a native implementation of webasm is unavailable. As suggested in #84, we should just have a simple way to detect whether a browser implements the format at all. Querying `mimeTypes` seems like an adequate solution; another option is to have something like `navigator.webasm`, since there's a need for a place to put webasm-related methods in the DOM anyway (so that webasm modules can import them, at the very least, just like `Math`, etc.)

When a native implementation of webasm is available, but one or two new/optional features are missing, the _webasm application_ needs a way to detect this and fallback to alternate implementations of particular functions that depend on it - the equivalent of an x86 application checking for SSE2, SSE3 and using different implementations of math/graphics routines. I think we should solve this by exposing a simple function for doing named feature detection, i.e. something like `navigator.webasm.featureSupported('native-simd')` or `navigator.webasm.instructionSupported('vec4-add')`. Feature detection outside in the JS realm (switching between entire executables) would use these DOM-exposed APIs, while feature detection inside a webasm executable would import them and call them and use them inside if statements. An ideal runtime can inline the constant return value of those queries into the executable and entirely kill dead branches, producing 0-runtime-cost fallback.

When a native implementation of webasm is available, but is missing essential application features, we need a way to fall-back onto a polyfill instead of failing. At a bare minimum, this means that the JS needs a way to get the entire body of the application's webasm executable, or any essential sections of it (code section, constant table, etc) from the native decoder. Without this, the application would be downloaded twice and that's a complete non-starter. The cost of decoding the whole application twice is also undesirable, which is why the above feature detection proposal is important. I'd suggest we have something simple here, like `navigator.webasm.getModuleSection(module, 'sectionName')`, that returns a given named section of a module (assuming we use a format like ELF that has named sections), probably as a Uint8Array (something like Blob would be pretty gross from a performance perspective).

Exposing a way to get at module sections as raw bytes will also support common usage scenarios for sections, like embedding essential resources (shaders, textures, cursors, icons) into executables.

Exposing feature detection and module section access in the DOM ensures that a JS polyfill can implement these APIs and expose them, so a webasm module can successfully use those APIs regardless of the presence of a native implementation.

How this would interact with CORS is a complicated question. I'm not sure there's any way to make CORS work right for polyfilled webasm, and with native webasm the question of how to secure and authenticate module access could be tricky.

Another question is what happens if multiple webasm executables are loaded in a single environment (page, interpreter, etc) - do we enforce that there's only one polyfill that's used to run all the modules? How do we ensure that happens correctly if multiple modules trigger a native-to-JS fallback due to missing features? Can we enforce a one-polyfill restriction if some of our modules are being loaded via CORS (in which case we want to prevent a compromised polyfill from accessing the remote module)?

EDIT: One alternate way to do feature detection would be instead to have a way to query the runtime about whether an _entire function_ was successfully compiled. Then you could simply query the availability of a series of functions and pick the first one that's available, instead of needing to check a long series of features.

**Comment by jfbastien** [comment]
We have `validate`. Not sure we addressed this fully, but it's been a while... Closing.
