### ISSUE TITLE
WebAssembly.Table.prototype.grow is underspecified

### ISSUE THREAD

**Issue by saambarati** [WebAssembly/design#900]
It needs the bit about throwing a type error when |this| is not an instance of WebAssembly.Table.

**Comment by saambarati** [comment]
The spec link for reference:
https://github.com/WebAssembly/design/blob/master/JS.md#webassemblytableprototypegrow

**Comment by flagxor** [comment]
Agreed, this needs a type error.
We should go through JS.md and double check other methods.

**Comment by flagxor** [comment]
We should also clarify what the return value is (it's not really specified). V8 current returns what the grow_memory instruction does.

**Comment by saambarati** [comment]
@flagxor Yeah, I hand't even thought about that. We should definitely specify the return value. My vote is to return `undefined` for anything that doesn't really need a return value, which is how I expect JS to normally behave. So my vote would be `undefined` for `grow(size)` as well.

**Comment by rossberg-chromium** [comment]
Returning `undefined` sgtm.

**Comment by saambarati** [comment]
It seems more people are in favor of specifying Table.prototye.grow to match Memory.prototye.grow and return the old size. Let's move discussion to this thread:
https://github.com/WebAssembly/design/issues/917
