### ISSUE TITLE
OOM errors

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#903]
Forking from https://github.com/WebAssembly/design/pull/901#issuecomment-266523709

Should we call out out-of-memory errors separately, or do they cause Compile / Link errors? This seems similar to @gahaas' clarification w.r.t. stack error in #875.

**Comment by flagxor** [comment]
We should do:
GrowMemory stays as is.
Everything else is up to the embedder, see Andreas' other verbiage.

**Comment by jfbastien** [comment]
As a clarification: I think OOM on `WebAssembly.validate` should be an OOM exception, not a validation failure: we may never be able to compile the module, but it's not fundamentally invalid. Pretty much the only valid usage of `validate` is to do feature detection, it would be odd to "lie" on OOM.

Again, this is a corner-case.

**Comment by titzer** [comment]
What JF says sounds reasonable to me.

**Comment by lukewagner** [comment]
Agreed; that also matches what we've done.

**Comment by sunfishcode** [comment]
This was fixed in #1059.
