### ISSUE TITLE
|this| value in wasm -> JS function?

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#906]
Should we just make |this| undefined?

Similar to #900.

**Comment by saambarati** [comment]
+1 for `undefined`

**Comment by jfbastien** [comment]
`undefined+1` would be `NaN`. 🙃

**Comment by rossberg-chromium** [comment]
I don't think there is any other option if we want to have any consistency with function calls in JavaScript.

Nit: You mean to refer to the _receiver_, not the `this` binding, which is an internal detail. Not all JS-side functions even have a notion of the latter, e.g. primitives. Moreover, sloppy functions convert an undefined receiver to the global object (themselves).

**Comment by lukewagner** [comment]
Agreed on `undefined` and that we should call this out explicitly in the spec.

**Comment by lukewagner** [comment]
Oops, forgot to close this when resolved by #923.
