### ISSUE TITLE
It's not clear in JS.md what values processing the Elements list creates during instantiation

### ISSUE THREAD

**Issue by saambarati** [WebAssembly/design#907]
For example, lets consider the following JS program:
```
module = new WebAssembly.Module({
    ;; single function (at index 0)
    ;; export function at index 0 as "foo"
    ;; import a table
    ;; elements section with a single element:
    ;;      element = { offset 0, function indices: [0] }
    (all of this is in the binary of course)
});

let table = new WebAssembly.Table({element: "anyfunc", initial: 1});
let instance = new WebAssembly.Instance(module,  {import: {table}});

instance.exports.foo === table.get(0) // What is this? true or false?
```

- Are the Web Assembly Function objects that get stored into table supposed to be exactly the same object that gets stored into the exports dictionary?

**Comment by rossberg-chromium** [comment]
Yes, they have to be the same. The wording of the algorithm in JS.md is pretty explicit on that, note the construction and querying of the `funcs` list.

**Comment by saambarati** [comment]
@rossberg-chromium I'm specifically talking about the elements section. There is hardly any text inside Instance construction talking about the Element section, and it doesn't reference the issue I stated above:
https://github.com/WebAssembly/design/blob/master/JS.md#webassemblyinstance-constructor

The querying you're talking about is done for function imports/exports and table exports. It's not talked about with respect to the Elements section.

If we want the behavior you describe, JS.md should have some text about it. FWIW, I agree that this should be the specced behavior.

**Comment by rossberg-chromium** [comment]
@saambarati, I don't quite understand, your example _does_ test function exports against table exports, so AFAICT, its behaviour is fully specified. And other than that, elements don't have any observable identity, so what is missing?

**Comment by saambarati** [comment]
@rossberg-chromium My example doesn't export a table. It imports a table and has the element section write an imported function into index zero in the table

**Comment by rossberg-chromium** [comment]
@saambarati, ah, yes, you're right, thanks! Probably the fix is to include all elements of imported tables in `funcs`and later run over the table to update it, independent of whether it is exported. I'll try to prepare a PR.

But to clarify the question in the abstract, the overarching idea is that every Wasm function should be wrapped into a JS function at most once.

**Comment by rossberg-chromium** [comment]
See #911.

**Comment by rossberg-chromium** [comment]
This is fixed.
