### ISSUE TITLE
Validation errors for elements

### ISSUE THREAD

**Issue by saambarati** [WebAssembly/design#908]
- Is it a validation error when an element will store to a provably out of bounds table index?
For example, this can be the case if the memory definition/import specifies a "maximum" field.

**Comment by jfbastien** [comment]
We should come to the same conclusion as for Data segments in #897.

**Comment by rossberg-chromium** [comment]
We dropped static check for this when we introduced importable tables/memories and globals as offsets. In the general case you cannot check, it's not worth making a special case here.

**Comment by saambarati** [comment]
@rossberg-chromium Yeah I agree. I wasn't really thinking about the init_expr as being the offset.
