### ISSUE TITLE
drop custom section names?

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/design#909]
I'm not sure what the point of custom section having identifier strings in the binary encoding. There is now way to validate that string. Shouldn't any identifying information be left up to the reader of the custom section?

**Comment by jfbastien** [comment]
We may want a JS API to expose custom section bits, and since they'll need *some* way of identifying themselves this approach seems as good as any.

**Comment by jfbastien** [comment]
To be clear: https://github.com/WebAssembly/design/blob/master/JS.md#webassemblymodulecustomsections

**Comment by wllang** [comment]
@wanderer They need some convention to identify one type from another. For example, a tool looking for data in a particular type of section. Otherwise it would be up to the web community to sort it out, how would you do it, add signatures to sections and hope there are no collisions?

**Comment by wanderer** [comment]
good points!
