### ISSUE TITLE
Cite pre-existing research

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#91]
Before going public we should cite pre-existing research. We're not inventing in a vacuum, it should be apparent in our documentation.

**Comment by titzer** [comment]
Resolved.

**Comment by jbondc** [comment]
Why is this resolved? It's not like Web Assembly is without any History.

**Comment by jfbastien** [comment]
We've been putting this type of content in Rationale.md. It's not perfect yet, but it's getting better!

**Comment by jbondc** [comment]
Alright, it looks relevant to add somewhere:
[1998] Typed Assembly Language 
https://www.cs.princeton.edu/~dpw/papers/tal-toplas.pdf
