### ISSUE TITLE
When should i64 exceptions happen in calls

### ISSUE THREAD

**Issue by kmiller68** [WebAssembly/design#913]
When calling a Wasm function that has an i64 as and argument or return value there are four places an exception can occur:

1. When calling an exported Wasm function that takes i64 argument from JS.
1. When calling an exported Wasm function that returns an i64 result from JS.
1. When importing a JS function to a Wasm module that takes an i64 argument.
1. When importing a JS function to a Wasm module that returns an i64.

The current behavior for all of these (or at least from what got out of JS.md) is to trigger the exception exactly when the i64 would be "touched". For example, in case 1, if you have a Wasm function with the signature: `(i32 * i64) -> i32`, and you called it with `instance.exports.func({ toNumber() { throw "gotcha"; } }, foo);` `"gotcha"` would be thrown. Is this the desired behavior? I would prefer if, rather, the host function immediately threw a TypeError.

Similarly, In the second case, the exported Wasm function would be called and any of its effects executed. Then, as the function returns, the TypeError would be generated. Here I would also prefer the host function be a TypeError stub.

In the last two cases, when a JS function is imported that claims to interface with i64, the current spec, as above throws an error at runtime. It seems to me that should be an instantiation time error, since we know if the import is JS or Wasm.

**Comment by rossberg-chromium** [comment]
Isn't this pretty unambiguous from JS.md's definition of ToWebAssemblyValue? For i64, you immediately throw.

**Comment by rossberg-chromium** [comment]
Ah, scratch that. I take it you are not asking what the specified semantics is but whether we should change it, specifically, the spec of the [[Call]] method of Exported Function Objects?

**Comment by kmiller68** [comment]
@rossberg-chromium Yeah, I would like to change the semantics. I think we should also change the spec for Imported JS Function Objects as well. Since, at least for imports we know that the Imported JS Function Object cannot handle an i64, thus we should fail to instantiate. e.g. 

<pre>(module (import "foo" "bar" (func (param i64)) )</pre>

passed to

<pre>new WebAssembly.instance(module, { foo: { bar() { } } }); // should throw a WebAssembly.LinkError</pre>

**Comment by lukewagner** [comment]
For exported functions, it sounds good to throw if there is `i64` in any argument/return slot at the beginning of the [[Call]].

For imported functions, I think it would be more useful to the developer to allow instantiation to succeed but unconditionally throw at the beginning of calling the import (symmetric to exported functions).  One reason I can think of is that, if and when we get the ability to pass `i64`s to JS (either we finally do get `int64` which it sounds like Brendan is re-proposing or we decide one day that that's never going to happen and come up with some wrapper object with low/high), we might want to have a polyfill that ships a single module that has both `i64` and `i32`-pair versions of each import and uses a dynamic test to determine which one to call.

**Comment by saambarati** [comment]
@lukewagner Why not relax this requirement later if we find your scenario useful. If we allow it now, we're effectively stuck with it forever.

**Comment by rossberg-chromium** [comment]
Making it an immediate error on call SGTM. I'd also be okay with making it a link error, but I can see @lukewagner's argument as well. I guess I'm fine either way.

**Comment by lukewagner** [comment]
@saambarati If we did that then, realistically, we'd still have the "throw on instantiate" behavior right up until we wanted to write the `i64` polyfill at which point in time it's too late; the polyfill won't work.

Is there any underlying impl challenge with the throw-eagerly-on-call?  At least for us, we just end up in a stub that passes the arg array as an array of unions to C++ which then can throw whenever it likes before it has to box anything into a js::Value.

**Comment by saambarati** [comment]
@lukewagner This isn't any harder or easier for us implement. I personally like the style of throwing as many errors as we can during instantiation, but I'm not tied to doing that here. I'm also okay with the behavior of throwing once the imported JS callee is called.
