### ISSUE TITLE
why no `tee_global`?

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/design#915]
why is there no `tee_global` equivalent to `tee_local`?

**Comment by dschuff** [comment]
I would think most of the time you'd want to copy the global into a local, rather than another global, wouldn't you?

**Comment by binji** [comment]
@dschuff I would assume that `tee_global` would do a `store_global` but keep the value on the stack, like `tee_local`.

@wanderer IIRC, we discussed adding it, but decided it could be added later.

**Comment by wllang** [comment]
Some of the benefit would be had from the more general `pick` operator which allows a copy of a stack value to be made and thus allows keeping a definition on the values stack. There might remain an encoding efficiency gain, but given that the stores to linear memory do not even have these variants it might not be a significant encoding efficiency gain. In the current state of the design this code pattern would save a definition used multiple times to a local variable and the runtime decoders track definitions in local variables to give the same decoded SSA form.

**Comment by lukewagner** [comment]
IIRC, there wouldn't have even been a `tee_local` were it not for the fact that `get_local`/`set_local` are such a huge proportion of total bytecode size that `tee_local` allows major size wins.

**Comment by wllang** [comment]
@wanderer Are you happy with the answers and can this be closed?

**Comment by wanderer** [comment]
ack, @wllang
