### ISSUE TITLE
What's the return value of Memory.prototype.grow

### ISSUE THREAD

**Issue by saambarati** [WebAssembly/design#916]
https://github.com/WebAssembly/design/blob/master/JS.md#webassemblymemoryprototypegrow
Says to return the value of:
https://github.com/WebAssembly/design/blob/master/Semantics.md#resizing
I'm not quite sure what that means. Is the link stale? Should it be to the ML interpreter here:
https://github.com/WebAssembly/spec/blob/e7632dc00c7ea0743d64a42d1ed3c39ed3cd5dfa/interpreter/spec/eval.ml#L213
?

As a matter of style, if Memory.prototype.grow succeeds, why would it return anything other than `undefined`? Since an error is thrown if it fails, I don't think anything else is needed to indicate success.

**Comment by lukewagner** [comment]
When wasm gets threads, the return value is useful for knowing which ranges of bytes were just claimed by this `grow` operation and not some interleaved `grow_memory` from a different thread.

**Comment by wllang** [comment]
It's to make it an atomic operation, see the discussion in https://github.com/WebAssembly/design/issues/525

**Comment by saambarati** [comment]
Ok. Sounds good to me. I'll implement returning the previous size inside JSC. Is it returning the previous size in bytes or pages?

**Comment by rossberg-chromium** [comment]
Returning the previous value SGTM.

**Comment by lukewagner** [comment]
Pages (to match [`grow_memory`](https://github.com/WebAssembly/design/blob/master/Semantics.md#resizing)).

**Comment by lukewagner** [comment]
I believe this is resolved by #922.
