### ISSUE TITLE
Table.prototype.grow needs to specify a return value

### ISSUE THREAD

**Issue by saambarati** [WebAssembly/design#917]
It doesn't right now:
https://github.com/WebAssembly/design/blob/master/JS.md#webassemblytableprototypegrow

**Comment by saambarati** [comment]
My vote would be for returning `undefined`. Like Memory.prototype.grow, I'm not sure what else would  make sense.

**Comment by binji** [comment]
Well, the `grow_memory` operator returns the old page size, so I asssume that `Table.prototype.grow` would as well.

See https://github.com/WebAssembly/design/blob/master/Semantics.md#resizing

**Comment by lukewagner** [comment]
Agreed, this is missing from JS.md and that, for the same reasons that `grow_memory`/`Memory.prototype.grow` return the previous size, so should `Table.prototype.grow`.  (That's actually what we're currently doing in SM.)

**Comment by saambarati** [comment]
Ok sounds good to me. We will do that in JSC. Let's just make sure we specify it in the API

**Comment by rossberg-chromium** [comment]
Whatever we do, it clearly should match Memory.p.grow.

**Comment by lukewagner** [comment]
(btw, I'm accumulating these JS.md TODOs on a list I'll get to when I'm back up to speed, but I'm quite happy for anyone else to make PRs first)

**Comment by lukewagner** [comment]
I believe this is resolved by #922.
