### ISSUE TITLE
Make file header into a valid section

### ISSUE THREAD

**Issue by qwertie** [WebAssembly/design#921]
In #860 I suggested changing the 8 header bytes of Wasm files to

    00 06 04 77 61 73 6D 01

This makes the header appear to be a valid user-defined section with the name "wasm".

The idea is to view the Wasm format as an instance of a more general "list of sections" or "LOS" format. Because files in LOS format have a header that is also a valid section, LOS files can be concatenated. Concatenation seems not to be a useful operation for Wasm modules themselves since the result would not be a valid module, but it might be useful for related formats, such as object files or debug info files defined outside the Wasm spec.

The "magic number" that identifies an LOS file would be the initial three bytes 00 06 04. Any LOS-based format would need a name that is four bytes long, and a one-byte version number.

**Comment by wllang** [comment]
@qwertie If you prepare a PR, a change to BinaryEncoding.md and to Rationale.md if you wish to explain it, then I will review it and approve the change subject to any substantive and reasonable technical objections.

**Comment by sunfishcode** [comment]
Now that we have a PR tracking this, https://github.com/WebAssembly/design/pull/928, we should continue discussion there.
