### ISSUE TITLE
call_import in example, but nowhere defined

### ISSUE THREAD

**Issue by jonas-db** [WebAssembly/design#924]
The JS API documentation contains an example that makes use of `call_import`, yet it is nowhere defined. Should it be `call_indirect` instead?

https://github.com/WebAssembly/design/blob/master/JS.md#sample-api-usage

**Comment by binji** [comment]
Good catch! There used to be a `call_import`, but it was removed, now you use `call` directly.

**Comment by lukewagner** [comment]
(Just put up a PR to fix this.)

**Comment by lukewagner** [comment]
Should be resolved by #925.
