### ISSUE TITLE
Should provably out of bounds loads/stores be a validation error?

### ISSUE THREAD

**Issue by saambarati** [WebAssembly/design#929]
Right now, they're not. There is a spec test:
https://github.com/WebAssembly/spec/blob/master/interpreter/test/address.wast
That assumes it's not a validation error, but instead, a runtime error.

It's possible to prove some loads/stores are out of bounds when
offset + sizeof(load/store)  > UINT_MAX

**Comment by lukewagner** [comment]
While the bounds checks may be provably out-of-bounds if executed, it's possible they are intentionally never executed, so this may frustrate more than it helps.  Also, to have deterministic validation, we'd have to precisely define what it means to be "provably out of bounds" which would get hairy and inevitably leave out some cases where you could still end up with a constant value in the compiler backend.

**Comment by saambarati** [comment]
@lukewagner By provably out of bounds, I'd mean the simplest possible proof, which is what I wrote:
offset + sizeof(load/store)
These are known to the world's most naive wasm compiler.

**Comment by saambarati** [comment]
@lukewagner To elaborate, I never want to propose something that would require a compiler churning on code as part of the validation step. But that's obviously not the case here.

For example, something I'd *not* be in favor of is if the following would be a validation error:
- wasm code emits a load from a constant UINT_MAX pointer.

This is trivial a compiler to figure out, but it should not be part of the validation. However, my point is that nothing like that is happening here. The `offset` and `sizeof(load/store)` are part of the actual load/store instruction. It requires no work extra work by the compiler to figure out their values.

**Comment by lukewagner** [comment]
Ah, I see; I thought you were just giving an example, not proposing the exact rule.  Yes, if we're only talking about constraining the `offset` immediate w.r.t `UINT32_MAX`, that sounds reasonable (and potentially avoids weird corner cases in the compiler backend :).

**Comment by saambarati** [comment]
@lukewagner Yes, sorry for not making that more clear. I am proposing the exact rule, which is based on looking at the constant operand to a load/store and the size of number of bytes of memory it loads/stores from.

**Comment by lukewagner** [comment]
sgtm.  Perhaps you could write up the PR for Semantics.md#addressing and BinaryEncoding.md#memory-related-operators?

**Comment by saambarati** [comment]
@lukewagner Sure, I'm happy to do that. Lets first make sure other implementors are also with this change. If they are, I will write the PR.

**Comment by lukewagner** [comment]
Oh sure, I was expecting that to block merging, but waiting before is cool too.

**Comment by sunfishcode** [comment]
I agree with the idea of rejecting code containing wraparound-related corner cases, in general. However, `offset + sizeof(load/store) > UINT32_MAX` does not prove an access is out of bounds. For example, if an access has sizeof(load/store) is 1, offset is UINT32_MAX, the linear memory size is 4 GiB, and the runtime base is 0, then the access is in bounds, while the rule proposed here would reject it at validation.

**Comment by saambarati** [comment]
@sunfishcode I think you're off by 1. Say your memory has size `X`.
You can load a single byte from these addresses:
`[0, X - 1]`

Replace `X` with `UINT32_MAX`, you get:
`[0, 2^32 - 1 - 1] = [0, 2^32 - 2]`
So your maximum possible offset for loading a byte from memory is `UINT32_MAX - 1`

In your example, offset = `2^32 - 1` where `2^32 - 1 > 2^32 - 2`

**Comment by binji** [comment]
@saambarati Yes, but the max size of linear memory is not `UINT32_MAX`, but `UINT32_MAX + 1`.

**Comment by saambarati** [comment]
@binji Gotcha. Makes sense.
So the rule should be:
```offset + sizeof(load/store) - 1 > UINT32_MAX```

**Comment by sunfishcode** [comment]
@saambarati That rule looks good to me.

**Comment by sunfishcode** [comment]
Closing; this topic is now being discussed in #930.
