### ISSUE TITLE
Multiple Return Values

### ISSUE THREAD

**Issue by Kardax** [WebAssembly/design#937]
As noted in the future features document, the stack based nature of WebAssembly lends itself to the possibility of supporting multiple return values from blocks / functions.  This would be immediately useful for returning values larger than 8 bytes without having to add extra steps to pass them through a memory area.  The binary encoding already leaves open the possibility for multiple return values by simply changing return_count from varint1 to varint32.

**Comment by titzer** [comment]
We actually already implemented a prototype of this in V8, actually, which was one of the prerequisites to generalizing from the postorder to the stack machine.

**Comment by titzer** [comment]
Closing, as this issue is already on the roadmap.

**Comment by RyanLamansky** [comment]
Would it be appropriate to re-open this and use a tracking label?

**Comment by lukewagner** [comment]
Since it's already on the roadmap, I think the next steps would be to create a spec repo branch adding the feature, tests, etc, but we're still figuring out that whole process.  I do think this is something we should get to soon, though.

**Comment by RyanLamansky** [comment]
Any progress on the process?  The issue I filed immediately before this one, #936, is similar but was never closed.  If that one is still open, this one should be re-opened.

**Comment by jfbastien** [comment]
I think @titzer closed it because he's pretty sure someone from his team or Mozilla will champion the idea soon. They both have sample implementations in their VM, and we've discussed this quite often over beers, so I expect it to happen in the future.

**Comment by rossberg-chromium** [comment]
Yeah, I will propose it once I'm through with writing the MVP spec.

**Comment by Thaina** [comment]
@rossberg-chromium I think this issue should be reopened until the MVP spec released

**Comment by jfbastien** [comment]
The MVP *design* is already out and shipping in some browsers. Multiple return values will need to be proposed to the WebAssembly CG before it can go into the spec. What @rossberg-chromium was saying was "I'm currently working on finishing writing the MVP spec, and a work item I want to tackle after this are multiple return values". There's no hard dependency between the two work items, but there's a soft dependency in @rossberg-chromium 😁

**Comment by dvtate** [comment]
bump

**Comment by rossberg** [comment]
For anybody rediscovering this old issue: multiple return values have been standardised in Wasm by now, the [proposal](https://github.com/WebAssembly/multi-value) has been merged into the spec as of 2020-04-09.
