### ISSUE TITLE
Node js prerequisite missing in Getting Started (or Developer’s Guide). 

### ISSUE THREAD

**Issue by Tudor44** [WebAssembly/design#941]
I have tried to get my first hello world example following the getting started guide of webassembly, but after run the compilation step I have this error:

`INFO:root:Checking JS engine ['/home/gdorsi/webassembly/emsdk/node/4.1.1_64bit/bin/node'] failed. Check your config file. Details: [Errno 8] Exec format error
WARNING:root:cannot check node version: [Errno 8] Exec format error
INFO:root:(Emscripten: Running sanity checks)
CRITICAL:root:The JavaScript shell used for compiling (['/home/gdorsi/webassembly/emsdk/node/4.1.1_64bit/bin/node']) does not seem to work, check the paths in /home/gdorsi/.emscripten`

**Comment by dschuff** [comment]
This prerequisite really applies to emscripten, not to WebAssembly proper (also it applies to emscripten when not using WebAssembly, i.e. just asm.js).
Looking at your error message though "Exec format error", I'm guessing that you are running a 64-bit build of the emscripten tools on a 32-bit machine. If that doesn't fix your issue and you want more help, I'd recommend posting to the emscripten mailing list (https://groups.google.com/forum/#!forum/emscripten-discuss) or opening an issues on https://github.com/kripken/emscripten/.

**Comment by Tudor44** [comment]
@dschuff thank you precisley I have an SO running a 32-bit version of Ubuntu (14.04) Bash System in Windows 10. I haven't tested in a clean installation in a phisical machine.

**Comment by jfbastien** [comment]
Seems addressed.
