### ISSUE TITLE
What do "internal slots" mean?

### ISSUE THREAD

**Issue by mtrofin** [WebAssembly/design#947]
In https://github.com/WebAssembly/design/blob/master/JS.md#webassemblymodule-objects

What does this mean?

"A WebAssembly.Module object represents the stateless result of compiling a WebAssembly binary-format module and contains one internal slot:

[[Module]] : an Ast.module which is the spec definition of a module"

- what does "internal slot" mean?
- what does the sentence "Ast.module which is the spec definition of a module"

**Comment by jfbastien** [comment]
It's TC39-speak: https://tc39.github.io/ecma262/#sec-source-text-module-records

It would be nice to stay with TC39-isms in JS.md, and drop spec-isms (where spec is the spec repo).

**Comment by rossberg-chromium** [comment]
@jfbastien, how would we do that without duplicating the entire spec and translating all of it into ECMAcobol?

**Comment by rossberg-chromium** [comment]
@mtrofin, note that `Ast.module` links into the spec (in the only way we currently have available).

**Comment by lukewagner** [comment]
@jfbastien I personally view JS.md as a "wrapper" around the core (host independent) wasm spec, making it inherent in its job to point into both ES262 and the core wasm spec since the interactions go both ways.

**Comment by jfbastien** [comment]
@rossberg-chromium I thought that you were working on doing exactly this: having an English spec.

@lukewagner I agree that JS.md just wraps other parts: I was referring to @mtrofin's question on "Ast.module which is the spec definition of a module". The current text isn't helpful. Once things are unified we can just have a link to the appropriate section. It's the best wrapper we have now, but I sure hope things don't stay that way in a final specification.

**Comment by lukewagner** [comment]
Oh right, yes, prose spec will be much nicer to link to from JS.md.

**Comment by mtrofin** [comment]
Closing - my question is answered, and I assume the other main observation made here (the desire for a plain language spec) is on the radar.
