### ISSUE TITLE
When do we throw if exported function exotic object's signature exposes i64?

### ISSUE THREAD

**Issue by mtrofin** [WebAssembly/design#949]
See: https://github.com/WebAssembly/design/blob/master/JS.md#exported-function-exotic-objects

"WebAssembly Exported Functions have a [[Call]](this, argValues) method defined as:

1. Let sig be the function type of the function's [[Closure]].
2. If sig contains an i64 (as argument or result), a TypeError is thrown."

When? I'm assuming "at validation", so perhaps we have a spec bug here?

**Comment by jfbastien** [comment]
Dup #913?

**Comment by lukewagner** [comment]
We're talking about the runtime semantics of calling the [[Call]] method of an exported wasm function, so this is at runtime, when you call an export that has `i64` in its signature.

**Comment by rossberg-chromium** [comment]
What @lukewagner said. And it's a TypeError instead of a RuntimeError because it's a JS interfacing matter, not a failure within Wasm code.
