### ISSUE TITLE
Split import section by kind and use signed indices to distinguish imports

### ISSUE THREAD

**Issue by AndrewScheidecker** [WebAssembly/design#954]
I'm proposing this as an alternative to #783; see that issue and #882 for past discussion. The problem this is trying to solve is that because the global, function, memory, and table index spaces are formed by merging the declarations of each kind in the import section with the definitions of each kind from their respective sections, you must parse the kind of each declaration in the import section to resolve those indices to a declaration or definition.

#783 proposes merging the different index spaces. This issue proposes instead splitting the import section by kind, and using negative indices to distinguish import declarations from definitions within the module. That would allow simple resolution of an index to a declaration or definition, whether the resolver has merged the import declarations and internal definitions into an explicit array representing the index space, or just knows the number of imports of each kind.

The simplest way to do the negative indices would be to say that if `index` is less-than zero, it denotes the import index `numImportsOfThisKind + index`. If `index` is greater-than-or-equal to zero, it denotes the definition index `index`.

Either the import section split or the signed index change could be done independently, but I think the combination of the two is more valuable.

**Comment by lukewagner** [comment]
I guess I don't really understand the root problem here: what's wrong with parsing all imports and definitions?  It seems hard to *not* to parse everything if you're trying to compile, interpret or otherwise manipulate the code.

**Comment by AndrewScheidecker** [comment]
[Here's my in-memory representation of a WebAssembly module](https://github.com/AndrewScheidecker/WAVM/blob/master/Include/WebAssembly/Module.h#L138). It's just a deserialized representation of the binary format.

When I instantiate a module I [construct arrays that correspond to the index space for each kind of object](https://github.com/AndrewScheidecker/WAVM/blob/master/Source/Runtime/RuntimePrivate.h#L112). That's not a problem.

An example of where the problem occurs is that when I validate a module, it's necessary to [build an array for the type of declarations in each index space](https://github.com/AndrewScheidecker/WAVM/blob/master/Source/WebAssembly/Validate.cpp#L605) just to validate the indices. If you're working with an uninstanced module, you need to separate the imports by kind to interpret indices that occur in the module.

It would be possible to separate the imports by kind in my module struct, but if everybody is going to deserialize modules into structures with imports separated by kind, what's the point of merging them when serializing?

**Comment by lukewagner** [comment]
At least for FF: while we do reify the function and global index spaces during the validation+compilation step, after that, we just generate custom vectors of metadata that use whatever index space makes sense for the supported operations (e.g., a vector of the function-import metadata used to patch in imports, a vector of the exported-function metadata used to create wrappers, etc).  These are all ad hoc,  impl-defined index spaces and mostly independent of the original spec-defined index space.

**Comment by rossberg-chromium** [comment]
I sympathise somewhat with this proposal. Another way to describe the disadvantage of the current organsiation is that there is no simple syntactic way to e.g. tell whether a given index is an import or not -- you have to go through the entire import section and count entries of a particular kind. (The rather ugly function at https://github.com/WebAssembly/spec/blob/master/interpreter/spec/ast.ml#L223 is a manifestation of that in the spec.) If they were split, it would be sufficient to read the length of the respective import section.

That said, I still don't think it's worth making this change. I actually had experimented with such a split in the AST of the interpreter at one point. But ultimately, I found that it was just trading one inconvenience for another. For example, various functions that were generic on imports then came in 4 versions. The symmetry between imports and exports got lost. And it is less modular wrt addition of new kinds of imports in the future.

**Comment by titzer** [comment]
On Mon, Jan 16, 2017 at 12:59 PM, rossberg-chromium <
notifications@github.com> wrote:

> I sympathise somewhat with this proposal. Another way to describe the
> disadvantage of the current organsiation is that there is no simple
> syntactic way to e.g. tell whether a given index is an import or not -- you
> have to go through the entire import section and count entries of a
> particular kind. (The rather ugly function at https://github.com/
> WebAssembly/spec/blob/master/interpreter/spec/ast.ml#L223 is a
> manifestation of that in the spec.) If they were split, it would be
> sufficient to read the length of the respective import section.
>

FWIW what we do in V8 is that we record the number of imports of each kind
so that it's a simple comparison to tell if a given index is an import or
not.

**Comment by rossberg-chromium** [comment]
@titzer, my understanding was that Andrew was considering tools that don't want to parse the whole thing.

**Comment by pizlonator** [comment]
It's too late for this.
