### ISSUE TITLE
memory_immediate

### ISSUE THREAD

**Issue by kf2093** [WebAssembly/design#958]
I am writing an interpreter and I'm trying to understand the memory_immediate section.  I am unsure of the use of the memory alignment value (in the flags field) since the offset specifies a byte offset.  Can the byte offset not just be used in isolation?  Or should the memory access be aligned to the next offset that is aligned to the memory alignment specified within the flags field?  

The description also mentions that flags may/does contain a 'memory-access-size' attribute, however I cannot make sense of what this is.  Is it just remnants from a previous version?

**Comment by binji** [comment]
The alignment value is used as a hint to generate better code in a WebAssembly executor. You can read about alignment behavior here: https://github.com/WebAssembly/design/blob/master/Semantics.md#alignment

> The description also mentions that flags may/does contain a 'memory-access-size' attribute, however I cannot make sense of what this is. Is it just remnants from a previous version?

It actually says this:
> The bits after the log(memory-access-size) least-significant bits must be set to 0.

But good point, the `memory-access-size` doesn't seem to be specified anywhere. The intention is that it the number of bytes accessed by the operator. See https://github.com/WebAssembly/design/blob/master/Semantics.md#linear-memory-accesses.

So, for example, a 4-byte access uses log2(4) = 2 bits of the flags field, so bits 2, 3, 4, etc. all must be zero.

**Comment by kf2093** [comment]
Thanks for the clarification!
