### ISSUE TITLE
Re-think br_table.

### ISSUE THREAD

**Issue by wllang** [WebAssembly/design#959]
The separation of the `br_table` target blocks from the `br_table` operator seems to cause: less constrained code than is needed in some ways but still too constrained than needed in other ways, deep nesting of explicit blocks, and a corner-case constraint on the target values stack for which the complexity of handling might not be warranted.

People have already complained about the deep nesting. Making the target blocks implicit might lead to a more constrained and easier to read presentation.

Keeping the block targets separate certainly makes `br_table` more flexible in some ways, for example it can branch to any target including the function return or a loop repeat target. But these use cases could also be implemented by a branch from an implicit block and that solution would be even more general than the current `br_table` anyway because each could have a different set of values to pass to the target.

The present `br_table` implementation is constrained to pass a fixed number of values to all branch targets. In a wasm SSA style encoding that must pass out live values, the setting of any local variable within the preceding explicit blocks (that is still live at any target) can result in a constraint that the targets must accept values even if not using them. This constraint differs from regular branches for which each branch has a separate set of values to pass and if a particular target has an unused value then it can also be removes from the branch values and need not be expressed in the encoding. So it turns out to be quite a complexity reasoning about all these constraints when making code transforms and simplifications etc. A solution is to use an alternative `br_table` with implicit blocks and to wrap explicit blocks around this only as necessary. This alternative `br_table` with implicit blocks passes the same SSA environment and values stack to all the implicit blocks and passes not extra values, and popped the condition definition from the values stack, and each implicit block has separate branches to targets with individual lists of values avoiding a difficult constraint.

The current `br_table` might have worked ok for a register based design, but it seems a poor fit for the values-stack design, and it looks unworkable with an SSA style encoding, so I expect that this is an area of the design that needs re-thinking as the design work progresses. It would be great to have some feedback from those exploring the wasm tools, working with multiple values and SSA style encodings and dealing with `br_table`?

**Comment by pizlonator** [comment]
It's too late for this.
