### ISSUE TITLE
"name" section for globals?

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/design#964]
BinaryEncoding.md describes a "name" section, which contains names for defined functions. However, there is currently no section for names for defined memories, defined tables, defined globals, or types.

Is this intended? Obviously, function names are the most important of those, however when debugging code it would be nice to see things like `get_global stack_pointer` instead of `get_global 3` or whatever.

**Comment by lukewagner** [comment]
That's a good point.  So we could just bake in more kinds of names into the fixed structure of the name section, or we could add some `varu32` bitmap field (to the beginning of the names section) that declares which kinds of names are present.  That would allow us to backwards-compatibly add new kinds of names in the future.

**Comment by sunfishcode** [comment]
I missed that https://github.com/WebAssembly/design/issues/750 is already open, which covers this. Closing this issue to move the discussion there.
