### ISSUE TITLE
Memory.grow when delta=0? 

### ISSUE THREAD

**Issue by dtig** [WebAssembly/design#966]
Performing Memory.grow with delta d, should DetachArrayBuffer(M.[[BufferObject]]). As per my understanding the use case for grow(0), is to query memory size. Should the buffer object be detached when delta=0 as well?

**Comment by lukewagner** [comment]
That's a good question.  We still haven't decided to remove `current_memory` (in #904) and from JS you can always test `memory.buffer.byteLength`, so probably those two would be the preferred way to query memory size.  Moreover, *maybe* there is some object-capabilities/revocation-type reason why one might want to do a `grow(0)` with the intent of detaching the extant `ArrayBuffer`?

**Comment by eholk** [comment]
One concern with having `(grow_memory 0)` not detach the buffer is that if we grow by a non-constant amount, you'd get different side effects if the value happened to be zero versus otherwise. It seems to me that `grow_memory` should be consistent and always detach. Then it seems like we'd want a way to query the current memory size without detaching, which seems like an argument in favor of keeping `current_memory`.

**Comment by jfbastien** [comment]
What's the usecase for calling `grow_memory` with a value of `0`?

A user-side memory manager *has* to keep track of its total allocated memory, right? Asking the runtime "how much memory do I have" seems to be a performance pitfall. Parallel this to C: `malloc` doesn't call `mmap` or `sbrk` on every invocation.

**Comment by eholk** [comment]
I think it would mostly be during initialization. For example, modules can specify a minimum and maximum size, but it may not know what size its memory is to start with. Of course, there are other ways to find out or provide this information, so maybe burning an opcode for it doesn't make sense.

**Comment by titzer** [comment]
I think it's OK to have a dedicated op. It expresses the intent of the program and doesn't overload a state changing operation to be a query operation. For those reasons, my preference would be that a `grow_memory(0)` would detach the buffer, making a nice guarantee that if `grow_memory(x)` does not fail by returning `-1`, the old memory buffer is detached.

**Comment by sunfishcode** [comment]
There seems to be consensus to avoid special-casing `grow_memory(0)`. Feel free to re-open this or open a new issue if desired.

Whether `current_memory` is a useful operation is covered by the open issue #904.
