### ISSUE TITLE
Unicode normalization

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#971]
Forking from #970: JS.md talk about [Unicode normalization](http://unicode.org/reports/tr15/).

A simple example from that document: my name "Jean-François Bastien" can be normalized two ways with

  Ç	↔	C+◌̧

This is a nice gotcha in Unicode. While interfacing between JS and wasm it would be good to know what to expect from producers and consumers. **We may choose not to normalize, but we should say so**.

I see 4 ways in which we can discuss normalization in JS.md:

1. Forbid / error / ignore non-normalized inputs.
2. Automatically normalize wasm inputs, and compare the normalized JS values.
3. Automatically normalize wasm inputs, and expect the user to call [normalize](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize).
4. Not normalize anything.

If we choose 2. or 3. we should specify which form of normalization we expect (because of course there are multiple forms of normalization).

**Comment by Kardax** [comment]
1, 2, and 3 seems like a good source for esoteric bugs in JS engines.

I vote 4.

**Comment by lukewagner** [comment]
I think the `convertToJSString` function Web.md#names already specifies 4.  Seems fine to add clarifying text to say that no normalization occurs, though.

**Comment by rossberg-chromium** [comment]
Agreed with @lukewagner.

**Comment by tabatkins** [comment]
FWIW, CSS doesn't normalize at all either.

**Comment by jfbastien** [comment]
Sweet. I want to make sure we document these decisions, and it seems we've reached consensus. Closing.
