### ISSUE TITLE
Document validation/type-checking rules

### ISSUE THREAD

**Issue by eholk** [WebAssembly/design#974]
Our documents frequently refer to validation errors and make statements about types. If I want to write my own validator or produce valid Wasm code, it is not clear to me where I would find all the rules I should adhere to or check. We should make sure this is clearly documented.

I would be satisfied with "see the spec interpreter" as an answer. I just want it to be clear where the canonical rules are rather than relying on shared intuition among the WebAssembly Community Group Members.

**Comment by flagxor** [comment]
The spec interpreter is considered definitive (ish) at this point.

**Comment by jfbastien** [comment]
@flagxor so addressing this issue merely requires adding links to the relevant spec sections from the design document?

**Comment by eholk** [comment]
@jfbastien Yes, a link to the relevant sections in the design document would satisfy me.

**Comment by rossberg-chromium** [comment]
Addressed by #894.
