### ISSUE TITLE
Future reserved module namespace name(s)

### ISSUE THREAD

**Issue by jayphelps** [WebAssembly/design#979]
In the future it may be desirable for wasm and/or wasm hosts wish to provide some inherently available modules. e.g. the [SIMD section](https://github.com/WebAssembly/design/blob/f1f8666b2dd8a75a35a605586517bf99157bd499/FutureFeatures.md#fixed-width-simd) mentions this as one possibility.

Before the gold rush of module namespace squatting/usage, should there be consideration into restricting some standard names for future use? One could imagine things like `std`, `wasm`, or perhaps even a special character prefix. `__doubleunderscoremeansreserved`. This is likely one giant bikeshedding nightmare that you all may have already discussed and punted on, but I don't see a lot of harm in squatting some names for the MVP (can be released later)

In the future world of GC/WebIDL, it would also be a shame if browser vendors couldn't provide a module with a simple and obvious name--though the specific host module name squatting is probably outside the scope of wasm itself, the spec might recommend a particular namespace that vendors could rally behind?

I also might be misunderstanding the intended behavior--if we will _always_ be required to dynamically link WebIDL/SIMD/etc modules ourselves from JS land

**Comment by jfbastien** [comment]
I'm not sure I understand: standard sections use numbers, whereas custom ones use names. Doesn't that remove the need for reservations? Modules aren't named (besides their JavaScript variable). Or am I misunderstanding what you have in mind?

**Comment by jayphelps** [comment]
@jfbastien I'm most likely the one misunderstanding. 😄

Assuming SIMD/WebIDL/etc land, will it always be the host's job (e.g. JS API) to dynamically link these modules with wasm at some by-convention name?

Maybe this helps explain what I'm talking about:

This section mentions:
> SIMD adds new local types (e.g., f32x4) so it has to be part of the core semantics. SIMD operators (e.g., f32x4.add) could be either builtin operators (no different from i32.add) or exports of a builtin SIMD module.

I assumed it was referring to something like this:

```
(func $f32x4_add (import "simd" "f32x4_add") (param f32x4 f32x4))
```

**Comment by jfbastien** [comment]
Oh yeah I guess this isn't super clear. The intent for SIMD, if/when it happens, is to be opcodes and not imports. WebIDL is more open: we haven't really settled on where it would be but the obvious place to start is to import from JS and, if/when it makes sense, expose the API directly to WebAssembly. Starting small reduces risk for WebAssembly, and burden on the web platform.

Our general approach has been: WebAssembly exposes a platform (both hardware and OS), so the primitives it exposes should reflect this. Whatever the embedder can offer a capability we might as well use that first to reduce complexity. If performance / complexity / etc would benefit then consider exposing them as a first-class thing.

Does this make sense? Maybe it's worth clarifying some of the text.

**Comment by jayphelps** [comment]
@jfbastien Thanks for clarifying, that's mostly what my understanding was except for SIMD this confused me: `exports of a builtin SIMD module` which doesn't sound inline with `opcodes and not imports` but could just be the terminology I assumed "exports" refer to "imports"--or perhaps its just out of date? That said, I certainly think SIMD makes sense (to me) as opcodes considering SIMD's first class support in other asm langs works well, just mostly using it as a concrete example of when we might later wish we had reserved a namespace.

**Comment by jayphelps** [comment]
Closing to reduce noise. It sounds like this is a non-issue.
