### ISSUE TITLE
dynamic linking verus module loading: what's the difference?

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#98]
#53 discusses dynamic linking (post-V1), and PRs such as #71 document module loading (V1 feature). Speaking in-person, @lukewagner, @kg, @ncbray and I don't quite agree on the differences.

1. Does dynamic linking inply heap sharing? We seem to agree it does.
2. Is module loading just FII/syscall?
3. If V1 had dynamic linking, how would uses of module loading be different?
  * Would developers hack-in dynamic linking support on top of V1 using module loading?
4. Is module loading hindering non-browser uses?
  * If `stdout` and `write` were accessed through a dynamic library then it may be more portable than if it went through module loading and baked-in `console.log`.

Maybe we should even consider supporting dynamic linking for V1.

**Comment by sunfishcode** [comment]
With #682, we now have a design which should be able to support proper dynamic linking in the MVP. Note that we're still not ready to declare a stable ABI yet, as we'll still want to incoporate ABI-exposed features such as multiple return values, zero-cost EH, and TLS, when they become available.

Also, within the context of #682, we now have an answer to the top-level question here, which is that there is now no fundamental wasm-level difference. From a toolchain perspective, there will surely be a set of conventions for how dynamic libraries interoperate with the dynamic linker and the main executable, however it'll be built on the same concept of wasm modules, with imports and exports of functions, linear memory, globals, and tables.
