### ISSUE TITLE
Compile from URL for Simplicity, Content Security Policy, and Streaming Compilation

### ISSUE THREAD

**Issue by RyanLamansky** [WebAssembly/design#982]
`fetch` is great, but to make WebAssembly easier to use, enable streaming compilation, and allow stricter content security policy, `WebAssembly.compile` should accept a URL as input, just like the HTML `<script>` does today.

**Comment by wllang** [comment]
The problems to address seem much wider than can be solved just accepting a URL to `WebAssembly.compile`, rather a description of the work to be done is needed, the pipelines to be set up and stages and linear memories to be allocated and released. This has been discussed in https://github.com/WebAssembly/design/issues/972

**Comment by Kardax** [comment]
@wllang This won't solve every problem, but does provide a path to streaming compilation and strict content security policy without interfering with work on the more complicated cases described in the discussion of #972 .

**Comment by wllang** [comment]
I'd like to see the form of a more general solutions before making a call on it 'interfering with work on the more complicated case', but lets see. The more general solution might be trivial but somewhat different for the use case in this issue.

**Comment by Kardax** [comment]
I should clarify that I'm not suggesting that the ability to take a `BufferSource` as input should be removed.  Both URLs and `BufferSource` should be accepted, with `BufferSource` allowing interesting scenarios like client-side WASM generation and the the URL for simple use cases.

**Comment by rossberg-chromium** [comment]
Keep in mind that Wasm might be embedded in non-web environments where URLs have little or no meaning.

**Comment by Kardax** [comment]
@rossberg-chromium The very first line of the JavaScript API document on webassembly.org:

> In the MVP, the only way to access WebAssembly on the Web is through an explicit JS API which is defined below.

An improvement to this API is the only thing I am proposing, nothing that would affect non-web compatibility.

**Comment by wllang** [comment]
Even if targeting a non-web device the compilation (aka build) process might have sources that can be named by a URL, even a wasm subset for a toothbrush micro-controller can be built in this way. It is quite common for low end IoT devices to have a local file systems in flash and these files can be named by a URL. Makefiles and the like are really common.

**Comment by jfbastien** [comment]
I think this is addressed by the `Response` APIs? Closing, happy to reopen if not.
