### ISSUE TITLE
Anticipate differential updates to applications

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#99]
Dynamic linking #53 will help reduce transfer size, but won't fix the differential update problem, e.g.: application fetches `wasm.google.com/libm.1.2.so` and already has `wasm.google.com/libm.1.1.so`, and could receive a differential update from `1.1` to `1.2` instead of downloading all of `1.2`.

Web Assembly probably shouldn't be the one fixing this issue, maybe HTTP should, but it's a great usecase to move the web platform forward.

EDITS:
- @kg points out later that differential updates may interact with small binary size. We should collect data on this to avoid regretting design decisions later.
- @slightlyoff suggests that ServiceWorkers could help with differential updates.
## 

As a reference, asm.js can do this. Trendy Entertainment does this by caching the string to the asm.js module in indexdb and computing their own patches.

It's possible that the [Streams API](http://www.w3.org/TR/streams-api/) may also help with this.

h/t @kg for raising this issue!

**Comment by luser** [comment]
For reference, Mozilla uses [bsdiff](http://www.daemonology.net/bsdiff/) for partial updates. It does a pretty good job but it doesn't do so well with our PGO-compiled binaries. Testing it against some wasm prototype data would be nice.

**Comment by slightlyoff** [comment]
bsdiff is pretty poor on sectioned binaries. Chrome winds up using
something called courgette instead:
https://www.chromium.org/developers/design-documents/software-updates-courgette

Would love to see data against that as well.

**Comment by jfbastien** [comment]
We have dynamic linking.
