### ISSUE TITLE
Nit: Should a 'Local Entry' in a function body be permitted to have a count of 0?

### ISSUE THREAD

**Issue by DLehenbauer** [WebAssembly/design#996]
As written, the spec appears to permit function bodies to have local entries with a count of 0.

On the surface, permitting a count of zero doesn't seem useful.  Was this intentionally allowed?

**Comment by rossberg-chromium** [comment]
We allow 0 sizes pretty much everywhere. That usually avoids specifying and checking extra corner cases. It can also be convenient for producers not to be required to special-case on 0 counts.

**Comment by titzer** [comment]
Agreed with @rossberg-chromium
